<?php
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>

<?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
    <?php /* @escapeNotVerified */ echo __(
        '<a href="%1" onclick="this.target=\'_blank\'" class="print | cs-link">Print receipt</a>',
        $block->getPrintUrl()
    ) ?>
    <?php echo $block->getChildHtml() ?>
<?php endif;?>
