<?php
// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="cs-checkout">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img
                src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                style="position: absolute;"
            >
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader',
            'jquery',
            'bundle'
        ], function(url, blockLoader, $, bundle) {

            //Creativestyle adjustments below

            // Checkout is loaded some time after script is loaded. We need mutation observer here to know when to
            // initialize field watching or tabs

            var checkout = document.getElementById('checkout');
            var phoneTriggered = false;
            var addressTriggered = false;

            var checkoutStep1Observer = new MutationObserver( function( mutations ) {
                var $phoneInputs = $( 'input[name="telephone"]' );
                var $addressForm = $( '#shipping-new-address-form select[name="country_id"]' );

                if ( $phoneInputs.length && !phoneTriggered) {
                    phoneTriggered = true;
                    setPhoneOptional();
                    setZipCityFields();
                }

                if ( $addressForm.length && !addressTriggered ) {
                    addressTriggered = true;
                    startTabs();

                    var $form = $( '#shipping-new-address-form' );

                    bundle.AddressAutofill(
                        {
                            streetField: $form.find( 'input[name="street[0]"]' ),
                            zipField: $form.find( 'input[name="postcode"]'),
                            cityField: $form.find( 'input[name="city"]'),
                            countrySelect: $form.find( 'select[name="country_id"]' ),
                        }
                    );
                }

                if ( phoneTriggered  && addressTriggered ) {
                    checkoutStep1Observer.disconnect();
                }

            });

            var checkoutObserverConfig = { attributes: true, childList: true, characterData: true };

            checkoutStep1Observer.observe( checkout, checkoutObserverConfig );


            // TEMPORARY WORKAROUND to make phone number optional
            // PLEASE CHECK if this feature is already implemeneted in Magento : https://github.com/magento/magento2/pull/8519

            function setPhoneOptional() {
                var $phoneInputs = $( 'input[name="telephone"]' );
                if( $phoneInputs.val() === '<?php /* @escapeNotVerified */ echo __('No phone provided') ?>' ) {
                    $phoneInputs.css( 'color', 'transparent' )
                }

                $phoneInputs.on( 'focus', function(){
                    $phoneInputs.css( 'color', '' )
                });

                $phoneInputs.parents( '.cs-input' ).removeClass( '_required required')
                $( '#shipping-method-buttons-container button' ).on( 'click', function() {
                    $phoneInputs.each( function(){
                        if( !$( this ).val() ) {
                            $( this ).css( 'color', 'transparent' ).val( '<?php /* @escapeNotVerified */ echo __('No phone provided') ?>' ).change();
                        }
                    })
                } );
            }
            // end of phone workaround


            // Set zip and city in one line
            function setZipCityFields() {
                $( 'input[name="postcode"]' ).parents( '.cs-form__field' ).addClass( 'cs-form__field--type_small' )
                    .after();
                $( 'input[name="city"]' ).parents( '.cs-form__field' ).addClass( 'cs-form__field--type_medium');
            }


            function checkActiveButton() {
                var activeButton = $( '.payment-method._active .cs-button-payment-method[type="submit"]:not(disabled):not(".disabled")');

                if ( activeButton.length ) {
                    $( '.cs-place-order-button' ).prop( 'disabled', false );
                } else {
                    $( '.cs-place-order-button' ).prop( 'disabled', true );
                }

                return activeButton;
            }


            function startTabs() {
                $( '#tab-customer-title' ).on( 'click', function() {
                    $( '#shipping-new-address-form .cs-input' ).addClass( 'cs-input--disabled' ).find( 'input, ' +
                        'select' ).attr( 'disabled', 'disabled' );
                });

                $( '#tab-new-user-title' ).on( 'click', function() {
                    $( '#shipping-new-address-form .cs-input' ).removeClass( 'cs-input--disabled' ).find( 'input,' +
                        ' ' +
                        'select' ).removeAttr( 'disabled' );
                });
            }

            function checkIfButtonsLoaded() {
                if ( $( '.cs-button-payment-method' ).length ) {
                    clearInterval( checkButtonsIntervalId );
                    checkActiveButton();
                    $( '#co-payment-form' ).on( 'click', function() {
                        checkActiveButton();
                    });

                    $( '.cs-place-order-button' ).on( 'click', function() {
                        var activeButton = checkActiveButton();
                        if ( activeButton.length ) {
                            activeButton.trigger( 'click' );
                        }

                    } );
                }

            }

            // Payment methods step does not work with mutation observer. Mutation observer is lost while payment
            // step is reloaded. We need watch fo step2 in intervals
            var checkButtonsIntervalId = setInterval( checkIfButtonsLoaded, 800 );

            //Creativestyle adjustments end

            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>
