<?php
// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="cs-checkout">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img
                src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                style="position: absolute;"
            >
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader',
            'jquery'
        ], function(url, blockLoader, $) {

            function checkActiveButton() {
                var activeButton = $( '.payment-method._active .cs-button-payment-method[type="submit"]:not(disabled):not(".disabled")');

                if ( activeButton.length ) {
                    $( '.cs-place-order-button' ).prop( 'disabled', false );
                } else {
                    $( '.cs-place-order-button' ).prop( 'disabled', true );
                }

                return activeButton;
            }

            function checkIfButtonsLoaded() {
                if ( $( '.cs-button-payment-method' ).length ) {
                    clearInterval( checkButtonsIntervalId );
                    checkActiveButton();
                    $( '#co-payment-form' ).on( 'click', function() {
                        checkActiveButton();
                    });

                    $( '.cs-place-order-button' ).on( 'click', function() {
                        var activeButton = checkActiveButton();
                        if ( activeButton.length ) {
                            activeButton.trigger( 'click' );
                        }

                    } );
                }

            }

            var checkButtonsIntervalId = setInterval( checkIfButtonsLoaded, 2000 );

            function checkIfAddressLoaded() {
                if ( $( '#shipping-new-address-form' ).length ) {
                    clearInterval( checkAddressIntervalId );
                    $( '#tab-customer-title' ).on( 'click', function() {
                        $( '#shipping-new-address-form .cs-input' ).addClass( 'cs-input--disabled' ).find( 'input, ' +
                            'select' ).attr( 'disabled', 'disabled' );
                    })

                    $( '#tab-new-user-title' ).on( 'click', function() {
                        $( '#shipping-new-address-form .cs-input' ).removeClass( 'cs-input--disabled' ).find( 'input,' +
                            ' ' +
                            'select' ).removeAttr( 'disabled' );
                    })
                }

            }

            var checkAddressIntervalId = setInterval( checkIfAddressLoaded, 800 );

            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>
