<?php
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success | cs-page-success__section">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p class="cs-page-success__subheadline">
                <?php
                    echo __('Your order number is: %1.', sprintf(
                        '<a href="%s" class="order-number"><strong>%s</strong></a>',
                        $block->escapeHtml($block->getViewOrderUrl()),
                        $block->escapeHtml($block->getOrderId()))
                    )
                ?>
            </p>
        <?php  else :?>
            <p class="cs-page-success__subheadline">
                <?php echo __('Your order # is: <span>%1</span>', $block->escapeHtml($block->getOrderId())) ?>
            </p>
        <?php endif;?>
        <p class="cs-page-success__text">
            <?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?>
        </p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="cs-page-success__button-wrapper">
            <a class="cs-page-success__button" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>">
                 <span class="cs-page-success__button-span"><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
                 <?= $block->getChildHtml('success.page.continue.button.icon'); ?>
            </a>
    </div>
</div>
