<?php
/**
* Template overridden to:
* - add magesuite classes
* - add button icon
*/

/** @var $block \Magento\Checkout\Block\Onepage\Success */ 
?>
<div class="checkout-success | cs-page-success__section">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p class="cs-page-success__subheadline">
                <?= $block->escapeHtml(__('Your order number is: %1.', sprintf(
                        '<a href="%s" class="order-number"><strong>%s</strong></a>',
                        $block->escapeUrl($block->getViewOrderUrl()),
                        $block->escapeHtml($block->getOrderId()))
                    ), ['a', 'strong'])
                ?>
            </p>
        <?php  else :?>
            <p class="cs-page-success__subheadline">
                <?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?>
            </p>
        <?php endif;?>
        <p class="cs-page-success__text">
            <?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?>
        </p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="cs-page-success__button-wrapper">
            <a class="cs-page-success__button" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
                 <span class="cs-page-success__button-span"><?= $block->escapeHtml( __('Continue Shopping')) ?></span>
                 <?= $block->getChildHtml('success.page.continue.button.icon'); ?>
            </a>
    </div>
</div>
