<?php

// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\Giftcard\Block\Giftcard\Info */

$giftcard = $block->getGiftcard()
?>
<div id="aw_giftcard__code_info_block" class="cs-giftcard__info">
    <?php if ($giftcard && $giftcard->getId()): ?>
        <div class="cs-giftcard__info-title">
            <span class="cs-giftcard__info-title-span"><?php echo $block->escapeHtml(__('Gift Card code Information')) ?></span>
        </div>
        <div class="cs-giftcard__info-content">
            <div class="cs-table cs-giftcard__codes-table">
                <table class="cs-table__body">
                    <tr>
                        <td class="cs-table__col cs-table__col--label">
                            <?php echo $block->escapeHtml(__('Code')) ?>
                        </td>
                        <td class="cs-table__col giftcard-code" data-th="<?php echo $block->escapeHtml(__('Code')) ?>">
                            <?php echo $block->escapeHtml($giftcard->getCode()) ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="cs-table__col cs-table__col--label">
                            <?php echo $block->escapeHtml(__('Availability')) ?>
                        </td>
                        <td class="cs-table__col  giftcard-state" data-th="<?php echo $block->escapeHtml(__('Availability')) ?>">
                            <?php echo $block->escapeHtml($block->formatState($giftcard->getState())) ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="cs-table__col cs-table__col--label">
                            <?php echo $block->escapeHtml(__('Balance')) ?>
                        </td>
                        <td class="cs-table__col  giftcard-balance" data-th="<?php echo $block->escapeHtml(__('Balance')) ?>">
                            <?php /* @noEscape */ echo $block->formatPrice($giftcard->getBalance()) ?>
                        </td>
                    </tr>
                    <?php if ($giftcard->getExpireAt()): ?>
                        <tr>
                            <td class="cs-table__col cs-table__col--label">
                                <?php echo $block->escapeHtml(__('Expire At')) ?>
                            </td>
                            <td class="cs-table__col giftcard-expire-at" data-th="<?php echo $block->escapeHtml(__('Expire At')) ?>">
                                <?php /* @noEscape */ echo $block->formatDate($giftcard->getExpireAt(), \IntlDateFormatter::MEDIUM) ?>
                            </td>
                        </tr>
                    <?php endif;?>
                </table>
            </div>
        </div>
    <?php else: ?>
        <div class="cs-messages">
            <?php foreach ($block->getMessages() as $message): ?>
                <div class="cs-messages__message cs-messages__message--<?php /* @noEscape */ echo $message->getType() ?>">
                    <span class="cs-messages__text"><?php echo $block->escapeHtml($message->getText()) ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
