<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Catalog\Product\View\Addto\Compare */
?>

<li class="cs-buybox__addto-item <?= $block->getAdditionalCssClasses() ?>">
    <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getPostDataParams() ?>'
        data-role="add-to-links"
        class="action tocompare cs-buybox__addto-link cs-buybox__addto-link--compare">
        <?= $block->getChildHtml(''); ?>
        <span class="cs-buybox__addto-label"><?= $block->getLinkLabel() ?></span>
    </a>
</li>

