<?php
/** @var $block \Magento\Framework\View\Element\Html\Links */
/** @var $block \Magento\Customer\Block\Account\Navigation */ 
$collapseOptions = $block->getCollapsibleWidgetOptions();
$isMediaQueryScopeSet = $collapseOptions['mediaQueryScope'];
?>
<div class="cs-stack-nav | cs-sticky-block cs-sticky-block--no-mobile">
    <div class="cs-stack-nav__content | account-nav"
    <?php if($block->getIsCollapsible()): ?>
         data-mage-init='{"collapsible":<?= !empty($collapseOptions) ? json_encode($collapseOptions) : '{}' ?>}'
    <?php endif; ?> 
    >
        <div class="cs-stack-nav__trigger" data-role="title">
           <?php /* @escapeNotVerified */ echo __('My Account Menu'); ?>
           <?= $block->getChildHtml('dashboard.nav.collapse.icon'); ?>
        </div>
        <nav class="cs-stack-nav__nav | nav items" data-role="content">
            <ul class="cs-stack-nav__list">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>
