<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="cs-stack-nav | cs-sticky-block-no-mobile | cs-dropdown">
    <div class="cs-stack-nav__content | account-nav">
        <div class="cs-stack-nav__trigger | cs-dropdown__trigger | cs-t-headline cs-t-headline--size_3">
           <?php /* @escapeNotVerified */ echo __('My Account Menu'); ?>
            <svg class="cs-stack-nav__trigger-icon">
                <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#arrow_next"></use>
            </svg>
        </div>
        <nav class="cs-stack-nav__nav | nav items | cs-dropdown__content cs-dropdown__content--only-mobile">
            <ul class="cs-stack-nav__list">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>