<?php
/** Template overridden to:
 * - add magesuite classes - cs-cms-block class allows to use general typography styles
 * - assign current category to a variable
 *
 * Aligned with Magento 2.4.5 at 09/2022
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php $currentCategory = $block->getCurrentCategory() ?>
<?php if ($description = $currentCategory->getDescription()): ?>
    <div class="cs-cms-block | cs-page-category__description">
        <?= /* @noEscape */ $this->helper(\Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $currentCategory,
            $description,
            'description'
        ) ?>
    </div>
<?php endif; ?>
