<?php
/**
 * Template has been overwritten in order to:
 * - add `fetchpriority` attribute
 * - leave an empty alt to mark the image as decorative and hide it from assistive technologies
 * - remove title for the same reason
 *
 * Aligned with Magento 2.4.8 in 04.2025
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput

$fetchPriorityHigh = $block->getFetchPriorityHigh() ? ' fetchpriority="high"' : null;
?>
<?php
    $_category  = $block->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $block->getImage()->getUrl($_category)) {
        $_imgHtml = '<div class="category-image"><img src="'
            . $block->escapeUrl($_imgUrl)
            . '" alt="" class="image"'
            . $fetchPriorityHigh . '/></div>';
        $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'image');
        /* @noEscape */ echo $_imgHtml;
    }
?>
