<?php
$isVisible = $block->getVisible();
?>

<?php if($isVisible): ?>
    <?php
    $wrapperTag = $block->getWrapperTag() ?? 'li';
    $wrapperClass = $block->getWrapperCssClass();
    $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';

    $buttonCssClass = $block->getButtonCssClass();
    $buttonCssClass = $buttonCssClass ? sprintf('class="%s"', $buttonCssClass) : '';

    $label = $block->getLabel();
    $icon = $block->getChildHtml();
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?>>
        <a href="#" <?= $buttonCssClass ?><?php if($label): ?> title="<?= $label; ?>"<?php endif; ?>>
            <?= $icon; ?>
        </a>
    </<?= $wrapperTag ?>>
<?php endif; ?>
