<?php
// @codingStandardsIgnoreFile
/* @var $block \Magento\Downloadable\Block\Catalog\Product\Links */ 
?>
<?php $linksPurchasedSeparately = $block->getLinksPurchasedSeparately(); ?>
<?php if ($block->getProduct()->isSaleable() && $block->hasLinks()):?>
    <?php 
    $links = $block->getLinks(); 
    $linksLength = 0; 
    $isRequired = $block->getLinkSelectionRequired();
    $linksTitle = $block->getLinksTitle();
    ?>
    <legend class="legend links-title | cs-visually-hidden">
        <span><?php /* @escapeNotVerified */ echo $linksTitle ?></span>
    </legend>
    <div class="cs-product-sale-block__option | downloads<?php if ($isRequired) echo ' required' ?><?php if
    (!$linksPurchasedSeparately) echo ' downloads-no-separately' ?>">
        <label class="cs-product-sale-block__option-label">
            <span><?php /* @escapeNotVerified */ echo $linksTitle ?></span>
        </label>

        <div
            class="cs-product-sale-block__option-list"
            id="downloadable-links-list"
            data-mage-init='{"downloadable":{
                 "linkElement":"input:checkbox[value]",
                 "allElements":"#links_all",
                 "config":<?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>}
             }'
            data-container-for="downloadable-links"
        >
            <?php foreach ($links as $link): ?>
                <?php
                    $linksLength++;
                    $linkId = $link->getId();
                ?>
                <div class="cs-input cs-input--type-checkbox | cs-product-sale-block__option-checkbox"
                     data-role="link">
                    <?php if ($linksPurchasedSeparately): ?>
                        <input
                            type="checkbox"
                            class="cs-input__checkbox"
                            <?php if ($isRequired): ?>data-validate="{'validate-one-checkbox-required-by-name':'downloadable-links-list'}" <?php endif; ?>
                            name="links[]"
                            id="links_<?php /* @escapeNotVerified */ echo $linkId ?>"
                            value="<?php /* @escapeNotVerified */ echo $linkId; ?>" <?php /* @escapeNotVerified */ echo $block->getLinkCheckedValue($link); ?>
                        />
                        <label class="cs-input__label" for="links_<?php /* @escapeNotVerified */ echo $linkId ?>">
                            <span><?php echo $block->escapeHtml($link->getTitle()); ?></span>
                            <?php if ($link->getSampleFile() || $link->getSampleUrl()): ?>
                                <a
                                    class="sample link"
                                    href="<?php /* @escapeNotVerified */ echo $block->getLinkSampleUrl($link) ?>" <?php echo $block->getIsOpenInNewWindow() ? 'target="_blank"' : ''; ?>
                                    >
                                    <?php /* @escapeNotVerified */ echo __('sample') ?>
                                </a>
                            <?php endif; ?>
                            <?php if ($linksPurchasedSeparately): ?>
                                <?php /* @escapeNotVerified */ echo $block->getLinkPrice($link); ?>
                            <?php endif; ?>
                        </label>
                    <?php else: ?>
                        <label class="cs-t-text" for="links_<?php /* @escapeNotVerified */ echo $linkId ?>">
                            <span><?php echo $block->escapeHtml($link->getTitle()); ?></span>
                            <?php if ($link->getSampleFile() || $link->getSampleUrl()): ?>
                                <a
                                    class="sample link"
                                    href="<?php /* @escapeNotVerified */ echo $block->getLinkSampleUrl($link) ?>" <?php echo $block->getIsOpenInNewWindow() ? 'target="_blank"' : ''; ?>
                                    >
                                    <?php /* @escapeNotVerified */ echo __('sample') ?>
                                </a>
                            <?php endif; ?>
                            <?php if ($linksPurchasedSeparately): ?>
                                <?php /* @escapeNotVerified */ echo $block->getLinkPrice($link); ?>
                            <?php endif; ?>
                        </label>
                    <?php endif; ?>

                </div>
            <?php endforeach; ?>
            <?php if ($linksPurchasedSeparately && $linksLength > 1): ?>
                <div class="field choice downloads-all | cs-input cs-input--type-checkbox">
                    <input type="checkbox"
                           class="cs-input__checkbox"
                           data-notchecked="<?php /* @escapeNotVerified */ echo __('Select all')?>"
                           data-checked="<?php /* @escapeNotVerified */ echo __('Unselect all')?>"
                           id="links_all" />
                    <label class="cs-input__label" for="links_all"><span><?php /* @escapeNotVerified */ echo __('Select
                    all')?></span></label>
                </div>
            <?php endif; ?>
        </div>
        <?php if ($isRequired): ?>
            <span id="links-advice-container"></span>
        <?php endif;?>
    </div>
<?php endif; ?>
