<?php
// @codingStandardsIgnoreFile
/**
 *
 * @var $block \Magento\Downloadable\Block\Catalog\Product\View\Type
 */
?>
<?php $_product = $block->getProduct() ?>

<?php if ($_product->getIsSalable()): ?>
    <div class="cs-product-sale-block__stock-text cs-product-sale-block__stock-text--available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <svg class="cs-product-sale-block__stock-icon cs-product-sale-block__stock-icon--available">
            <use xlink:href="#check"></use>
        </svg>
        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
    </div>
<?php else: ?>
    <div class="cs-product-sale-block__stock-text cs-product-sale-block__stock-text--unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
    </div>
<?php endif; ?>
<?php echo $block->getChildHtml() ?>
