<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart */
/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?php /* @escapeNotVerified */
    echo $block->getLayout()->renderElement($childName, false); ?>
<?php endforeach; ?>

<fieldset class="cs-grid-product__fieldset | fieldset">
    <div class="cs-grid-product__section">

    <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
        <div class="cs-input | cs-grid-product__section-item | cs-qty-increment">
            <!--                <label class="cs-input__label" for="qty[--><?php ///* @escapeNotVerified */ echo $item->getId() ?><!--]"><span>--><?php ///* @escapeNotVerified */ echo __('Qty') ?><!--</span></label>-->
            <div class="cs-input__control">
                <input type="number" data-role="qty" id="qty[<?php /* @escapeNotVerified */
                echo $item->getId() ?>]" class="cs-input__input | cs-qty-increment__input" data-validate="{'required-number':true,'validate-greater-than-zero':true}" pattern="[0-9]?([,\.][0-9]{1,2})" size="5"
                       name="qty[<?php /* @escapeNotVerified */
                       echo $item->getId() ?>]" value="<?php /* @escapeNotVerified */
                echo $block->getAddToCartQty($item) * 1 ?>">
                <button type="button" class="cs-qty-increment__button cs-qty-increment__button--decrement">
                    <svg class="cs-qty-increment__icon cs-qty-increment__icon--minus">
                        <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#minus"></use>
                    </svg>
                </button>

                <button type="button" class="cs-qty-increment__button cs-qty-increment__button--increment">
                    <svg class="cs-qty-increment__icon cs-qty-increment__icon--plus">
                        <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#plus"></use>
                    </svg>
                </button>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($product->isSaleable()): ?>
        <div class="cs-grid-product__section-item">
            <button type="button" data-role="tocart" data-post='<?php /* @escapeNotVerified */
            echo $block->getItemAddToCartParams($item) ?>' title="<?php /* @escapeNotVerified */
            echo __('Add to Cart') ?>" data-item-id="<?php /* @escapeNotVerified */
            echo $item->getId() ?>" class="cs-button cs-button--look_default cs-button--look_square">
                <svg class="cs-button__icon cs-button__icon--center cs-button__icon--cart">
                    <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#cart"></use>
                </svg>
                <svg class="cs-button__icon">
                    <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
                </svg>
            </button>
        </div>

    </div>
    <?php else: ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="cs-grid-product__stock" title="<?php /* @escapeNotVerified */
            echo __('Availability') ?>">
                <span class="cs-t-text cs-t-text--look_success"><?php /* @escapeNotVerified */
                    echo __('In stock') ?></span>
            </p>
        <?php else: ?>
            <p class="cs-grid-product__stock" title="<?php /* @escapeNotVerified */
            echo __('Availability') ?>">
                <span class="cs-t-text cs-t-text--look_error"><?php /* @escapeNotVerified */
                    echo __('Out of stock') ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>
</fieldset>

