<?php
// @codingStandardsIgnoreFile
/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
?>

<div class="cs-input | cs-grid-product__comment | comment-box">
    <label class="cs-input__label | label" for="product-item-comment-<?php /* @escapeNotVerified */ echo $item->getWishlistItemId() ?>">
        <span><?php /* @escapeNotVerified */ echo __('Comment') ?></span>
    </label>
    <div class="cs-input__control">
        <textarea
            id="product-item-comment-<?php /* @escapeNotVerified */ echo $item->getWishlistItemId() ?>"
            name="description[<?php /* @escapeNotVerified */ echo $item->getWishlistItemId() ?>]"
            title="<?php /* @escapeNotVerified */ echo __('Comment') ?>"
            class="cs-input__textarea"
            ><?php echo($block->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
