<?php
// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<a
    class="cs-grid-product__figure-wrapper"
    href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>"
    title="<?php echo $block->escapeHtml($product->getName()) ?>"
>
    <?php echo $block->getImage($product, 'wishlist_thumbnail')->toHtml(); ?>
</a>
