<?php
// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="cs-grid-product__name cs-grid-product__name--no-space">
    <a
        href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($item) ?>"
        title="<?php echo $block->escapeHtml($product->getName()) ?>"
        class="cs-grid-product__name-link"
    >
        <?php echo $block->escapeHtml($product->getName()) ?>
    </a>
</div>
