<?php
// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
$dailyDealHelper = $this->helper('Creativestyle\DailyDealExtension\Helper\OfferData');
$dailyDealData = $dailyDealHelper->prepareOfferData($product);
$priceHtmlDeal = $dailyDealData && $dailyDealData['deal'] ? $dailyDealData['oldPriceHtmlOnTile'] : '';
$dailyDealPriceClass = $dailyDealData && $dailyDealData['deal'] && $dailyDealData['displayType'] === 'badge_counter' ? ' cs-grid-product__price--dailydeal-countdown' : '';
?>

<div class="cs-grid-product__price<?php echo $dailyDealPriceClass ?>">
<?php foreach ($block->getChildNames() as $childName): ?>
    <?php /* @escapeNotVerified */ echo $block->getLayout()->renderElement($childName, false); ?>
<?php endforeach;?>
<?php if($dailyDealData && $dailyDealData['deal'] && $dailyDealData['displayType'] === 'badge_counter') {
    echo '<div class="price-box price-final_price_without_daily_deal" style="display: none;">'.$priceHtmlDeal.'</div>';
} ?>
</div>
