<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
    /** @var $block \Magento\Swatches\Block\Product\Renderer\Listing\Configurable */
    $productId = $block->getProduct()->getId();
?>
<div class="cs-swatches cs-swatches--mini cs-swatches--color-only cs-swatches--static">
    <div
        class="swatch-opt-<?= /* @escapeNotVerified */ $productId; ?>"
        data-role="swatch-option-<?= /* @escapeNotVerified */ $productId ?>"
    ></div>
</div>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-option-<?= /* @escapeNotVerified */ $productId ?>]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorProduct": ".cs-grid-product__swatches",
                "onlySwatches": true,
                "enableControlLabel": false,
                "numberToShow": <?= /* @escapeNotVerified */ $block->getNumberSwatchesPerProduct(); ?>,
                "jsonConfig": <?= /* @escapeNotVerified */ $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?= /* @escapeNotVerified */ $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?= /* @escapeNotVerified */ $block->getMediaCallback() ?>",
                "classes": {
                    "attributeClass": "cs-swatches__attribute",
                    "attributeLabelClass": "cs-swatches__attribute-label",
                    "attributeSelectedOptionLabelClass": "cs-swatches__attribute-selected",
                    "attributeOptionsWrapper": "cs-swatches__list cs-swatches__list--mini",
                    "attributeInput": "cs-swatches__input",
                    "optionClass": "cs-swatches__swatch",
                    "selectClass": "cs-swatches__select",
                    "moreButton": "cs-swatches__more",
                    "loader": "cs-swatches__loader"
                }
            }
        }
    }
</script>
