<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Info\Buttons\Rss */
?>
<?php if ($block->isRssAllowed() && $block->getLink()): ?>
    <div class="cs-info-block__buttons cs-info-block__buttons--right">
        <a href="<?php /* @escapeNotVerified */ echo $block->getLink() ?>" class="cs-info-block__button | cs-button cs-button--size_300 cs-button--look_light">
            <?php /* @escapeNotVerified */ echo $block->getLabel() ?>
            <svg class="cs-button__icon">
                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
            </svg>
        </a>
    </div>

<?php endif; ?>
