<?php
// @codingStandardsIgnoreFile
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
    $mobileLogoPath = $block->getVar('header/mobile_logo_path', 'Magento_Theme');
    $mobileLogoWidth = $block->getVar('header/mobile_logo_width', 'Magento_Theme');
    $mobileLogoHeight = $block->getVar('header/mobile_logo_height', 'Magento_Theme');
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div class="cs-header__logo">
    <?php if ($block->isHomePage()): ?>
        <div class="logo cs-logo cs-logo--text">
    <?php else: ?>
        <a class="logo cs-logo cs-logo--link" href="<?= $block->getUrl(''); ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <?php endif; ?>
        <?php if ($mobileLogoPath): ?>
            <img class="cs-logo__image<?php if ($mobileLogoPath): ?> cs-logo__image--mobile<?php endif; ?>"
                src="<?= $block->getViewFileUrl($mobileLogoPath) ?>"
                alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                <?= $mobileLogoWidth ? 'width="' . $mobileLogoWidth . '"' : '' ?>
                <?= $mobileLogoHeight ? 'height="' . $mobileLogoHeight . '"' : '' ?>
            />
        <?php endif; ?>
        <img class="cs-logo__image<?php if ($mobileLogoPath): ?> cs-logo__image--desktop<?php endif; ?>"
            src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
            alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
    <?php if (!$block->isHomePage()): ?>
        </a>
    <?php else: ?>
        </div>
    <?php endif; ?>
</div>
