<?php
// @codingStandardsIgnoreFile
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div class="cs-header__logo">
    <?php if ($block->isHomePage()): ?>
        <div class="logo cs-logo cs-logo--text">
    <?php else: ?>
        <a class="logo cs-logo cs-logo--link" href="<?= $block->getUrl(''); ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
    <?php endif; ?>
            <img class="cs-logo__image"
                src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
                alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
    <?php if (!$block->isHomePage()): ?>
        </a>
    <?php else: ?>
        </div>
    <?php endif; ?>
</div>
