<?php
/**
 * Template overridden in order to:
 * - add magesuite classes
 * Aligned with Aheadworks_Faq v1.8.0 in 06/2026
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Aheadworks\Faq\ViewModel\Category $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="cs-faq-index__container">
    <p class="cs-faq-index__text"><?= /* @noEscape */ $viewModel->getContent() ?></p>
</div>
