<?php
/**
 * Template overridden in order to:
 * - change tag
 * - add magesuite classes
 * Aligned with Aheadworks_Faq v1.8.0 in 06/2026
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Aheadworks\Faq\ViewModel\Category $viewModel */
$viewModel = $block->getViewModel();
?>
<h2 class="cs-faq-index__title"><?= $escaper->escapeHtml($viewModel->getTitle()) ?></h2>
