<?php
/**
 * File has been overwritten in order to customize markup
 */
?>

<div class="cs-dashboard__block">
    <fieldset
        class="cs-form__fieldset | repertus_address_type_fieldset"
        data-repertus-post-number="<?php echo $this->getPostNumber(); ?>"
        data-repertus-station-number="<?php echo $this->getStationNumber(); ?>"
    >
        <legend class="cs-title-block cs-title-block--bordered cs-title-block--space-bottom">
            <span class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light">
                <?php echo __('Address Type'); ?>
            </span>
        </legend>
        <div class="cs-input | cs-form__field cs-form__field--type_packstation | repertus_address_type repertus_address_type--add-fields">
            <div class="cs-input__control">
                <select
                    id="repertus_packstation_type"
                    form="form-validate"
                    name="repertus_packstation_type"
                    title="<?php echo __('Address Type'); ?>"
                    class=""
                    aria-required="true" s
                    tyle="display: inline-block;"
                >
                    <?php
                        foreach ($this->getAddressTypes() as $key => $addressType) {
                            echo '<option value="'. $key . '" '. ($this->isAddressTypeSelected($key) ? 'selected="selected"' : '') .'>'. __($addressType) . '</option>';
                        }
                    ?>

                </select>
                <div class="cs-form__buttons">
                    <button class="cs-button cs-button--type_long cs-button--type_wide-mobile cs-button--look_default | repertus_packstation--search-button">
                        <span class="cs-button__span"><?php echo __('Search for Packstation'); ?></span>
                        <svg class="cs-button__icon">
                            <use xlink:href="#arrow_next"></use>
                        </svg>
                    </button>
                </div>
            </div>
        </div>
    </fieldset>
</div>


<script type="text/x-magento-init">
    {
        "#repertus_packstation_type": {
            "Repertus_Packstation/js/form/components/account_address_type_select": {
                "dataScope": "checkout.steps.shipping-step.shippingAddress.shipping-address-fieldset.repertus_address_type_group",
                "formSelector": ".form-address-edit",
                "packstationNumberSelector": "#repertus_post_number",
                "packstationNumberFieldSelector": "#repertus_number",
                "countrySelector": "#country",
                "zipFieldSelector": "#zip",
                "cityFieldSelector": "#city",
                "streetFieldsetSelector": ".field.street",
                "street1FieldSelector": "#street_1",
                "street2FieldSelector": "#street_2",
                "street3FieldSelector": "#street_3",
                "searchBtnSelector": ".repertus_packstation--search-button",
                "defaultBillingFieldSelector": ".field.choice.set.billing"
            }
        }
    }
</script>
