<?php
/**
 * Template has been overwritten in order to:
 * 1. Add additional container (label) for filter title and count (lines: 22, 34)
 * 2. All echoes changed into shorthand
 * 3. Helper for displaying count assigned to variable
 * 4. Improve a11y
 * Aligned with Smile_Elasticsuite v2.12.0 in 06/2026
 *
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\FilterRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

$displayProductCountOnLayer = $this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer();
?>

<ol class="items">
    <?php foreach ($filterItems as $key=>$filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?php if ($this->isMultipleSelectEnabled()) : ?>
                        <input id="<?= $escaper->escapeHtmlAttr($filterItem->getLabel() . '_' . $key) ?>" type="checkbox" onclick="this.parentNode.click();" <?php if($filterItem->getIsSelected()) : ?>checked<?php endif; ?> />
                        <label for="<?= $escaper->escapeHtmlAttr($filterItem->getLabel() . '_' . $key) ?>">
                    <?php else: ?>
                        <span>
                    <?php endif; ?>
                        <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                        <?php if ($displayProductCountOnLayer): ?>
                            <span class="count">
                                <?= /* @escapeNotVerified */ $filterItem->getCount()?>
                            <span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?>
                                <?= /* @escapeNotVerified */ __('item')?>
                            <?php else:?>
                                <?= /* @escapeNotVerified */ __('items') ?>
                            <?php endif;?></span></span>
                        <?php endif; ?>
                    </<?= $this->isMultipleSelectEnabled() ? 'label' : 'span' ?>>
                </a>
            <?php else:?>
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                <?php if ($displayProductCountOnLayer): ?>
                    <span class="count">
                        <?= /* @escapeNotVerified */ $filterItem->getCount()?>
                        <span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?>
                            <?= /* @escapeNotVerified */ __('item')?>
                        <?php else:?>
                            <?= /* @escapeNotVerified */ __('items') ?><?php endif;?>
                        </span>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
