<?php
/**
 * @var $block \Smile\ElasticsuiteCatalog\Block\Navigation\Renderer\Slider
 */
?>

<div class="cs-aftersearch-nav__price | price-inputs-wrapper">
    <div class="cs-aftersearch-nav__price-field cs-aftersearch-nav__price-field--from | cs-input">
        <span class="cs-aftersearch-nav__currency">&euro;</span>
        <input
            type="text"
            id="price_from"
            class="cs-aftersearch-nav__price-input | cs-input__input"
        >
    </div>
    <div class="cs-aftersearch-nav__price-field cs-aftersearch-nav__price-field--to | cs-input">
        <label for="price_to" id="price_to_label" class="cs-aftersearch-nav__price-label">
            <?php echo $block->escapeHtml(__('To')); ?>
        </label>
        <span class="cs-aftersearch-nav__currency">&euro;</span>
        <input
            type="text"
            id="price_to"
            class="cs-aftersearch-nav__price-input | cs-input__input"
        >
    </div>
</div>

<div class="cs-aftersearch-nav__rangeSlider | smile-es-range-slider" data-role="<?php /* @noEscape */ echo $block->getDataRole(); ?>">
    <div data-role="from-label" class="cs-visually-hidden"></div>
    <div data-role="to-label" class="cs-visually-hidden"></div>
    <div data-role="slider-bar" class="cs-visually-hidden"></div>
    <div class="actions-toolbar | cs-aftersearch-nav__rangeSlider-actions-box">
        <div data-role="message-box" class="cs-aftersearch-nav__rangeSlider-msg"></div>
        <div class="actions-primary | cs-aftersearch-nav__rangeSlider-actions">
            <a class="cs-button cs-button--look_default cs-button--size_300 | cs-aftersearch-nav__price-apply-button" data-role="apply-range">
                <span class="cs-button__span"><?php /* @noEscape */ echo __('OK'); ?></span> 
                <svg class="cs-button__icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#arrow_next"></use></svg>
            </a>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    { "[data-role=<?php /* @noEscape */ echo $block->getDataRole(); ?>]" : { "rangeSlider" : <?php echo  /* @noEscape */ $block->getJsonConfig(); ?> } }
</script>
