<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php $totalNum = $block->getTotalNum(); ?>
<p class="cs-category-page__toolbar-amount | cs-t-text" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1): ?>
        <?php /* @escapeNotVerified */ echo __('Items %1-%2 of %3',
            '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
            '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
            '<span class="toolbar-number">' . $totalNum . '</span>') ?>
    <?php elseif ($totalNum == 1): ?>
        <?php /* @escapeNotVerified */ echo __('%1 Item',
            '<span class="toolbar-number">' . $totalNum . '</span>') ?>
    <?php else: ?>
        <?php /* @escapeNotVerified */ echo __('%1 Items',
            '<span class="toolbar-number">' . $totalNum . '</span>') ?>
    <?php endif; ?>
</p>
