<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="cs-category-page__toolbar-limiter | cs-input">
    <label class="cs-category-page__toolbar-label | cs-t-text cs-t-text--look_label" for="limiter">
        <?php /* @escapeNotVerified */ echo __('Display') ?>
    </label>
    <div class="control cs-input__control">
        <select id="limiter" data-role="limiter" class="cs-input__select">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <option value="<?php /* @escapeNotVerified */ echo $_key ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                    selected="selected"<?php endif ?>>
                    <?php /* @escapeNotVerified */ echo $_limit ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
