<?php
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="cs-category-page__toolbar-sorter | cs-input | sorter">
    <label class="cs-category-page__toolbar-label" for="sorter">
        <?php /* @escapeNotVerified */ echo __('Sort By: ') ?>
    </label>

    <?php 
        $options = [];

        foreach ($block->getAvailableOrders() as $key => $order){
            $orders = [
                'value' => $key,
                'label' => $block->escapeHtml(__($order))
            ];

            if($block->isOrderCurrent($key)) {
                $orders['params'] = 'selected=selected';
            }

            $options[] = $orders;
        }
    ?>

    <?=$this->getLayout()->createBlock( 
            'Creativestyle\FrontendExtension\Block\Twig', 'select-sorter', [
                'data' => [
                    'params' => 'data-role=sorter',
                    'options' => $options
                ]
            ]
        )->setTemplate("select/select.twig")->toHtml();
    ?>


    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a
            title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>"
            href="#" class="action sorter-action sort-desc"
            data-role="direction-switcher"
            data-value="asc"
        >
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a
            title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>"
            href="#"
            class="action sorter-action sort-asc"
            data-role="direction-switcher"
            data-value="desc"
        >
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
