<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="cs-category-page__toolbar-sorter | cs-input | sorter">
    <label class="cs-category-page__toolbar-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By: ') ?></label>

    <?php 
        $options = [];

        foreach ($block->getAvailableOrders() as $_key => $_order){
            $_ = [
                'value' => $_key,
                'label' => $block->escapeHtml(__($_order))
            ];

            if($block->isOrderCurrent($_key)) {
                $_['params'] = 'selected=selected';
            }

            $options[] = $_;
        }
    ?>

    <?=$this->getLayout()->createBlock( 
            'Creativestyle\FrontendExtension\Block\Twig', 'select-sorter', [
                'data' => [
                    'params' => 'id=sorter data-role=sorter',
                    'options' => $options
                ]
            ]
        )->setTemplate("select/select.twig")->toHtml();
    ?>


    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
