<?php
/**
 * Template overridden to:
 * - add magesuite classes
 * - introduce xml configuration (etc/view.xml)
 * - add icons
 * Aligned with Magento 2.4.7 in 04/2024
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->isEnabledViewSwitcher()) :?>
    <div class="modes cs-viewmode-switcher">
        <?php $_modes = $block->getModes(); ?>
        <?php if ($_modes && count($_modes) > 1) :?>
            <?php
                $prefixLabel = $block->getVar('toolbar/viewmode_switcher/prefix_label', 'Magento_Catalog')
            ?>

            <?php if(!empty($prefixLabel)): ?>
                <p class="modes-label cs-viewmode-switcher__label" id="modes-label"><?= $block->escapeHtml(__($prefixLabel)) ?> </p>
            <?php endif; ?>

            <ul class="cs-viewmode-switcher__modes">
                <?php foreach ($block->getModes() as $_code => $_label) :?>
                    <?php $codeLowercase = strtolower($_code) ?>
                    <?php if ($block->isModeActive($_code)) :?>
                        <li class="cs-viewmode-switcher__mode cs-viewmode-switcher__mode--current">
                            <span title="<?= $block->escapeHtmlAttr($_label) ?>"
                                class="modes-mode active mode-<?= $block->escapeHtmlAttr($codeLowercase) ?> cs-viewmode-switcher__mode-action cs-viewmode-switcher__mode-action--<?= $block->escapeHtmlAttr($codeLowercase) ?>"
                                data-value="<?= $block->escapeHtmlAttr($codeLowercase) ?>">
                                <?php if($block->getVar('toolbar/viewmode_switcher/display_modes_icons', 'Magento_Catalog')): ?>
                                    <?= $this->getLayout()
                                         ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                         ->setIconUrl('images/icons/toolbar/viewmode-' . $codeLowercase . '.svg')
                                         ->setCssClass('cs-viewmode-switcher__mode-icon cs-viewmode-switcher__mode-icon--' . $codeLowercase)
                                         ->setInlined(true)
                                         ->setLazyLoaded(false)
                                         ->toHtml(); ?>
                                <?php endif; ?>
                                <span class="cs-viewmode-switcher__mode-label<?php if(!$block->getVar('toolbar/viewmode_switcher/display_modes_labels', 'Magento_Catalog')): ?> cs-visually-hidden<?php endif; ?>"><?= $block->escapeHtml($_label) ?></span>
                            </span>
                        </li>
                    <?php else :?>
                        <li class="cs-viewmode-switcher__mode">
                            <a class="modes-mode mode-<?= $block->escapeHtmlAttr($codeLowercase) ?> cs-viewmode-switcher__mode-action cs-viewmode-switcher__mode-action--<?= $block->escapeHtmlAttr($codeLowercase) ?>"
                               title="<?= $block->escapeHtmlAttr($_label) ?>"
                               href="#"
                               data-role="mode-switcher"
                               data-value="<?= $block->escapeHtmlAttr($codeLowercase) ?>"
                               id="mode-<?= $block->escapeHtmlAttr($codeLowercase) ?>"
                               aria-labelledby="modes-label mode-<?= $block->escapeHtmlAttr($codeLowercase) ?>">
                                <?php if($block->getVar('toolbar/viewmode_switcher/display_modes_icons', 'Magento_Catalog')): ?>
                                    <?= $this->getLayout()
                                         ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                         ->setIconUrl('images/icons/toolbar/viewmode-' . $codeLowercase . '.svg')
                                         ->setCssClass('cs-viewmode-switcher__mode-icon cs-viewmode-switcher__mode-icon--' . $codeLowercase)
                                         ->setInlined(true)
                                         ->setLazyLoaded(false)
                                         ->toHtml(); ?>
                                <?php endif; ?>
                                <span class="cs-viewmode-switcher__mode-label<?php if(!$block->getVar('toolbar/viewmode_switcher/display_modes_labels', 'Magento_Catalog')): ?> cs-visually-hidden<?php endif; ?>"><?= $block->escapeHtml($_label) ?></span>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    </div>
<?php endif; ?>
