<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <h2 class="cs-styleguide__title">
        Badges
    </h2>

    <div class="cs-styleguide__section cs-styleguide__section--column">
        <ul class="cs-page-product__badges">
            <li class="cs-page-product__badge-item">
                <span class="cs-page-product__badge cs-page-product__badge--top">
                    <span class="cs-page-product__badge-text"><?= __('Top'); ?></span>
                </span>
            </li>
            <li class="cs-page-product__badge-item">
                <span class="cs-page-product__badge cs-page-product__badge--free">
                    <span class="cs-page-product__badge-text"><?= __('Free'); ?></span>
                </span>
            </li>
            <li class="cs-page-product__badge-item">
                <span class="cs-page-product__badge cs-page-product__badge--daily-deal">
                    <span class="cs-page-product__badge-text"><?= __('Daily deal'); ?></span>
                </span>
            </li>    
            <li class="cs-page-product__badge-item">
                <span class="cs-page-product__badge cs-page-product__badge--popular">
                    <span class="cs-page-product__badge-text"><?= __('Popular'); ?></span>
                </span>
            </li>
            <li class="cs-page-product__badge-item">
                <span class="cs-page-product__badge cs-page-product__badge--free-shipping">
                    <span class="cs-page-product__badge-text"><?= __('Free shipping'); ?></span>
                </span>
            </li>
            <li class="cs-page-product__badge-item">
                <span class="cs-page-product__badge cs-page-product__badge--discount">
                    <span class="cs-page-product__badge-text"><?= __('-50%'); ?></span>
                </span>
            </li>
            <li class="cs-page-product__badge-item">
                <span class="cs-page-product__badge cs-page-product__badge--new">
                    <span class="cs-page-product__badge-text"><?= __('New'); ?></span>
                </span>
            </li>
        </ul>
    </div>
</div>