<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <div class="cs-styleguide__title">
        Badges
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <div class="cs-multiple-badges">
            <span class="cs-badge cs-badge--attention cs-badge--label-big cs-badge--cut">
                <span class="cs-badge__span cs-badge__span--no-space"><?= __('Sale'); ?></span>
            </span>
            <span class="cs-badge cs-badge--label-big">
                <span class="cs-badge__span"><?= __('-30%'); ?></span>
            </span>
        </div>

        <div>
            <span class="cs-badge cs-badge--new cs-badge--label-big cs-badge--cut">
                <span class="cs-badge__span cs-badge__span--no-space"><?= __('New'); ?></span>
            </span>
        </div>

        <div>

            <span class="cs-badge cs-badge--info">
                <span class="cs-badge__span">2</span>
            </span>
        </div>


    </div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">

        <div class="cs-multiple-badges">
            <span class="cs-badge cs-badge--attention cs-badge--cut">
                <span class="cs-badge__span cs-badge__span--no-space"><?= __('Sale'); ?></span>
            </span>
            <span class="cs-badge">
                <span class="cs-badge__span"><?= __('-30%'); ?></span>
            </span>
        </div>

        <div>
            <span class="cs-badge cs-badge--new cs-badge--cut">
                <span class="cs-badge__span cs-badge__span--no-space"><?= __('New'); ?></span>
            </span>
        </div>


        <span class="cs-badge cs-badge--short cs-badge--attention">
            <span class="cs-badge__span">4</span>
        </span>

    </div>
</div>
