<div class="cs-styleguide__title">
    Buttons
</div>

<div class="cs-styleguide__section cs-styleguide__section--block">

    <div style="width: 30rem;">
        <button type="submit" title="cart" class="cs-button cs-button--type_wide cs-button--type_cart">
            <svg class="cs-button__icon cs-button__icon--cart">
                <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#cart"></use>
            </svg>
            Add to cart
        </button>
    </div>

    <button class="cs-button cs-button--type_long cs-button--look_default">
        Look: default, size: normal, type: long
        <svg class="cs-button__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
        </svg>
    </button>

    <button class="cs-button cs-button--look_default">
        Look: default, size: normal
        <svg class="cs-button__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
        </svg>
    </button>

    <button class="cs-button cs-button--look_light">
        Look: light, size: normal
        <svg class="cs-button__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
        </svg>
    </button>

    <button class="cs-button cs-button--look_default cs-button--size_300">
        Look: default, size: 300
        <svg class="cs-button__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
        </svg>
    </button>

    <button class="cs-button cs-button--look_light cs-button--size_300">
        Look: light, size: 300
        <svg class="cs-button__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
        </svg>
    </button>

    <a href="#" title="<?php /* @escapeNotVerified */ echo __('Remove This Item') ?>" class="cs-button--look_remove">
        <svg class="cs-button__remove-icon">
            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#close"></use>
        </svg>
        <span class="cs-visually-hidden"><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
    </a>


</div>