<div class="cs-styleguide__container">

    <h2 class="cs-styleguide__title">
        Buttons
    </h2>

    <div class="cs-styleguide__section">
    <div class="cs-styleguide__box-group cs-styleguide__box-group--buttons">
            <button class="cs-styleguide__button cs-styleguide__button--primary">
                <span class="cs-styleguide__button-span--no-icon">Button primary no icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--secondary">
                <span class="cs-styleguide__button-span--no-icon">Button secondary no icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--link">
                <span class="cs-styleguide__button-span--no-icon">Button link no icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--success">
                <span class="cs-styleguide__button-span--no-icon">Button success no icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--error">
                <span class="cs-styleguide__button-span--no-icon">Button error no icon</span>
            </button>
    </div>
    <div class="cs-styleguide__box-group cs-styleguide__box-group--buttons">
            <button class="cs-styleguide__button cs-styleguide__button--primary-has-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/arrow_next.svg')
                    ->setCssClass('cs-button__icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
                <span class="cs-styleguide__button-span--has-icon">Button primary has icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--secondary-has-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-addtocart.svg')
                    ->setCssClass('cs-button__icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
                <span class="cs-styleguide__button-span--has-icon">Button secondary has icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--link-has-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-addtocart.svg')
                    ->setCssClass('cs-button__icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
                <span class="cs-styleguide__button-span--has-icon">Button link has icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--success-has-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-success.svg')
                    ->setCssClass('cs-button__icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
                <span class="cs-styleguide__button-span--has-icon">Button success has icon</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--error-has-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-fail.svg')
                    ->setCssClass('cs-button__icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
                <span class="cs-styleguide__button-span--has-icon">Button error has icon</span>
            </button>
    </div>
    <div class="cs-styleguide__box-group cs-styleguide__box-group--buttons">
            <button class="cs-styleguide__button cs-styleguide__button--primary-icon-left">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-addtocart.svg')
                    ->setCssClass('cs-styleguide__button-icon--left')
                    ->setInlined(true)
                    ->toHtml();
                ?>
                <span class="cs-styleguide__button-span--icon-left">Button primary icon left</span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--secondary-icon-left">
                <span class="cs-styleguide__button-span--icon-left">Button secondary icon left</span>
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/arrow_prev.svg')
                    ->setCssClass('cs-styleguide__button-icon--left')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--link-icon-left">
                <span class="cs-styleguide__button-span--icon-left">Button link icon left</span>
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-addtocart.svg')
                    ->setCssClass('cs-styleguide__button-icon--left')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--success-icon-left">
                <span class="cs-styleguide__button-span--icon-left">Button success icon left</span>
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-success.svg')
                    ->setCssClass('cs-styleguide__button-icon--left')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--error-icon-left">
                <span class="cs-styleguide__button-span--icon-left">Button error icon left</span>
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-fail.svg')
                    ->setCssClass('cs-styleguide__button-icon--left')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
    </div>
    <div class="cs-styleguide__box-group cs-styleguide__box-group--buttons">
            <button class="cs-styleguide__button cs-styleguide__button--primary-only-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/plus.svg')
                    ->setCssClass('cs-styleguide__button-icon--only-icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
                </span>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--secondary-only-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/logout.svg')
                    ->setCssClass('cs-styleguide__button-icon--only-icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--link-only-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/edit.svg')
                    ->setCssClass('cs-styleguide__button-icon--only-icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--success-only-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-success.svg')
                    ->setCssClass('cs-styleguide__button-icon--only-icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
            <button class="cs-styleguide__button cs-styleguide__button--error-only-icon">
                <?= $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/addtocart/icon-fail.svg')
                    ->setCssClass('cs-styleguide__button-icon--only-icon')
                    ->setInlined(true)
                    ->toHtml();
                ?>
            </button>
    </div>

</div>
