<div class="cs-styleguide__title">
    Buttons
</div>

<div class="cs-styleguide__section cs-styleguide__section--columns">

    <div>
        <button type="submit" title="cart" class="cs-button cs-button--type_wide cs-button--type_cart" style="width: 30rem;">
            <svg class="cs-button__icon cs-button__icon--cart">
                <use xlink:href="#cart"></use>
            </svg>
            <span class="cs-button__span">
                Add to cart
            </span>
        </button>
    </div>

    <div>
        <button class="cs-button cs-button--type_long cs-button--look_default">
            <span class="cs-button__span">Look: default, size: normal, type: long</span>
            <svg class="cs-button__icon">
                <use xlink:href="#arrow_next"></use>
            </svg>
        </button>
    </div>

    <div>
        <button class="cs-button cs-button--look_default">
             <span class="cs-button__span">Look: default, size: normal</span>
            <svg class="cs-button__icon">
                <use xlink:href="#arrow_next"></use>
            </svg>
        </button>
    </div>

    <div>
        <button class="cs-button cs-button--look_light">
             <span class="cs-button__span">Look: light, size: normal</span>
            <svg class="cs-button__icon">
                <use xlink:href="#arrow_next"></use>
            </svg>
        </button>
    </div>

    <div>
        <button class="cs-button cs-button--look_default cs-button--size_300">
            <span class="cs-button__span"> Look: default, size: 300</span>
            <svg class="cs-button__icon">
                <use xlink:href="#arrow_next"></use>
            </svg>
        </button>
    </div>

    <div>
        <button class="cs-button cs-button--look_light cs-button--size_300">
            <span class="cs-button__span"> Look: light, size: 300</span>
            <svg class="cs-button__icon">
                <use xlink:href="#arrow_next"></use>
            </svg>
        </button>
    </div>

    <div>
        <a href="#" title="<?php /* @escapeNotVerified */ echo __('Remove This Item') ?>" class="cs-button--look_remove">
            <svg class="cs-button__remove-icon">
                <use xlink:href="#close"></use>
            </svg>
            <span class="cs-visually-hidden"><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
        </a>
    </div>

    <div>
        <ul class="cs-list cs-list--unstyled cs-list--inline">
            <li class="cs-footer-list__item">
                <a href="#" class="cs-button-social">
                    <svg class="cs-button-social__icon cs-button-social__icon--fb">
                        <use xlink:href="#facebook"></use>
                    </svg>
                    <span class="cs-visually-hidden"><?=__('Go to Facebook');?></span>
                </a>
            </li>

            <li class="cs-footer-list__item">
                <a href="#" class="cs-button-social">
                    <svg class="cs-button-social__icon cs-button-social__icon--gplus">
                        <use xlink:href="#google_plus"></use>
                    </svg>
                    <span class="cs-visually-hidden"><?=__('Go to Google Plus');?></span>
                </a>
            </li>

            <li class="cs-footer-list__item">
                <a href="#" class="cs-button-social">
                    <svg class="cs-button-social__icon cs-button-social__icon--yt">
                        <use xlink:href="#you_tube"></use>
                    </svg>
                    <span class="cs-visually-hidden"><?=__('Go to You Tube');?></span>
                </a>
            </li>
        </ul>
    </div>

</div>