<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <h2 class="cs-styleguide__title">
        Carousel navigation
    </h2>

    <div class="cs-styleguide__section cs-styleguide__section--wide">
        <div class="cs-products-carousel--ready" data-mobile-is-slider data-view-mode="grid">
            <div class="cs-products-carousel__wrapper">        
                <button class="cs-products-carousel__nav" type="button" aria-disabled="false">
                    <?= $this->getLayout()
                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                        ->setIconUrl('images/icons/icon_arrow-left.svg')
                        ->setCssClass("cs-products-carousel__nav-icon")
                        ->setInlined(true)
                        ->toHtml(); 
                    ?>
                </button>
                <button class="cs-products-carousel__nav" type="button" aria-disabled="false">
                    <?= $this->getLayout()
                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                        ->setIconUrl('images/icons/icon_arrow-right.svg')
                        ->setCssClass("cs-products-carousel__nav-icon")
                        ->setInlined(true)
                        ->toHtml(); 
                    ?>
                </button>
            </div>
            <div class="cs-products-carousel__wrapper">
                <ul class="cs-products-carousel__pagination">
                    <li tabindex="0" role="button" aria-label="Go to slide 1" class="cs-products-carousel__pagination-item cs-products-carousel__pagination-item--active">
                        <button class="cs-products-carousel__pagination-button">1</button>
                    </li>
                    <li class="cs-products-carousel__pagination-item">
                        <button class="cs-products-carousel__pagination-button">2</button>
                    </li>
                    <li class="cs-products-carousel__pagination-item">
                        <button class="cs-products-carousel__pagination-button">3</button>
                    </li>
                </ul>
            </div>
            <div class="cs-products-carousel__wrapper">
                <div class="cs-products-carousel__pagination">
                    <span class="cs-products-carousel__number cs-products-carousel__number--current">1</span>
                    /
                    <span class="cs-products-carousel__number cs-products-carousel__number--total">5</span>
                </div>   
            </div>
        </div>
    </div>
</div>