<div class="cs-styleguide__title">
    Carousels
</div>

<div class="cs-styleguide__section cs-styleguide__section--columns">

    <div>
        <div style="display: flex;width: 140px;justify-content: space-between;">

            <button class="cs-hero__nav cs-hero__nav--prev cs-hero__nav--large" type="button" style="position:relative; transform: initial; left: 0; top: 0;">
                <svg class="cs-hero__nav-icon">
                    <use xlink:href="#icon_arrow-left"></use>
                </svg>
            </button>

            <button class="cs-hero__nav cs-hero__nav--next cs-hero__nav--large" type="button" style="position:relative; transform: initial; left: 0; top: 0;">
                <svg class="cs-hero__nav-icon">
                    <use xlink:href="#icon_arrow-right"></use>
                </svg>
            </button>

        </div>
    </div>


    <div>
        <ul class="cs-hero__pagination" style="position: relative; transform: initial; left: 0;">
            <li class="cs-hero__pagination-item">
                <button class="cs-hero__pagination-button">1</button>
            </li>
            <li class="cs-hero__pagination-item cs-hero__pagination-item--active">
                <button class="cs-hero__pagination-button">2</button>
            </li>
            <li class="cs-hero__pagination-item">
                <button class="cs-hero__pagination-button">3</button>
            </li>
        </ul>
    </div>

</div>