<div class="cs-styleguide__title">
    Color palette
</div>

<div class="cs-styleguide__section">
    <div class="cs-styleguide__color-section">
        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #324dcf;">
            </div>
            <div class="cs-styleguide__color-text">
                Main 1 <br>
                CeruleanBlue <br>
                #324dcf <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #142b9e;">
            </div>
            <div class="cs-styleguide__color-text">
                Support 1 <br>
                CeruleanBlueHover <br>
                #142b9e <br>
            </div>
        </div>

    </div>

    <div class="cs-styleguide__color-section">
        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #212121;">
            </div>
            <div class="cs-styleguide__color-text">
                Main 3 <br>
                MineShaft <br>
                #212121 <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #696969;">
            </div>
            <div class="cs-styleguide__color-text">
                Support 2 <br>
                DoveGray <br>
                #696969 <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #888;">
            </div>
            <div class="cs-styleguide__color-text">
                Support 3 <br>
                Gray <br>
                #888888 <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #dcdcdc;">
            </div>
            <div class="cs-styleguide__color-text">
                Support 4 <br>
                Alto <br>
                #dcdcdc <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #f0f0f0;">
            </div>
            <div class="cs-styleguide__color-text">
                Support 3 <br>
                Gallery  <br>
                #f0f0f0 <br>
            </div>
        </div>

    </div>

    <div class="cs-styleguide__color-section">
        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #fff;border: 1px solid #dcdcdc;">
            </div>
            <div class="cs-styleguide__color-text">
                Background 1 <br>
                White <br>
                #ffffff <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #000;;">
            </div>
            <div class="cs-styleguide__color-text">
                Background 2 <br>
                Black <br>
                #000000 <br>
            </div>
        </div>

    </div>

    <div class="cs-styleguide__color-section">
        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #37b841;">
            </div>
            <div class="cs-styleguide__color-text">
                Validation 1 <br>
                Apple <br>
                #37b841 <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #d5efd7;">
            </div>
            <div class="cs-styleguide__color-text">
                Validation 2 <br>
                Peppermint  <br>
                #d5efd7 <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #e41f12;">
            </div>
            <div class="cs-styleguide__color-text">
                Validation 3 <br>
                Crimson <br>
                #e41f12 <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #f8d0ce;">
            </div>
            <div class="cs-styleguide__color-text">
                Validation 4 <br>
                Azaela <br>
                #f8d0ce <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #fed400;">
            </div>
            <div class="cs-styleguide__color-text">
                Support 6 <br>
                Gold <br>
                #fed400 <br>
            </div>
        </div>

        <div class="cs-styleguide__color">
            <div class="cs-styleguide__color-color" style="background: #fdf4ca;">
            </div>
            <div class="cs-styleguide__color-text">
                Validation 5 <br>
                HalfColonialWhite <br>
                #fdf4ca <br>
            </div>
        </div>

    </div>


</div>
