<div class="cs-styleguide__section cs-styleguide__section--colors">
        <h2 class="cs-styleguide__title">Color palette</h2>
        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--primary-500">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Primary 500</p>
                    <p>$color_primary-500</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--primary-800">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Primary 800</p>
                    <p>$color_primary-800</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--secondary-200">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Secondary 200</p>
                    <p>$color_secondary-200</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--secondary-500">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Secondary 500</p>
                    <p>$color_secondary-500</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--background-200">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Background 200</p>
                    <p>$color_background-200</p>
                </div>
            </div>

            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--background-500">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Background 500</p>
                    <p>$color_background-500</p>
                </div>
            </div>

            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--background-600">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Background 600</p>
                    <p>$color_background-600</p>
                </div>
            </div>

            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--background-700">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Background 700</p>
                    <p>$color_background-700</p>
                </div>
            </div>

            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--background-800">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Background 800</p>
                    <p>$color_background-800</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--border-100">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Border 100</p>
                    <p>$color_border-100</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--border-200">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Border 200</p>
                    <p>$color_border-200</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--border-500">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Border 500</p>
                    <p>$color_border-500</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--border-700">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Border 700</p>
                    <p>$color_border-700</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--error-200">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Error 200</p>
                    <p>$color_error-200</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--error-500">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Error 500</p>
                    <p>$color_error-500</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--error-600">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Error 600</p>
                    <p>$color_error-600</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--warning-200">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Warning 200</p>
                    <p>$color_warning-200</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--warning-500">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Warning 500</p>
                    <p>$color_warning-500</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--warning-600">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Warning 600</p>
                    <p>$color_warning-600</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--warning-700">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Warning 700</p>
                    <p>$color_warning-700</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
            <div class="cs-styleguide__box-color cs-styleguide__box-color--success-200">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Success 200</p>
                    <p>$color_success-200</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--success-500">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Success 500</p>
                    <p>$color_success-500</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--success-600">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Success 600</p>
                    <p>$color_success-600</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--success-700">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Success 700</p>
                    <p>$color_success-700</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors">
            <div class="cs-styleguide__box-wrapper">
            <div class="cs-styleguide__box-color cs-styleguide__box-color--review-active">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Review Active</p>
                    <p>$color_review-active</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--review-bar-active">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Review Bar Active</p>
                    <p>$color_review-bar-active</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--review-inactive">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Review Inactive</p>
                    <p>$color_review-inactive</p>
                </div>
            </div>
            <div class="cs-styleguide__box-wrapper">
                <div class="cs-styleguide__box-color cs-styleguide__box-color--review-control-inactive">
                </div>
                <div class="cs-styleguide__box-text">
                    <p>Color Review Control Inactive</p>
                    <p>$color_review-control-inactive</p>
                </div>
            </div>
        </div>

        <div class="cs-styleguide__box-group cs-styleguide__box-group--colors cs-styleguide__box-group--extra-colors">
            <?= $block->getChildHtml('styleguide_extra_colors'); ?>
        </div>
    </div>
