<div class="cs-styleguide__title">
    Extras
</div>

<div class="cs-styleguide__section cs-styleguide__section--space">


    <div class="cs-star-rating ">
        <span class="cs-star-rating__stars">
            <i class="cs-star-rating__star cs-star-rating__star--active"></i>
            <i class="cs-star-rating__star cs-star-rating__star--active"></i>
            <i class="cs-star-rating__star cs-star-rating__star--active"></i>
            <i class="cs-star-rating__star cs-star-rating__star--active"></i>
            <i class="cs-star-rating__star"></i>
        </span>
        <span class="cs-star-rating__text">
            <span itemprop="ratingValue">4</span> / <span itemprop="bestRating">5</span> <span itemprop="reviewCount">(3 Reviews)</span>
        </span>
    </div>


    <ul class="cs-progress-bar">
        <li class="cs-progress-bar__item _complete">
            <span class="cs-progress-bar__indicator-wrapper">
                <span class="cs-progress-bar__indicator"></span>
            </span>
            <span class="cs-progress-bar__item-text">Shipping</span>
        </li>

        <li class="cs-progress-bar__item _active">
            <span class="cs-progress-bar__indicator-wrapper">
                <span class="cs-progress-bar__indicator"></span>
            </span>
            <span class="cs-progress-bar__item-text">Review &amp; Payments</span>
        </li>

        <li class="cs-progress-bar__item">
            <span class="cs-progress-bar__indicator-wrapper">
                <span class="cs-progress-bar__indicator"></span>
            </span>
            <span class="cs-progress-bar__item-text">Thank you</span>
        </li>
    </ul>



    <div class="cs-stack-nav">
        <div class="cs-stack-nav__content | account-nav | cs-collapse cs-collapse--only-mobile">
            <div class="cs-stack-nav__trigger | cs-collapse__trigger cs-collapse__trigger--arrowed cs-collapse__trigger--in">
                My Account Menu
                <svg class="cs-stack-nav__trigger-icon | cs-collapse__trigger-icon">
                    <use xlink:href="#arrow_next"></use>
                </svg>
            </div>
            <nav class="cs-stack-nav__nav | nav items | cs-collapse__content cs-collapse__content--in">
                <ul class="cs-stack-nav__list">
                    <li class="nav item current"><strong>Account Information</strong></li>
                    <li class="nav item"><a href="#">Edit Account Information</a></li>
                    <li class="nav item"><a href="#">My Addresses</a></li>
                    <li class="nav item"><a href="#">My Downloadable Products</a></li>
                    <li class="nav item"><a href="#">My Orders</a></li>
                    <li class="nav item"><a href="#">Newsletter Subscriptions</a></li>
                    <li class="nav item"><a href="#">My Product Reviews</a></li>
                    <li class="nav item"><a href="#">My Wish List</a></li>
                </ul>
            </nav>
        </div>
    </div>


</div>