<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <div class="cs-styleguide__title">
        Forms
    </div>


    <div class="cs-styleguide__section cs-styleguide__section--columns" >


        <div>
            <div class="field">
                <label for="street" class="label">
                    Label
                </label>

                <div class="control">
                    <input type="text" name="street" id="street" value="" title="Street" class="input-text"
                           autocomplete="off">
                </div>
            </div>
        </div>

        <div>
            <div class="field | _with-tooltip">
                <label for="company" class="cs-input__label">
                    Label - input with tooltip text
                </label>

                <div class="control">
                    <input type="text" name="company" id="company" value="" title="Company" class="input-text"
                           autocomplete="off">
                </div>
                <div class="field-tooltip toggle">
                <span class="field-tooltip-action action-help" tabindex="0" data-toggle="dropdown"
                      data-bind="mageInit: {'dropdown':{'activeClass': '_active'}}" aria-haspopup="true"
                      aria-expanded="false"></span>

                    <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true">
                        For delivery questions.
                    </div>
                </div>
            </div>
        </div>

        <div>
            <div class="field">
                <label for="name" class="cs-input__label">
                    Label - disabled input
                </label>

                <div class="control">
                    <input type="text" name="zip" id="zip" value="" title="Zip" class="input-text" disabled
                           autocomplete="off" placeholder="Disabled">
                </div>
            </div>
        </div>

        <div>
            <div class="field | required">
                <label for="street1" class="label">
                    Label - required field
                </label>

                <div class="control">
                    <input type="text" name="street1" id="street1" value="" title="Street1" class="input-text"
                           autocomplete="off">
                </div>
            </div>
        </div>

        <div>
            <div class="field | required _error">
                <label for="name" class="label">
                    Label - required input with error
                </label>

                <div class="control">
                    <input type="text" name="name" id="name" value="" title="Name" class="input-text | mage-error"
                           autocomplete="off">
                </div>
                <div for="name" generated="true" class="mage-error" id="name-error" style="display: block;">This is a
                    required field.
                </div>
            </div>
        </div>

        <div></div>
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--columns"  style="background: white;">
        <div>
            <div class="field password required">
                <label for="password" class="label"><span>Password</span></label>
                <div class="control">
                    <input type="password" name="password" id="password" title="Password" class="input-text valid" value="xxxxxxxxxxx">
                    <div id="password-strength-meter-container" class="password-very-strong">
                        <div id="password-strength-meter" class="password-strength-meter">
                            Password Strength:
                            <span id="password-strength-meter-label">Very Strong</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="field password required">
                <label for="password" class="label"><span>Password</span></label>
                <div class="control">
                    <input type="password" name="password" id="password" title="Password" class="input-text" value="xxxxxx">
                    <div id="password-strength-meter-container" class="password-medium">
                        <div id="password-strength-meter" class="password-strength-meter">
                            Password Strength:
                            <span id="password-strength-meter-label">Medium</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="field password required">
                <label for="password" class="label"><span>Password</span></label>
                <div class="control">
                    <input type="password" name="password" id="password" title="Password" class="input-text mage-error" value="xxx">
                    <div for="password" class="mage-error" id="password-error">Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.</div>
                    <div id="password-strength-meter-container" class="password-weak">
                        <div id="password-strength-meter" class="password-strength-meter">
                            Password Strength:
                            <span id="password-strength-meter-label">Weak</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns"  style="padding: 0; width: 100%; background: white;">
        <div class="field _required" name="shippingAddress.country_id" style="padding-right: 4rem; width: 40rem;">
            <label class="label">
                <span>Htmlselect</span>
            </label>

            <div class="control">
                <select class="cs-select">
                    <option value="position" selected="selected"> Position</option>
                    <option value="name"> Product Name</option>
                    <option value="price"> Price</option>
                </select>
            </div>
        </div>    

        <div class="field _required" name="shippingAddress.country_id" style="width: 40rem;">
            <label class="label">
                <span>Normal select</span>
            </label>

            <div class="control">
                <select class="select" name="country_id">
                    <option data-title="Afghanistan" value="AF">Afghanistan</option>
                    <option data-title="Åland Islands" value="AX">Åland Islands</option>
                    <option data-title="Albania" value="AL">Albania</option>
                    <option data-title="Algeria" value="DZ">Algeria</option>
                    <option data-title="American Samoa" value="AS">American Samoa</option>
                </select>    
            </div>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns"  style="background: white;">
        <div>
            <div class="field">
                <input type="radio" class="radio" id="styleguide-radio-1"/>
                <label for="styleguide-radio-1" class="label">Label</label>
            </div>
        </div>
        <div>
            <div class="field">
                <input type="radio" class="radio" id="styleguide-radio-2" disabled/>
                <label for="styleguide-radio-2" class="label">Disabled</label>
            </div>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns"  style="background: white;">
        <div>
            <div class="field">
                <input type="checkbox" class="checkbox" id="billing-address-book"/>
                <label class="label" for="billing-address-book">
                    Save in address book
                </label>
            </div>
        </div>
        <div>
            <div class="field">
                <input type="checkbox" class="checkbox" id="billing-address-book" disabled/>
                <label class="label" for="billing-address-book">
                    Save in address book
                </label>
            </div>
        </div>

        <div>
            <div class="field | required">
                <input type="checkbox" name="checkbox-error"id="checkbox-error" class="checkbox required-entry mage-error">
                <label for="checkbox-error" class="label">Sign Up for Newsletter</label>
                <div for="checkbox-error" class="mage-error">This is a required field.</div>
            </div>
        </div>
    </div>


    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section">

        <div id="ui-datepicker-div" class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all"
             style="display: block;">
            <div class="ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all"><a
                    class="ui-datepicker-prev ui-corner-all" data-handler="prev" data-event="click" title="Prev"><span
                        class="ui-icon ui-icon-circle-triangle-w">Prev</span></a><a
                    class="ui-datepicker-next ui-corner-all ui-state-disabled" title="Next"><span
                        class="ui-icon ui-icon-circle-triangle-e">Next</span></a>

                <div class="ui-datepicker-title"><select class="ui-datepicker-month" data-handler="selectMonth"
                                                         data-event="change">
                        <option value="0" selected="selected">Jan</option>
                    </select><select class="ui-datepicker-year" data-handler="selectYear" data-event="change">
                        <option value="2000">2000</option>
                        <option value="2001">2001</option>
                        <option value="2002">2002</option>
                        <option value="2003">2003</option>
                        <option value="2004">2004</option>
                        <option value="2005">2005</option>
                        <option value="2006">2006</option>
                        <option value="2007">2007</option>
                        <option value="2008">2008</option>
                        <option value="2009">2009</option>
                        <option value="2010">2010</option>
                        <option value="2011">2011</option>
                        <option value="2012">2012</option>
                        <option value="2013">2013</option>
                        <option value="2014">2014</option>
                        <option value="2015">2015</option>
                        <option value="2016">2016</option>
                        <option value="2017" selected="selected">2017</option>
                    </select></div>
            </div>
            <table class="ui-datepicker-calendar">
                <thead>
                <tr>
                    <th class="ui-datepicker-week-end"><span title="Sunday">Su</span></th>
                    <th><span title="Monday">Mo</span></th>
                    <th><span title="Tuesday">Tu</span></th>
                    <th><span title="Wednesday">We</span></th>
                    <th><span title="Thursday">Th</span></th>
                    <th><span title="Friday">Fr</span></th>
                    <th class="ui-datepicker-week-end"><span title="Saturday">Sa</span></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="0"
                        data-year="2017"><a class="ui-state-default" href="#">1</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">2</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">3</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">4</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">5</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">6</a></td>
                    <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="0"
                        data-year="2017"><a class="ui-state-default" href="#">7</a></td>
                </tr>
                <tr>
                    <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="0"
                        data-year="2017"><a class="ui-state-default" href="#">8</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">9</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">10</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">11</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">12</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">13</a></td>
                    <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="0"
                        data-year="2017"><a class="ui-state-default" href="#">14</a></td>
                </tr>
                <tr>
                    <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="0"
                        data-year="2017"><a class="ui-state-default" href="#">15</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">16</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">17</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">18</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">19</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">20</a></td>
                    <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="0"
                        data-year="2017"><a class="ui-state-default" href="#">21</a></td>
                </tr>
                <tr>
                    <td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="0"
                        data-year="2017"><a class="ui-state-default" href="#">22</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">23</a></td>
                    <td class=" " data-handler="selectDay" data-event="click" data-month="0" data-year="2017"><a
                            class="ui-state-default" href="#">24</a></td>
                    <td class=" ui-datepicker-days-cell-over " data-handler="selectDay" data-event="click"
                        data-month="0" data-year="2017"><a class="ui-state-default ui-state-hover" href="#">25</a></td>
                    <td class=" ui-datepicker-unselectable ui-state-disabled  ui-datepicker-today"><span
                            class="ui-state-default">26</span></td>
                    <td class=" ui-datepicker-unselectable ui-state-disabled "><span class="ui-state-default">27</span>
                    </td>
                    <td class=" ui-datepicker-week-end ui-datepicker-unselectable ui-state-disabled "><span
                            class="ui-state-default">28</span></td>
                </tr>
                <tr>
                    <td class=" ui-datepicker-week-end ui-datepicker-unselectable ui-state-disabled "><span
                            class="ui-state-default">29</span></td>
                    <td class=" ui-datepicker-unselectable ui-state-disabled "><span class="ui-state-default">30</span>
                    </td>
                    <td class=" ui-datepicker-unselectable ui-state-disabled "><span class="ui-state-default">31</span>
                    </td>
                    <td class=" ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled">&nbsp;</td>
                    <td class=" ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled">&nbsp;</td>
                    <td class=" ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled">&nbsp;</td>
                    <td class=" ui-datepicker-week-end ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled">
                        &nbsp;</td>
                </tr>
                </tbody>
            </table>
        </div>


    </div>

</div>





