<div class="cs-styleguide__title">
    Forms
</div>

<div class="cs-styleguide__section cs-styleguide__section--columns">
    <form class="cs-header-search | cs-input" style="width: 40rem">
        <input class="cs-header-search__input | cs-input__input" type="search" name="q" value="" placeholder="Search entire store here..." maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">

        <div class="cs-header-search__autocomplete" style="display: none;"></div>
        <div class="cs-input__button">
            <button class="cs-button cs-button--look_default cs-button--look_on-input" type="submit">
                <svg class="cs-button__icon cs-button__icon--center cs-button__icon--search">
                    <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#search"></use>
                </svg>
                <span class="cs-visually-hidden">Search</span>
            </button>
        </div>
    </form>

    <div class="cs-form__field | cs-input | _with-tooltip">
        <label for="company" class="cs-input__label">
            Company
        </label>

        <div class="cs-input__control">
            <input type="text" name="company" id="company" value="" title="Company" class="cs-input__input" autocomplete="off">
        </div>
        <div class="field-tooltip toggle">
            <span class="field-tooltip-action action-help" tabindex="0" data-toggle="dropdown" data-bind="mageInit: {'dropdown':{'activeClass': '_active'}}" aria-haspopup="true" aria-expanded="false"></span>

            <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true">
               For delivery questions.
            </div>
        </div>
    </div>
    <div class="cs-form__field | cs-input | required">
        <label for="street" class="cs-input__label">
            Street address
        </label>

        <div class="cs-input__control">
            <input type="text" name="street" id="street" value="" title="Street" class="cs-input__input" autocomplete="off">
        </div>
    </div>

    <div class="cs-form__field | cs-input | _error">
        <label for="name" class="cs-input__label">
            Name
        </label>

        <div class="cs-input__control">
            <input type="text" name="name" id="name" value="" title="Name" class="cs-input__input" autocomplete="off">
        </div>
        <div for="name" generated="true" class="mage-error" id="name-error" style="display: block;">This is a required field.</div>
    </div>
    <div class="cs-form__field | cs-input">
        <label for="name" class="cs-input__label">
            Zip
        </label>

        <div class="cs-input__control">
            <input type="text" name="zip" id="zip" value="" title="Zip" class="cs-input__input" disabled autocomplete="off" placeholder="Disabled">
        </div>
    </div>

    <div class="cs-input" style="width: 40rem">

        <?= $this->getLayout()->createBlock('Creativestyle\FrontendExtension\Block\Twig', 'select-sorter', ['data' => ['params' => 'id=sorter data-role=sorter', 'options' => array(0 => array("value" => "position", "label" => "Position", "params" => "selected=selected"), 1 => array("value" => "name", "label" => "Product Name"), 2 => array("value" => "price", "label" => "Price")),]])->setTemplate("select/select.twig")->toHtml(); ?>
    </div>


    <div class="cs-form__field | cs-input | password required">
        <label for="password" class="cs-input__label"><span>Password</span></label>

        <div class="cs-input__control">
            <input type="password" name="password" id="password" title="Password" class="input-text mage-error" data-password-min-length="8" data-password-min-character-sets="3" required autocomplete="off" aria-invalid="true" aria-describedby="password-error">

            <div id="password-strength-meter-container" data-role="password-strength-meter" class="password-strength-meter-1">
                <div id="password-strength-meter" class="password-strength-meter">
                    Password Strength:
                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">Weak</span>

                    <div class="password-strength-meter__icons-wrapper">
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                    </div>
                </div>
            </div>
        </div>

        <div for="password" generated="true" class="mage-error" id="password-error" style="display: block;">Minimum length of this field must be equal or greater than 8 symbols. Leading and trailing spaces will be ignored.</div>
    </div>

    <div class="cs-form__field | cs-input | password required">
        <label for="password" class="cs-input__label"><span>Password</span></label>

        <div class="cs-input__control">
            <input type="password" name="password" id="password" title="Password" class="input-text" data-password-min-length="8" data-password-min-character-sets="3" required autocomplete="off">

            <div id="password-strength-meter-container" data-role="password-strength-meter" class="password-strength-meter-4">
                <div id="password-strength-meter" class="password-strength-meter">
                    Password Strength:
                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">Very strong</span>

                    <div class="password-strength-meter__icons-wrapper">
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                        <svg class="password-strength-meter__icon">
                            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                        </svg>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div>
        <div class="cs-input cs-input--type-radio">
            <input type="radio" class="cs-input__radio" id="styleguide-radio"/>
            <label for="styleguide-radio" class="cs-input__label">Label</label>
        </div>

        <div class="cs-input cs-input--type-radio">
            <input type="radio" class="cs-input__radio" id="styleguide-radio2"/>
            <label for="styleguide-radio2" class="cs-input__label  cs-input__label--big">Big label</label>
        </div>

        <div class="cs-input cs-input--type-radio">
            <input type="radio" class="cs-input__radio" id="styleguide-radio3" disabled />
            <label for="styleguide-radio3" class="cs-input__label">Disabled</label>
        </div>

        <div style="width: 100%;margin-top: 3rem;">

            <div class="cs-input | cs-qty-increment ">
                <input type="number" name="qty" size="2" maxlength="" class="cs-input__input | cs-qty-increment__input" value="1">

                <button type="button" class="cs-qty-increment__button cs-qty-increment__button--decrement cs-qty-increment__button--disabled" disabled="disabled">
                    <svg class="cs-qty-increment__icon cs-qty-increment__icon--minus">
                        <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#minus"></use>
                    </svg>
                </button>

                <button type="button" class="cs-qty-increment__button cs-qty-increment__button--increment">
                    <svg class="cs-qty-increment__icon cs-qty-increment__icon--plus">
                        <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#plus"></use>
                    </svg>
                </button>
            </div>

        </div>
    </div>

    <div class="">
        <div class="cs-input cs-input--type-checkbox">
            <input type="checkbox" class="cs-input__checkbox" id="billing-address-book" />
            <label class="cs-input__label" for="billing-address-book">
                Save in address book
            </label>
        </div>

        <div class="cs-input cs-input--type-checkbox">
            <input type="checkbox" class="cs-input__checkbox" id="shipping-address-book" disabled />
            <label class="cs-input__label" for="shipping-address-book">
                Save in address book
            </label>
        </div>

        <div class="cs-input cs-input--type-checkbox | required">
            <input type="checkbox" name="checkbox-error" title="Sign Up for Newsletter" value="1" id="checkbox-error" class="cs-input__checkbox required-entry mage-error" aria-invalid="true" aria-describedby="is_subscribed-error">
            <label for="checkbox-error" class="cs-input__label">Sign Up for Newsletter</label>
            <div for="checkbox-error" generated="true" class="mage-error" id="is_subscribed-error">This is a required field.</div>
        </div>


        <div class="cs-input cs-input--type-checkbox">
            <input type="checkbox" class="cs-input__checkbox" id="long-label" />
            <label class="cs-input__label" for="long-label">
                <a href="#" class="cs-link" target="_blank">Sed ut perspiciatis unde</a> omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit
            </label>
        </div>

    </div>



</div>