<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <div class="cs-styleguide__title">
        Icons
    </div>


    <div class="cs-styleguide__section">
        <?php

        $icons = [
            'arrow_prev','arrow_next', 'icon_arrow-left', 'icon_arrow-right', 'close', 'check', 'rhomb',
            'user', 'heart', 'cart', 'search',
            'edit', 'remove', 'plus', 'minus',
            'burger',  'compare', 'logout', 'sign-in', 'pin', 'share', 'mail',
            'facebook', 'you_tube', 'google_plus',
            'available', 'packaging', 'shipping',
            'dhl', 'hermes', 'gls',
            'giropay',  'klarna', 'mastercard', 'visa', 'paydirekt', 'paypal', 'electronic_cash', 'sofort_uberweisung',
            'bank_transfer', 'authorize_net', 'advance_payment', 'purchase_order', 'on_delivery', 'money_order',
            'invoice', 'direct_debit', 'creditcard'
        ]

        ?>


        <?php foreach ($icons as $icon): ?>
            <div class="cs-styleguide__box-wrapper cs-styleguide__box-wrapper--small">
                <div class="cs-styleguide__box">
                    <svg class="cs-styleguide__icon">
                        <use xlink:href="#<?php echo $icon; ?>"></use>
                    </svg>
                </div>
                <div class="cs-styleguide__box-text">
                    <?php echo $icon; ?>
                </div>
            </div>
        <?php endforeach; ?>

    </div>
</div>