<div class="cs-styleguide__container">

    <div class="cs-styleguide__title">
        Information design
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--wide">
        <div class="cs-headline">
            <h2 class="cs-headline__title">Headline</h2>

            <p class="cs-headline__subtitle">Subheadline text</p>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>


    <div class="cs-styleguide__section cs-styleguide__section--wide">
        <div class="cs-cms-block">
            <h2>Headline H2</h2>

            <p><strong>For science, for music</strong></p>

            <p>Phasellus vitae ipsum ac quam venenatis sodales. Etiam ut tellus sed diam eleifend
                volutpat.
                Sed ut lacus et purus tempor volutpat molestie sit amet lacus. Vestibulum ultrices diam sapien, vel
                consectetur
                nisl placerat vitae. Nunc at justo tempus, varius urna et, posuere orci. Donec in egestas urna, in
                mattis purus.
                Vestibulum pretium consectetur consectetur. Quisque egestas, urna eget imperdiet tempor, arcu quam
                sodales
                risus, quis accumsan risus nisi ac augue. Sed porta orci eu eros mattis feugiat. Duis sed sollicitudin
                odio.
                Duis vitae tellus vel velit varius sagittis.</p>

            <p><strong>For science, for music</strong></p>

            <p>Phasellus vitae ipsum ac quam venenatis sodales. Etiam ut tellus sed diam eleifend
                volutpat.
                Sed ut lacus et purus tempor volutpat molestie sit amet lacus. Vestibulum ultrices diam sapien, vel
                consectetur
                nisl placerat vitae. Nunc at justo tempus, varius urna et, posuere orci. Donec in egestas urna, in
                mattis purus.
                Vestibulum pretium consectetur consectetur. Quisque egestas, urna eget imperdiet tempor, arcu quam
                sodales
                risus, quis accumsan risus nisi ac augue. Sed porta orci eu eros mattis feugiat. Duis sed sollicitudin
                odio.
                Duis vitae tellus vel velit varius sagittis.</p>
        </div>

    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">

        <ul class="cs-list cs-list--unstyled">

            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Check out faster
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Save multiple shipping addresses
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Access your order history
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Track new orders
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Save items to your wish list
            </li>

        </ul>


        <div class="cs-cms-block">
            <ul>
                <li>Japanese quartz movement.</li>
                <li>Strap fits 7" to 8.0".</li>
                <li>Japanese quartz movement.</li>
                <li>Strap fits 7" to 8.0".</li>
            </ul>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section">

        <div class="table-wrapper">
            <table class="data table">
                <caption class="table-caption">Orders</caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id">Order #</th>
                        <th scope="col" class="col date">Date</th>
                        <th scope="col" class="col shipping">Ship To</th>
                        <th scope="col" class="col total">Order Total</th>
                        <th scope="col" class="col status">Status</th>
                        <th scope="col" class="col actions">Action</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td data-th="Order #" class="col id">000000006</td>
                    <td data-th="Date" class="col date">15.01.17</td>
                    <td data-th="Ship To" class="col shipping">Max Mustermann</td>
                    <td data-th="Order Total" class="col total"><span class="price">47,00&nbsp;$</span></td>
                    <td data-th="Status" class="col status">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/6/" class="action view">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/6/" class="action order">
                            Reorder
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="col id">000000007</td>
                    <td data-th="Date" class="col date">25.04.17</td>
                    <td data-th="Ship To" class="col shipping">Emma Braun</td>
                    <td data-th="Order Total" class="col total"><span class="price">33,60&nbsp;$</span></td>
                    <td data-th="Status" class="col tatus">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/5/" class="action view">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="action order">
                            Reorder
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="col id">000000005</td>
                    <td data-th="Date" class="col date">25.01.17</td>
                    <td data-th="Ship To" class="col shipping">Emma Braun</td>
                    <td data-th="Order Total" class="col total"><span class="price">233,60&nbsp;$</span>
                    </td>
                    <td data-th="Status" class="col status">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/5/" class="action view">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="action order">
                            Reorder
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
