<div class="cs-styleguide__container">

    <div class="cs-styleguide__title">
        Information design
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--wide">
        <div class="cs-headline">
            <h2 class="cs-headline__title">Headline</h2>

            <p class="cs-headline__subtitle">Subheadline text</p>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--wide">

        <?= $this->getLayout()->createBlock('Creativestyle\FrontendExtension\Block\Twig', 'my-reviews-rating2',
            ['data' => [
                'shownumbers' => true,
                'categories' => [
                    'main_category' => [
                        'name' => 'Product category',
                        'url' => '',
                        'products_count' => '123'
                    ],
                    'sub_categories' => [
                        [
                            'name' => 'Jackets',
                            'url' => '',
                            'products_count' => '12'
                        ],
                        [
                            'name' => 'Hoodies & Sweatshirt',
                            'url' => '',
                            'products_count' => '42'
                        ],
                        [
                            'name' => 'Tees',
                            'url' => '',
                            'products_count' => '32'
                        ],
                        [
                            'name' => 'Bras & Tanks',
                            'url' => '',
                            'products_count' => '52'
                        ]
                    ]
                ],
                'activeStars' => 3.5,
                'text' => '(34 Ratings)'
            ]
            ])->setTemplate("star-rating/star-rating.twig")->toHtml(); ?>


        <div class="cs-category-links ">
            <h2 class="cs-category-links__title">
                Product category
            </h2>

            <div class="cs-category-links__dropdown cs-category-links-dropdown">

                <div class="cs-category-links__subtitle | cs-category-links-dropdown__trigger">
                    All products<span class="cs-category-links__qty">(50)
            </span>
                </div>

                <div class="cs-category-links__list-wrapper | cs-category-links-dropdown__content">
                    <ul class="cs-category-links__list">
                        <li class="cs-category-links__list-item ">
                            <a href="http://demo.creativeshop.io/women/tops-women/jackets-women.html"
                               class="cs-category-links__link">
                                Jackets<span class="cs-category-links__qty">(12)
                            </span>

                            </a>
                        </li>
                        <li class="cs-category-links__list-item ">
                            <a href="http://demo.creativeshop.io/women/tops-women/hoodies-and-sweatshirts-women.html"
                               class="cs-category-links__link">
                                Hoodies &amp; Sweatshirts<span class="cs-category-links__qty">(12)
                            </span>

                            </a>
                        </li>
                        <li class="cs-category-links__list-item ">
                            <a href="http://demo.creativeshop.io/women/tops-women/tees-women.html"
                               class="cs-category-links__link">
                                Tees<span class="cs-category-links__qty">(12)
                            </span>

                            </a>
                        </li>
                        <li class="cs-category-links__list-item ">
                            <a href="http://demo.creativeshop.io/women/tops-women/tanks-women.html"
                               class="cs-category-links__link">
                                Bras &amp; Tanks<span class="cs-category-links__qty">(14)
                            </span>

                            </a>
                        </li>
                    </ul>

                    <ul class="cs-category-links__list-all">
                        <li class="cs-category-links__list-all-item">
                            <a href="http://demo.creativeshop.io/women/tops-women.html" class="cs-category-links__link">
                                All products<span class="cs-category-links__qty">(50)
                        </span>

                                <svg class="cs-category-links__list-all-icon">
                                    <use xlink:href="#icon_arrow-right"></use>
                                </svg>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>


    <div class="cs-styleguide__section cs-styleguide__section--wide">
        <div class="cs-cms-block">
            <h2>Headline H2</h2>

            <p><strong>For science, for music</strong></p>

            <p>Phasellus vitae ipsum ac quam venenatis sodales. Etiam ut tellus sed diam eleifend
                volutpat.
                Sed ut lacus et purus tempor volutpat molestie sit amet lacus. Vestibulum ultrices diam sapien, vel
                consectetur
                nisl placerat vitae. Nunc at justo tempus, varius urna et, posuere orci. Donec in egestas urna, in
                mattis purus.
                Vestibulum pretium consectetur consectetur. Quisque egestas, urna eget imperdiet tempor, arcu quam
                sodales
                risus, quis accumsan risus nisi ac augue. Sed porta orci eu eros mattis feugiat. Duis sed sollicitudin
                odio.
                Duis vitae tellus vel velit varius sagittis.</p>

            <p><strong>For science, for music</strong></p>

            <p>Phasellus vitae ipsum ac quam venenatis sodales. Etiam ut tellus sed diam eleifend
                volutpat.
                Sed ut lacus et purus tempor volutpat molestie sit amet lacus. Vestibulum ultrices diam sapien, vel
                consectetur
                nisl placerat vitae. Nunc at justo tempus, varius urna et, posuere orci. Donec in egestas urna, in
                mattis purus.
                Vestibulum pretium consectetur consectetur. Quisque egestas, urna eget imperdiet tempor, arcu quam
                sodales
                risus, quis accumsan risus nisi ac augue. Sed porta orci eu eros mattis feugiat. Duis sed sollicitudin
                odio.
                Duis vitae tellus vel velit varius sagittis.</p>
        </div>

    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">

        <ul class="cs-list cs-list--unstyled">

            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Check out faster
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Save multiple shipping addresses
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Access your order history
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Track new orders
            </li>
            <li class="cs-list__item">
                <svg class="cs-list__bullet cs-list__bullet--tick">
                    <use xlink:href="#check"></use>
                </svg>
                Save items to your wish list
            </li>

        </ul>


        <div class="cs-cms-block">
            <ul>
                <li>Japanese quartz movement.</li>
                <li>Strap fits 7" to 8.0".</li>
                <li>Japanese quartz movement.</li>
                <li>Strap fits 7" to 8.0".</li>
            </ul>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>


    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <div style="width:100%;">
            <div class="cs-attributes-list">
                <dl class="cs-attributes-list__list cs-attributes-list__list--columns"
                    id="product-attribute-specs-table">
                    <dt class="cs-attributes-list__item-label">Breathable:
                    </dt>
                    <dd class="cs-attributes-list__item">
                        Yes
                    </dd>
                    <dt class="cs-attributes-list__item-label">Climate:
                    </dt>
                    <dd class="cs-attributes-list__item">
                        Cool, Spring, Windy, Wintry
                    </dd>
                    <dt class="cs-attributes-list__item-label">Style:
                    </dt>
                    <dd class="cs-attributes-list__item">
                        Jacket, Lightweight, Full Zip
                    </dd>
                    <dt class="cs-attributes-list__item-label">Endurance:
                    </dt>
                    <dd class="cs-attributes-list__item">
                        Nylon, Polyester, CoolTech™
                    </dd>
                    <dt class="cs-attributes-list__item-label">Pattern:
                    </dt>
                    <dd class="cs-attributes-list__item">
                        Solid
                    </dd>
                    <dt class="cs-attributes-list__item-label">Manufacturer:
                    </dt>
                    <dd class="cs-attributes-list__item">
                        Cool, Spring, Windy, Wintry
                    </dd>
                </dl>
            </div>
        </div>

    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section">

        <div class="cs-table">
            <table class="cs-table__body">
                <caption class="cs-visually-hidden">Orders</caption>
                <thead class="cs-table__head">
                <tr>
                    <th scope="col" class="cs-table__col-head id">Order #</th>
                    <th scope="col" class="cs-table__col-head date">Date</th>
                    <th scope="col" class="cs-table__col-head shipping">Ship To</th>
                    <th scope="col" class="cs-table__col-head total">Order Total</th>
                    <th scope="col" class="cs-table__col-head status">Status</th>
                    <th scope="col" class="cs-table__col-head actions">Action</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td data-th="Order #" class="cs-table__col | id">000000006</td>
                    <td data-th="Date" class="cs-table__col | date">15.01.17</td>
                    <td data-th="Ship To" class="cs-table__col | shipping">Max Mustermann</td>
                    <td data-th="Order Total" class="cs-table__col | total"><span class="price">47,00&nbsp;$</span></td>
                    <td data-th="Status" class="cs-table__col | status">Pending</td>
                    <td data-th="Actions" class="cs-table__col cs-table__col--actions | actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/6/" class="cs-link cs-link--separator">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/6/" class="cs-link">
                            Reorder
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="cs-table__col | id">000000007</td>
                    <td data-th="Date" class="cs-table__col | date">25.04.17</td>
                    <td data-th="Ship To" class="cs-table__col | shipping">Emma Braun</td>
                    <td data-th="Order Total" class="cs-table__col | total"><span class="price">33,60&nbsp;$</span></td>
                    <td data-th="Status" class="cs-table__col | status">Pending</td>
                    <td data-th="Actions" class="cs-table__col cs-table__col--actions | actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/5/" class="cs-link cs-link--separator">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="cs-link">
                            Reorder
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="cs-table__col | id">000000005</td>
                    <td data-th="Date" class="cs-table__col | date">25.01.17</td>
                    <td data-th="Ship To" class="cs-table__col | shipping">Emma Braun</td>
                    <td data-th="Order Total" class="cs-table__col | total"><span class="price">233,60&nbsp;$</span>
                    </td>
                    <td data-th="Status" class="cs-table__col | status">Pending</td>
                    <td data-th="Actions" class="cs-table__col cs-table__col--actions | actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/5/" class="cs-link cs-link--separator">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="cs-link">
                            Reorder
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>