<div class="cs-styleguide__container">

    <div class="cs-styleguide__title">
        Table
    </div>

    <div class="cs-styleguide__section">
        <div class="table-wrapper">
            <table class="data table">
                <caption class="table-caption">Orders</caption>
                <thead>
                    <tr>
                        <th scope="col" class="col id">Order #</th>
                        <th scope="col" class="col date">Date</th>
                        <th scope="col" class="col shipping">Ship To</th>
                        <th scope="col" class="col total">Order Total</th>
                        <th scope="col" class="col status">Status</th>
                        <th scope="col" class="col actions">Action</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td data-th="Order #" class="col id">000000006</td>
                    <td data-th="Date" class="col date">15.01.17</td>
                    <td data-th="Ship To" class="col shipping">Max Mustermann</td>
                    <td data-th="Order Total" class="col total"><span class="price">47,00&nbsp;$</span></td>
                    <td data-th="Status" class="col status">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/6/" class="action view">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/6/" class="action order">
                            Reorder
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="col id">000000007</td>
                    <td data-th="Date" class="col date">25.04.17</td>
                    <td data-th="Ship To" class="col shipping">Emma Braun</td>
                    <td data-th="Order Total" class="col total"><span class="price">33,60&nbsp;$</span></td>
                    <td data-th="Status" class="col tatus">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/5/" class="action view">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="action order">
                            Reorder
                        </a>
                    </td>
                </tr>
                <tr>
                    <td data-th="Order #" class="col id">000000005</td>
                    <td data-th="Date" class="col date">25.01.17</td>
                    <td data-th="Ship To" class="col shipping">Emma Braun</td>
                    <td data-th="Order Total" class="col total"><span class="price">233,60&nbsp;$</span>
                    </td>
                    <td data-th="Status" class="col status">Pending</td>
                    <td data-th="Actions" class="col actions">
                        <a href="http://m2c.dev/sales/order/view/order_id/5/" class="action view">
                            View Order
                        </a>
                        <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="action order">
                            Reorder
                        </a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
</div>
