<div class="cs-styleguide__title">
    Lists
</div>

<div class="cs-styleguide__section cs-styleguide__section--columns">

    <ul class="cs-list cs-list--unstyled">

        <li class="cs-list__item">
            <svg class="cs-list__bullet cs-list__bullet--tick">
                <use xlink:href="#check"></use>
            </svg>
            Check out faster
        </li>
        <li class="cs-list__item">
            <svg class="cs-list__bullet cs-list__bullet--tick">
                <use xlink:href="#check"></use>
            </svg>
            Save multiple shipping addresses
        </li>
        <li class="cs-list__item">
            <svg class="cs-list__bullet cs-list__bullet--tick">
                <use xlink:href="#check"></use>
            </svg>
            Access your order history
        </li>
        <li class="cs-list__item">
            <svg class="cs-list__bullet cs-list__bullet--tick">
                <use xlink:href="#check"></use>
            </svg>
            Track new orders
        </li>
        <li class="cs-list__item">
            <svg class="cs-list__bullet cs-list__bullet--tick">
                <use xlink:href="#check"></use>
            </svg>
            Save items to your wish list
        </li>

    </ul>


    <div class="cs-cms-block">
        <ul>
            <li>Japanese quartz movement.</li>
            <li>Strap fits 7" to 8.0".</li>
            <li>Japanese quartz movement.</li>
            <li>Strap fits 7" to 8.0".</li>
        </ul>
    </div>

    <div style="width:100%;">
        <div class="cs-attributes-list">
            <dl class="cs-attributes-list__list cs-attributes-list__list--columns" id="product-attribute-specs-table">
                <dt class="cs-attributes-list__item-label">Breathable:
                </dt>
                <dd class="cs-attributes-list__item">
                    Yes
                </dd>
                <dt class="cs-attributes-list__item-label">Climate:
                </dt>
                <dd class="cs-attributes-list__item">
                    Cool, Spring, Windy, Wintry
                </dd>
                <dt class="cs-attributes-list__item-label">Style:
                </dt>
                <dd class="cs-attributes-list__item">
                    Jacket, Lightweight, Full Zip
                </dd>
                <dt class="cs-attributes-list__item-label">Endurance:
                </dt>
                <dd class="cs-attributes-list__item">
                    Nylon, Polyester, CoolTech™
                </dd>
                <dt class="cs-attributes-list__item-label">Pattern:
                </dt>
                <dd class="cs-attributes-list__item">
                    Solid
                </dd>
                <dt class="cs-attributes-list__item-label">Manufacturer:
                </dt>
                <dd class="cs-attributes-list__item">
                    Cool, Spring, Windy, Wintry
                </dd>
            </dl>
        </div>
    </div>

</div>