<div class="cs-styleguide__title">
    Messages
</div>

<div class="cs-styleguide__section cs-styleguide__section--wide">

    <div class="cs-messages">
        <div class="cs-messages__message cs-messages__message--error">
            <div class="cs-messages__text">An unexpected error ocured. Try again later.</div>
        </div>
        <div class="cs-messages__message cs-messages__message--success">
            <div class="cs-messages__text">Your account infromations were successfully updated.</div>
        </div>
        <div class="cs-messages__message cs-messages__message--notice">
            <div class="cs-messages__text">You have to choose color of your product.</div>
        </div>
        <div class="cs-messages__message cs-messages__message--info">
            <div class="cs-messages__text">Wait for yoour e-mail address to be verified.</div>
        </div>
    </div>

    <aside class="modal-popup confirm cs-modal _show" data-role="modal" data-type="popup" tabindex="0" style="position:relative;">
        <div data-role="focusable-start" tabindex="0"></div>
        <div class="modal-inner-wrap" data-role="focusable-scope"  style="position:relative;">
            <header class="modal-header | cs-modal__header">

                <button class="action-close | cs-modal__close" data-role="closeBtn" type="button">
                    <span>Close</span>
                </button>
            </header>
            <div class="modal-content | cs-modal__content" data-role="content"><div>Are you sure you want to delete this address?</div></div>

            <footer class="modal-footer | cs-modal__footer">

                <button class="action-secondary action-dismiss" type="button" data-role="action"><span>Cancel</span>
                    <span class="cs-button__icon cs-button__icon--bg"></span>
                </button>

                <button class="action-primary action-accept" type="button" data-role="action"><span>OK</span>
                    <span class="cs-button__icon cs-button__icon--bg"></span>
                </button>

            </footer>

        </div>
        <div data-role="focusable-end" tabindex="0"></div>
    </aside>
</div>