<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <div class="cs-styleguide__title">
        Pagination
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--wide">

        <div class="cs-category-page__toolbar">

            <div class="cs-category-page__toolbar-left">
                <div class="cs-category-page__modes | modes">
                    <strong class="modes-label">View as</strong>
                    <strong title="Grid" class="modes-mode active mode-grid" data-value="grid">
                        <span>Grid</span>
                    </strong>
                    <a class="modes-mode mode-list" title="List" href="#" data-role="mode-switcher" data-value="list">
                        <span>List</span>
                    </a>
                </div>

                <p class="cs-category-page__toolbar-amount | cs-t-text">
                    Items <span class="toolbar-number">1</span>-<span class="toolbar-number">5</span> of <span
                        class="toolbar-number">48</span></p>

                <div class="cs-category-page__toolbar-sorter | cs-input | sorter">
                    <label class="cs-category-page__toolbar-label">Sort By: </label>


                    <select class="cs-select" data-role="sorter" tabindex="-98">

                        <option value="position" selected="selected"> Position</option>
                        <option value="name"> Product Name</option>
                        <option value="price"> Price</option>

                    </select>


                    <a title="Set Descending Direction" href="#" class="action sorter-action sort-asc"
                       data-role="direction-switcher" data-value="desc">
                        <span>Set Descending Direction</span>
                    </a>
                </div>

                <div class="cs-category-page__toolbar-limiter | cs-input">
                    <label class="cs-category-page__toolbar-label">
                        Display: </label>

                    <div class="control cs-input__control | cs-visually-hidden">
                        <select data-role="limiter" class="cs-input__select">
                            <option value="5" selected="selected">
                                5
                            </option>
                            <option value="24">
                                24
                            </option>
                            <option value="48">
                                48
                            </option>
                            <option value="all">
                                All
                            </option>
                        </select>
                    </div>

                    <div class="cs-pagination cs-pagination--limiter">
                        <button class="cs-pagination__item" data-value="5">
                <span class="cs-pagination__number  cs-pagination__number--current">
                    5                </span>
                        </button>
                        <button class="cs-pagination__item" data-value="24">
                <span class="cs-pagination__number ">
                    24                </span>
                        </button>
                        <button class="cs-pagination__item" data-value="48">
                <span class="cs-pagination__number ">
                    48                </span>
                        </button>
                        <button class="cs-pagination__item" data-value="all">
                <span class="cs-pagination__number ">
                    All                </span>
                        </button>
                    </div>
                </div>


            </div>
            <div class="cs-category-page__toolbar-right">


                <div class="cs-pagination">
                    <div class="cs-pagination__content">

                        <span class="cs-pagination__prev" title="Previous">
                            <svg class="cs-pagination__prev-icon cs-pagination__prev-icon--disabled">
                                <use xlink:href="#icon_arrow-left"></use>
                            </svg>
                        </span>
                        <span class="cs-pagination__label-wrapper">
                            <span class="cs-pagination__label">Page: </span>
                        </span>

                        <ul class="cs-pagination__pager">


                            <li class="cs-pagination__item current">
                                <span class="cs-pagination__number cs-pagination__number--current">1</span>
                            </li>
                            <li class="cs-pagination__item">
                                <a href="http://m2c.dev/men/tops-men.html?p=2" class="cs-pagination__number">2 </a>
                            </li>
                            <li class="cs-pagination__item">
                                <a href="http://m2c.dev/men/tops-men.html?p=3" class="cs-pagination__number">3 </a>
                            </li>
                            <li class="cs-pagination__item">
                                <a href="http://m2c.dev/men/tops-men.html?p=4" class="cs-pagination__number">4 </a>
                            </li>
                            <li class="cs-pagination__item">
                                <a href="http://m2c.dev/men/tops-men.html?p=5" class="cs-pagination__number">5 </a>
                            </li>

                        </ul>


                        <ul class="cs-pagination__pager">
                            <li class="cs-pagination__separator">
                                of
                            </li>

                            <li class="cs-pagination__item cs-pagination__item--single">
                                <a class="cs-pagination__number" href="http://m2c.dev/men/tops-men.html?p=10">10</a>
                            </li>
                        </ul>


                        <a class="cs-pagination__next" href="http://m2c.dev/men/tops-men.html?p=2" title="Next">
                            <svg class="cs-pagination__next-icon">
                                <use xlink:href="#icon_arrow-right"></use>
                            </svg>
                        </a>

                    </div>
                    <div class="cs-pagination__content-mobile">

                        <a class="cs-button cs-button--look_light cs-button--type_wide"
                           href="http://m2c.dev/men/tops-men.html?p=2" title="Next page"> Next page
                            <svg class="cs-button__icon">
                                <use xlink:href="#arrow_next"></use>
                            </svg>
                        </a>
                    </div>
                </div>


            </div>

        </div>
    </div>
</div>