<div class="cs-styleguide__container cs-styleguide__container--contrast">

    <h2 class="cs-styleguide__title">
        Pagination
    </h2>

    <div class="cs-styleguide__section cs-styleguide__section--wide">
        <div class="cs-page-category__toolbar-wrapper cs-page-category__toolbar-wrapper--top">
            <div class="toolbar toolbar-products cs-toolbar cs-page-category__toolbar">              
                <div class="cs-toolbar__item cs-toolbar__item--pagination">
                    <div class="pages cs-pagination" role="navigation">
                        <div class="cs-pagination__content" role="menubar">

                            <?php 
                                $previousPageIcon = 
                                    $this->getLayout()
                                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                        ->setIconUrl('images/icons/toolbar/pagination-previous-page.svg')
                                        ->setCssClass('cs-pagination__action-icon cs-pagination__action-icon--previous-page')
                                        ->setAltText('Previous page')
                                        ->setInlined(true)
                                        ->setLazyLoaded(true)
                                        ->toHtml();
                            ?>

                            <div class="item pages-item-previous cs-pagination__prev" role="none">
                                <span class="link previous cs-pagination__action cs-pagination__action--previous-page cs-pagination__action--disabled"
                                title="Previous page"
                                tabindex="0"
                                role="menuitem">
                                    <?= $previousPageIcon ?>         
                                </span>
                            </div>      
                            <label class="label pages-label cs-pagination__prefix-label">
                                Page:
                            </label>
                            <div class="field cs-pagination__page-provider">
                                <input
                                    class="input-text cs-pagination__page-provider-input"
                                    type="number"
                                    min="1"
                                    max="10"
                                    size="2"
                                    value="1"
                                    data-url-pattern='https://test.magesuite.io/women.html?p=10'
                                >
                                <label class="label cs-pagination__page-provider-label">
                                    / 10
                                </label>
                            </div>

                            <?php 
                            $nextPageIcon = 
                                $this->getLayout()
                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                    ->setIconUrl('images/icons/toolbar/pagination-next-page.svg')
                                    ->setCssClass('cs-pagination__action-icon cs-pagination__action-icon--next-page')
                                    ->setAltText('Next page')
                                    ->setInlined(true)
                                    ->setLazyLoaded(true)
                                    ->toHtml();
                            ?>

                            <div class="item pages-item-previous cs-pagination__next" role="none">
                                <span class="link previous cs-pagination__action cs-pagination__action--previous-page"
                                title="Next page"
                                tabindex="0"
                                role="menuitem">
                                    <?= $nextPageIcon ?>      
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cs-toolbar__item cs-toolbar__item--pagination">
                    <div class="pages cs-pagination" role="navigation">
                        <div class="cs-pagination__content" role="menubar">

                            <?php 
                                $previousPageIcon = 
                                    $this->getLayout()
                                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                        ->setIconUrl('images/icons/toolbar/pagination-previous-page.svg')
                                        ->setCssClass('cs-pagination__action-icon cs-pagination__action-icon--previous-page')
                                        ->setAltText('Previous page')
                                        ->setInlined(true)
                                        ->setLazyLoaded(true)
                                        ->toHtml();
                            ?>

                            <div class="item pages-item-previous cs-pagination__prev" role="none">
                                <span class="link previous cs-pagination__action cs-pagination__action--previous-page cs-pagination__action--disabled"
                                title="Previous page"
                                tabindex="0"
                                role="menuitem">
                                    <?= $previousPageIcon ?>         
                                </span>
                            </div>     
                            <label class="label pages-label cs-pagination__prefix-label">
                                Page:
                            </label>
                            <ul class="items pages-items cs-pagination__items" role="none">
                                <li class="item current cs-pagination__item cs-pagination__item--first-page cs-pagination__item--current" role="none">
                                    <a class="page first cs-pagination__number cs-pagination__number--first-page" href="#" role="menuitem">
                                        <span class="label cs-visually-hidden"><?= /* @escapeNotVerified */ __('You\'re currently reading page') ?>2</span>
                                        <span>1</span>
                                    </a>
                                </li>
                                <li class="item cs-pagination__item" role="none">
                                    <a class="page cs-pagination__number" href="#" role="menuitem">
                                        <span>2</span>
                                    </a>
                                </li>                         
                                <li class="item cs-pagination__item" role="none">
                                    <a class="page cs-pagination__number" href="#" role="menuitem">
                                        <span>3</span>
                                    </a>
                                </li>  
                                <li class="item cs-pagination__item" role="none">
                                    <a class="page cs-pagination__number" href="#" role="menuitem">
                                        <span>4</span>
                                    </a>
                                </li>
                                <li class="item cs-pagination__item cs-pagination__item--last-page" role="none">
                                    <a class="page last cs-pagination__number cs-pagination__number--last-page" href="#" role="menuitem">
                                        <span>5</span>
                                    </a>
                                </li>
                            </ul>

                            <?php 
                            $nextPageIcon = 
                                $this->getLayout()
                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                    ->setIconUrl('images/icons/toolbar/pagination-next-page.svg')
                                    ->setCssClass('cs-pagination__action-icon cs-pagination__action-icon--next-page')
                                    ->setAltText('Next page')
                                    ->setInlined(true)
                                    ->setLazyLoaded(true)
                                    ->toHtml();
                            ?>

                            <div class="item pages-item-previous cs-pagination__next" role="none">
                                <span class="link previous cs-pagination__action cs-pagination__action--previous-page"
                                title="Next page"
                                tabindex="0"
                                role="menuitem">
                                    <?= $nextPageIcon ?>      
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cs-toolbar__item cs-toolbar__item--pagination">
                    <div class="cs-pagination__content-mobile">
                        <a class="cs-button cs-button--look_light cs-button--type_wide" href="http://m2c.dev/men/tops-men.html?p=2"
                            title="Next page"> Next page
                            <svg class="cs-button__icon">
                                <use xlink:href="#arrow_next"></use>
                            </svg>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    
    <div class="cs-styleguide__section cs-styleguide__section--wide">
        <div class="cs-page-category__toolbar-wrapper cs-page-category__toolbar-wrapper--top">
            <div class="toolbar toolbar-products cs-toolbar cs-page-category__toolbar">                     
                <div class="cs-toolbar__item cs-toolbar__item--sorter">
                    <div class="toolbar-sorter sorter cs-sorter">
                        <label class="sorter-label cs-toolbar__label cs-sorter__label">Sort By: </label>
                        <div class="cs-html-select">
                            <select id="sorter" data-role="sorter" class="sorter-options cs-select cs-sorter__select">
                                <option value="position">Position - Ascending</option>
                                <option value="position">Position - Descending</option>
                                <option value="position">Price - Ascending</option>
                                <option value="position">Price - Descending</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="cs-toolbar__item cs-toolbar__item--limiter">
                    <div class="field limiter cs-limiter" role="navigation">
                        <label class="label cs-toolbar__label cs-limiter__label cs-limiter__label--prefix">
                            <span>Display:</span>
                        </label>
                            <ul class="cs-limiter__pagination" role="menubar">
                                <li class="cs-limiter__pagination-item  cs-limiter__pagination-item--current" role="none">
                                    <button class="cs-limiter__pagination-number" data-value="5" roe="menuitem">
                                        <span>5</span>
                                    </button>
                                </li>
                                <li class="cs-limiter__pagination-item" role="none">
                                    <button class="cs-limiter__pagination-number" data-value="24" roe="menuitem">
                                        <span>24</span>
                                    </button>
                                </li>
                                <li class="cs-limiter__pagination-item" role="none">
                                    <button class="cs-limiter__pagination-number" data-value="48" roe="menuitem">
                                        <span>48</span>
                                    </button>
                                </li>
                                <li class="cs-limiter__pagination-item" role="none">
                                    <button class="cs-limiter__pagination-number" data-value="all" roe="menuitem">
                                        <span>All</span>
                                    </button>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="cs-toolbar__item cs-toolbar__item--viewmode-switcher">
                        <div class="modes cs-viewmode-switcher">
                            <ul class="cs-viewmode-switcher__modes">
                                <li class="cs-viewmode-switcher__mode">
                                    <span
                                        class="modes-mode mode-grid cs-viewmode-switcher__mode-action cs-viewmode-switcher__mode-action--grid">
                                        <?= $this->getLayout()
                                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                                    ->setIconUrl('images/icons/toolbar/viewmode-grid.svg')
                                                    ->setCssClass('cs-viewmode-switcher__mode-icon cs-viewmode-switcher__mode-icon--grid')
                                                    ->setInlined(true)
                                                    ->setLazyLoaded(true)
                                                    ->toHtml(); ?>
                                    </span>
                                </li>
                                <li class="cs-viewmode-switcher__mode cs-viewmode-switcher__mode--current">
                                    <span
                                        class="modes-mode mode-list cs-viewmode-switcher__mode-action cs-viewmode-switcher__mode-action--list">
                                        <?= $this->getLayout()
                                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                                    ->setIconUrl('images/icons/toolbar/viewmode-list.svg')
                                                    ->setCssClass('cs-viewmode-switcher__mode-icon cs-viewmode-switcher__mode-icon--list')
                                                    ->setInlined(true)
                                                    ->setLazyLoaded(true)
                                                    ->toHtml(); ?>
                                    </span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>