<div class="cs-styleguide__title">
    Qty increment
</div>
<div class="cs-styleguide__section">
    <div style="width: 100%;">

        <div class="cs-input | cs-qty-increment ">
            <input type="number" name="qty" size="2" maxlength="" class="cs-input__input | cs-qty-increment__input"
                   value="1">

            <button type="button"
                    class="cs-qty-increment__button cs-qty-increment__button--decrement cs-qty-increment__button--disabled"
                    disabled="disabled">
                <svg class="cs-qty-increment__icon cs-qty-increment__icon--minus">
                    <use xlink:href="#minus"></use>
                </svg>
            </button>

            <button type="button" class="cs-qty-increment__button cs-qty-increment__button--increment">
                <svg class="cs-qty-increment__icon cs-qty-increment__icon--plus">
                    <use xlink:href="#plus"></use>
                </svg>
            </button>
        </div>

    </div>
</div>