<div class="cs-styleguide__title">
    Social buttons
</div>

<div class="cs-styleguide__section cs-styleguide__section--columns"><div>
    <ul class="cs-list cs-list--unstyled cs-list--inline">
        <li class="cs-footer-list__item">
            <a href="#" class="cs-button-social">
                <svg class="cs-button-social__icon cs-button-social__icon--fb">
                    <use xlink:href="#facebook"></use>
                </svg>
                <span class="cs-visually-hidden"><?=__('Go to Facebook');?></span>
            </a>
        </li>

        <li class="cs-footer-list__item">
            <a href="#" class="cs-button-social">
                <svg class="cs-button-social__icon cs-button-social__icon--gplus">
                    <use xlink:href="#google_plus"></use>
                </svg>
                <span class="cs-visually-hidden"><?=__('Go to Google Plus');?></span>
            </a>
        </li>

        <li class="cs-footer-list__item">
            <a href="#" class="cs-button-social">
                <svg class="cs-button-social__icon cs-button-social__icon--yt">
                    <use xlink:href="#you_tube"></use>
                </svg>
                <span class="cs-visually-hidden"><?=__('Go to You Tube');?></span>
            </a>
        </li>
    </ul>
</div>

</div>