<div class="cs-styleguide__container">

    <div class="cs-styleguide__title">
        Swatches & Quantity
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">

        <div class="cs-swatches__attribute size" attribute-code="size" attribute-id="142" style="width:30rem;">
            <span class="cs-swatches__attribute-label">Size</span>
            <span class="cs-swatches__attribute-selected"></span>

            <div class="cs-swatches__list clearfix">
                <div class="cs-swatches__swatch text disabled" option-type="0" option-id="167" option-label="XS"
                     option-tooltip-thumb="" option-tooltip-value="XS">XS
                </div>
                <div class="cs-swatches__swatch text selected" option-type="0" option-id="168" option-label="S"
                     option-tooltip-thumb="" option-tooltip-value="S">S
                </div>
                <div class="cs-swatches__swatch text" option-type="0" option-id="169" option-label="M"
                     option-tooltip-thumb="" option-tooltip-value="M">M
                </div>
                <div class="cs-swatches__swatch text" option-type="0" option-id="170" option-label="L"
                     option-tooltip-thumb="" option-tooltip-value="L">L
                </div>
                <div class="cs-swatches__swatch text" option-type="0" option-id="171" option-label="XL"
                     option-tooltip-thumb="" option-tooltip-value="XL">XL
                </div>
            </div>
        </div>


    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <div class="cs-swatches__attribute color" attribute-code="color" attribute-id="93">
            <span class="cs-swatches__attribute-label">Color</span>
            <span class="cs-swatches__attribute-selected"></span>

            <div class="cs-swatches__list clearfix">
                <div class="cs-swatches__swatch color disabled" option-type="1" option-id="50" option-label="Blue"
                     option-tooltip-thumb="" option-tooltip-value="#1857f7"
                     style="background: #1857f7 no-repeat center; background-size: initial;">
                </div>
                <div class="cs-swatches__swatch color" option-type="1" option-id="54" option-label="Red1"
                     option-tooltip-thumb="" option-tooltip-value="#F2C626"
                     style="background: #F2C626 no-repeat center; background-size: initial;">
                </div>
                <div class="cs-swatches__swatch color selected" option-type="1" option-id="53" option-label="Green"
                     option-tooltip-thumb="" option-tooltip-value="#53a828"
                     style="background: #53a828 no-repeat center; background-size: initial;">
                </div>
                <div class="cs-swatches__swatch color" option-type="1" option-id="58" option-label="Red"
                     option-tooltip-thumb="" option-tooltip-value="#ff0000"
                     style="background: #ff0000 no-repeat center; background-size: initial;">
                </div>
            </div>
        </div>
    </div>

    <div class="cs-styleguide__separator"></div>


    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <div class="cs-swatches cs-swatches--mini cs-swatches--color-only cs-swatches--static">
            <div class="swatch-opt-243">
                <div class="cs-swatches__attribute color" attribute-code="color" attribute-id="93">
                    <div class="cs-swatches__list cs-swatches__list--mini clearfix">
                        <div class="cs-swatches__swatch color selected" option-type="1" option-id="50"
                             option-label="Blue" option-tooltip-thumb="" option-tooltip-value="#1857f7"
                             style="background: #1857f7 no-repeat center; background-size: initial;"></div>
                        <div class="cs-swatches__swatch color" option-type="1" option-id="54" option-label="Red1"
                             option-tooltip-thumb="" option-tooltip-value="#F2C626"
                             style="background: #F2C626 no-repeat center; background-size: initial;">
                        </div>
                        <div class="cs-swatches__swatch color" option-type="1" option-id="53" option-label="Green"
                             option-tooltip-thumb="" option-tooltip-value="#53a828"
                             style="background: #53a828 no-repeat center; background-size: initial;"></div>
                        <div class="cs-swatches__swatch color" option-type="1" option-id="58" option-label="Red"
                             option-tooltip-thumb="" option-tooltip-value="#ff0000"
                             style="background: #ff0000 no-repeat center; background-size: initial;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section" style="padding-top: 20px;">
        <div style="width: 100%;">

            <div class="cs-input | cs-qty-increment ">
                <input type="number" name="qty" size="2" maxlength="" class="cs-input__input | cs-qty-increment__input"
                       value="1">

                <button type="button"
                        class="cs-qty-increment__button cs-qty-increment__button--decrement cs-qty-increment__button--disabled"
                        disabled="disabled">
                    <svg class="cs-qty-increment__icon cs-qty-increment__icon--minus">
                        <use xlink:href="#minus"></use>
                    </svg>
                </button>

                <button type="button" class="cs-qty-increment__button cs-qty-increment__button--increment">
                    <svg class="cs-qty-increment__icon cs-qty-increment__icon--plus">
                        <use xlink:href="#plus"></use>
                    </svg>
                </button>
            </div>

        </div>
    </div>
</div>