<div class="cs-styleguide__container">

    <h2 class="cs-styleguide__title">
        Swatches & Quantity
    </h2>

    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <div class="cs-buybox">
            <div class="fieldset">
                <div class="swatch-opt" data-role="swatch-options">
                    <div class="swatch-attribute size">
                        <span class="swatch-attribute-label">Size</span>
                        <span class="swatch-attribute-selected-option"></span>

                        <div class="swatch-attribute-options clearfix">
                            <div class="swatch-option text disabled" option-type="0" id="option-label-size-222-item-170" index="0" tabindex="0" option-type="0" option-id="170" option-label="XS"
                                option-tooltip-thumb option-tooltip-value="XS" role="option" thumb-width="110" thumb-height="110">XS
                            </div>
                            <div class="swatch-option text" option-type="0" option-id="168" option-label="S"
                                option-tooltip-thumb="" option-tooltip-value="S">S
                            </div>
                            <div class="swatch-option text" option-type="0" option-id="169" option-label="M"
                                option-tooltip-thumb="" option-tooltip-value="M">M
                            </div>
                            <div class="swatch-option text" option-type="0" option-id="170" option-label="L"
                                option-tooltip-thumb="" option-tooltip-value="L">L
                            </div>
                            <div class="swatch-option text selected" option-type="0" option-id="171" option-label="XL"
                                option-tooltip-thumb="" option-tooltip-value="XL">XL
                            </div>
                        </div>
                    </div>

                    <div class="swatch-attribute color">
                        <span class="swatch-attribute-label">Color</span>
                        <span class="swatch-attribute-selected-option"></span>

                        <div class="swatch-attribute-options clearfix">
                            <div class="swatch-option color disabled" option-type="1" option-id="50" option-label="Blue" 
                                option-tooltip-thumb="" option-tooltip-value="#1857f7" 
                                style="background: #1857f7 no-repeat center; background-size: initial;">
                            </div>
                            <div class="swatch-option color" option-type="1" option-id="54" option-label="Yellow"
                                option-tooltip-thumb="" option-tooltip-value="#F2C626"
                                style="background: #F2C626 no-repeat center; background-size: initial;">
                            </div>
                            <div class="swatch-option color" option-type="1" option-id="53" option-label="Green"
                                option-tooltip-thumb="" option-tooltip-value="#53a828"
                                style="background: #53a828 no-repeat center; background-size: initial;">
                            </div>
                            <div class="swatch-option color selected" option-type="1" option-id="58" option-label="Red"
                                option-tooltip-thumb="" option-tooltip-value="#ff0000"
                                style="background: #ff0000 no-repeat center; background-size: initial;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="cs-buybox__qty-wrapper">
        <div class="cs-buybox__qty-increment">
            <div class="cs-qty-increment">
                <input type="number" name="qty" size="3" value="1" class="cs-qty-increment__input" min="1" max="1000">
                <span role="button" tabindex="0" class="cs-qty-increment__button cs-qty-increment__button--decrement" aria-pressed="false">
                    <?= $this->getLayout()
                            ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                            ->setIconUrl('images/icons/qty-increment/minus.svg')
                            ->setCssClass('cs-qty-increment__icon cs-qty-increment__icon--decrement')
                            ->setAltText(__('Decrement product quantity icon'))
                            ->setInlined(true)
                            ->toHtml(); ?>
                </span>
                <span role="button" tabindex="0" class="cs-qty-increment__button cs-qty-increment__button--increment" aria-pressed="false">
                    <?= $this->getLayout()
                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                        ->setIconUrl('images/icons/qty-increment/plus.svg')
                        ->setCssClass('cs-qty-increment__icon cs-qty-increment__icon--increment')
                        ->setAltText(__('Increment product quantity icon'))
                        ->setInlined(true)
                        ->toHtml(); ?>
                </span>
            </div>
        </div>
    </div>   
</div>

<script>   
    require(["jquery", "Magento_Swatches/js/swatch-renderer"], function ($) {
        $('.swatch-option')
            .SwatchRendererTooltip();
    });
</script>  