<div class="cs-styleguide__title">
    Tables
</div>

<div>

    <div class="cs-table">
        <table class="cs-table__body">
            <caption class="cs-visually-hidden">Orders</caption>
            <thead class="cs-table__head">
            <tr>
                <th scope="col" class="cs-table__col-head id">Order #</th>
                <th scope="col" class="cs-table__col-head date">Date</th>
                <th scope="col" class="cs-table__col-head shipping">Ship To</th>
                <th scope="col" class="cs-table__col-head total">Order Total</th>
                <th scope="col" class="cs-table__col-head status">Status</th>
                <th scope="col" class="cs-table__col-head actions">Action</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td data-th="Order #" class="cs-table__col | id">000000006</td>
                <td data-th="Date" class="cs-table__col | date">15.01.17</td>
                <td data-th="Ship To" class="cs-table__col | shipping">Max Mustermann</td>
                <td data-th="Order Total" class="cs-table__col | total"><span class="price">47,00&nbsp;$</span></td>
                <td data-th="Status" class="cs-table__col | status">Pending</td>
                <td data-th="Actions" class="cs-table__col cs-table__col--actions | actions">
                    <a href="http://m2c.dev/sales/order/view/order_id/6/" class="cs-link cs-link--separator">
                        View Order
                    </a>
                    <a href="http://m2c.dev/sales/order/reorder/order_id/6/" class="cs-link">
                        Reorder
                    </a>
                </td>
            </tr>
            <tr>
                <td data-th="Order #" class="cs-table__col | id">000000007</td>
                <td data-th="Date" class="cs-table__col | date">25.04.17</td>
                <td data-th="Ship To" class="cs-table__col | shipping">Emma Braun</td>
                <td data-th="Order Total" class="cs-table__col | total"><span class="price">33,60&nbsp;$</span></td>
                <td data-th="Status" class="cs-table__col | status">Pending</td>
                <td data-th="Actions" class="cs-table__col cs-table__col--actions | actions">
                    <a href="http://m2c.dev/sales/order/view/order_id/5/" class="cs-link cs-link--separator">
                        View Order
                    </a>
                    <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="cs-link">
                        Reorder
                    </a>
                </td>
            </tr>
            <tr>
                <td data-th="Order #" class="cs-table__col | id">000000005</td>
                <td data-th="Date" class="cs-table__col | date">25.01.17</td>
                <td data-th="Ship To" class="cs-table__col | shipping">Emma Braun</td>
                <td data-th="Order Total" class="cs-table__col | total"><span class="price">233,60&nbsp;$</span></td>
                <td data-th="Status" class="cs-table__col | status">Pending</td>
                <td data-th="Actions" class="cs-table__col cs-table__col--actions | actions">
                    <a href="http://m2c.dev/sales/order/view/order_id/5/" class="cs-link cs-link--separator">
                        View Order
                    </a>
                    <a href="http://m2c.dev/sales/order/reorder/order_id/5/" class="cs-link">
                        Reorder
                    </a>
                </td>
            </tr>
            </tbody>
        </table>
    </div>

</div>