<div class="cs-styleguide__container">


    <div class="cs-styleguide__title">
        Typography
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--wide ">

        <h1 class="cs-hero__headline">
            Hero image headline
        </h1>

        <p class="cs-hero__subheadline">
            Hero image subheadline
        </p>
    </div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">

        <h1 class="cs-t-headline cs-t-headline--size_1">
            Headline H1
        </h1>

        <h1 class="cs-t-headline cs-t-headline--size_1 cs-t-headline--look_light">
            Headline H1 light + span <span class="cs-t-headline__span">(14)</span>
        </h1>

        <h1 class="cs-t-headline cs-t-headline--size_1 cs-t-headline--look_bordered">
            Headline H1 bordered
        </h1>

        <h2 class="cs-t-headline cs-t-headline--size_2">
            Headline H2 + span <span class="cs-t-headline__span">(14)</span>
        </h2>

        <h2 class="cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light">
            Headline H2 Light
        </h2>

        <h2 class="cs-t-headline cs-t-headline--size_2 cs-t-headline--look_bordered">
            Headline H2 bordered
        </h2>

        <h3 class="cs-t-headline cs-t-headline--size_3">
            Headline H3
        </h3>

        <h3 class="cs-t-headline cs-t-headline--size_3 cs-t-headline--look_light">
            Headline H3 light
        </h3>

        <h3 class="cs-t-headline cs-t-headline--size_3 cs-t-headline--look_bordered">
            Headline H3
        </h3>
        <h4 class="cs-t-headline cs-t-headline--size_4">
            Headline H4
        </h4>
        <h4 class="cs-t-headline cs-t-headline--size_4 cs-t-headline--look_light">
            Headline H4 light
        </h4>
        <h4 class="cs-t-headline cs-t-headline--size_4 cs-t-headline--look_bordered">
            Headline H4 light bordered + span <span class="cs-t-headline__span">(14)</span>
        </h4>
    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <p class="cs-product-tile__name">
            Product name
        </p>
    </div>

    <div class="cs-styleguide__separator"></div>

    <div class="cs-styleguide__section cs-styleguide__section--columns">

        <p class="cs-t-text">
            Content text - main size
        </p>

        <p class="cs-t-text cs-t-text--look_success">
            Content text - look success
        </p>

        <p class="cs-t-text cs-t-text--look_error">
            Content text - look error
        </p>

        <p class="cs-t-text cs-t-text--look_link">
            Content text - look link
        </p>

        <p class="cs-t-text cs-t-text--look_attention">
            Content text - look attention
        </p>

        <p class="cs-t-text cs-t-text--look_label">
            Content text - look label
        </p>
    </div>

    <div class="cs-styleguide__separator"></div>


    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <p class="cs-t-text cs-t-text--size_300">
            Content text - size 300
        </p>
        <label class="cs-input__label">
            Input label
        </label>

        <h3 class="cs-footer__column-title">Footer list title</h3>
    </div>

    <div class="cs-styleguide__separator"></div>


    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <p class="cs-t-text cs-t-text--size_250">
            Content text - size 250
        </p>

    </div>

    <div class="cs-styleguide__separator"></div>


    <div class="cs-styleguide__section cs-styleguide__section--columns">
        <p class="cs-t-text cs-t-text--size_200">
            Content text - size 200
        </p>
    </div>

</div>
