<div class="cs-styleguide__container">

    <h2 class="cs-styleguide__title">
        Typography
    </h2>

    <div class="cs-styleguide__section">
        <div class="cs-styleguide__typography-group">
            <h1>Headline H1</h1>
            <h2>Headline H2</h2>
            <h2>Headline H2 + span <span>(14)</span></h2>
            <h3>Headline H3</h3>
            <h4>Headline H4</h4>
            <h5>Headline H5</h5>
            <h6>Headline H6</h6>
        </div>
        <div class="cs-styleguide__typography-group">
            <p>Example of regular paragraph.</p>
            <p><span class="cs-styleguide__text--underline">Underline text</span></p>
            <p><strong>Strong text</strong></p>
            <p><em>Italic text</em></p>
            <p><a title="link example" href="#">Link example</a></p>
        </div>

        <div class="cs-styleguide__typography-group">
            <ul class="cs-styleguide__list--circle-type">
                <li>Check out faster</li>
                <li>Save multiple shipping addresses</li>
                <li>Access your order history</li>
            </ul>
            <ul class="cs-styleguide__list--disc-type">
                <li>Check out faster</li>
                <li>Save multiple shipping addresses</li>
                <li>Access your order history</li>
            </ul>
            <ul class="cs-styleguide__list--square-type">
                <li>Check out faster</li>
                <li>Save multiple shipping addresses</li>
                <li>Access your order history</li>
            </ul>
        </div>

        <div class="cs-styleguide__typography-group">
            <ul>
                <li>Check out faster</li>
                <li>Save multiple shipping addresses</li>
                <li><a title="linkList" href="#">Listed link example</a></li>
            </ul>
            <p class="cs-styleguide__paragraph--text-200">Paraghaph with $color_text-200 example.</p>
            <p class="cs-styleguide__paragraph--text-300">Paraghaph with $color_text-400 example.</p>
            <p class="cs-styleguide__paragraph--text-400">Paraghaph with $color_text-500 example.</p>
            <p class="cs-styleguide__paragraph--text-500">Paraghaph with $color_text-600 example.</p>
            <p class="cs-styleguide__paragraph--text-600">Paraghaph with $color_text-800 example.</p>
            <p class="cs-styleguide__paragraph--text-800">Paraghaph with $color_text-900 example.</p>
            <p class="cs-styleguide__paragraph--text-900">Paraghaph with $color_text-300 example.</p>
        </div>

        <div class="cs-styleguide__typography-group cs-styleguide__typography-group--columns">
            <p class="cs-styleguide__paragraph cs-styleguide__paragraph--left">Quibusdam hic praesentium iure. Eaque quibusdam odit dolores perspiciatis fuga eligendi facilis. Totam dignissimos cumque dolores accusamus dolorum reprehenderit sint ullam. Voluptates consequuntur enim quos possimus accusantium quia sequi totam.</p>
            <p class="cs-styleguide__paragraph cs-styleguide__paragraph--center">Quibusdam hic praesentium iure. Eaque quibusdam odit dolores perspiciatis fuga eligendi facilis. Totam dignissimos cumque dolores accusamus dolorum reprehenderit sint ullam. Voluptates consequuntur enim quos possimus accusantium quia sequi totam.</p>
            <p class="cs-styleguide__paragraph cs-styleguide__paragraph--right">Quibusdam hic praesentium iure. Eaque quibusdam odit dolores perspiciatis fuga eligendi facilis. Totam dignissimos cumque dolores accusamus dolorum reprehenderit sint ullam. Voluptates consequuntur enim quos possimus accusantium quia sequi totam.</p>
        </div>
    </div>

</div>
