<?php
$collapseOptions = $block->getCollapsibleWidgetOptions();
$isMediaQueryScopeSet = $collapseOptions['mediaQueryScope'];
?>
<div
    class="cs-footer__section <?= $block->getAdditionalCssClasses() ?>"
    <?php if($block->getIsCollapsible()): ?>
         data-mage-init='{"collapsible":<?= !empty($collapseOptions) ? json_encode($collapseOptions) : '{}' ?>}'
    <?php endif; ?>
>
    <?= $block->getChildHtml(); ?>
</div>
