<?php
$collapseOptions = $block->getCollapsibleWidgetOptions();
$isMediaQueryScopeSet = $collapseOptions['mediaQueryScope'];
$headline = $block->getHeadline();
$headlineTag = $block->getHeadlineTag() ?? 'h3';
?>
<div
    class="cs-footer__section <?= $block->getAdditionalCssClasses() ?>"
    <?php if($block->getIsCollapsible()): ?>
         data-mage-init='{"collapsible":<?= !empty($collapseOptions) ? json_encode($collapseOptions) : '{}' ?>}'
    <?php endif; ?>
>
    <?php if ($headline): ?>
    <<?= $headlineTag ?> class="cs-footer__section-title"<?php if($block->getIsCollapsible()): ?> data-role="title"<?php endif; ?>>
            <?= $headline; ?>
        </<?= $headlineTag ?>>
    <?php endif; ?>
    <?= $block->getChildHtml(); ?>
</div>
