<?php
/**
 * Template overridden in order to add magesuite classes
 * Aligned with Magento 2.4.9 in 05/2026
 */
?>
<?php
$hasCloseButton = $block->getVar('global_messages/has_close_button', 'Magento_Theme');
$messageVisibilityTime = $block->getVar('global_messages/message_visibility_time', 'Magento_Theme');
?>
<div data-bind="scope: 'messages'">
    <div data-bind="attr: {
    class: (cookieMessagesObservable().length > 0) || (messages().messages && messages().messages.length > 0)
        ? 'cs-messages cs-messages--active'
        : 'cs-messages'
    }">
        <!-- ko if: cookieMessagesObservable().length > 0 -->
        <div aria-atomic="true" role="alert" data-bind="foreach: { data: cookieMessagesObservable, as: 'message' }" class="messages cs-messages__inner">
            <div data-bind="attr: {
                class: 'message-' + message.type + ' ' + message.type + ' message cs-messages__message cs-messages__message--' + message.type,
                'data-ui-id': 'message-' + message.type
                }
                <?php if ($hasCloseButton): ?>
                ,
                afterRender: function() {
                    if (message.type === 'success') {
                        setTimeout(function() {
                            $parent.removeCookieMessage(message);
                        }, <?= $escaper->escapeJs($messageVisibilityTime); ?>);
                    }
                }
                <?php endif; ?>
                ">
                <div data-bind="html: $parent.prepareMessageForHtml(message.text)" class="cs-messages__text"></div>
                <?php if ($hasCloseButton): ?>
                    <button type="button" class="action small cs-messages__close" data-bind="
                        click: function() {
                            $parent.removeCookieMessage(message);
                            return false;
                        }"
                    >
                        <span class="cs-messages__close-span"><?= __('Close'); ?></span>
                    </button>
                <?php endif; ?>
            </div>
        </div>
        <!-- /ko -->
        <!-- ko if: messages().messages && messages().messages.length > 0 -->
        <div aria-atomic="true" role="alert" data-bind="foreach: { data: messages().messages, as: 'message' }" class="messages cs-messages__inner">
            <div data-bind="attr: {
                class: 'message-' + message.type + ' ' + message.type + ' message cs-messages__message cs-messages__message--' + message.type,
                'data-ui-id': 'message-' + message.type
                }
                <?php if ($hasCloseButton): ?>
                ,
                afterRender: function() {
                    if (message.type === 'success') {
                        setTimeout(function() {
                            $parent.removeMessage(message);
                        }, <?= $escaper->escapeJs($messageVisibilityTime); ?>);
                    }
                }
                <?php endif; ?>
                ">
                <div data-bind="html: $parent.prepareMessageForHtml(message.text)" class="cs-messages__text"></div>
                <?php if ($hasCloseButton): ?>
                    <button type="button" class="action small cs-messages__close" data-bind="
                        click: function() {
                            $parent.removeMessage(message);
                            return false;
                        }"
                    >
                        <span class="cs-messages__close-span"><?= __('Close'); ?></span>
                    </button>
                <?php endif; ?>
            </div>
        </div>
        <!-- /ko -->
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Magento_Theme/js/view/messages"
                        }
                    }
                }
            }
    }
</script>
