<?php
// @codingStandardsIgnoreFile
/**
 * @var \Magento\Paypal\Block\Billing\Agreement\View $block
 */
$relatedOrders = $block->getRelatedOrders();
?>
<div class="cs-info-block | cs-dashboard__block | block-billing-agreements-view">
    <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
        <h2 class="cs-title-block__span cs-title-block__span--middle">
            <?php echo $block->escapeHtml(__('Billing Agreement # ')); ?>
            <?php echo $block->escapeHtml($block->getReferenceId()); ?>
        </h2>
        <?php if ($block->getCanCancel()): ?>
            <button data-mage-init='{"Magento_Paypal/js/in-context/billing-agreement": {
                        "cancelMessage" : "<?php echo $block->escapeHtml(__('Are you sure you want to do this?')); ?>",
                        "cancelUrl" : "<?php echo $block->escapeUrl($block->getCancelUrl()) ?>"
                    }}'
                    type="button" title="<?php echo $block->escapeHtml(__('Cancel')); ?>"
                    class="cs-button cs-button--look_light cs-button--size_300" />
                <span class="cs-button__span"><?php echo $block->escapeHtml(__('Cancel')); ?></span>
                <svg class="cs-button__icon">
                    <use xlink:href="#arrow_next"></use>
                </svg>
            </button>
        <?php endif; ?>
    </div>
    <div class="cs-info-block | cs-dashboard__block">
        <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
            <h2 class="cs-title-block__span">
                <?php echo $block->escapeHtml(__('Agreement Information')); ?>
            </h2>
        </div>

        <div class="cs-table cs-table--tablet-small billing-agreements-view">
            <table class="cs-table__body table-billing-agreements-view">
                <caption class="cs-visually-hidden"><?php echo $block->escapeHtml(__('Agreement Information')); ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="cs-table__col-head id">
                        <?php echo $block->escapeHtml(__('Reference ID:')); ?>
                    </th>
                    <th scope="col" class="cs-table__col-head status">
                        <?php echo $block->escapeHtml(__('Status:')); ?>
                    </th>
                    <th scope="col" class="cs-table__col-head created">
                        <?php echo $block->escapeHtml(__('Created:')); ?>
                    </th>
                    <?php if ($block->getAgreementUpdatedAt()): ?>
                        <th scope="col" class="cs-table__col-head updated">
                            <?php echo $block->escapeHtml(__('Updated:')); ?>
                        </th>
                    <?php endif; ?>
                    <th scope="col" class="cs-table__col-head payment">
                        <?php echo $block->escapeHtml(__('Payment Method:')); ?>
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Reference ID:')); ?>" class="cs-table__col id">
                        <?php echo $block->escapeHtml($block->getReferenceId()); ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status:')); ?>" class="cs-table__col status">
                        <?php echo $block->escapeHtml($block->getAgreementStatus()); ?>
                    </td>
                    <td data-th="<?php echo $block->escapeHtml(__('Created:')); ?>" class="cs-table__col created">
                        <?php echo $block->escapeHtml($block->getAgreementCreatedAt()); ?>
                    </td>
                    <?php if ($block->getAgreementUpdatedAt()): ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Updated:')); ?>" class="cs-table__col updated">
                            <?php echo $block->escapeHtml($block->getAgreementUpdatedAt()); ?>
                        </td>
                    <?php endif; ?>
                    <td data-th="<?php echo $block->escapeHtml(__('Payment Method:')); ?>" class="cs-table__col payment">
                        <?php echo $block->escapeHtml($block->getPaymentMethodTitle()); ?>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php if (count($relatedOrders) > 0): ?>
    <div class="block block-billing-orders-view">
        <?php echo $block->getChildHtml('pager'); ?>
        <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
            <h2 class="cs-title-block__span">
                <?php echo $block->escapeHtml(__('Related Orders')); ?>
            </h2>
        </div>

        <div class="cs-table cs-table--tablet-small billing-agreements-related">
            <table class="cs-table__body table-billing-agreements-related" id="related-orders-table">
                <caption class="cs-visually-hidden"><?php echo $block->escapeHtml(__('Related Orders')) ?></caption>
                <thead>
                <tr>
                    <th scope="col" class="cs-table__col-head id">
                        <?php echo $block->escapeHtml(__('Order #')); ?>
                    </th>
                    <th scope="col" class="cs-table__col-head date">
                        <?php echo $block->escapeHtml(__('Date')); ?>
                    </th>
                    <th scope="col" class="cs-table__col-head shipto">
                        <?php echo $block->escapeHtml(__('Ship To')); ?>
                    </th>
                    <th scope="col" class="cs-table__col-head total">
                        <?php echo $block->escapeHtml(__('Order Total')); ?>
                    </th>
                    <th scope="col" class="cs-table__col-head status">
                        <?php echo $block->escapeHtml(__('Order Status')); ?>
                    </th>
                    <th scope="col" class="cs-table__col-head actions">&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($relatedOrders as $order): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Order #')); ?>" class="cs-table__col id">
                            <?php echo $block->escapeHtml($block->getOrderItemValue(
                                $order, 'order_increment_id'
                            )); ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Date')); ?>" class="cs-table__col date">
                            <?php echo $block->escapeHtml($block->getOrderItemValue($order, 'created_at')); ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Ship To')); ?>" class="cs-table__col shipto">
                            <?php echo $block->escapeHtml($block->getOrderItemValue(
                                $order, 'shipping_address'
                            )); ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order Total')); ?>" class="cs-table__col total">
                            <?php /* @noEscape */ echo $block->getOrderItemValue($order, 'order_total'); ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order Status')); ?>" class="cs-table__col status">
                            <?php echo $block->escapeHtml($block->getOrderItemValue(
                                $order, 'status_label'
                            )); ?>
                        </td>
                        <td data-th="" class="cs-table__col actions">
                            <a href="<?php echo $block->escapeUrl($block->getOrderItemValue(
                                $order, 'view_url'
                            )); ?>">
                                <span><?php echo $block->escapeHtml(__('View Order')); ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    </div>
<?php endif; ?>

<div class="actions-toolbar">
    <div class="secondary">
        <a href="<?php echo $block->escapeUrl($block->getBackUrl()); ?>">
            <?php echo $block->escapeHtml(__('Back to Billing Agreements')); ?>
        </a>
    </div>
</div>
