<div class="cs-side-nav">

    <div class="cs-side-nav__main">
        <a href="#" class="cs-side-nav__link">Women</a>
    </div>

    <div class="cs-side-nav__collapse | cs-collapse">
        <div class="cs-side-nav__collapse-trigger | cs-collapse__trigger">
            <a href="#" class="cs-side-nav__link">Tops</a>
        </div>
        <div class="cs-side-nav__content | cs-collapse__content cs-collapse__content--initial-in">
            <ul class="cs-side-nav__list">
                <li class="cs-side-nav__list-item">
                    <a href="#" class="cs-side-nav__link">Jackets</a>
                </li>
                <li class="cs-side-nav__list-item cs-side-nav__list-item--active">
                    <a href="#" class="cs-side-nav__link">Hoodies & Sweatshirts</a>
                </li>
                <li class="cs-side-nav__list-item">
                    <a href="#" class="cs-side-nav__link">Tees</a>
                </li>
                <li class="cs-side-nav__list-item">
                    <a href="#" class="cs-side-nav__link">Bras & Tanks</a>
                </li>
            </ul>

        </div>
    </div>

    <div class="cs-side-nav__collapse | cs-collapse">
        <div class="cs-side-nav__collapse-trigger | cs-collapse__trigger">
            <a href="#" class="cs-side-nav__link">Bottoms</a>
        </div>
        <div class="cs-side-nav__content | cs-collapse__content cs-collapse__content--initial-in">
            <ul class="cs-side-nav__list">
                <li class="cs-side-nav__list-item">
                    <a href="#" class="cs-side-nav__link">Pants</a>
                </li>
                <li class="cs-side-nav__list-item">
                    <a href="#" class="cs-side-nav__link">Shorts</a>
                </li>
            </ul>

        </div>
    </div>

</div>