<?php
// @codingStandardsIgnoreFile

/** @var \Aheadworks\Pquestion\Block\Question\QList $this */
?>

<?php $this->getVoteMap();?>
<?php $questionCollection = $this->getQuestionCollection(); ?>
<div class="aw-pq-question-list-wrapper box-collateral">
    <?php if ($questionCollection->getSize() > 1) : ?>
        <div class="aw-pq-question-sort pager">
            <?= /* @noEscape */ $this->getChildHtml('aw_pq_question_sort'); ?>
        </div>
    <?php endif; ?>
    <div class="aw-pq-list box-content">
        <?php if ($questionCollection->getSize() > 0) : ?>
            <?php foreach ($questionCollection as $question): ?>
                <div class="aw-pq-list__question-item aw-pq-list__question-item_hidden">
                    <div class="aw-pq-list__question-expand aw-pq-list__question-expand_arrow_right" data-question-id="<?= (int)$question->getId();?>"></div>
                    <div class="aw-pq-list__helpfulness-wrapper">
                        <div class="aw-pq-list__helpfulness">
                            <div class="aw-pq-list__helpfulness-layout">
                                <div class="aw-pq-list__helpfulness-layout-unit">
                                    <a title="<?= $this->escapeHtml($this->getTitleForQuestionVote());?>" data-question-id="<?= /* @noEscape */ $question->getId(); ?>" class="aw-pq-list__helpfulness-icon aw-pq-list__helpfulness-icon_like<?php if ($this->isCustomerLikeQuestion($question->getId())) : ?> aw-pq-list__helpfulness-icon_like_voted<?php endif; ?><?php if (!$this->isCustomerCanVoteQuestion()) : ?> aw-pq-list__helpfulness-icon_state_disabled<?php endif;?>" href=""">
                                        <?= $this->getChildHtml('aw_pq_question_list.icon.thumb-up')?>
                                    </a>
                                </div>
                                <div class="aw-pq-list__helpfulness-layout-unit aw-pq-list__helpfulness-layout-unit_position_center">
                                    <?php $questionHelpfulness = $this->escapeHtml($question->getHelpfulness()); ?>
                                    <span class="aw-pq-list__helpfulness-value"><?= __($questionHelpfulness); ?></span>
                                    <span class="aw-pq-list__helpfulness-progress" style="display:none;"><?= __($questionHelpfulness) ?></span>
                                </div>
                                <div class="aw-pq-list__helpfulness-layout-unit">
                                    <a title="<?= $this->escapeHtml($this->getTitleForQuestionVote());?>" data-question-id="<?= /* @noEscape */ $question->getId(); ?>" class="aw-pq-list__helpfulness-icon aw-pq-list__helpfulness-icon_dislike<?php if ($this->isCustomerDislikeQuestion($question->getId())) : ?> aw-pq-list__helpfulness-icon_dislike_voted<?php endif; ?><?php if (!$this->isCustomerCanVoteQuestion()) : ?> aw-pq-list__helpfulness-icon_state_disabled<?php endif;?>" href="#">
                                        <?= $this->getChildHtml('aw_pq_question_list.icon.thumb-down')?>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="aw-pq-list__answer-list">
                        <div class="aw-pq-list__question">
                            <div class="aw-pq-list__question-label">
                                <?= __('Question'); ?>
                            </div>
                            <div class="aw-pq-list__question-wrapper">
                                <div class="aw-pq-list__question-content">
                                    <?= /* @noEscape */ $this->getQuestionContent($question); ?>
                                </div>
                                <div class="aw-pq-list__question-info">
                                    <?php $authorName = $this->escapeHtml($question->getAuthorName()); ?>
                                    <?php if ($question->getIsAdmin()) : ?>
                                        <?php $authorName = '<span class="aw-pq-list__admin-name">' . $authorName . ' ' . __('(Admin)') . '</span>'; ?>
                                    <?php endif; ?>
                                    <?= /* @noEscape */ __('Question by: %1', $authorName); ?>
                                </div>
                                <div class="aw-pq-list__question-info">
                                    <?= /* @noEscape */ __('on %1', $this->formatDate($question->getCreatedAt(), \IntlDateFormatter::MEDIUM, true)); ?>
                                </div>
                            </div>
                        </div>
                        <?php $answerCollection = $this->getAnswerCollectionForQuestion($question); ?>
                        <?php if ($answerCollection->getSize() > 0) : ?>
                            <?php foreach ($answerCollection as $answer) : ?>
                                <div class="aw-pq-list__answer-item<?php if ($answer->getIsAdmin()): ?> aw-pq-list__answer-item_type_admin<?php endif; ?>">
                                    <div class="aw-pq-list__answer">
                                        <div class="aw-pq-list__answer-label">
                                            <div class="aw-pq-list__answer-helpfulness-wrapper">
                                                <div class="aw-pq-list__answer-label-text">
                                                    <?= __('Answer'); ?>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="aw-pq-list__answer-wrapper">

                                            <div class="aw-pq-list__answer-content"><?= /* @noEscape */ $this->getAnswerContent($answer); ?></div>

                                            <?php $authorName = $this->escapeHtml($answer->getAuthorName()); ?>
                                            <?php if ($answer->getIsAdmin()) : ?>
                                                <?php $authorName = '<span class="aw-pq-list__admin-name">' . $authorName . ' ' . __('(Admin)') . '</span>'; ?>
                                            <?php endif; ?>
                                            <div class="aw-pq-list__answer-date"><?= /* @noEscape */ __('Answer by: %1 on %2', $authorName, $this->formatDate($answer->getCreatedAt(), \IntlDateFormatter::MEDIUM, true)); ?></div>
                                            <div class="aw-pq-list__helpfulness aw-pq-list__helpfulness--answer">
                                                <div class="aw-pq-list__helpfulness-layout">
                                                    <div class="aw-pq-list__helpfulness-layout-unit">
                                                        <a title="<?= $this->escapeHtml($this->getTitleForAnswerVote());?>" data-answer-id="<?= /* @noEscape */ $answer->getId(); ?>" class="aw-pq-list__helpfulness-icon aw-pq-list__helpfulness-icon_like<?php if ($this->isCustomerLikeAnswer($answer->getId())) : ?> aw-pq-list__helpfulness-icon_like_voted<?php endif; ?><?php if (!$this->isCustomerCanVoteAnswer()) : ?> aw-pq-list__helpfulness-icon_state_disabled<?php endif;?>" href="#">
                                                            <?= $this->getChildHtml('aw_pq_question_list.icon.thumb-up')?>
                                                        </a>
                                                    </div>
                                                    <div class="aw-pq-list__helpfulness-layout-unit aw-pq-list__helpfulness-layout-unit_position_center">
                                                        <?php $answerHelpfulness = $this->escapeHtml($answer->getHelpfulness()); ?>
                                                        <span class="aw-pq-list__helpfulness-value"><?= __($answerHelpfulness); ?></span>
                                                        <span class="aw-pq-list__helpfulness-progress" style="display:none;"><?= __($answerHelpfulness); ?></span>
                                                    </div>
                                                    <div class="aw-pq-list__helpfulness-layout-unit">
                                                        <a title="<?= $this->escapeHtml($this->getTitleForAnswerVote());?>" data-answer-id="<?=/* @noEscape */ $answer->getId(); ?>" class="aw-pq-list__helpfulness-icon aw-pq-list__helpfulness-icon_dislike<?php if ($this->isCustomerDislikeAnswer($answer->getId())) : ?> aw-pq-list__helpfulness-icon_dislike_voted<?php endif; ?><?php if (!$this->isCustomerCanVoteAnswer()) : ?> aw-pq-list__helpfulness-icon_state_disabled<?php endif;?>" href="#">
                                                            <?= $this->getChildHtml('aw_pq_question_list.icon.thumb-down')?>
                                                        </a>

                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            <?php endforeach; ?>
                        <?php else : ?>
                            <?php if ($this->canAnswerQuestion()) : ?>
                                <div class="aw-pq-list__no-answers"><?= $this->escapeHtml(__('No answers yet. Be the first to answer the question!')); ?></div>
                            <?php else : ?>
                                <div class="aw-pq-list__no-answers"><?= $this->escapeHtml(__('No answers yet.')); ?></div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <div class="aw-pq-list__answer-action-bar">
                            <div class="aw-pq-list__next-answer" style="display:none">
                                <button class="aw-pq-list__next-answer-button">
                                    <span class="aw-pq-list__next-answer-button-span"><?= $this->escapeHtml(__('Next Answer')); ?></span>
                                    <?= $block->getChildHtml('aw_pq_question_list.next-answer.button.icon'); ?>
                                </button>
                            </div>
                            <?php if ($this->canAnswerQuestion() || true) : ?>
                                <button type="button" class="aw_pq__add-answer-button aw-pq-list__add-answer-button" title="<?= $this->escapeHtml(__('Add Answer')); ?>">
                                    <span class="aw_pq__add-answer-button-span aw-pq-list__add-answer-button-span">
                                        <?= $this->escapeHtml(__('Add Answer')); ?>
                                    </span>
                                    <?= $block->getChildHtml('aw_pq_question_list.add-answer.button.icon'); ?>
                                </button>
                            <?php else : ?>
                                <?= /* @noEscape */ $this->getAnswerMessage(); ?>
                            <?php endif; ?>
                            <div class="aw-pq-question-form__wrapper aw-pq-answer-form" style="display: none;">
                                <?= /* @noEscape */ $this->getChildBlock('aw_pq_add_answer_form')->setQuestionId($question->getId())->toHtml(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else : ?>
            <div class="aw-pq-list__no-questions"><?= $this->escapeHtml(__('No questions yet. Be the first to ask the question!')); ?></div>
        <?php endif; ?>
        <script type="text/javascript">
            require([
                'AWPquestion', 'AWPquestionVoter'
            ], function($) {
                var config = {
                    'addQuestionButtonSelector': '.aw-pq-list__add-question-button',
                    'addQuestionButtonTextContainerSelector': 'span span',
                    'addQuestionButtonText': {
                        'inactive': <?= /* @noEscape */ \Zend_Json::encode(__('Ask Question'));?>,
                        'active': <?= /* @noEscape */ \Zend_Json::encode(__('Hide Question Form'));?>
                    },
                    'questionFormSelector': '.aw-pq-question-form',
                    'questionContentSelector': '.aw-pq-list__question-content',
                    'questionExpandSelector': '.aw-pq-list__question-expand',
                    'questionExpandStatus': {
                        'activeClassName': 'aw-pq-list__question-expand_arrow_right',
                        'inactiveClassName': 'aw-pq-list__question-expand_arrow_down'
                    },
                    'questionItemContainerSelector': '.aw-pq-list__question-item',
                    'questionItemHiddenClass': 'aw-pq-list__question-item_hidden',
                    'nextQuestionsSelector': '.aw-pq-list__next-question',
                    'questionPageSize': <?= /* @noEscape */ $this->getQuestionPageSize();?>,
                    'answerItemHiddenClass': 'aw-pq-list__answer-item_hidden',
                    'answerListContainerSelector': '.aw-pq-list__answer-list',
                    'addAnswerButtonSelector': '.aw_pq__add-answer-button',
                    'addAnswerButtonTextContainerSelector': 'span span',
                    'addAnswerButtonText': {
                        'inactive': <?= /* @noEscape */ \Zend_Json::encode(__('Add Answer'));?>,
                        'active': <?= /* @noEscape */ \Zend_Json::encode(__('Hide Answer Form'));?>
                    },
                    'nextAnswersSelector': '.aw-pq-list__next-answer',
                    'answerFormSelector': '.aw-pq-answer-form',
                    'answerPageSize': <?= /* @noEscape */ $this->getAnswerPageSize();?>
                };
                new AWPqItemManager(config);

                var voterManagerConfig = {
                    'voterContainerSelector': '.aw-pq-list__helpfulness',
                    'likeSelector': '.aw-pq-list__helpfulness-icon_like',
                    'questionAttrName': 'data-question-id',
                    'answerAttrName': 'data-answer-id',
                    'likeQuestionUrl': '<?= $this->escapeUrl($this->getLikeQuestionUrl()); ?>',
                    'likeAnswerUrl': '<?= $this->escapeUrl($this->getLikeAnswerUrl()); ?>',
                    'disabledClass': 'aw-pq-list__helpfulness-icon_state_disabled',
                    'votedLikeClass': 'aw-pq-list__helpfulness-icon_like_voted',
                    'dislikeSelector': '.aw-pq-list__helpfulness-icon_dislike',
                    'dislikeQuestionUrl': '<?= $this->escapeUrl($this->getDislikeQuestionUrl()); ?>',
                    'dislikeAnswerUrl': '<?= $this->escapeUrl($this->getDislikeAnswerUrl()); ?>',
                    'votedDislikeClass': 'aw-pq-list__helpfulness-icon_dislike_voted',
                    'valueSelector': '.aw-pq-list__helpfulness-value',
                    'progressSelector': '.aw-pq-list__helpfulness-progress',
                    'formKey': <?= /* @noEscape */ \Zend_Json::encode($this->getSessionFormKey());?>
                };
                new AWPqVoteManager(voterManagerConfig);
            });
        </script>
    </div>

    <div class="aw-pq-question__question">
        <div class="aw-pq-list__next-question" style="display:none;">
            <button class="aw-pq-list__next-question-button">
                <span class="aw-pq-list__next-question-button-span"><?= $this->escapeHtml(__('More Questions')); ?></span>
                <?= $block->getChildHtml('aw_pq_question_list.next-question.button.icon'); ?>
            </button>
        </div>
        <?php if ($this->canAskQuestion()) : ?>
            <button type="button" class="aw-pq-list__add-question-button" title="<?= $this->escapeHtml(__('Ask Question')); ?>" >
                <span class="aw-pq-list__add-question-button-span"><?= $this->escapeHtml(__('Ask Question')); ?></span>
                <?= $block->getChildHtml('aw_pq_question_list.add-question.button.icon'); ?>
            </button>
        <?php else : ?>
            <div class="aw-pq-list__please-login-note">
                <?= /* @noEscape */ __("You must be <a href='%1'>logged in</a> to ask questions.", $this->getLoginUrl()); ?>
            </div>
        <?php endif; ?>
        <?php if ($this->canAskQuestion()) : ?>
            <div class="aw-pq-question-form__wrapper aw-pq-question-form" style="display: none;">
                <?= /* @noEscape */ $this->getChildHtml('aw_pq_ask_question_form'); ?>
            </div>
        <?php endif; ?>
    </div>

</div>

