include:
- project: gitlab-automation/gitlab-ci-automation
  ref: mgs-theme
  file:
  - /jobs/magesuite.yaml

variables:
  MAGESUITE_THEME_MODULE: 1
  MAGESUITE_ROOT_THEME: 1
  NODEJS_MODULE: 1
  NODEJS_PRETTIER: 1
  NODEJS_STYLELINT: 1
  NODEJS_TSLINT: 1
