<?php
/**
 * Template overridden to
 * - extend feature
 * Aligned with MageSuite_PositiveIndicators v3.2.11 in 05/2025
 */

    $qty = $block->getProductQty();
    $displayFlag = $block->shouldDisplayInfoOnProductPage($qty);
?>
<?php if($displayFlag): ?>
    <div class="cs-indicator-low-stock">
        <div class="cs-indicator-low-stock__content">
            <?= $block->getChildHtml(''); ?>
            <span class="cs-indicator-low-stock__label">
                <?php if($qty == 1) {
                    echo __('<span>Hurry up!</span> Only <span>1 product</span> available!');
                } else {
                    echo __('<span>Hurry up!</span> Only <span>%1 products</span> available!', $qty);
                } ?>
            </span>
        </div>
    </div>
<?php endif; ?>
