<?php
    $label = $block->getXmlLabel();
?>
<li class="cs-header-user-nav__item <?= $block->getAdditionalCssClasses() ?>">
    <a href="<?php /* @escapeNotVerified */ echo $block->getHref(); ?>" class="cs-header-user-nav__link">
        <div class="cs-header-user-nav__icon-wrapper">
            <?= $block->getChildHtml('my-account-link.icon'); ?>
            <?php if (!empty($label)): ?>
                <span class="cs-header-user-nav__label"><?= __($block->escapeHtml($label)); ?></span>
            <?php endif; ?>
        </div>
    </a>
</li>
