<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
    <div class="cs-info-block | block-new-customer">

        <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
            <h2
                id="block-new-customer-heading"
                role="heading"
                aria-level="2"
                class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light"
            >
                <?php /* @escapeNotVerified */ echo __("I don't have an account yet") ?>
            </h2>
        </div>

        <div class="cs-info-block__content" aria-labelledby="block-new-customer-heading">
            <p class="cs-t-text cs-t-text--look_attention cs-t-text--type_wide">
                <?php /* @escapeNotVerified */ echo __('Create an account and:') ?>
            </p>
            <ul class="cs-list cs-list--unstyled">
                <li class="cs-list__item">
                    <svg class="cs-list__bullet cs-list__bullet--tick">
                        <use xlink:href="#check"></use>
                    </svg>
                    <?php /* @escapeNotVerified */ echo __('Check out faster') ?>
                </li>
                <li class="cs-list__item">
                    <svg class="cs-list__bullet cs-list__bullet--tick">
                        <use xlink:href="#check"></use>
                    </svg>
                    <?php /* @escapeNotVerified */ echo __('Save multiple shipping addresses') ?>
                </li>
                <li class="cs-list__item">
                    <svg class="cs-list__bullet cs-list__bullet--tick">
                        <use xlink:href="#check"></use>
                    </svg>
                    <?php /* @escapeNotVerified */ echo __('Access your order history') ?>
                </li>
                <li class="cs-list__item">
                    <svg class="cs-list__bullet cs-list__bullet--tick">
                        <use xlink:href="#check"></use>
                    </svg>
                    <?php /* @escapeNotVerified */ echo __('Track new orders') ?>
                </li>
                <li class="cs-list__item">
                    <svg class="cs-list__bullet cs-list__bullet--tick">
                        <use xlink:href="#check"></use>
                    </svg>
                    <?php /* @escapeNotVerified */ echo __('Save items to your wish list') ?>
                </li>
            </ul>
            <div class="cs-info-block__buttons">
                <a
                    href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>"
                    class="cs-button cs-button--type_long cs-button--type_wide-mobile  cs-button--look_default"
                >
                   <span class="cs-button__span"> <?php /* @escapeNotVerified */ echo __("I'am a new customer") ?></span>
                    <svg class="cs-button__icon">
                        <use xlink:href="#arrow_next"></use>
                    </svg>
                </a>
            </div>
        </div>
    </div>
<?php endif; ?>
