<?php
// @codingStandardsIgnoreFile
?>

<?php $product = $block->getProduct() ?>
<?php if ($product->isSaleable() && $block->hasOptions()):?>
    <button
        id="bundle-slide"
        class="cs-button cs-button--type_wide  cs-button--look_light customize"
        type="button"
    >
        <span class="cs-button__span"><?php /* @escapeNotVerified */ echo __('Customize'); ?></span>
        <svg class="cs-button__icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </button>
<?php endif;?>
