<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$product = $block->getProduct();
?>
<?php if ($product->isSaleable() && $block->hasOptions()): ?>
    <div id="bundleSummary"
         class="cs-bundle-box__summary block-bundle-summary"
         data-mage-init='{"sticky":{"container": ".product-add-form"}}'>
        <div class="cs-bundle-box__title">
            <?php /* @escapeNotVerified */ echo __('Your Customization'); ?> 
        </div>

        <div class="cs-bundle-box__summary-content | bundle-summary">
            <div id="bundle-summary" data-container="product-summary">
                <ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
                <script data-template="bundle-summary" type="text/x-magento-template">
                    <li>
                        <div class="cs-bundle-box__product-name cs-bundle-box__product-name--small-space"><%- data
                            ._label_ %>:</div>
                        <div data-container="options"></div>
                    </li>
                </script>
                <script data-template="bundle-option" type="text/x-magento-template">
                    <div><?php /* @escapeNotVerified */ echo __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?></div>
                </script>
            </div>
        </div>

        <div class="content">
            <div class="bundle-info">
                <div class="cs-bundle-box__add product-details">

                    <?php if ($product->getIsSalable()): ?>
                        <p class="cs-bundle-box__availability" title="<?php /*
 * @escapeNotVerified */ echo __
                        ('Availability') ?>">
                            <svg class="cs-product-sale-block__stock-icon cs-product-sale-block__stock-icon--available">
                                <use xlink:href="#check"></use>
                            </svg>
                            <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                        </p>
                    <?php else: ?>
                        <p class="cs-bundle-box__availability cs-bundle-box__availability--unavailable" title="<?php
                        /* @escapeNotVerified */ echo __('Availability') ?>">
                            <link itemprop="availability" href="http://schema.org/OutOfStock" />
                            <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                        </p>
                    <?php endif; ?>
                    <?php echo $block->getChildHtml('', true);?>
                </div>
            </div>

        </div>
    </div>
    <script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()): ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>
<?php endif; ?>
