<?php
// @codingStandardsIgnoreFile
// Override due to reorganize elements and introduce BEM
?>

<?php
    $product = $block->getProduct();
?>
<?php if ($product->isSaleable() && $block->hasOptions()): ?>
<div id="bundleSummary"
     class="block-bundle-summary cs-bundle-box__summary"
     data-mage-init='{"sticky":{"container": ".product-add-form"}}'>
    <div class="content cs-bundle-box__summary-content">
        <div class="bundle-info cs-bundle-box__summary-section cs-bundle-box__summary-section--product-details">
            <p class="title cs-bundle-box__summary-title"><?= /* @escapeNotVerified */ __('Your Customization') ?></p>
            <div class="cs-bundle-box__summary-product-details">
                <?= $block->getImage($product, 'bundled_product_customization_page')->toHtml() ?>
                <p class="product name cs-bundle-box__summary-product-name"><?= $block->escapeHtml($product->getName()) ?></p>
            </div>
        </div>
        <div class="bundle-info cs-bundle-box__summary-section cs-bundle-box__summary-section--addtocart">
            <div id="bundle-summary" data-container="product-summary">
                <ul data-mage-init='{"productSummary": []}' class="bundle items cs-bundle-box__bunde-items"></ul>
                <script data-defer-ignore="true" data-template="bundle-summary" type="text/x-magento-template">
                    <li class="cs-bundle-box__bundle-item">
                        <p class="label cs-bundle-box__bunde-item-name"><%- data._label_ %>:</p>
                        <div class="cs-bundle-box__bunde-item-value" data-container="options"></div>
                    </li>
                </script>
                <script data-defer-ignore="true" data-template="bundle-option" type="text/x-magento-template">
                    <div><?= /* @escapeNotVerified */ __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?></div>
                </script>
            </div>

            <div class="product-details cs-bundle-box__summary-extras">
                <?= $block->getChildHtml('', true) ?>    
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 300,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".cs-container--page-pdp-bundle-config"
                <?php if ($block->isStartCustomization()): ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>
<?php endif; ?>
