
<div class="cs-info-block cs-info-block--space | block-amazon-login">

    <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
        <h2 class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light">
            <span
                id="block-amazon-login-heading"
                role="heading"
                aria-level="2"
            >
                <?php /* @escapeNotVerified */ echo __('Login with Amazon') ?>
            </span>
        </h2>
    </div>

    <div class="cs-info-block__content" aria-labelledby="block-amazon-login-heading">
        <p class="cs-t-text"><?php /* @escapeNotVerified */ echo __('With Amazon Pay and Login with Amazon, you can
        easily sign-in
         and use the shipping and payment information stored in your Amazon account to place an order on this shop. ') ?></p>
        <div class="cs-form__buttons cs-form__buttons--no-space">
            <div class="amazon-button-container">
                <div class="amazon-button-container__cell">
                    <div id="LoginWithAmazon" class="login-with-amazon" data-mage-init='{"amazonButton": {"buttonType": "LwA"}}'></div>
                </div>
                <div class="amazon-button-container__cell">
                    <div class="field-tooltip toggle">
                        <span class="field-tooltip-action action-help" data-mage-init='{"dropdown": {"activeClass": "_active"}}' data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></span>
                        <div class="field-tooltip-content" data-target="dropdown" aria-hidden="true"><?php /* @escapeNotVerified */  echo __('Securely login into our website using your existing Amazon details.'); ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



