<?php
// @codingStandardsIgnoreFile
/** @var $block Aheadworks\Giftcard\Block\Checkout\Cart\Giftcard */
// @TODO: refactor .cs-form & .cs-button classes

$placeholder = $block->getInputPlaceholder();
$inputLabel = $block->getInputLabel();
$buttonApplyLabel = $block->getButtonApplyLabel();
$buttonCheckLabel = $block->getButtonCheckLabel();
$collapseOptions = $block->getCollapsibleWidgetOptions();
?>

<div class="block aw-giftcard cs-discount <?= $block->getAdditionalCssClasses() ?>" id="block-aw-giftcard" 
    <?php if($block->getIsCollapsible()): ?>
        data-mage-init='{"collapsible":<?= !empty($collapseOptions) ? json_encode($collapseOptions) : '{}' ?>}'
    <?php endif; ?>
    >
    <div class="cs-discount__title title" data-role="title">
        <span class="cs-discount__title-text" id="block-aw-giftcard-heading" role="heading" aria-level="2">
            <?= $block->getHeadline(); ?>
        </span>
        <?= $block->getChildHtml('checkout.cart.aw.giftcard.icon'); ?>
    </div>
    <div class="content cs-discount__content" data-role="content" aria-labelledby="block-aw-giftcard-heading">
        <?php echo $block->getChildHtml('giftcard_codes') ?>
        <div id="aw_giftcard__code_info"></div>
        <form
            id="discount-aw-giftcard-form"
            class="cs-discount__form cs-form"
            action=""
            method="post"
            data-mage-init='{"awGiftCardManagement":{}}'
        >
            <div class="fieldset aw-giftcard cs-discount__form-fieldset cs-form__fieldset">
                <div class="field cs-discount__form-field cs-form__field cs-input">
                    <?php if(!empty($inputLabel)): ?>
                    <label for="code" class="cs-discount__form-label cs-input__label label">
                        <span><?= $block->escapeHtml($inputLabel); ?></span>
                    </label>
                    <?php endif; ?>
                    <div class="cs-discount__form-control cs-input__control control">
                        <input
                            type="text"
                            class="cs-discount__form-input cs-input__input input-text"
                            name="code"
                            <?php if(!empty($placeholder)): ?>placeholder="<?= $block->escapeHtml($placeholder); ?>"<?php endif; ?>
                            data-validate="{required:true}"
                        />
                    </div>
                </div>
                <div class="actions-toolbar cs-discount__toolbar cs-form__buttons">
                    <button
                        class="action apply-aw-giftcard primary cs-discount__button cs-button cs-giftcard__button-apply"
                        type="submit"
                        value="<?= $block->escapeHtml($buttonApplyLabel); ?>"
                        data-role="aw-giftcard-apply-action"
                        data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getActionUrl()) ?>"
                    >
                        <span class="cs-discount__button-span cs-button__span"><?= $block->escapeHtml($buttonApplyLabel); ?></span>
                        <?= $block->getChildHtml('checkout.cart.aw.giftcard.apply.icon'); ?>
                    </button>
                    <button
                        class="action check-aw-giftcard cs-discount__button cs-button cs-giftcard__button-status"
                        type="button"
                        value="<?= $block->escapeHtml($buttonCheckLabel); ?>"
                        data-role="aw-giftcard-check-code-action"
                        data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getCheckCodeUrl()) ?>"
                    >
                        <span class="cs-discount__button-span cs-button__span"><?= $block->escapeHtml($buttonCheckLabel); ?></span>
                        <?= $block->getChildHtml('checkout.cart.aw.giftcard.check.icon'); ?>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
