<?php

// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\Giftcard\Block\Customer\Giftcard */
?>
<div class="cs-info-block cs-dashboard__block cs-giftcard">
    <div id="aw_giftcard__code_info"></div>
    <?php echo $block->getChildHtml('aw_giftcard_codes') ?>
    <form
        id="aw_giftcard__check_code_form"
        class="cs-form"
        action=""
        method="post"
        data-mage-init='{"awGiftCardManagement":{}}'
    >
        <fieldset class="cs-form__fieldset aw_giftcard__check">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="cs-form__field cs-input required">
                <label class="cs-input__label" for="code">
                    <span><?php echo $block->escapeHtml(__('Enter Gift Card code')) ?></span>
                </label>
                <div class="cs-input__control">
                    <input
                        type="text"
                        name="code"
                        value=""
                        title="<?php echo $block->escapeHtml(__('Enter Gift Card code')) ?>"
                        class="cs-input__input"
                        data-validate="{required:true}"
                    >
                </div>
            </div>
        </fieldset>
        <div class="cs-form__buttons">
            <button type="button"
                    class="cs-button cs-giftcard__button-ua"
                    title="<?php echo $block->escapeHtml(__('Check Status and Balance')) ?>"
                    data-role="aw-giftcard-check-code-action"
                    data-url="<?php /* @noEscape */ echo $block->escapeUrl($block->getCheckCodeUrl()) ?>">
                <span class="cs-button__span">
                    <?php echo $block->escapeHtml(__('Check Status and Balance')) ?>
                </span>
                <svg class="cs-button__icon">
                    <use xlink:href="#arrow_next"></use>
                </svg>
            </button>
        </div>
    </form>

</div>
