<?php
/**
 * Template overwritten to:
 * - add magesuite classes
 * - replace text with childHtml block
 * - remove title attribute
 *
 * Aligned with Magento 2.4.6 at 04/2023
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <div class="cs-cart-item__link cs-cart-item__link--edit">
        <a class="cs-cart-item__link-wrapper"
           href="<?= $block->escapeUrl($block->getConfigureUrl()) ?>"
        >
            <?= $block->getChildHtml(); ?>
        </a>
    </div>
<?php endif ?>
