<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit */
?>
<?php if ($block->isProductVisibleInSiteVisibility()): ?>
    <div class="cs-cart-item__link cs-cart-item__link--left">
        <a class="cs-cart-item__link-wrapper"
           href="<?php /* @escapeNotVerified */ echo $block->getConfigureUrl() ?>"
           title="<?php echo $block->escapeHtml(__('Edit item parameters')); ?>"
        >
            <?= $block->getChildHtml(); ?>
        </a>
    </div>
<?php endif ?>
