<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<div class="cs-cart-item__link cs-cart-item__link--remove">
    <a class="cs-cart-item__link-wrapper"
        href="#"
        title="<?= $block->escapeHtml(__('Remove item')); ?>"
        data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson(); ?>'
        data-uenc-update="true"
    >
        <?= $block->getChildHtml(); ?>
    </a>
</div>

