<?php
/**
 * Template overwritten to:
 * - add magesuite classes
 * - replace text with childHtml block
 * - add  data-uenc-update attribute
 * - remove title attribute
 *
 * Aligned with Magento 2.4.6 at 04/2023
 */

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<div class="cs-cart-item__link cs-cart-item__link--remove">
    <a class="cs-cart-item__link-wrapper"
        href="#"
        data-post='<?= /* @noEscape */ $block->getDeletePostJson(); ?>'
        data-uenc-update="true"
    >
        <?= $block->getChildHtml(); ?>
    </a>
</div>

