<?php if ($block->canShowBlock()): ?>
    <div class="cs-tabs__content cs-search-results-switcher__content" id="tab-content-cmspages" data-role="content">
        <h2 class="cs-search-results-switcher__headline">
            <?= __('Pages results')?> <span class="cs-search-results-switcher__count"><?= $block->getResultCount(); ?></span>
        </h2>
        <ul class="cs-search-results-cms">
        <?php foreach ($block->getPageCollection() as $currentPage) : ?>
            <li class="cs-search-results-cms__item">
                <a class="cs-search-results-cms__link" href="<?= $block->getPageUrl($currentPage->getId())?>">
                    <?= $this->getLayout()
                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                        ->setIconUrl('images/icons/cms/article.svg')
                        ->setCssClass('cs-search-results-cms__icon')
                        ->setInlined(true)
                        ->toHtml();
                    ?>
                    <span class="cs-search-results-cms__title"><?= $currentPage->getTitle(); ?></span>
                </a>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
