<?php if ($block->canShowBlock()): ?>
    <div class="cs-tabs__content cs-searchresults-switcher__content" id="tab-content-cmspages" data-role="content">
        <h2 class="cs-t-headline cs-t-headline--size_2"><?php echo __('Pages results')?> <span class="cs-t-headline__count">55</span></h2>

        <ul class="cs-list cs-list--unstyled">
            <?php foreach ($block->getPageCollection() as $currentPage) : ?>
                <li class="cs-list__item cs-list__item--bold">
                    <a class="cs-list__flex-link" href="<?php echo $block->getPageUrl($currentPage->getId())?>">
                        <svg class="cs-list__bullet cs-list__bullet--article"><use xlink:href="#article"></use></svg>
                        <?php echo $currentPage->getTitle(); ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
