<?php if ($block->canShowBlock()): ?>
    <div class="cs-tabs__content cs-searchresults-switcher__content" id="tab-content-cmspages" data-role="content">
        <h2><?php echo __('Pages results')?> <span><?php echo $block->getResultCount(); ?></span></h2>

        <ul class="cs-searchresults-switcher__list">
            <?php foreach ($block->getPageCollection() as $currentPage) : ?>
                <li class="cs-searchresults-switcher__list-item">
                    <a class="cs-searchresults-switcher__list-item-link" href="<?php echo $block->getPageUrl($currentPage->getId())?>">
                        <svg class="cs-searchresults-switcher__list-item-icon"><use xlink:href="#article"></use></svg>
                        <?php echo $currentPage->getTitle(); ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
