<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>


<div class="page-title-wrapper">
    <h1 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading">
        <span class="base" data-ui-id="page-title-wrapper">
            <?php /* @escapeNotVerified */ echo __('Search results for: "%1"', $block->getHeadline()) ?></span>
    </h1>
</div>
