<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>


<div class="page-title-wrapper">
    <h1 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading">
        <span class="base" data-ui-id="page-title-wrapper">
            <?php /* @escapeNotVerified */ echo $block->getHeadline() ?>
            <span class="page-title__span cs-searchresults-switcher__overall-count"></span>
        </span>
    </h1>
</div>
