<div class="cs-tabs cs-tabs--bar cs-search-results-switcher">
    <div class="cs-tabs__triggers cs-search-results-switcher__triggers">
        <div class="cs-tabs__title cs-tabs__title--active" data-role="collapsible">
            <a class="cs-tabs__title-link cs-search-results-switcher__trigger"
               tabindex="-1"
               data-toggle="switch"
               href="#all">
                <?php echo __('All results'); ?> <span class="cs-tabs__title-span" id="count-all"></span>
            </a>
        </div>

        <div class="cs-tabs__title" data-role="collapsible">
            <a class="cs-tabs__title-link cs-search-results-switcher__trigger"
               tabindex="-1"
               data-toggle="switch"
               href="#tab-content-cmspages"
               id="tab-cmspages-title">
                <?php echo __('Pages'); ?> <span class="cs-tabs__title-span" id="count-cms"></span>
            </a>
        </div>

        <div class="cs-tabs__title" data-role="collapsible">
            <a class="cs-tabs__title-link cs-search-results-switcher__trigger"
               tabindex="-1"
               data-toggle="switch"
               href="#tab-content-products"
               id="tab-products-title">
                <?php echo __('Products'); ?> <span class="cs-tabs__title-span" id="count-products"></span>
            </a>
        </div>
    </div>
</div>
