<?php
/**
 * Custom template
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
$areas = $block->getAreas() ?? [];
$areas = array_filter($areas, fn($area) => $area !== null);
$sortOrder = array_column($areas, 'sort_order');
array_multisort($sortOrder, SORT_ASC, $areas);
?>
<?php if (!empty($areas)) : ?>
<div class="cs-tabs cs-tabs--bar cs-search-results-switcher">
    <div class="cs-tabs__triggers cs-search-results-switcher__triggers">
    <?php foreach ($areas as $key => $area) : ?>
        <?php $isAriaSelected = $area['is_aria_selected'] ?? 'false'; ?>
        <div class="cs-tabs__title cs-search-results-switcher__trigger-wrapper cs-search-results-switcher__trigger-wrapper--<?= $escaper->escapeHtmlAttr($key); ?> <?= /** @noEscape  */ $area['additional_css'] ?? '' ?>"
             data-role="collapsible">
            <a class="cs-tabs__title-link cs-search-results-switcher__trigger"
               data-toggle="switch"
               role="tab"
               aria-selected="<?= $escaper->escapeHtmlAttr($isAriaSelected); ?>"
               href="<?= $escaper->escapeHtmlAttr($area['title_href']); ?>"
               id="<?= $escaper->escapeHtmlAttr($area['title_id']); ?>">
                <?= $escaper->escapeHtmlAttr($area['label']); ?> <span class="cs-tabs__title-span" id="<?= $escaper->escapeHtmlAttr($area['count_id']) ?>"></span>
            </a>
        </div>
    <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>
