<?php
/**
 * Template has been overwritten in order to adjust markup
 * for toolbar-amount and toolbar-limiter.
 * NOTE: Pager container element has been removed.
 */

// @codingStandardsIgnoreFile

/** @var \Aheadworks\RewardPoints\Block\Html\Pager $block */
?>
<?php if ($block->getTotalNum()): ?>

        <?php if ($block->getShowAmounts()): ?>
        <div class="cs-toolbar__item cs-toolbar__item--amount">
            <p class="toolbar-amount">
                <span class="toolbar-number">
                <?php if ($block->getLastPageNum()>1): ?>
                    <?php /* @escapeNotVerified */ echo __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
                <?php elseif ($block->getTotalNum() == 1): ?>
                    <?php /* @escapeNotVerified */ echo __('%1 Item', $block->getTotalNum()) ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo __('%1 Item(s)', $block->getTotalNum()) ?>
                <?php endif; ?>
                </span>
            </p>
        </div>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages">
            <strong class="label pages-label" id="paging-label"><?php /* @escapeNotVerified */ echo __('Page') ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
            <?php if (!$block->isFirstPage()): ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?php echo $block->escapeHtml($text ? 'link ' : 'action ') ?> previous" href="<?php echo $block->escapeHtml($block->getPreviousPageUrl()) ?>" title="<?php echo $block->escapeHtml($text ? $text : __('Previous')) ?>">
                        <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                        <span><?php echo $block->escapeHtml($text ? $text : __('Previous')) ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()): ?>
                <li class="item">
                    <a class="page first" href="<?php echo $block->escapeHtml($block->getFirstPageUrl()) ?>">
                        <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()): ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?php echo $block->escapeHtml($block->getPreviousJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page)): ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?php /* @escapeNotVerified */ echo __('You\'re currently reading page') ?></span>
                            <span><?php echo $block->escapeHtml($_page) ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?php echo $block->escapeHtml($block->getPageUrl($_page)) ?>" class="page">
                            <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                            <span><?php echo $block->escapeHtml($_page) ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()): ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?php echo $block->escapeHtml($block->getNextJumpUrl()) ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()): ?>
              <li class="item">
                  <a class="page last" href="<?php echo $block->escapeHtml($block->getLastPageUrl()) ?>">
                      <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                      <span><?php echo $block->escapeHtml($block->getLastPageNum()) ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()): ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?php echo $block->escapeHtml($text ? 'link ' : 'action ') ?> next" href="<?php echo $block->escapeHtml($block->getNextPageUrl()) ?>" title="<?php echo $block->escapeHtml($text ? $text : __('Next')) ?>">
                        <span class="label"><?php /* @escapeNotVerified */ echo __('Page') ?></span>
                        <span><?php echo $block->escapeHtml($text ? $text : __('Next')) ?></span>
                    </a>
                </li>
            <?php endif;?>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="cs-toolbar__item cs-toolbar__item--limiter">
            <strong class="limiter-label"><?php /* @escapeNotVerified */ echo __('Show') ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?php echo $block->escapeHtml($block->getLimitUrl($_key)) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?php echo $block->escapeHtml($_limit) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?php /* @escapeNotVerified */ echo __('per page') ?></span>
        </div>
    <?php endif ?>

<?php endif ?>
