<?php
// @codingStandardsIgnoreFile
$ratingData = $block->getRatingData();
?>

<div class="cs-review">
    <div class="cs-review__title" ><?= $block->getTitle(); ?></div>

    <div class="cs-review__rating">
        <?= $this->getLayout()
                 ->createBlock(\Magento\Framework\View\Element\Template::class)
                 ->setMaxStars($ratingData['maxStars'])
                 ->setActiveStars($ratingData['activeStars'])
                 ->setHideReviewsCount(true)
                 ->setAdditionalClasses('cs-star-rating--review')
                 ->setTemplate('Magento_Review::rating-stars.phtml')
                 ->toHtml();
        ?>
    </div>
    <div class="cs-review__meta">
        <span class="cs-review__author cs-review__meta-item"><?= $block->getAuthor(); ?></span>
        <time class="cs-review__date cs-review__meta-item" datetime="<?= $block->getDate(); ?>">
            <?= $block->getDate(); ?>
        </time>
    </div>
    <p class="cs-review__content"><?= $block->getContent(); ?></p>
</div>
