<?php
// @codingStandardsIgnoreFile

?>
<?php
$items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($items)): ?>

    <div class="cs-reviews__content" id="customer-reviews">
        <ol class="cs-reviews__list">
            <?php $i = 0;
            foreach ($items as $review): ?>
                <?php
                $i++;
                $createdAt = $review->getCreatedAt();
                $ratingVotes = $review->getRatingVotes();
                $overallRating = !count($ratingVotes) ? null : round(array_sum(array_map(function ($vote) {
                        return $vote->getPercent();
                    }, iterator_to_array($ratingVotes))) / (100 * count($ratingVotes)) * 5);
                ?>
                <li class="cs-reviews__item">
                    <?= $this->getLayout()->createBlock('Creativestyle\FrontendExtension\Block\Twig', 'pdp-review-' . $i, [
                        'data' => [
                            'title' => $block->escapeHtml($review->getTitle()),
                            'rating' => [
                                'maxStars' => 5,
                                'activeStars' => $overallRating,
                                'text' => ''
                            ],
                            'author' => $block->escapeHtml($review->getNickname()),
                            'datetime' => $block->formatDate($createdAt, $format),
                            'date' => $block->formatDate($createdAt, $format),
                            'content' => nl2br($block->escapeHtml($review->getDetail()))
                        ]
                    ])->setTemplate("review/review.twig")->toHtml(); ?>

                </li>
            <?php endforeach; ?>
        </ol>
        <?= $block->getChildHtml('toolbar') ?>
    </div>
<?php endif; ?>
