<?php
// @codingStandardsIgnoreFile

?>
<?php
$items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($items)): ?>
    <div class="cs-reviews__content" id="customer-reviews">
        <ol class="cs-reviews__list">
            <?php
            foreach ($items as $review): ?>

                <?php
                $createdAt = $review->getCreatedAt();
                $ratingVotes = $review->getRatingVotes();
                $ratingCategoriesCount = count($ratingVotes);

                if ($ratingCategoriesCount) {

                    $percentageRatingsList = array_map(function ($vote) {
                        return $vote->getPercent();
                    }, iterator_to_array($ratingVotes));

                    $averagePercentageRating = array_sum($percentageRatingsList)/$ratingCategoriesCount;
                    $starScore = round($averagePercentageRating/20);

                } else {
                    $starScore = null;
                }
                ?>

                <li class="cs-reviews__item">
                    <?= $this->getLayout()
                             ->createBlock(\Magento\Framework\View\Element\Template::class)
                             ->setTemplate('Magento_Review::product/view/list-item.phtml')
                             ->setTitle($block->escapeHtml($review->getTitle()))
                             ->setRatingData([
                                "maxStars" => 5,
                                "activeStars" => $starScore
                             ])
                             ->setAuthor($block->escapeHtml($review->getNickname()))
                             ->setDate($block->formatDate($createdAt, $format))
                             ->setContent(nl2br($block->escapeHtml($review->getDetail())))
                             ->toHtml();
                    ?>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildHtml('toolbar') ?>
<?php endif; ?>
