<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)): ?>

    <div class="cs-reviews__content" id="customer-reviews">
        <ol class="cs-reviews__list">
            <?php $i = 0;
            foreach ($_items as $_review): ?>
                <?php
                $i++;
                $overallRating = !count($_review->getRatingVotes()) ? null : round(array_sum(array_map(function ($vote) {
                            return $vote->getPercent();
                        }, iterator_to_array($_review->getRatingVotes()))) / (100 * count($_review->getRatingVotes())) * 5);
                ?>
                <li class="cs-reviews__item">
                    <?= $this->getLayout()->createBlock('Creativestyle\FrontendExtension\Block\Twig', 'pdp-review-' . $i, ['data' => ['title' => $block->escapeHtml($_review->getTitle()), 'rating' => ['maxStars' => 5, 'activeStars' => $overallRating, 'text' => '<span itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating"><meta itemprop="worstRating" content="1"/><meta itemprop="bestRating" content="5"/><meta itemprop="ratingValue" content="' . $overallRating . '" /></span>'], 'author' => $block->escapeHtml($_review->getNickname()), 'datetime' => $block->formatDate($_review->getCreatedAt(), $format), 'date' => $block->formatDate($_review->getCreatedAt(), $format), 'content' => nl2br($block->escapeHtml($_review->getDetail()))]])->setTemplate("review/review.twig")->toHtml(); ?>

                    <?php /* if (count($_review->getRatingVotes())): ?>
                        <div class="review-ratings">
                        <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                        <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                            <span class="label rating-label"><span><?php echo $block->escapeHtml($_vote->getRatingCode()) ?></span></span>
                            <div class="rating-result" title="<?php /* @escapeNotVerified */ /* echo $_vote->getPercent() ?>%">
    	                        <meta itemprop="worstRating" content = "1"/>
    	                        <meta itemprop="bestRating" content = "100"/>
                                <span style="width:<?php /* @escapeNotVerified */ /* echo $_vote->getPercent() ?>%">
                                    <span itemprop="ratingValue"><?php /* @escapeNotVerified */ /* echo $_vote->getPercent() ?>%</span>
                                </span>
                            </div>
                        </div>
                        <?php endforeach; ?>
                        </div>
                    <?php endif; */ ?>

                </li>
            <?php endforeach; ?>
        </ol>
        <?php /* <div class="cs-reviews__toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div> */ ?>
    </div>
<?php endif; ?>
