<?php
/**
 * Template overridden in order to:
 * - add magesuite classes
 * - change layout
 * - add separator
 * Aligned with Magento 2.4.7 in 04/2024
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <?php $displayCustomSeparator = $block->getVar('breadcrumbs/custom_separator/display', 'Magento_Theme'); ?>
    <div class="cs-breadcrumbs">
        <ul class="cs-breadcrumbs__list">
            <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="cs-breadcrumbs__item <?= $block->escapeHtmlAttr($crumbName) ?>">
                    <?php if ($crumbInfo['link']) : ?>
                        <a
                            class="cs-breadcrumbs__link"
                            href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                            title="<?= $block->escapeHtml($crumbInfo['title']) ?>"
                        >
                            <span>
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </span>
                        </a>
                        <?php if ($displayCustomSeparator) : ?>
                            <span class="cs-breadcrumbs__separator">
                                <?= $this->getLayout()
                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                    ->setIconUrl($block->getVar('breadcrumbs/custom_separator/icon'))
                                    ->setCssClass('cs-breadcrumbs__separator-icon')
                                    ->setInlined(true)
                                    ->toHtml();
                                ?>
                            </span>
                        <?php endif; ?>
                    <?php else: ?>
                        <span>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        </span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
