<?php
/** @see \Magento\Theme\Block\Html\Breadcrumbs */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <?php $displayCustomSeparator = $block->getVar('breadcrumbs/custom_separator/display', 'Magento_Theme'); ?>
    <div class="cs-breadcrumbs">
        <ul class="cs-breadcrumbs__list">
            <?php $i = 1; foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="cs-breadcrumbs__item <?= $block->escapeHtmlAttr($crumbName) ?>">
                    <?php if ($crumbInfo['link']) : ?>
                        <a
                            class="cs-breadcrumbs__link"
                            href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                            title="<?= $block->escapeHtml($crumbInfo['title']) ?>"
                        >
                            <span>
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </span>
                        </a>
                        <?php if ($displayCustomSeparator) : ?>
                            <span class="cs-breadcrumbs__separator">
                                <?= $this->getLayout()
                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                    ->setIconUrl($block->getVar('breadcrumbs/custom_separator/icon'))
                                    ->setCssClass('cs-breadcrumbs__separator-icon')
                                    ->setInlined(true)
                                    ->toHtml(); 
                                ?>
                            </span>
                        <?php endif; ?>
                    <?php /* elseif ($crumbInfo['last']) : ?>
                        <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
                    <?php */ else: ?>
                        <span>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        </span>
                    <?php endif; ?>
                </li>
            <?php $i++; endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
