<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="cs-breadcrumbs">
        <h2 class="cs-visually-hidden"><?=__('Breadcrumbs');?></h2>
        <ul class="cs-breadcrumbs__list" itemscope itemtype="http://schema.org/BreadcrumbList">
            <?php $i = 1; foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                <li class="cs-breadcrumbs__item <?php /* @escapeNotVerified */ echo $crumbName ?>" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                    <?php if ($crumbInfo['link']) : ?>
                        <a class="cs-breadcrumbs__link" href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>" itemscope itemtype="http://schema.org/Thing" itemprop="item">
                            <span itemprop="name"><?php echo $block->escapeHtml($crumbInfo['label']) ?></span>
                        </a>
                    <?php /* elseif ($crumbInfo['last']) : ?>
                        <strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
                    <?php */ else: ?>
                        <span itemprop="name"><?php echo $block->escapeHtml($crumbInfo['label']) ?></span>
                    <?php endif; ?>
                    <meta itemprop="position" content="<?php echo $i ?>" />
                </li>
            <?php $i++; endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
