<?php
/**
* Font loading based on https://dev.to/masakudamatsu/loading-google-fonts-and-any-other-web-fonts-as-fast-as-possible-in-early-2021-4f5o
*/
$localFonts = $block->getLocalFonts();

if (!empty($localFonts)):
    /**
     * Loop through all local fonts defined in XML
     */
    foreach ($localFonts as $url):
        if (!empty($url)):
            $localFontUrl = $this->getViewFileUrl($url); ?>
            <link rel="preload" as="style" href="<?= $localFontUrl ?>">
            <link rel="stylesheet" href="<?= $localFontUrl ?>" media="print" onload="this.media='all'">
            <noscript><link rel="stylesheet" href="<?= $localFontUrl ?>"></noscript>
        <?php endif;
    endforeach;
endif; ?>
