<?php
/**
 * Module for asynchronous font loading which speeds up first page render.
 * Just add path to your desired font stylesheet to the array below.
 */
?>
<script>
    [
        'https://fonts.googleapis.com/css?family=Libre+Franklin:200,300,400,700,900',
    ].map(function(url) {
        const link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = url;
        document.head.appendChild(link);
    });
</script>
