<div class="cs-information-stripe">
    <div class="cs-information-stripe__wrapper">
        <ul class="cs-information-stripe__list">
            <li class="cs-information-stripe__item">
                <span class="cs-text cs-t-text--size_300">
                <span class="cs-t-text__span"><?=__('Phone');?></span>
                <a href="tel:+49123450440" class="cs-t-text__span  cs-t-text__span--look_attention">
                    +49 (0) 9631 604 0
                </a>
                </span>
            </li>
            <li class="cs-information-stripe__item cs-information-stripe__item--last | cs-t-text cs-t-text--size_300 | cs-hide-mobile">
                <span class="cs-text cs-t-text--size_300">
                    <span class="cs-t-text__span"><?=__('Today open till %1', '<span class="cs-t-text__span cs-t-text__span--look_link cs-t-text--size_300">19:00</span>');?> </span>
                </span>
            </li>
        </ul>
    </div>
</div>
