<div class="cs-information-stripe">
    <div class="cs-information-stripe__wrapper">
        <ul class="cs-information-stripe__list | cs-list cs-list--inline cs-list--unstyled">
            <li class="cs-information-stripe__item | cs-list__item cs-list__item">
                <span class="cs-text cs-t-text--size_300">
                    <!--                <svg class="cs-list__bullet cs-list__bullet--tick">-->
<!--                    <use xlink:href="-->
<!--                    <start php>$this->getViewFileUrl('images/sprites.svg');?>#check"></use>-->
<!--                </svg>-->

                <span class="cs-t-text__span"><?=__('Phone');?></span>
                <a href="tel:+49123450440" class="cs-t-text__span  cs-t-text__span--look_attention">
                    +49 (0) 9631 604 0
                </a>
                </span>
            </li>
            <li class="cs-information-stripe__item | cs-list__item cs-list__item--stripe | cs-t-text cs-t-text--size_300">
                <span class="cs-text cs-t-text--size_300">
                    <span class="cs-t-text__span"><?=__('Today open till %1', '<span class="cs-t-text__span cs-t-text__span--look_link cs-t-text--size_300">19:00</span>');?> </span>
                </span>
            </li>
        </ul>
        <div class="cs-information-stripe__contact">

            <ul class="cs-information-stripe__list | cs-list cs-list--inline cs-list--unstyled">
                <li class="cs-information-stripe__item | cs-list__item | cs-text cs-t-text--size_300">
                    <a href="#" class="cs-link cs-link--look_text cs-link--size_300">
                        <svg class="cs-link__icon">
                            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#pin"></use>
                        </svg>
                        <?=__('Shop');?>
                    </a>
                </li>
                <li class="cs-information-stripe__item | cs-list__item | cs-text cs-t-text--size_300">
                    <a href="#" class="cs-link cs-link--look_text cs-link--size_300">
                        <svg class="cs-link__icon">
                            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#mail"></use>
                        </svg>
                        <?=__('Contact');?>
                    </a>
                </li>
            </ul>

        </div>
    </div>
</div>
