<div class="cs-information-stripe">
    <div class="cs-information-stripe__wrapper">
        <ul class="cs-information-stripe__list cs-information-stripe__list--featured">
            <li class="cs-information-stripe__item">
               <span class="cs-information-stripe__item-text"><?=__('Discreet and rapid delivery');?></span>
            </li>
            <li class="cs-information-stripe__item">
                <span class="cs-information-stripe__item-text"><?=__('All offers include VAT');?></span>
            </li>
            <li class="cs-information-stripe__item cs-information-stripe__item--last">
                <span class="cs-information-stripe__item-text"><?=__('24h delivery');?>
</span>
            </li>
        </ul>
        <ul class="cs-information-stripe__list">
            <li class="cs-information-stripe__item">
                <a href="tel:+49123450440" class="cs-information-stripe__phone-number">
                    <?=__('+49 (030) 123 450 440');?>
                </a>
                <span class="cs-information-stripe__phone-label">
                    <?=__('Our lines are open:');?>
                </span>
                <span class="cs-information-stripe__phone-hours">
                    <?=__('Mon - Fri, 10:00-16:00');?>
                </span>
            </li>
        </ul>
    </div>
    <?=$this->getChildHtml();?>
</div>
