<?php
/**
* Custom template
*/
?>
<div class="cs-header__offcanvas-toggle">
    <button class="cs-offcanvas-toggle" aria-label="<?= __('Toggle mobile navigation'); ?>" aria-expanded="false">
        <span class="cs-offcanvas-toggle__icon"></span>
        <?php if ($block->getVar('header/mobile_search_in_offcanvas', 'Magento_Theme')): ?>
            <?= $this->getLayout()
                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                ->setIconUrl('images/icons/offcanvas-toggle/icon-menu-search.svg')
                ->setCssClass('cs-offcanvas-toggle__menu-search-icon')
                ->setAltText(__('Menu and search'))
                ->setInlined(true)
                ->setLazyLoaded(true)
                ->toHtml();
            ?>
        <?php endif; ?>
        <?php if ($block->getMenuText()): ?>
            <span class="cs-offcanvas-toggle__text"><?= __($block->getMenuText()); ?></span>
        <?php endif ?>
    </button>
</div>
