<?php
// @codingStandardsIgnoreFile

/**
 * @see \Magento\Theme\Block\Html\Pager
 */

//show input field instead of default pagination
$inputInsteadOfLinks = true;
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
        <div class="cs-pager">
    <?php endif ?>

    <?php if ($block->getShowAmounts()): ?>
        <p class="cs-pager__block">
            <span class="cs-t-text">
            <?php $totalNum =  $block->getTotalNum(); ?>
            <?php if ($block->getLastPageNum()>1): ?>
                <?php /* @escapeNotVerified */ echo __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $totalNum) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php /* @escapeNotVerified */ echo __('%1 Item', $totalNum) ?>
            <?php else: ?>
                <?php /* @escapeNotVerified */ echo __('%1 Item(s)', $totalNum) ?>
            <?php endif; ?>
            </span>
        </p>
    <?php endif ?>

    <?php if ($block->getLastPageNum()>1): ?>
        <div class="cs-pagination">
            <div class="cs-pagination__content">
                <?php
                    $anchorTextForPrevious = $block->getAnchorTextForPrevious();
                    $text = $anchorTextForPrevious ? $anchorTextForPrevious : '';
                    $lastPageNum = $block->getLastPageNum();
                ?>
                <?php if (!$block->isFirstPage()): ?>
                    <a
                        class="cs-pagination__prev"
                        href="<?php /* @escapeNotVerified */ echo $block->getPreviousPageUrl() ?>"
                        title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>"
                    >
                        <svg class="cs-pagination__prev-icon">
                            <use xlink:href="#icon_arrow-left"></use>
                        </svg>
                    </a>
                <?php else: ?>
                    <span class="cs-pagination__prev" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>">
                        <svg class="cs-pagination__prev-icon cs-pagination__prev-icon--disabled">
                            <use xlink:href="#icon_arrow-left"></use>
                        </svg>
                    </span>
                <?php endif;?>

                <span class="cs-pagination__label-wrapper">
                    <span class="cs-pagination__label"><?php /* @escapeNotVerified */ echo __('Page') ?>: </span>
                </span>

                <?php //show input field instead of default pagination ?>
                <?php if($inputInsteadOfLinks): ?>

                    <div class="cs-pagination__selector">

                        <?php
                            $_urlLastPage = $block->getPageUrl($lastPageNum);
                            $_urlPattern = str_replace('p=' . $lastPageNum, 'p=[page]', $_urlLastPage);
                        ?>

                        <input
                            class="cs-pagination__selector-input | cs-input__input"
                            type="number"
                            max="<?php /* @escapeNotVerified */ echo $block->getLastPageNum(); ?>"
                            size="2"
                            value="<?php /* @escapeNotVerified */ echo $block->getCurrentPage() ?>"
                            data-url-pattern='<?php /* @escapeNotVerified */ echo $block->escapeHtml($_urlPattern); ?>'
                        >

                        <span class="cs-pagination__selector-lastpage">
                            / <?php /* @escapeNotVerified */ echo $lastPageNum; ?>
                        </span>

                    </div>

                <?php else: ?>

                    <ul class="cs-pagination__pager">

                        <?php if ($block->canShowFirst()): ?>
                            <li class="cs-pagination__item">
                                <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getFirstPageUrl() ?>">
                                    1
                                </a>
                            </li>
                        <?php endif;?>

                        <?php if ($block->canShowPreviousJump()): ?>
                            <li class="cs-pagination__item">
                                <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getPreviousJumpUrl() ?>">
                                    ...
                                </a>
                            </li>
                        <?php endif;?>

                        <?php foreach ($block->getFramePages() as $page): ?>
                            <?php if ($block->isPageCurrent($page)): ?>
                                <li class="cs-pagination__item current">
                                    <span class="cs-pagination__number cs-pagination__number--current">
                                        <?php /* @escapeNotVerified */ echo $page ?>
                                    </span>
                                </li>
                            <?php else: ?>
                                <li class="cs-pagination__item">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getPageUrl($page) ?>" class="cs-pagination__number">
                                        <?php /* @escapeNotVerified */ echo $page ?>
                                    </a>
                                </li>
                            <?php endif;?>
                        <?php endforeach;?>

                        <?php if ($block->canShowNextJump()): ?>
                            <li class="cs-pagination__item">
                                <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getNextJumpUrl() ?>">...</a>
                            </li>
                        <?php endif;?>

                    </ul>

                    <?php if ($block->getFrameEnd() < $lastPageNum): ?>
                        <ul class="cs-pagination__pager">
                            <li class="cs-pagination__separator">
                                <?php /* @escapeNotVerified */ echo __('of'); ?>
                            </li>

                            <li class="cs-pagination__item cs-pagination__item--single">
                                <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getLastPageUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $lastPageNum; ?>
                                </a>
                            </li>
                        </ul>
                    <?php endif;?>

                <?php endif; ?>

                <?php
                    $anchorTextForNext = $block->getAnchorTextForNext();
                    $text = $anchorTextForNext ? $anchorTextForNext : '';
                ?>
                <?php if (!$block->isLastPage()): ?>
                    <a
                        class="cs-pagination__next"
                        href="<?php /* @escapeNotVerified */ echo $block->getNextPageUrl() ?>"
                        title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>"
                    >
                        <svg class="cs-pagination__next-icon">
                            <use xlink:href="#icon_arrow-right"></use>
                        </svg>
                    </a>
                <?php else: ?>
                    <span class="cs-pagination__next" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>">
                        <svg class="cs-pagination__next-icon cs-pagination__next-icon--disabled">
                            <use xlink:href="#icon_arrow-right"></use>
                        </svg>
                    </span>
                <?php endif;?>
            </div>

            <div class="cs-pagination__content-mobile">
                <?php if (!$block->isLastPage()): ?>
                    <a
                        class="cs-button cs-button--look_light cs-button--type_wide"
                        href="<?php /* @escapeNotVerified */ echo $block->getNextPageUrl() ?>"
                        title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next page') ?>"
                    >
                        <span class="cs-button__span"><?php echo __('Next page'); ?></span>
                        <svg class="cs-button__icon">
                            <use xlink:href="#arrow_next"></use>
                        </svg>
                    </a>
                <?php endif;?>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="cs-pager__block">
            <div class="cs-pager__input | cs-input cs-input--inline">

                <label class="cs-pager__input-span | cs-t-text" for="limiter">
                    <?php /* @escapeNotVerified */ echo __('Show') ?>
                </label>
                <div class="cs-pager__input-span | cs-input__control">
                    <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="cs-input__select">
                        <?php foreach ($block->getAvailableLimit() as $key => $limit): ?>
                            <option
                                value="<?php /* @escapeNotVerified */ echo $block->getLimitUrl($key) ?>"
                                <?php if ($block->isLimitCurrent($key)): ?>  selected="selected"<?php endif ?>
                            >
                                <?php /* @escapeNotVerified */ echo $limit ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <span class="cs-pager__input-span | cs-t-text"><?php /* @escapeNotVerified */ echo __('per page') ?></span>

            </div>
        </div>
    <?php endif ?>


    <?php if ($block->getUseContainer()): ?>
        </div>
    <?php endif ?>

<?php endif ?>
