<div class="cs-page-bottom">
    <div class="cs-page-bottom__group cs-page-bottom__group--info  | cs-hide-mobile">
        <img
            class="cs-page-bottom__image cs-page-bottom__image--circle | lazyload"
            src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
            data-src="<?= $this->getViewFileUrl('images/trusted-shops.png'); ?>"
            data-srcset="<?= $this->getViewFileUrl('images/trusted-shops.png'); ?>,
                <?= $this->getViewFileUrl('images/trusted-shops@2x.png'); ?> 2x"
            alt="<?php echo __('Trusted Shops certified') ?>"
            width="47" height="47"
        />
        <noscript>
            <img
                class="cs-page-bottom__image cs-page-bottom__image--circle"
                src="<?= $this->getViewFileUrl('images/trusted-shops.png'); ?>"
                srcset="<?= $this->getViewFileUrl('images/trusted-shops.png'); ?>,
                    <?= $this->getViewFileUrl('images/trusted-shops@2x.png'); ?> 2x"
                alt="<?php echo __('Trusted Shops certified') ?>"
                width="47" height="47"
            />
        </noscript>
        <p class="cs-page-bottom__text cs-page-bottom__text--small">
            <?php echo __('Tax and 1,95€ shipping cost included to all prices.'); ?>
        </p>
    </div>

    <span class="cs-page-bottom__divider | cs-hide-mobile"></span>

    <div class="cs-page-bottom__group cs-page-bottom__group--shipping | cs-hide-mobile">
        <p class="cs-page-bottom__text | cs-hide-mobile">
            <?php echo __('Shipping methods:'); ?>
        </p>
        <svg class="cs-page-bottom__logo cs-page-bottom__logo--hermes">
        	<use xlink:href="#hermes"></use>
        </svg>
        <svg class="cs-page-bottom__logo cs-page-bottom__logo--dhl">
        	<use xlink:href="#dhl"></use>
        </svg>

    </div>

    <span class="cs-page-bottom__divider | cs-hide-mobile"></span>

    <div class="cs-page-bottom__group cs-page-bottom__group--payment">
        <p class="cs-page-bottom__text | cs-hide-mobile">
            <?php echo __('Payment methods:'); ?>
        </p>
        <svg class="cs-page-bottom__logo cs-page-bottom__logo--paypal">
        	<use xlink:href="#paypal"></use>
        </svg>
        <svg class="cs-page-bottom__logo cs-page-bottom__logo--visa">
        	<use xlink:href="#visa"></use>
        </svg>
        <svg class="cs-page-bottom__logo cs-page-bottom__logo--mastercard">
        	<use xlink:href="#mastercard"></use>
        </svg>
        <svg class="cs-page-bottom__logo cs-page-bottom__logo--s-u">
        	<use xlink:href="#sofort_uberweisung"></use>
        </svg>
        <svg class="cs-page-bottom__logo cs-page-bottom__logo--klarna">
        	<use xlink:href="#klarna"></use>
        </svg>

    </div>

</div>
