<div class="cs-page-bottom">
    <div class="cs-page-bottom__group">
        <img
            class="cs-page-bottom__image cs-page-bottom__image--circle | cs-hide-mobile"
            src="<?= $this->getViewFileUrl('images/trusted-shops.png'); ?>"
            alt="<?php /* @escapeNotVerified */ echo __('Trusted shops logo') ?>"
        />
        <p class="cs-page-bottom__text cs-page-bottom__text--small | cs-hide-mobile">
            Alle Preise inkl. gesetzlicher MwSt., zzgl. 1,95 € Versandkosten.
        </p>
    </div>

    <span class="cs-page-bottom__divider | cs-hide-mobile"></span>

    <div class="cs-page-bottom__group">
        <p class="cs-page-bottom__text | cs-hide-mobile">
            Shipping methods:
        </p>

        <img
            class="cs-page-bottom__image | cs-hide-mobile"
            src="<?= $this->getViewFileUrl('images/shipping-methods.png'); ?>"
            alt="<?php /* @escapeNotVerified */ echo __('Shipping methods') ?>"
        />
    </div>

    <span class="cs-page-bottom__divider | cs-hide-mobile"></span>

    <div class="cs-page-bottom__group">
        <p class="cs-page-bottom__text | cs-hide-mobile">
            Payment methods:
        </p>

        <img
            class="cs-page-bottom__image"
            src="<?= $this->getViewFileUrl('images/payment-methods.png'); ?>"
            alt="<?php /* @escapeNotVerified */ echo __('Payment methods') ?>"
        />
    </div>

</div>
