<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
        <div class="cs-pager">
    <?php endif ?>

    <?php if ($block->getShowAmounts()): ?>
        <p class="cs-pager__block">
            <span class="cs-t-text">
            <?php if ($block->getLastPageNum()>1): ?>
                <?php /* @escapeNotVerified */ echo __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php /* @escapeNotVerified */ echo __('%1 Item', $block->getTotalNum()) ?>
            <?php else: ?>
                <?php /* @escapeNotVerified */ echo __('%1 Item(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
    <?php endif ?>

    <?php if ($block->getLastPageNum()>1): ?>
        <div class="cs-pagination">
            <div class="cs-pagination__content">
                <?php if (!$block->isFirstPage()): ?>
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="cs-pagination__prev" href="<?php /* @escapeNotVerified */ echo $block->getPreviousPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>">
                        <svg class="cs-pagination__prev-icon">
                            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#icon_arrow-left"></use>
                        </svg>
                    </a>
                <?php else: ?>
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <span class="cs-pagination__prev" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Previous') ?>">
                        <svg class="cs-pagination__prev-icon cs-pagination__prev-icon--disabled">
                            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#icon_arrow-left"></use>
                        </svg>
                    </span>
                <?php endif;?>

                <ul class="cs-pagination__pager">
                    <li class="cs-pagination__item">
                        <span class="cs-pagination__label | cs-t-text cs-t-text--look_label"><?php /* @escapeNotVerified */ echo __('Page') ?>: </span>
                    </li>

                    <?php if ($block->canShowFirst()): ?>
                        <li class="cs-pagination__item">
                            <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getFirstPageUrl() ?>">1</a>
                        </li>
                    <?php endif;?>

                    <?php if ($block->canShowPreviousJump()): ?>
                        <li class="cs-pagination__item">
                            <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getPreviousJumpUrl() ?>">...</a>
                        </li>
                    <?php endif;?>

                    <?php foreach ($block->getFramePages() as $_page): ?>
                        <?php if ($block->isPageCurrent($_page)): ?>
                            <li class="cs-pagination__item current">
                                <span class="cs-pagination__number cs-pagination__number--current"><?php /* @escapeNotVerified */ echo $_page ?></span>
                            </li>
                        <?php else: ?>
                            <li class="cs-pagination__item">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getPageUrl($_page) ?>" class="cs-pagination__number"><?php /* @escapeNotVerified */ echo $_page ?>
                                </a>
                            </li>
                        <?php endif;?>
                    <?php endforeach;?>

                    <?php if ($block->canShowNextJump()): ?>
                        <li class="cs-pagination__item">
                            <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getNextJumpUrl() ?>">...</a>
                        </li>
                    <?php endif;?>

                    <?php if ($block->canShowLast()): ?>
                        <li class="cs-pagination__item">
                            <a class="cs-pagination__number" href="<?php /* @escapeNotVerified */ echo $block->getLastPageUrl() ?>"><?php /* @escapeNotVerified */ echo $block->getLastPageNum() ?></a>
                        </li>
                    <?php endif;?>
                </ul>

                <?php if (!$block->isLastPage()): ?>
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="cs-pagination__next" href="<?php /* @escapeNotVerified */ echo $block->getNextPageUrl() ?>" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>">
                        <svg class="cs-pagination__next-icon">
                            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#icon_arrow-right"></use>
                        </svg>
                    </a>
                <?php else: ?>
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <span class="cs-pagination__next" title="<?php /* @escapeNotVerified */ echo $text ? $text : __('Next') ?>">
                        <svg class="cs-pagination__next-icon cs-pagination__next-icon--disabled">
                            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#icon_arrow-right"></use>
                        </svg>
                    </span>
                <?php endif;?>

            </div>
        </div>
    <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="cs-pager__block">
            <div class="cs-pager__input | cs-input cs-input--inline">
                <label class="cs-pager__input-span | cs-t-text" for="limiter"><?php /* @escapeNotVerified */ echo __('Show') ?></label>
                <div class="cs-pager__input-span | cs-input__control">
                    <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="cs-input__select">
                        <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                            <option value="<?php /* @escapeNotVerified */ echo $block->getLimitUrl($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                                selected="selected"<?php endif ?>>
                                <?php /* @escapeNotVerified */ echo $_limit ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <span class="cs-pager__input-span | cs-t-text"><?php /* @escapeNotVerified */ echo __('per page') ?></span>

            </div>

        </div>
    <?php endif ?>


    <?php if ($block->getUseContainer()): ?>
        </div>
    <?php endif ?>

<?php endif ?>
