<div class="cs-pwa-notification-panel cs-pwa-notification-panel--request">
    <div class="cs-pwa-notification-panel__icon-wrapper">
    <?= $block->getChildHtml('pwa.notification.panel.icon.request'); ?>
    <?= $block->getChildHtml('pwa.notification.panel.icon.browser'); ?>
    <?= $block->getChildHtml('pwa.notification.panel.icon.enabled'); ?>
    </div>    
    <div class="cs-pwa-notification-panel__message-wrapper">
        <div class="cs-pwa-notification-panel__message cs-pwa-notification-panel__message--request">
            <span class="cs-pwa-notification-panel__message-title"><?= __('Activate notifications'); ?></span>
            <span class="cs-pwa-notification-panel__message-description"><?= __('May we inform you in browser about order and delivery status?'); ?></span>
        </div>
        <div class="cs-pwa-notification-panel__message cs-pwa-notification-panel__message--browser">
            <span class="cs-pwa-notification-panel__message-title"><?= __('Almost there'); ?></span>
            <span class="cs-pwa-notification-panel__message-description"><?= __('Allow Magesuite.io to send you notifications. You can confirm this in the message of your browser.'); ?></span>
        </div>
        <div class="cs-pwa-notification-panel__message cs-pwa-notification-panel__message--enabled">
            <span class="cs-pwa-notification-panel__message-title"><?= __('Notifications activated'); ?></span>
            <span class="cs-pwa-notification-panel__message-description"><?= __('We will keep you up to date with the most important informations about your order.'); ?></span>
        </div>
    </div>
    <div class="cs-pwa-notification-panel__actions">
        <div class="cs-pwa-notification-panel__action cs-pwa-notification-panel__action--request">
            <button class="cs-pwa-notification-panel__button cs-pwa-notification-panel__button--accept">
                <spac class="cs-pwa-notification-panel__button-span"><?= __('Yes, please'); ?></span>
                <?= $block->getChildHtml('pwa.notification.panel.button.accept.icon'); ?>
            </button>
            <button class="cs-pwa-notification-panel__button cs-pwa-notification-panel__button--decline">
                <spac class="cs-pwa-notification-panel__button-span"><?= __('No, thank you'); ?></span>
                <?= $block->getChildHtml('pwa.notification.panel.button.decline.icon'); ?>
            </button>
        </div>
        <div class="cs-pwa-notification-panel__action cs-pwa-notification-panel__action--browser">
            <div class="cs-pwa-notification-panel__permission">
                <span class="cs-pwa-notification-panel__permission-title">
                    <?= __('www.magesuite.io want to:'); ?>
                </span>
                <span class="cs-pwa-notification-panel__permission-title">
                    <?= $block->getChildHtml('pwa.notification.panel.permission.icon'); ?>
                    <?= __('Show notifications:'); ?>
                </span>
                <div class="cs-pwa-notification-panel__permission-button-wrapper">
                    <span class="cs-pwa-notification-panel__permission-button cs-pwa-notification-panel__permission-button--allow">
                        <?= __('Allow'); ?>
                    </span>
                    <span class="cs-pwa-notification-panel__permission-button cs-pwa-notification-panel__permission-button--block">
                        <?= __('Block'); ?>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="cs-pwa-notification-panel__close">
        <?= $block->getChildHtml('pwa.notification.panel.close.icon'); ?>
    </a>
</div>