<?php
/**
 * Initializing all needed scripts.
 */
?>
<script type="text/x-magento-init">
{
    "*": {
        "bundle": {}
    }
}
</script>
<script>
    (function (doc) {
        var scripts = doc.getElementsByTagName('script');
        var script = scripts[scripts.length - 1];
        var xhr = new XMLHttpRequest();
        xhr.onload = function () {
            var div = doc.createElement('div');
            div.innerHTML = this.responseText;
            div.style.display = 'none';
            script.parentNode.insertBefore(div, script);
        };
        xhr.open('get', <?=$this->getViewFileUrl('images/sprites.svg');?>, true);
        xhr.send();
    })(document)
</script>
