<script>
    requirejs.config({
        paths: {
            'Swiper': 'swiper',
            'vendors': 'vendors',
            'Stickyfill': 'stickyfill',
            'isMobile': 'ismobile',
            'creativeshop': 'bundle'
        },
        shim: {
            'vendors': {
                deps: [
                    'jquery'
                ]
            },
            'Stickyfill': {
                deps: [
                    'jquery'
                ],
                exports: 'Stickyfill'
            },
            'isMobile': {
                exports: 'isMobile'
            }
        }
    });
</script>

<script type="text/x-magento-init">
{
    "*": {
        "creativeshop": {}
    }
}
</script>
