<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$target = $block->getTarget();
$label = $block->getLabel();
?>
<a class="cs-header__skip | cs-visually-hidden action skip <?php /* @escapeNotVerified */ echo $target?>" href="#<?php /* @escapeNotVerified */ echo $target?>"><span><?php /* @escapeNotVerified */ echo $label ?></span></a>
