<a
    class="cs-header-user-area__section cs-header-user-area__section--my-account"
    href="<?php /* @escapeNotVerified */ echo $block->getHref() ?>"
>
    <div class="cs-header-user-area__icon-wrapper">
        <svg class="cs-header-user-area__icon cs-header-user-area__icon--my-account">
            <use xlink:href="#user"></use>
        </svg>
    </div>
    <p class="cs-header-user-area__label"><?=__('My account');?></p>
</a>