<?php
/**
* Template overridden to use custom rating-stars.phtml template
*/
?>
<?php
$reviewsCount = $block->getReviewsCount();
$ratingSummary = $block->getRatingSummary();
// Since 2.3.3 rating summary is being returned directly, not as an object.
if (is_object($ratingSummary)) {
    $reviewsCount = $ratingSummary->getReviewsCount();
    $ratingSummary = $ratingSummary->getRatingSummary();
}
?>
<?php if ($reviewsCount && $block->getReviewsCount()): ?>

        <?php
            // Transforms rating summary (0..100) into star count (0..5, with a step of a 0.5)
            $activeStars = round($ratingSummary / 10) / 2;

            echo $this->getLayout()
                    ->createBlock(\Magento\Framework\View\Element\Template::class)
                    ->setMaxStars(5)
                    ->setActiveStars($activeStars)
                    ->setReviewsCount($reviewsCount)
                    ->setHideReviewsCount(false)
                    ->setReviewsLink(true)
                    ->setShowNumericalScore($block->getShowNumericalScore())
                    ->setTemplate('Magento_Review::rating-stars.phtml')
                    ->toHtml();
        ?>

<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()): ?>

    <div class="cs-buybox__no-review">
        <a class="cs-buybox__no-review-link" href="#reviews"><?= $block->escapeHtml(__('Be the first to review this product')) ?></a>
    </div>

<?php endif; ?>
