<?php
/**
 * Template overridden to use custom rating-stars.phtml template
 *
 * Aligned with Magento 2.4.5 at 09/2022
 */
?>
<?php
/** @var $block \Magento\Review\Block\Product\ReviewRenderer */
$csProductHelper = $this->helper(MageSuite\Frontend\Helper\Product::class);
$rating = $csProductHelper->getReviewSummary($block->getProduct(), true);
$ratingData = $rating['data'];
$votes = $rating['data']['votes'];
$allVotes = array_sum($votes);
?>
<?php if ($allVotes > 0): ?>

    <?php
    echo $this->getLayout()
        ->createBlock(\Magento\Framework\View\Element\Template::class)
        ->setMaxStars($ratingData['maxStars'])
        ->setActiveStars($ratingData['activeStars'])
        ->setReviewsCount($allVotes)
        ->setHideReviewsCount(false)
        ->setReviewsLink(true)
        ->setShowNumericalScore($block->getShowNumericalScore())
        ->setTemplate('Magento_Review::rating-stars.phtml')
        ->toHtml();
    ?>

<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()): ?>

    <div class="cs-buybox__no-review">
        <a class="cs-buybox__no-review-link" href="#reviews"><?= $block->escapeHtml(__('Be the first to review this product')) ?></a>
    </div>

<?php endif; ?>
