<?php
// @codingStandardsIgnoreFile
    $url = $block->getReviewsUrl() . '#reviews';
    $urlForm = $block->getReviewsUrl() . '#review-form';
?>

<?php if ($block->getReviewsCount()): ?>

        <?= $this->getLayout()
                 ->createBlock(\Magento\Framework\View\Element\Template::class)
                 ->setMaxStars(5)
                 ->setActiveStars(round($block->getRatingSummary()*2/20)/2)
                 ->setReviewsCount($block->getReviewsCount())
                 ->setHideReviewsCount(true)
                 ->setTemplate('Magento_Review::rating-stars.phtml')
                 ->toHtml();
        ?>

<?php elseif ($block->getDisplayIfEmpty()): ?>

    <div class="cs-buybox__no-review">
        <a class="cs-buybox__no-review-link" href="<?php /* @escapeNotVerified */ echo $urlForm; ?>"><?php /* @escapeNotVerified */ echo __('Be the first to review this product') ?></a>
    </div>

<?php endif; ?>
