<?php
/**
 * This template is used in related products section,
 * however it is not visible on the frontend
 * In corresponding summary.phtml template (full version) there is a fix and a note:
 * "Since 2.3.3 rating summary is being returned directly, not as an object."
 * However still there are rare cases when rating is return as an object
 * what results in critical error
 * Aligned with Magento 2.4.9 in 05/2026
 */

/** @var \Magento\Review\Block\Product\ReviewRenderer $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
?>
<?php if ($block->isReviewEnabled() && $block->getReviewsCount()): ?>
    <?php
        $rating = $block->getRatingSummary();
        // fix a case when $rating is an object
        if (is_object($rating)) {
            $rating = $rating->getRatingSummary();
        }
    ?>
    <div class="product-reviews-summary short<?= !$rating ? ' no-rating' : '' ?>">
        <?php if ($rating):?>
        <div class="rating-summary">
            <span class="label"><span><?= $escaper->escapeHtml(__('Rating')) ?>:</span></span>
            <div class="rating-result"
                 id="rating-result_<?= /* @noEscape */ $block->getProduct()->getId() ?>"
                 title="<?= $escaper->escapeHtmlAttr($rating) ?>%">
                <span>
                    <span><?= $escaper->escapeHtml($rating) ?>%</span>
                </span>
            </div>
            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                'width:' . $block->escapeHtmlAttr($rating) . '%',
                '#rating-result_' . $block->getProduct()->getId() . ' span'
            ) ?>
        </div>
        <?php endif;?>
        <div class="reviews-actions">
            <a class="action view"
               href="<?= $escaper->escapeUrl($url) ?>"><?= $escaper->escapeHtml($block->getReviewsCount()) ?>
                &nbsp;<span><?= ($block->getReviewsCount() == 1) ?
                        $escaper->escapeHtml(__('Review')) : $escaper->escapeHtml(__('Reviews')) ?>
                </span>
            </a>
        </div>
    </div>
<?php elseif ($block->isReviewEnabled() && $block->getDisplayIfEmpty()): ?>
    <div class="product-reviews-summary short empty">
        <div class="reviews-actions">
            <a class="action add" href="<?= $escaper->escapeUrl($urlForm) ?>">
                <?= $escaper->escapeHtml(__('Be the first to review this product')) ?>
            </a>
        </div>
    </div>
<?php endif; ?>
