<?php
/**
 * @var $block \Smile\ElasticsuiteCore\Block\Search\Form\Mini
 * @var $helper \Magento\Search\Helper\Data
 */
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<div class="cs-header__search">
    <form role="search" class="cs-header-search" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
        <div class="cs-header-search__field">
            <label class="label cs-header-search__label" for="search" data-role="minisearch-label">
                <span><?= $block->escapeHtml(__('Search')) ?></span>
            </label>
            <input id="search"
                data-mage-init='{
                    "quickSearch":{
                        "formSelector":"#search_mini_form",
                        "url":"<?= /* @escapeNotVerified */ $block->getUrl('search/ajax/suggest'); ?>",
                        "destinationSelector":"#search_autocomplete",
                        "templates": <?= /* @noEscape */ $block->getJsonSuggestRenderers();?>,
                        "priceFormat" : <?= /* @noEscape */ $block->getJsonPriceFormat();?>}
                    }'
                type="search"
                name="<?= /* @escapeNotVerified */ $helper->getQueryParamName(); ?>"
                value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText(); ?>"
                placeholder="<?= /* @escapeNotVerified */ $block->getSearchPlaceholder(); ?>"
                class="cs-header-search__input"
                maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength(); ?>"
                role="combobox"
                aria-haspopup="false"
                aria-autocomplete="both"
                aria-expanded="false"
                autocomplete="off"
                data-block="autocomplete-form"
                aria-controls="search_autocomplete"
            />
            <div class="cs-header-search__action">
                <span class="cs-header-search__close">
                    <?= $block->getChildHtml('top.search.icon.close'); ?>
                    <span class="cs-header-search__close-label"><?= /* @escapeNotVerified */ __('Close search'); ?></span>
                </span>
                <button class="cs-header-search__button" type="submit">
                    <span class="cs-header-search__button-container cs-header-search__button-container--search">
                        <?= $block->getChildHtml('top.search.icon.submit'); ?>
                    </span>
                    <span class="cs-header-search__button-container cs-header-search__button-container--loader">
                        <?= $block->getChildHtml('top.search.icon.loader'); ?>
                    </span>
                    <span class="cs-header-search__button-label"><?= /* @escapeNotVerified */ __('Search'); ?></span>
                </button>
            </div>
        </div>
        <div
            id="search_autocomplete"
            class="cs-header-search__autocomplete search-autocomplete cs-autocomplete"
            aria-labelledby="search_autocomplete"
            role="grid"
        ></div>
    </form>
</div>
