<?php
/**
* template overridden to:
* - add magesuite classes
* - add icon to button
*/
?>
<?php
/** @var \Magento\Captcha\Block\Captcha\DefaultCaptcha $block */

/** @var \Magento\Captcha\Model\DefaultModel $captcha */
$captcha = $block->getCaptchaModel();
/** @var bool $validationEnabled */
$validationEnabled = $block->hasData('frontend_validation') ? $block->getData('frontend_validation') : true;
$inputName = $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE);
$loaderUrl = $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif'));
$note = $block->escapeHtml(__('<strong>Attention</strong>: Captcha is case sensitive.'), ['strong']);
?>
<div class="cs-form__field cs-input cs-captcha<?php if ($validationEnabled): ?> required<?php endif; ?>"
     role="<?= $block->escapeHtmlAttr($block->getFormId()) ?>">
    <label class="cs-input__label" for="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>"><span><?= $block->escapeHtml(__('Please type the letters and numbers below')) ?></span></label>
    <div class="cs-captcha__wrapper">
        <input
            name="<?= /* @noEscape */ $inputName ?>[<?= $block->escapeHtmlAttr($block->getFormId()) ?>]"
            type="text"
            class="cs-input__input<?php if ($validationEnabled): ?> required-entry<?php endif; ?>"
            <?php if ($validationEnabled): ?>data-validate="{required:true}"<?php endif; ?>
            id="captcha_<?= $block->escapeHtmlAttr($block->getFormId()) ?>" 
            autocomplete="off"/>
        <div
            class="cs-captcha__image-controls"
            data-captcha="<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
            id="captcha-container-<?= $block->escapeHtmlAttr($block->getFormId()) ?>"
            data-mage-init='{"captcha":{"url": "<?= $block->escapeUrl($block->getRefreshUrl()) ?>",
                                            "imageLoader": "<?= /* @noEscape */ $loaderUrl ?>",
                                             "type": "<?= $block->escapeHtmlAttr($block->getFormId()) ?>"}}'
        >
            <img
                alt="<?= $block->escapeHtmlAttr(__('Please type the letters and numbers below')) ?>"
                class="cs-captcha__image | captcha-img"
                height="<?= /* @noEscape */ (float) $block->getImgHeight() ?>"
                src="<?= $block->escapeUrl($captcha->getImgSrc()) ?>"/>
            <button
                type="button"
                class="cs-captcha__button captcha-reload"
                title="<?= $block->escapeHtmlAttr(__('Reload captcha')) ?>"
            >
                <?= $block->getChildHtml('captcha.button.icon'); ?>
                <span class="cs-captcha__button-span"><?= $block->escapeHtml(__('Reload captcha')) ?></span>
            </button>
        </div>
        <?php if ($captcha->isCaseSensitive()):?>
            <div class="cs-captcha__note"><?= /* @noEscape */ $note ?></div>
        <?php endif; ?>
    </div>
</div>
