<?php
// @codingStandardsIgnoreFile
/**
 * @var \MageSuite\Navigation\Block\Navigation $block
 * @var \Magento\Framework\Escaper $escaper
 */
$level = 0;
$nextIcon = $block->getChildHtml('navigation.offcanvas.icon.next');
$prevIcon = $block->getChildHtml('navigation.offcanvas.icon.prev');
$showCategoryIcon = $block->getShowCategoryIcon();
$showCategoryIconSubcats = $block->getShowCategoryIconSubcats();
$showParentOnReturnLink = $block->getShowParentOnReturnLink();
$showIconOnReturnLink = $block->getShowIconOnReturnLink();
?>
<nav class="cs-offcanvas-navigation" aria-label="<?= $escaper->escapeHtml(__('Mobile Navigation')); ?>">
    <?= $block->getChildHtml('navigation.offcanvas.search'); ?>
    <ul class="cs-offcanvas-navigation__list cs-offcanvas-navigation__list--current cs-offcanvas-navigation__list--level_<?= $escaper->escapeHtmlAttr($level); ?>">
        <?php foreach ($block->getItems() as $item) :
            $itemUrl = $item->getUrl();
            $itemId = $item->getId();
            $itemLabel = $item->getLabel();
            $itemIdentifier = $item->getIdentifier() ?? '';
            $itemHasSubitems = $item->hasSubItems();
            $itemCategoryIcon = $showCategoryIcon ? $item->getCategoryIcon() : '';
            $itemNextAdditionalClasses = '';

            if ($itemHasSubitems) {
                $itemNextAdditionalClasses .= ' cs-offcanvas-navigation__link--parent';

                if (!$nextIcon) {
                    $itemNextAdditionalClasses .= '  cs-offcanvas-navigation__link--next';
                }
            }
            ?>
            <li class="cs-offcanvas-navigation__item cs-offcanvas-navigation__item--level_<?= $escaper->escapeHtmlAttr($level); ?>"
                <?php if ($itemIdentifier) : ?>
                    data-category-identifier="<?= $escaper->escapeHtmlAttr($itemIdentifier); ?>"
                <?php endif; ?>
            >
                <a class="cs-offcanvas-navigation__link<?= $escaper->escapeHtmlAttr($itemNextAdditionalClasses); ?>"
                   href="<?= $escaper->escapeUrl($itemUrl); ?>"
                   data-category-id="<?= $escaper->escapeHtmlAttr($itemId) ?>"
                >
                    <?php if ($itemHasSubitems && $nextIcon) : ?>
                        <?= $nextIcon ?>
                    <?php endif; ?>
                    <?php if ($itemCategoryIcon) : ?>
                        <span class="cs-offcanvas-navigation__category-icon-wrapper">
                            <img src="<?= $escaper->escapeUrl($itemCategoryIcon); ?>" alt="<?= $escaper->escapeHtmlAttr($itemLabel); ?>" class="cs-offcanvas-navigation__category-icon">
                        </span>
                    <?php endif; ?>
                    <span class="cs-offcanvas-navigation__text">
                        <?= $escaper->escapeHtml($itemLabel); ?>
                    </span>
                </a>
                <?php
                    if ($itemHasSubitems) {
                        echo $this->getLayout()
                            ->createBlock(Magento\Framework\View\Element\Template::class)
                            ->setTemplate("MageSuite_Navigation::offcanvas/list.phtml")
                            ->setItem($item)
                            ->setParent(false)
                            ->setLevel($level + 1)
                            ->setNextIcon($nextIcon)
                            ->setPrevIcon($prevIcon)
                            ->setShowCategoryIconSubcats($showCategoryIconSubcats)
                            ->setShowParentOnReturnLink($showParentOnReturnLink)
                            ->setShowIconOnReturnLink($showIconOnReturnLink)
                            ->toHtml();
                    }
                    ?>
            </li>
        <?php endforeach; ?>
        <?= $block->getChildHtml('navigation.offcanvas.after.list'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.authorization'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.after.authorization'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.switcher-language'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.after.language'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.switcher-currency'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.after'); ?>
    </ul>
</nav>
