<?php
// @codingStandardsIgnoreFile
/** @var \MageSuite\Navigation\Block\Navigation $block */
$level = 0;
$nextIcon = $block->getChildHtml('navigation.offcanvas.icon.next');
$prevIcon = $block->getChildHtml('navigation.offcanvas.icon.prev');
$showCategoryIconSubcats = $block->getShowCategoryIconSubcats();
?>
<nav class="cs-offcanvas-navigation" aria-label="<?= /* @escapeNotVerified */ __('Mobile Navigation'); ?>">
    <?= $block->getChildHtml('navigation.offcanvas.search'); ?>
    <ul class="cs-offcanvas-navigation__list cs-offcanvas-navigation__list--current cs-offcanvas-navigation__list--level_<?= $level; ?>">
        <?php foreach ($block->getItems() as $item) :
            $itemUrl = $item->getUrl();
            $itemId = $item->getId();
            $itemLabel = $item->getLabel();
            $itemIdentifier = $item->getIdentifier() ?? '';
            $itemHasSubitems = $item->hasSubItems();
            $itemNextAdditionalClasses = '';

            if ($itemHasSubitems) {
                $itemNextAdditionalClasses .= ' cs-offcanvas-navigation__link--parent';

                if (!$nextIcon) {
                    $itemNextAdditionalClasses .= '  cs-offcanvas-navigation__link--next';
                }
            }
            ?>
            <li class="cs-offcanvas-navigation__item cs-offcanvas-navigation__item--level_<?= $level; ?>"<?php if($itemIdentifier): ?> data-category-identifier="<?= $itemIdentifier; ?>"<?php endif; ?>>
                <a class="cs-offcanvas-navigation__link<?= $itemNextAdditionalClasses; ?>" href="<?= $itemUrl; ?>" data-category-id="<?= $itemId ?>">
                    <?php if ($itemHasSubitems && $nextIcon) : ?>
                        <?= $nextIcon ?>
                    <?php endif; ?>
                    <span class="cs-offcanvas-navigation__text">
                        <?= $itemLabel; ?>
                    </span>
                </a>
                <?php
                    if ($itemHasSubitems) {
                        echo $this->getLayout()
                            ->createBlock(Magento\Framework\View\Element\Template::class)
                            ->setTemplate("MageSuite_Navigation::offcanvas/list.phtml")
                            ->setItem($item)
                            ->setLevel($level + 1)
                            ->setNextIcon($nextIcon)
                            ->setPrevIcon($prevIcon)
                            ->setShowCategoryIconSubcats($showCategoryIconSubcats)
                            ->toHtml();
                    }
                    ?>
            </li>
        <?php endforeach; ?>
        <?= $block->getChildHtml('navigation.offcanvas.after.list'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.authorization'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.after.authorization'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.switcher-language'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.after.language'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.switcher-currency'); ?>
        <?= $block->getChildHtml('navigation.offcanvas.after'); ?>
    </ul>
</nav>
