<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Framework\View\Element\Template $block */
$level = $block->getLevel();
$nextIcon = $block->getNextIcon();
$prevIcon = $block->getPrevIcon();
$showCategoryIconSubcats = $block->getShowCategoryIconSubcats();
$showParentOnReturnLink = $block->getShowParentOnReturnLink();

$item = $block->getItem();
$itemUrl = $item->getUrl();
$itemLabel = $item->getLabel();
$itemIdentifier = $item->getIdentifier() ?? '';

$parent = $block->getParent();
$parentLabel = $parent ? $parent->getLabel() : false;
?>
<ul class="cs-offcanvas-navigation__list cs-offcanvas-navigation__list--level_<?= $level; ?>">
    <li class="cs-offcanvas-navigation__item"<?php if($itemIdentifier): ?> data-category-identifier="<?= $itemIdentifier; ?>"<?php endif; ?>>
        <a class="cs-offcanvas-navigation__link cs-offcanvas-navigation__link--return<?= !$prevIcon ? ' cs-offcanvas-navigation__link--prev' : '' ?>" href="<?= $itemUrl; ?>">
            <?php if ($prevIcon) : ?>
                <?= $prevIcon ?>
            <?php endif; ?>
            <span class="cs-offcanvas-navigation__text">
                <?php if ($showParentOnReturnLink && $parentLabel) : ?>
                    <span class="cs-offcanvas-navigation__text-parent">
                        <?= $parentLabel ?>
                    </span>
                <?php endif; ?>
                <?= $itemLabel; ?>
            </span>
        </a>
    </li>
    <?php if (!$item->isUrlDisabled()) : ?>
        <li class="cs-offcanvas-navigation__item cs-offcanvas-navigation__item--all-products">
            <a class="cs-offcanvas-navigation__link" href="<?= $itemUrl; ?>"><?= __('All products'); ?></a>
        </li>
    <?php endif; ?>
<?php
foreach($item->getSubItems() as $subItem):
    $subItem = $subItem;
    $subItemId = $subItem->getId();
    $subItemUrl = $subItem->getUrl();
    $subItemLabel = $subItem->getLabel();
    $subItemIdentifier = $subItem->getIdentifier() ?? '';
    $subItemHasSubItems = $subItem->hasSubItems();
    $subItemCategoryIcon = $showCategoryIconSubcats ? $subItem->getCategoryIcon() : '';
    $itemNextAdditionalClasses = '';

    if ($subItemHasSubItems) {
        $itemNextAdditionalClasses .= ' cs-offcanvas-navigation__link--parent';

        if (!$nextIcon) {
            $itemNextAdditionalClasses .= '  cs-offcanvas-navigation__link--next';
        }
    }
?>
    <li class="cs-offcanvas-navigation__item cs-offcanvas-navigation__item--level_<?= $level; ?>"<?php if($subItemIdentifier): ?> data-category-identifier="<?= $subItemIdentifier; ?>"<?php endif; ?>>
        <a
            class="cs-offcanvas-navigation__link<?= $itemNextAdditionalClasses ?>"
            href="<?= $subItemUrl; ?>"
            data-category-id="<?= $subItemId ?>"
        >
            <?php if ($subItemHasSubItems && $nextIcon) : ?>
                <?= $nextIcon ?>
            <?php endif; ?>
            <?php if ($subItemCategoryIcon): ?>
                <span class="cs-offcanvas-navigation__category-icon-wrapper">
                    <img src="<?= $subItemCategoryIcon; ?>" alt="<?= $subItemLabel; ?>" class="cs-offcanvas-navigation__category-icon">
                </span>
            <?php endif; ?>
            <span class="cs-offcanvas-navigation__text">
                <?= $subItemLabel; ?>
            </span>
        </a>
        <?php
            if ($subItemHasSubItems) {
                echo $this->getLayout()
                    ->createBlock(Magento\Framework\View\Element\Template::class)
                    ->setTemplate("MageSuite_Navigation::offcanvas/list.phtml")
                    ->setItem($subItem)
                    ->setParent($item)
                    ->setLevel($level + 1)
                    ->setNextIcon($block->getNextIcon())
                    ->setPrevIcon($block->getPrevIcon())
                    ->setShowCategoryIconSubcats($showCategoryIconSubcats)
                    ->setShowParentOnReturnLink($showParentOnReturnLink)
                    ->toHtml();
            }
        ?>
    </li>
<?php endforeach; ?>
</ul>
