<?php
/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $helper \Magento\Search\Helper\Data
 */
$helper = $this->helper('Magento\Search\Helper\Data');
?>

<?php if ($block->getVar('header/mobile_search_in_offcanvas', 'Magento_Theme')): ?>
    <div class="cs-offcanvas-navigation__search">
        <form role="search" class="cs-header-search cs-header-search--in-offcanvas" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get" id="cs-header-search-offcanvas">
            
            <div 
                class="cs-header-search__field cs-header-search__field--offcanvas"
                role="combobox"
                aria-owns="search_autocomplete_offcanvas"
                aria-haspopup="grid"
            >
                <label class="label cs-header-search__label" for="search" data-role="minisearch-label">
                    <span><?= $block->escapeHtml(__('Search')) ?></span>
                </label>
                <input
                    id="search-offcanvas"
                    data-mage-init='{
                        "quickSearch":{
                            "formSelector":"#cs-header-search-offcanvas",
                            "url":"<?= /* @escapeNotVerified */ $block->getUrl('search/ajax/suggest'); ?>",
                            "destinationSelector":"#search_autocomplete_offcanvas",
                            "templates": <?= /* @noEscape */ $block->getJsonSuggestRenderers();?>,
                            "priceFormat" : <?= /* @noEscape */ $block->getJsonPriceFormat();?>
                        }
                    }'
                    type="search"
                    name="<?= /* @escapeNotVerified */ $helper->getQueryParamName(); ?>"
                    value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText(); ?>"
                    placeholder="<?= /* @escapeNotVerified */ $block->getSearchPlaceholder(); ?>"
                    class="cs-header-search__input"
                    maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength(); ?>"
                    role="combobox"
                    aria-controls="search_autocomplete_offcanvas"
                    aria-autocomplete="list"
                    autocomplete="off"
                    data-block="autocomplete-form">
                    
                 <div class="cs-header-search__action">
                    <span class="cs-header-search__close">
                        <?= $block->getChildHtml('top.search.icon.close'); ?>
                        <span class="cs-header-search__close-label"><?= /* @escapeNotVerified */ __('Close search'); ?></span>
                    </span>
                    <button class="cs-header-search__button" type="submit">
                        <span class="cs-header-search__button-container cs-header-search__button-container--search">
                            <?= $block->getChildHtml('top.search.icon.submit'); ?>
                        </span>
                        <span class="cs-header-search__button-container cs-header-search__button-container--loader">
                            <?= $block->getChildHtml('top.search.icon.loader'); ?>
                        </span>
                        <span class="cs-header-search__button-label"><?= /* @escapeNotVerified */ __('Search'); ?></span>
                    </button>
                </div>

            </div>
            <div id="search_autocomplete_offcanvas" class="cs-header-search__autocomplete search-autocomplete cs-autocomplete"></div>
        </form>
    </div>
<?php endif; ?>

