<?php

// @codingStandardsIgnoreFile
/** @var \MageSuite\Navigation\Block\Navigation $block */

$level = 0;

$showCategoryIconRoot = $block->getShowCategoryIconRoot();
$showProductsAmountRoot = $block->getShowProductsAmountRoot();

$showCategoryIconSubcats = $block->getShowCategoryIconSubcats();
$showProductsAmountSubcats = $block->getShowProductsAmountSubcats();

$thirdLevelLimit = intval($block->getThirdLevelLimit());
$cacheKey = md5(implode('|', $block->getCacheKeyInfo()));
$cacheGenerationTime = time();

$imageTeaserConfig = $block->getData('imageTeaserConfig');

?>
<nav
    class="cs-navigation"
    data-cache-key="<?= $cacheKey; ?>"
    data-cache-generation-time="<?= $cacheGenerationTime; ?>"
    data-mobile-endpoint-url="<?= $block->getMobileNavigationEndpointUrl(); ?>"
    aria-label="<?= /* @escapeNotVerified */ __('Main Navigation'); ?>"
>
    <ul class="cs-navigation__list cs-navigation__list--main">
        <?php foreach($block->getItems() as $item):
            $itemId = $item->getId();
            $itemIdentifier = $item->getIdentifier();
            $itemIsAllCategories = $itemIdentifier === 'all-categories';
            $itemUrl = $itemIsAllCategories ? 'javascript:void(0);' : $item->getUrl();
            $itemLabel = $item->getLabel();
            $itemHasCustomUrl = $item->hasCustomUrl();
            $itemHasSubItems = $item->hasSubItems();
            $hasFlyout = $itemHasSubItems || $item->hasFeaturedProducts() || $item->hasImageTeaser();
            $itemCategoryIcon = $showCategoryIconRoot ? $item->getCategoryIcon() : '';
            $itemNumberOfProducts = $showProductsAmountRoot ? $item->getNumberOfProducts() : 0;
        ?>
            <li
                class="cs-navigation__item cs-navigation__item--main<?= $itemHasCustomUrl ? ' cs-navigation__item--custom' : ''; ?><?= $hasFlyout ? ' cs-navigation__item--with-flyout' : ''; ?>"
                data-category-id="<?= $itemId; ?>"
                data-category-identifier="<?= $itemIdentifier ?>"
            >
                <a
                    href="<?= $itemUrl; ?>"
                    class="cs-navigation__link cs-navigation__link--main<?= $itemCategoryIcon ? ' cs-navigation__link--with-icon' : ''; ?>"
                >
                    <?php if ($itemCategoryIcon): ?>
                        <span class="cs-navigation__link-icon-wrapper cs-navigation__link-icon-wrapper--root">
                            <?php if (strpos($item->getCategoryIconMimeType(), 'image/svg') === false): ?>
                                <img src="<?= $itemCategoryIcon; ?>" alt="<?= $itemLabel; ?>" class="cs-navigation__link-icon cs-navigation__link-icon--img">
                            <?php else: ?>
                                <?=
                                $this->getLayout()
                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                    ->setIconUrl($itemCategoryIcon)
                                    ->setCssClass('cs-navigation__link-icon cs-navigation__link-icon--svg')
                                    ->setInlined(true)
                                    ->toHtml();
                                ;?>
                            <?php endif;?>
                        </span>
                    <?php endif; ?>
                    <?= $itemLabel; ?>
                    <?php if ($itemNumberOfProducts): ?>
                        <span class="cs-navigation__products-qty"><?= $itemNumberOfProducts; ?></span>
                    <?php endif; ?>
                </a>
                <?php
                    if ($hasFlyout) {
                        echo $this->getLayout()
                            ->createBlock(Magento\Framework\View\Element\Template::class)
                            ->setTemplate("MageSuite_Navigation::main/flyout.phtml")
                            ->setItem($item)
                            ->setShowCategoryIconSubcats($showCategoryIconSubcats)
                            ->setShowProductsAmountSubcats($showProductsAmountSubcats)
                            ->setThirdLevelLimit($thirdLevelLimit)
                            ->setLevel($level + 1)
                            ->setImageTeaserConfig($imageTeaserConfig)
                            ->toHtml();
                    }
                ?>
            </li>
        <?php endforeach; ?>
    </ul>
</nav>
