<?php
    // @codingStandardsIgnoreFile
    /** @var \Magento\Framework\View\Element\Template $block */

    $item = $block->getItem();
    $featuredProducts = $item->getFeaturedProducts();
    $productsList = $featuredProducts->getProducts();
    $header = $featuredProducts->getHeader();
?>
<div class="cs-navigation__products">
    <?php if ($header): ?>
        <p class="cs-navigation__products-header"><?= $header; ?></p>
    <?php endif; ?>

    <ul class="cs-navigation__products-list">
        <?php foreach($productsList as $product): ?>
            <li class="cs-navigation__product">
                <?= $this->getLayout()
                    ->createBlock(\MageSuite\ProductTile\Block\Tile::class)
                    ->setAreas(['navigation'])
                    ->setSection('navigation')
                    ->render($product);
                ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
