<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Framework\View\Element\Template $block */

$item = $block->getItem();
$itemId = $item->getId();
$additionalCssClasses = $block->getAdditionalCssClasses() ?? '';
$level = $block->getLevel();
$isAllCategories = $item->getIdentifier() === 'all-categories';
if ($isAllCategories) {
    $additionalCssClasses .= ' cs-navigation__flyout--all-categories';
}

$showCategoryIconSubcats = $block->getShowCategoryIconSubcats();
$showProductsAmountSubcats = $block->getShowProductsAmountSubcats();

$thirdLevelLimit = $block->getThirdLevelLimit();
$itemHasTeaser = $item->hasImageTeaser();
if ($itemHasTeaser) {
    $additionalCssClasses .= ' cs-navigation__flyout--with-teaser';
}
?>
<div
    class="cs-navigation__flyout <?= $additionalCssClasses ?>"
    data-category-identifier="<?= $item->getCategoryIdentifier() ?>"
    data-parent-item-id="<?= $itemId; ?>"
>
<?php
if ($item->hasSubItems()) {
    echo $this->getLayout()
        ->createBlock(Magento\Framework\View\Element\Template::class)
        ->setTemplate("MageSuite_Navigation::main/list.phtml")
        ->setItem($item)
        ->setShowCategoryIconSubcats($showCategoryIconSubcats)
        ->setShowProductsAmountSubcats($showProductsAmountSubcats)
        ->setThirdLevelLimit(99)
        ->setLevel($level)
        ->setIsAllCategories($isAllCategories)
        ->toHtml();

    if ($isAllCategories) {
        foreach($item->getSubItems() as $subItem) {
            if ($subItem->hasSubItems()) {
                echo $this->getLayout()
                    ->createBlock(Magento\Framework\View\Element\Template::class)
                    ->setTemplate("MageSuite_Navigation::main/list.phtml")
                    ->setItem($subItem)
                    ->setShowCategoryIconSubcats($showCategoryIconSubcats)
                    ->setShowProductsAmountSubcats($showProductsAmountSubcats)
                    ->setThirdLevelLimit($thirdLevelLimit)
                    ->setLevel($level)
                    ->setIsMegaDropdownSublist(true)
                    ->toHtml();
            }

            if ($subItem->hasImageTeaser()) {
                echo $this->getLayout()
                    ->createBlock(Magento\Framework\View\Element\Template::class)
                    ->setTemplate("MageSuite_Navigation::main/image-teaser-legacy.phtml")
                    ->setItem($subItem)
                    ->setButtonIcon($block->getImageTeaserButtonIcon())
                    ->setAdditionalCssClasses('cs-navigation__teaser cs-navigation__teaser--hidden')
                    ->toHtml();
            }
        }
    }
}

if ($item->hasFeaturedProducts()) {
    echo $this->getLayout()
        ->createBlock(Magento\Framework\View\Element\Template::class)
        ->setTemplate("MageSuite_Navigation::main/featured-products.phtml")
        ->setItem($item)
        ->toHtml();
}

if ($item->hasImageTeaser()) {
    echo $this->getLayout()
        ->createBlock(Magento\Framework\View\Element\Template::class)
        ->setTemplate("MageSuite_Navigation::main/image-teaser-legacy.phtml")
        ->setItem($item)
        ->setButtonIcon($block->getImageTeaserButtonIcon())
        ->setAdditionalCssClasses('cs-navigation__teaser')
        ->toHtml();
}
?>
</div>
