<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Framework\View\Element\Template $block */

$item = $block->getItem();
$itemId = $item->getId();
$additionalCssClasses = $block->getAdditionalCssClasses() ?? '';
$level = $block->getLevel();
$isAllCategories = $item->getIdentifier() === 'all-categories';
if ($isAllCategories) {
    $additionalCssClasses .= ' cs-navigation__flyout--all-categories';
}

$showCategoryIconSubcats = $block->getShowCategoryIconSubcats();
$showProductsAmountSubcats = $block->getShowProductsAmountSubcats();
$thirdLevelLimit = $block->getThirdLevelLimit();
$itemHasImageTeaser = $item->hasImageTeaser();
$itemHasFeaturedProducts = $item->hasFeaturedProducts();

if ($itemHasImageTeaser) {
    $additionalCssClasses .= ' cs-navigation__flyout--with-teaser';
    // Fill image teaser fixed config data with data fetched dynamically
    $imageTeaserData = $item->getImageTeaser()->getItems()['0'];
    $imageTeaserConfig = $block->getImageTeaserConfig();
    $imageTeaserConfigItems = &$imageTeaserConfig['items']['0'];
    $imageTeaserConfigItems['image']['raw'] = $imageTeaserData['image']['raw'];
    $imageTeaserConfigItems['image']['decoded'] = $imageTeaserData['image']['decoded'];
    $imageTeaserConfigItems['slogan'] = $imageTeaserData['slogan'];
    $imageTeaserConfigItems['description'] = $imageTeaserData['description'];
    $imageTeaserConfigItems['cta'] = $imageTeaserData['cta'];
}

if ($itemHasFeaturedProducts) {
    $additionalCssClasses .= ' cs-navigation__flyout--with-product';
}
?>

<div
    class="cs-navigation__flyout <?= $additionalCssClasses ?>"
    data-category-identifier="<?= $item->getCategoryIdentifier() ?>"
    data-parent-item-id="<?= $itemId; ?>"
>

<?php
if ($item->hasSubItems()) {
    echo $this->getLayout()
        ->createBlock(Magento\Framework\View\Element\Template::class)
        ->setTemplate("MageSuite_Navigation::main/list.phtml")
        ->setItem($item)
        ->setShowCategoryIconSubcats($showCategoryIconSubcats)
        ->setShowProductsAmountSubcats($showProductsAmountSubcats)
        ->setThirdLevelLimit($thirdLevelLimit ?? 99)
        ->setLevel($level)
        ->setIsAllCategories($isAllCategories)
        ->toHtml();

    if ($isAllCategories) {
        foreach($item->getSubItems() as $subItem) {
            if ($subItem->hasSubItems()) {
                echo $this->getLayout()
                    ->createBlock(Magento\Framework\View\Element\Template::class)
                    ->setTemplate("MageSuite_Navigation::main/list.phtml")
                    ->setItem($subItem)
                    ->setShowCategoryIconSubcats($showCategoryIconSubcats)
                    ->setShowProductsAmountSubcats($showProductsAmountSubcats)
                    ->setThirdLevelLimit($thirdLevelLimit ?? 99)
                    ->setLevel($level)
                    ->setIsMegaDropdownSublist(true)
                    ->toHtml();
            }

            if ($subItem->hasImageTeaser()) {
                // Fill image teaser fixed config data with data fetched dynamically
                $subImageTeaserData = $subItem->getImageTeaser()->getItems()['0'];
                $subImageTeaserConfig = $block->getImageTeaserConfig();
                $subImageTeaserConfigItems = &$subImageTeaserConfig['items']['0'];
                $subImageTeaserConfigItems['image']['raw'] = $subImageTeaserData['image']['raw'];
                $subImageTeaserConfigItems['image']['decoded'] = $subImageTeaserData['image']['decoded'];
                $subImageTeaserConfigItems['slogan'] = $subImageTeaserData['slogan'];
                $subImageTeaserConfigItems['description'] = $subImageTeaserData['description'];
                $subImageTeaserConfigItems['cta'] = $subImageTeaserData['cta'];

                echo $this->getLayout()
                    ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
                    ->setItem($subItem)
                    ->setData($subImageTeaserConfig)
                    ->setMix('cs-navigation__teaser')
                    ->toHtml();
            }
        }
    }
}

if ($itemHasFeaturedProducts) {
    echo $this->getLayout()
        ->createBlock(Magento\Framework\View\Element\Template::class)
        ->setTemplate("MageSuite_Navigation::main/featured-products.phtml")
        ->setItem($item)
        ->toHtml();
}

if ($itemHasImageTeaser) {
    echo $this->getLayout()
        ->createBlock('MageSuite\ContentConstructorFrontend\Block\Component\ImageTeaser')
        ->setItem($item)
        ->setData($imageTeaserConfig)
        ->setMix('cs-navigation__teaser cs-image-teaser--featured')
        ->toHtml();
}
?>

</div>
