<?php
    $level = $block->getLevel();
    $item = $block->getItem();
    $itemId = $item->getId();
    $itemUrl = $item->getUrl();
    $itemLabel = $item->getLabel();
    $itemHasCustomUrl = $item->hasCustomUrl();
    $itemCategoryIdentifier = $item->getCategoryIdentifier() ?? '';

    $showCategoryIconSubcats = $block->getShowCategoryIconSubcats();
    $showProductsAmountSubcats = $block->getShowProductsAmountSubcats();
?>
<ul class="cs-navigation__list cs-navigation__list--level_<?= $level ; ?>">
<?php if ($level === 1): ?>
    <li
        class="cs-navigation__item cs-navigation__item--level_<?= $level ; ?> cs-navigation__item--touch <?= $itemHasCustomUrl ? ' cs-navigation__item--custom' : '' ?>"
        data-category-id="<?= $itemId; ?>"
        data-category-identifier="<?= $itemCategoryIdentifier; ?>"
    >
        <a href="<?= $itemUrl; ?>" class="cs-navigation__link cs-navigation__link--level_<?= $level ; ?> cs-navigation__link--touch">
            <?= __("Go to %1", $itemLabel); ?>
        </a>
    </li>
<?php endif; ?>
<?php
foreach($item->getSubItems() as $subItem):
    $subItem = $subItem;
    $subItemId = $subItem->getId();
    $subItemUrl = $subItem->getUrl();
    $subItemLabel = $subItem->getLabel();
    $subItemHasCustomUrl = $subItem->hasCustomUrl();
    $subItemCategoryIdentifier = $subItem->getCategoryIdentifier() ?? '';
    $subItemCategoryIcon = $showCategoryIconSubcats ? $subItem->getCategoryIcon() : '';
    $subItemNumberOfProducts = $showProductsAmountSubcats ? $subItem->getNumberOfProducts() : 0;
?>
    <li
        class="cs-navigation__item cs-navigation__item--level_<?= $level; ?><?= $subItemHasCustomUrl ? ' cs-navigation__item--custom' : ''; ?>"
        data-category-id="<?= $subItemId; ?>"
        data-category-identifier="<?= $subItemCategoryIdentifier; ?>"
    >
        <a
            href="<?= $subItemUrl; ?>"
            class="cs-navigation__link cs-navigation__link--level_<?= $level; ?><?= $subItemCategoryIcon ? ' cs-navigation__link--with-icon' : ''; ?>"
        >
            <?php if ($subItemCategoryIcon): ?>
                <span class="cs-navigation__link-icon-wrapper">
                    <img src="<?= $subItemCategoryIcon; ?>" alt="<?= $subItemLabel; ?>" class="cs-navigation__link-icon">
                </span>
            <?php endif; ?>
            <?= $subItemLabel; ?>
            <?php if ($subItemNumberOfProducts): ?>
                <span class="cs-navigation__link-products-qty"><?= $subItemNumberOfProducts; ?></span>
            <?php endif; ?>
        </a>
        <?php
            if ($subItem->hasSubItems()) {
                echo $this->getLayout()
                    ->createBlock(Magento\Framework\View\Element\Template::class)
                    ->setTemplate("MageSuite_Navigation::main/list.phtml")
                    ->setItem($subItem)
                    ->setShowProductsAmountSubcats($showProductsAmountSubcats)
                    ->setShowCategoryIconSubcats($showCategoryIconSubcats)
                    ->setLevel($level + 1)
                    ->toHtml();
            }
        ?>
    </li>
<?php endforeach; ?>
</ul>
