<a class="cs-header-user-area__section cs-header-user-area__section--favourites" href="#">
    <div class="cs-header-user-area__icon-wrapper">
        <span class="cs-header-user-area__badge | cs-badge cs-badge--short cs-badge--attention">
            <span class="cs-badge__span">3</span>
        </span>
        <svg class="cs-header-user-area__icon cs-user-area__icon--favourites">
            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#heart"></use>
        </svg>
    </div>
    <p class="cs-header-user-area__label | cs-t-text cs-t-text--size_200 cs-t-text--look_caption"><?=__('Wishlist');?></p>
</a>