<a class="cs-header-user-area__section cs-header-user-area__section--my-account" href="#">
    <div class="cs-header-user-area__icon-wrapper">
        <svg class="cs-header-user-area__icon cs-header-user-area__icon--my-account">
            <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#user"></use>
        </svg>
    </div>
    <p class="cs-header-user-area__label | cs-t-text cs-t-text--size_200 cs-t-text--look_caption"><?=__('My account');?></p>
</a>