
<meta property="og:title" content="<?php echo $block->getTitle(); ?>"/>
<meta property="og:type" content="article"/>
<meta property="og:url" content="<?php echo $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>"/>
<meta property="og:description" content="<?php echo strip_tags($block->getPageDescription()) ?>"/>
<meta property="og:site_name" content="<?php echo $block->getStoreName(); ?>"/>

<meta name="twitter:card" content="summary"/>
<meta name="twitter:site" content="@mysite;"/>
<meta name="twitter:title" content="<?php echo $block->getTitle(); ?>"/>
<meta name="twitter:description" content="<?php echo strip_tags($block->getPageDescription()) ?>"/>