
<?php if ($currentProduct = $block->getCurrentProduct()): ?>
    <meta property="og:title" content="<?php echo $currentProduct->getName(); ?>"/>
    <meta property="og:type" content="product"/>
    <?php
    $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
        ->init($currentProduct, 'product_page_image_large')
        ->setImageFile($currentProduct->getFile())
        ->getUrl();
    ?>
    <meta property="og:image" content="<?php echo $imageUrl;?>" />
    <meta property="og:url" content="<?php echo $currentProduct->getProductUrl(); ?>"/>
    <meta property="og:description" content="<?php echo $block->getProductDescription(); ?>"/>
    <meta property="og:site_name" content="<?php echo $block->getStoreName(); ?>"/>

    <meta property="product:price:amount" content="<?php echo $currentProduct->getFinalPrice(); ?>"/>
    <meta property="product:price:currency" content="<?php echo $block->getCurrency(); ?>"/>
    <meta property="product:availability"
          content="<?php echo $currentProduct->isAvailable() ? __('In stock') : __('Out of stock'); ?>"/>
    <meta property="product:retailer_item_id" content="<?php echo $currentProduct->getSku() ?>"/>

    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:site" content="@mysite"/>
    <meta name="twitter:title" content="<?php echo $block->getTitle(); ?>"/>
    <meta name="twitter:description" content="<?php echo $block->getProductDescription() ?>"/>
    <?php
    $smallImageUrl = $this->helper('Magento\Catalog\Helper\Image')
        ->init($currentProduct, 'small_image')
        ->setImageFile($currentProduct->getFile())
        ->getUrl();
    ?>
    <meta name="twitter:image" content="<?php echo $imageUrl;?>" />

<?php endif; ?>
