<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="cs-info-block | cs-dashboard__block">

    <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
        <h2 class="cs-title-block__span">
            <?php /* @escapeNotVerified */ echo __('My addresses') ?>
        </h2>
        <span class="cs-title-block__span">
            <a
                class="cs-info-block__title-link"
                href="<?php /* @escapeNotVerified */ echo $block->getAddressBookUrl() ?>"
            >
                <?php /* @escapeNotVerified */ echo __('Manage Addresses') ?>
            </a>
        </span>
    </div>

    <div class="cs-info-block__content">
        <div class="cs-info-block__box | box-billing-address">
            <h3 class="cs-info-block__box-title">
                <?php /* @escapeNotVerified */ echo __('Default Billing Address') ?>
            </h3>
            <div class="cs-info-block__box-content">
                <address>
                    <?php echo $block->getPrimaryBillingAddressHtml() ?>
                </address>
            </div>
            <div class="cs-info-block__box-actions">
                <a
                    class="action edit"
                    href="<?php /* @escapeNotVerified */ echo $block->getPrimaryBillingAddressEditUrl() ?>"
                    data-ui-id="default-billing-edit-link"
                >
                    <?php /* @escapeNotVerified */ echo __('Change Billing Address') ?>
                </a>
            </div>
        </div>
        <div class="cs-info-block__box | box-shipping-address">
            <h3 class="cs-info-block__box-title">
                <?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?>
            </h3>
            <div class="cs-info-block__box-content">
                <address>
                    <?php echo $block->getPrimaryShippingAddressHtml() ?>
                </address>
            </div>
            <div class="cs-info-block__box-actions">
                <a
                    class="action edit"
                    href="<?php /* @escapeNotVerified */ echo $block->getPrimaryShippingAddressEditUrl() ?>"
                    data-ui-id="default-shipping-edit-link"
                >
                    <?php /* @escapeNotVerified */ echo __('Change Shipping Address') ?>
                </a>
            </div>
        </div>
    </div>
</div>
