<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="cs-info-block  | cs-dashboard__block">
    <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
        <h2 class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light">
            <?php /* @escapeNotVerified */ echo __('Account Information') ?>
        </h2>
    </div>

    <div class="cs-info-block__content">
        <div class="cs-info-block__box | box-information">
            <h3 class="cs-info-block__box-title | cs-t-headline cs-t-headline--size_4">
                <?php /* @escapeNotVerified */ echo __('Contact Information') ?>
            </h3>
            <div class="cs-info-block__box-content">
                <p class="cs-info-block__line | cs-t-text cs-t-text--look_light">
                    <?php echo $block->escapeHtml($block->getName()) ?>
                </p>
                <p class="cs-info-block__line | cs-t-text cs-t-text--look_light">
                    <?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                </p>
            </div>
            <div class="cs-info-block__box-actions">
                <a
                    class="cs-link cs-link--separator"
                    href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/edit') ?>"
                >
                    <?php /* @escapeNotVerified */ echo __('Edit') ?>
                </a>
                <a
                    href="<?php /* @escapeNotVerified */ echo $block->getChangePasswordUrl() ?>"
                    class="action change-password  | cs-link"
                >
                    <?php /* @escapeNotVerified */ echo __('Change Password') ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="cs-info-block__box | box-newsletter">
                <h3 class="cs-info-block__box-title | cs-t-headline cs-t-headline--size_4">
                    <?php /* @escapeNotVerified */ echo __('Newsletters') ?>
                </h3>
                <div class="cs-info-block__box-content">
                    <p class="cs-info-block__line | cs-t-text cs-t-text--look_light">
                        <?php if ($block->getIsSubscribed()): ?>
                            <?php /* @escapeNotVerified */ echo __('You subscribe to "General Subscription".') ?>
                        <?php else: ?>
                            <?php /* @escapeNotVerified */ echo __('You don\'t subscribe to our newsletter.') ?>
                        <?php endif; ?>
                    </p>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $block->getChildHtml('customer.account.dashboard.info.extra')?>
                </div>
                <div class="cs-info-block__box-actions">
                    <a class="cs-link" href="<?php /* @escapeNotVerified */ echo $block->getUrl('newsletter/manage') ?>">
                        <?php /* @escapeNotVerified */ echo __('Edit') ?>
                    </a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>

