<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Customer\Wishlist\Button */
?>
<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->getShared() < $block->getConfig()->getSharingEmailLimit()): ?>
<div class="cs-wishlist__button">
    <button
        type="submit"
        name="save_and_share"
        title="<?php /* @escapeNotVerified */ echo __('Share Wish List') ?>"
        class="cs-button cs-button--look_light cs-button--type_wide"
    >
        <span class="cs-button__span"> <?php /* @escapeNotVerified */ echo __('Share Wish List') ?></span>
        <svg class="cs-button__icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </button>
</div>
<?php endif;?>
