<?php
// @codingStandardsIgnoreFile
?>

<?php if ($block->getWishlist()->getItemsCount() && $block->getWishlist()->isSalable()): ?>
<div class="cs-wishlist__button">
    <button
        type="button"
        data-role="all-tocart"
        title="<?php /* @escapeNotVerified */ echo __('Add All to Cart') ?>"
        class="cs-button cs-button--look_light cs-button--type_wide"
    >
        <span class="cs-button__span"> <?php /* @escapeNotVerified */ echo __('Add All to Cart') ?></span>
        <svg class="cs-button__icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </button>
</div>
<?php endif;?>
