<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
<div class="cs-wishlist__button">
    <button type="submit" name="do" title="<?php /* @escapeNotVerified */ echo __('Update Wish List') ?>" class="cs-button cs-button--look_light cs-button--wide">
        <?php /* @escapeNotVerified */ echo __('Update Wish List') ?>
        <svg class="cs-button__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
        </svg>
    </button>
</div>
<?php endif;?>
