<?php
// @codingStandardsIgnoreFile
?>

<?php if ($block->getWishlist()->getItemsCount()): ?>
<div class="cs-wishlist__button">
    <button type="submit"
            name="do"
            title="<?php /* @escapeNotVerified */ echo __('Update Wish List') ?>"
            class="cs-button cs-button--look_light cs-button--type_wide">
        <span class="cs-button__span"> <?php /* @escapeNotVerified */ echo __('Update Wish List') ?></span>
        <svg class="cs-button__icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </button>
</div>
<?php endif;?>
