<?php
// @codingStandardsIgnoreFile
/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */
?>
<?php
$option = $block->getOption();
$selections = $option->getSelections()
?>
<div class="cs-bundle-box__field field option <?php echo ($option->getRequired()) ? ' required': ''; ?>">
    <label class="cs-bundle-box__product-name">
        <?php echo $block->escapeHtml($option->getTitle()) ?>
    </label>
    <div class="cs-bundle-box__options-list | cs-input cs-input--type-checkbox">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($selections[0]) ?>
                <input
                    type="hidden"
                    class="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>  product bundle option"
                    name="bundle_option[<?php /* @escapeNotVerified */ echo $option->getId() ?>]"
                    value="<?php /* @escapeNotVerified */ echo $selections[0]->getSelectionId() ?>"
                    />
            <?php else:?>
                <?php foreach($selections as $selection): ?>
                    <div class="cs-bundle-box__option cs-bundle-box__option--small-space field choice">
                        <input
                            class="cs-input__checkbox bundle-option-<?php /* @escapeNotVerified */ echo $option->getId()
                            ?> checkbox product bundle option change-container-classname"
                            id="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>-<?php /* @escapeNotVerified */ echo $selection->getSelectionId() ?>"
                            type="checkbox"
                            <?php if ($option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' . $option->getId() . ']&quot;]:checked\'}"'?>
                            name="bundle_option[<?php /* @escapeNotVerified */ echo $option->getId() ?>][<?php /* @escapeNotVerified */ echo $selection->getId() ?>]"
                            data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $option->getId() ?>][<?php /* @escapeNotVerified */ echo $selection->getId() ?>]"
                            <?php if ($block->isSelected($selection)) echo ' checked="checked"' ?>
                            <?php if (!$selection->isSaleable()) echo ' disabled="disabled"' ?>
                            value="<?php /* @escapeNotVerified */ echo $selection->getSelectionId() ?>"
                            />
                        <label
                            class="cs-input__label  cs-input__label--big"
                            for="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>-<?php /* @escapeNotVerified */ echo $selection->getSelectionId() ?>"
                            >
                            <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($selection) ?>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>
