<?php
// @codingStandardsIgnoreFile
?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio */ ?>
<?php
    $option = $block->getOption();
    $selections  = $option->getSelections();
    $default     = $option->getDefaultSelection();
    list($defaultQty, $canChangeQty) = $block->getDefaultValues();
?>

<div class="field option <?= ($option->getRequired()) ? ' required': '' ?> cs-bundle-box__field">
    <label class="label cs-bundle-box__product-name">
        <?= $block->escapeHtml($option->getTitle()) ?>
    </label>
    <div class="control cs-bundle-box__options-list">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($selections[0]) ?>
                <input
                    type="hidden"
                    class="bundle-option-<?php echo (int)$option->getId() ?>  product bundle option"
                    name="bundle_option[<?php echo (int)$option->getId() ?>]"
                    value="<?php echo (int)$selections[0]->getSelectionId() ?>"
                    id="bundle-option-<?php echo (int)$option->getId() ?>-<?php echo (int)$selections[0]->getSelectionId() ?>"
                    checked="checked"
                    />
            <?php else:?>
                <?php if (!$option->getRequired()): ?>
                    <div class="field choice cs-bundle-box__option">
                        <input
                            type="radio"
                            class="radio product bundle option"
                            id="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>"
                            name="bundle_option[<?php /* @escapeNotVerified */ echo $option->getId() ?>]"
                            data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $option->getId() ?>]"
                            <?php echo ($default && $default->isSalable())?'':' checked="checked" ' ?>
                            value=""
                        />
                        <label
                            class="label cs-bundle-box__product-option-name"
                            for="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>"
                        >
                            <span><?php /* @escapeNotVerified */ echo __('None') ?></span>
                        </label>
                    </div>
                <?php endif; ?>
                <?php foreach ($selections as $selection): ?>
                    <div class="cs-bundle-box__option">
                        <input
                            type="radio"
                            class="radio product bundle option change-container-classname"
                            id="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>-<?php /* @escapeNotVerified */ echo $selection->getSelectionId() ?>"
                            <?php if ($option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':true}"'?>
                            name="bundle_option[<?php /* @escapeNotVerified */ echo $option->getId() ?>]"
                            data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $option->getId() ?>]"
                            <?php if ($block->isSelected($selection)) echo ' checked="checked"' ?>
                            <?php if (!$selection->isSaleable()) echo ' disabled="disabled"' ?>
                            value="<?php /* @escapeNotVerified */ echo $selection->getSelectionId() ?>"
                        />
                        <label
                            class="label cs-bundle-box__product-option-name"
                            for="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>-<?php /* @escapeNotVerified */ echo $selection->getSelectionId() ?>"
                        >
                            <span><?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($selection) ?></span>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>-container"></div>
            <?php endif; ?>
        </div>

        <?php if($canChangeQty): ?>
            <div class="field qty qty-holder cs-bundle-box__qty cs-box-addtocart__qty-wrapper">
                <label class="cs-box-addtocart__label" for="bundle-option-<?php /* @escapeNotVerified */ echo $option->getId() ?>-qty-input">
                    <span><?php /* @escapeNotVerified */ echo __('Qty') ?></span>
                </label>
                <div class="control cs-box-addtocart__qty-increment">
                    <?php $disabled = !$canChangeQty ? ' disabled="disabled"' : ''; ?>

                    <?= $this->getLayout()
                          ->createBlock('Magento\Framework\View\Element\Template')
                          ->setInputName('bundle_option_qty['.$option->getId().']')
                          ->setAdditionalInputCssClasses($canChangeQty ? ' input-text qty' : ' input-text qty qty-disabled')
                          ->setInputInitialValue($defaultQty)
                          ->setInputAdditionalParams('id="bundle-option-'.$option->getId().'-qty-input" data-selector="bundle_option_qty['.$option->getId().']" data-min-value="1" min="1"'.$disabled)
                          ->setDecrementIconUrl($block->getViewFileUrl($block->getVar('qty_increment/icons/decrement', 'MageSuite_ThemeHelpers')))
                          ->setIncrementIconUrl($block->getViewFileUrl($block->getVar('qty_increment/icons/increment', 'MageSuite_ThemeHelpers')))
                          ->setTemplate($block->getVar('qty_increment/template', 'MageSuite_ThemeHelpers'))
                          ->toHtml(); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
