<?php
/** Template overridden to:
 * - add magesuite classes
 * - show qty-increment only when qty can change
 * Aligned with Magento 2.4.7 in 04/2024
 */
?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */ ?>
<?php $_option      = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>

<div class="field option <?= ($_option->getRequired()) ? ' required': ''; ?> cs-bundle-box__field">
    <label class="label cs-bundle-box__product-name" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>">
        <?= $block->escapeHtml($_option->getTitle()) ?>
    </label>
    <div class="control cs-bundle-box__options-list">
        <?php if ($block->showSingle()) : ?>
            <?= /* @noEscape */ $block->getSelectionTitlePrice($_selections[0]) ?>
            <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selections[0]) ?>
            <input type="hidden"
                   class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>  product bundle option"
                   name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                   value="<?= $block->escapeHtmlAttr($_selections[0]->getSelectionId()) ?>"/>
        <?php else :?>
            <select id="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>"
                    name="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                    data-selector="bundle_option[<?= $block->escapeHtmlAttr($_option->getId()) ?>]"
                    class="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?> product bundle option bundle-option-select change-container-classname cs-select"
                <?php if ($_option->getRequired()) { echo 'data-validate = {required:true}'; } ?>>
                <option value=""><?= $block->escapeHtml(__('Choose a selection...')) ?></option>
                <?php foreach ($_selections as $_selection) : ?>
                    <option value="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                        <?php if ($block->isSelected($_selection)) { echo ' selected="selected"'; } ?>
                        <?php if (!$_selection->isSaleable()) { echo ' disabled="disabled"'; } ?>>
                        <?= /* @noEscape */ $block->getSelectionTitlePrice($_selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <div id="option-tier-prices-<?= $block->escapeHtmlAttr($_option->getId()) ?>" class="option-tier-prices">
                <?php foreach ($_selections as $_selection) : ?>
                    <div data-role="selection-tier-prices"
                         data-selection-id="<?= $block->escapeHtmlAttr($_selection->getSelectionId()) ?>"
                         class="selection-tier-prices">
                        <?= /* @noEscape */ $block->getTierPriceRenderer()->renderTierPrice($_selection) ?>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php if($_canChangeQty): ?>
            <div class="field qty qty-holder cs-bundle-box__qty cs-box-addtocart__qty-wrapper">
                <label class="label cs-box-addtocart__label" for="bundle-option-<?= $block->escapeHtmlAttr($_option->getId()) ?>-qty-input">
                    <span><?= $block->escapeHtml(__('Qty')) ?></span>
                </label>

                <div class="control cs-box-addtocart__qty-increment">
                    <?php $disabled = !$_canChangeQty ? ' disabled="disabled"' : ''; ?>

                    <?= $this->getLayout()
                          ->createBlock('Magento\Framework\View\Element\Template')
                          ->setInputName('bundle_option_qty['.$block->escapeHtmlAttr($_option->getId()).']')
                          ->setAdditionalInputCssClasses($_canChangeQty ? ' input-text qty' : ' input-text qty qty-disabled')
                          ->setInputInitialValue($block->escapeHtmlAttr($_defaultQty))
                          ->setInputAdditionalParams('id="bundle-option-'.$block->escapeHtmlAttr($_option->getId()).'-qty-input" data-selector="bundle_option_qty['.$_option->getId().']" data-min-value="1" min="1"'.$disabled)
                          ->setDecrementIconUrl($block->getVar('qty_increment/icons/decrement', 'MageSuite_ThemeHelpers'))
                          ->setIncrementIconUrl($block->getVar('qty_increment/icons/increment', 'MageSuite_ThemeHelpers'))
                          ->setTemplate($block->getVar('qty_increment/template', 'MageSuite_ThemeHelpers'))
                          ->toHtml(); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
