<?php
// @codingStandardsIgnoreFile
/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */
?>

<?php
    $option      = $block->getOption();
    $selections  = $option->getSelections();
    $default     = $option->getDefaultSelection();
    list($defaultQty, $canChangeQty) = $block->getDefaultValues();
?>

<div class="field option <?= ($option->getRequired()) ? ' required': ''; ?> cs-bundle-box__field">
    <label class="label cs-bundle-box__product-name" for="bundle-option-<?= /* @escapeNotVerified */ $option->getId() ?>">
        <?= $block->escapeHtml($option->getTitle()) ?>
    </label>
    <div class="control cs-bundle-box__options-list">
        <?php if ($block->showSingle()): ?>
            <?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($selections[0]) ?>
            <input
                type="hidden"
                class="bundle-option-<?= /* @escapeNotVerified */ $option->getId() ?>  product bundle option"
                name="bundle_option[<?= /* @escapeNotVerified */ $option->getId() ?>]"
                value="<?= /* @escapeNotVerified */ $selections[0]->getSelectionId() ?>"
                />
        <?php else:?>
            <select
                id="bundle-option-<?= /* @escapeNotVerified */ $option->getId() ?>"
                name="bundle_option[<?= /* @escapeNotVerified */ $option->getId() ?>]"
                data-selector="bundle_option[<?= /* @escapeNotVerified */ $option->getId() ?>]"
                class="bundle-option-<?= /* @escapeNotVerified */ $option->getId() ?> product bundle option bundle-option-select change-container-classname cs-select"
                <?php if ($option->getRequired()) echo 'data-validate = {required:true}' ?>
                >
                <option value=""><?= /* @escapeNotVerified */ __('Choose a selection...') ?></option>
                <?php foreach ($selections as $selection): ?>
                    <option value="<?= /* @escapeNotVerified */ $selection->getSelectionId() ?>"
                        <?php if ($block->isSelected($selection)) echo ' selected="selected"' ?>
                        <?php if (!$selection->isSaleable()) echo ' disabled="disabled"' ?>>
                        <?= /* @escapeNotVerified */ $block->getSelectionTitlePrice($selection, false) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>

        <?php if($canChangeQty): ?>
            <div class="field qty qty-holder cs-bundle-box__qty cs-box-addtocart__qty-wrapper">
                <label class="label cs-box-addtocart__label" for="bundle-option-<?= /* @escapeNotVerified */ $option->getId() ?>-qty-input">
                    <span><?= /* @escapeNotVerified */ __('Qty') ?></span>
                </label>

                <div class="control cs-box-addtocart__qty-increment">
                    <?php $disabled = !$canChangeQty ? ' disabled="disabled"' : ''; ?>

                    <?= $this->getLayout()
                          ->createBlock('Magento\Framework\View\Element\Template')
                          ->setInputName('bundle_option_qty['.$option->getId().']')
                          ->setAdditionalInputCssClasses($canChangeQty ? ' input-text qty' : ' input-text qty qty-disabled')
                          ->setInputInitialValue($defaultQty)
                          ->setInputAdditionalParams('id="bundle-option-'.$option->getId().'-qty-input" data-selector="bundle_option_qty['.$option->getId().']" data-min-value="1" min="1"'.$disabled)
                          ->setDecrementIconUrl($block->getViewFileUrl($block->getVar('qty_increment/icons/decrement', 'MageSuite_ThemeHelpers')))
                          ->setIncrementIconUrl($block->getViewFileUrl($block->getVar('qty_increment/icons/increment', 'MageSuite_ThemeHelpers')))
                          ->setTemplate($block->getVar('qty_increment/template', 'MageSuite_ThemeHelpers'))
                          ->toHtml(); ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
