<?php 
/* @TODO: Remove twig in future */
$_item = $block->getData('item');
echo $this->getLayout()->createBlock(
    'MageSuite\Frontend\Block\Twig',
    'cart-item'.$_item->getId(), [
        'data' => [
            "namespace" => 'cs-',
            "minValue" => 1,
            "initialValue" =>  /* @escapeNotVerified */ $block->getQty(),
            "maxLength" => 12,
            "size" => 2,
            "name" => 'cart['. /* @escapeNotVerified */ $_item->getId().'][qty]',
            'inputClass' => 'qty',
            "inputParams" => 'id="cart-'./* @escapeNotVerified */ $_item->getId().'-qty"
                            name="cart'./* @escapeNotVerified */ $_item->getId().'][qty]"
                            data-cart-item-id="'./* @escapeNotVerified */ $_item->getSku().'"
                            data-role="cart-item-qty"
                            data-validate="{required:true,\'validate-greater-than-zero\':true}"',
            "icons" => [
                "increment" => '#plus',
                "decrement" => '#minus'
            ]
        ]
    ]
)->setTemplate( "qty-increment/qty-increment.twig" )->toHtml(); 
?>