<?php

// @codingStandardsIgnoreFile

/** @var \Aheadworks\Pquestion\Block\Customer\Question\Grid $this */
?>
<div class="cs-info-block | cs-dashboard__block">

    <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
        <h2 class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light">
            <?php echo $this->escapeHtml(__('Your Questions'));?>
        </h2>
    </div>

    <div class="cs-info-block__content">
            <?php $questionCollection = $this->getCollection(); ?>
            <?php if ($questionCollection->getSize()) : ?>
                <div class="cs-table">
                    <table class="data-table cs-table__body" id="aw-pq-customer-questions-table">
                        <col width="150" />
                        <col />
                        <col width="1" />
                        <col width="130" />
                        <thead class="cs-table__head">
                        <tr>
                            <th class="cs-table__col-head">
                                <span class="nobr"><?php echo $this->escapeHtml(__('Product')); ?></span>
                            </th>
                            <th class="cs-table__col-head">
                                <span class="nobr"><?php echo $this->escapeHtml(__('Question')); ?></span>
                            </th>
                            <th class="cs-table__col-head">
                                <span class="nobr"><?php echo $this->escapeHtml(__('Status')); ?></span>
                            </th>
                            <th class="cs-table__col-head">
                                <span class="nobr"><?php echo $this->escapeHtml(__('Is Answered?')); ?></span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($questionCollection as $question) : ?>
                            <tr>
                                <td
                                    class="cs-table__col"
                                    data-th="<?php echo $this->escapeHtml(__('Product')); ?>"
                                >
                                    <a
                                        href="<?php echo $this->escapeUrl($this->getProductUrlByQuestion($question));?>"
                                        title="<?php echo $this->escapeHtml($this->getProductNameByQuestion($question));?>"
                                        class="cs-link"
                                    >
                                        <?php echo $this->escapeHtml($this->getProductNameByQuestion($question));?>
                                    </a>
                                </td>
                                <td
                                    class="cs-table__col"
                                    title="<?php echo $this->escapeHtml($this->escapeHtml($question->getContent()));?>"
                                    data-th="<?php echo $this->escapeHtml(__('Question')); ?>"
                                >
                                    <?php echo $this->escapeHtml($this->truncateString($this->escapeHtml($question->getContent()), 300));?>
                                </td>
                                <td class="cs-table__col" data-th="<?php echo $this->escapeHtml(__('Status')); ?>">
                                    <?php echo $this->escapeHtml($this->getStatusLabelByQuestion($question)); ?>
                                </td>
                                <td class="cs-table__col" data-th="<?php echo $this->escapeHtml(__('Is Answered?')); ?>">
                                    <span class="nobr">
                                        <?php echo $this->escapeHtml($this->getIsAnsweredLabelForQuestion($question)); ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php else: ?>
                <p class="cs-t-text cs-t-text--look_light"><?php echo $this->escapeHtml(__('There are no questions yet.')); ?></p>
            <?php endif ?>
        </div>

</div>

