<?php
/** @var \MageSuite\BrandManagement\Block\All $block */
$brands = $block->getAllBrands();
$brandsByFirstLetter = $block->getBrandsGroupedByFirstLetter();
$sizeCollection = sizeof($brands);
?>

<div class="cs-brands-index__list-wrapper">
    <div class="cs-brands-index__list">
        <?php  foreach($brandsByFirstLetter as $letter => $brands): ?>
            <div class="cs-brands-index__list-item" id="letter-<?=strtoupper($letter)?>">
                <div class="cs-brands-index__section-left">
                    <p><?=strtoupper($letter)?></p>
                </div>
                <div class="cs-brands-index__section-right">
                    <div class="cs-brands-index__brands">
                        <?php foreach ($brands as $brand) :?>
                            <a class="cs-brands-index__brand" href="<?php echo $brand->getBrandUrl();?>" target="_blank"><?php echo $brand->getBrandName();?></a>
                        <?php endforeach;?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
    <?php if($sizeCollection > 15): ?>
        <?= $block->getChildHtml('page.scroll'); ?>
    <?php endif ?>
</div>
