<?php

/** @var \MageSuite\BrandManagement\Block\All $block */
$brands = $block->getAllBrands();

?>
<div class="cs-brands-index__icons">
    <div class="cs-brands-index__icons-wrapper">
        <?php foreach ($brands as $brand): ?>
            <?php if(!empty($brand->getBrandIconUrl()) and $brand->getIsFeatured()): ?>
                <a class="cs-brands-index__icon" href="<?php echo $brand->getBrandUrl()?>" target="_blank">
                    <img class="cs-brands-index__img" src="<?php echo $brand->getBrandIconUrl()?>" alt="<?php echo $brand->getBrandName()?>">
                </a>
            <?php endif; ?>
        <?php endforeach;?>
    </div>
</div>
