<?php
// @codingStandardsIgnoreFile
/* @var $block \Magento\Framework\View\Element\Template */
?>
<div
    class="cs-info-block | block-compare"
    data-bind="scope: 'compareProducts'"
    data-role="compare-products-sidebar"
>
    <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
        <h2 class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light">
            <span id="block-compare-heading" role="heading" aria-level="2">
                <?php /* @escapeNotVerified */ echo __('Compare Products') ?>
            </span>
            <span
                class="cs-t-headline__span"
                data-bind="text: '('+compareProducts().countCaption+')', css: {'no-display': !compareProducts().count}"
            ></span>
        </h2>
        <!-- ko if: compareProducts().count -->
        <a
            id="compare-clear-all"
            href="#"
            class="cs-title-block__span | cs-link"
            data-post="<?=$block->escapeHtml($this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataClearList()) ?>"
        >
            <span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span>
        </a>
        <!-- /ko -->
    </div>
    <!-- ko if: compareProducts().count -->
    <div
        class="cs-info-block__content"
        aria-labelledby="block-compare-heading"
        data-bind="css: {'no-display': !compareProducts().count}"
    >
        <ol id="compare-items" class="cs-list cs-list--unstyled cs-list--multiline" data-bind="foreach: compareProducts().items">
            <li class="cs-list__item cs-list__item--inputs">
                <input type="hidden" class="compare-item-id" data-bind="value: id"/>
                <a
                    href="#"
                    data-bind="attr: {'data-post': remove_url}"
                    title="<?php /* @escapeNotVerified */ echo __('Remove This Item') ?>"
                    class="cs-button--look_remove cs-button--look_remove_space"
                >
                    <svg class="cs-button__remove-icon">
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#close"></use>
                    </svg>
                    <span class="cs-visually-hidden"><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
                </a>
                <a data-bind="attr: {href: product_url}, html: name" class="cs-list__link cs-list__link--short"></a>

            </li>
        </ol>
        <div class="cs-info-block__buttons">
            <a data-bind="attr: {'href': compareProducts().listUrl}" class="cs-button cs-button--look_light cs-button--size_300">
                <span class="cs-button__span"><?php /* @escapeNotVerified */ echo __('Compare') ?></span>
                <svg class="cs-button__icon">
                    <use xlink:href="#arrow_next"></use>
                </svg>
            </a>
        </div>
    </div>
    <!-- /ko -->
    <!-- ko ifnot: compareProducts().count -->
    <div class="cs-info-block__line | cs-t-text cs-t-text--look_light">
        <?php /* @escapeNotVerified */ echo __('You have no items to compare.') ?>
    </div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-sidebar]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
