<?php
/**
 * Template override:
 * - move print option inside table
 * - display additional information: star ratings, addtocart & addto wishlist components
 * - change remove link to button
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
$total = $block->getItems()->getSize();
$productNameInFooter = $block->getProductNameInFooter();
$taxInfoEnabled = $block->getTaxInfoEnabled();
$taxInfoLabel = $block->getTaxInfoLabel();
$csProductHelper = $this->helper('MageSuite\Frontend\Helper\Product');
?>
<?php if ($total) :?>
    <div class="cs-product-compare table-wrapper comparison">
        <table class="data table table-comparison" id="product-comparison"
               data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Compare Products')) ?></caption>
            <thead>
            <tr>
                <?php $index = 0; ?>
                <?php $helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
                <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $item) :?>
                    <?php if ($index++ == 0) :?>
                        <th scope="row" class="" rowspan="2">
                            <a href="#" class="action print hidden-print" title="<?= $block->escapeHtmlAttr(__('Print This Page')) ?>">
                                <?= $this->getLayout()
                                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                    ->setIconUrl('images/icons/compare/icon-print.svg')
                                    ->setCssClass('print-icon')
                                    ->setInlined(true)
                                    ->toHtml();
                                ?>
                                <span class="print-span"><?= $block->escapeHtml(__('Print This Page')) ?></span>
                            </a>
                        </th>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="cell product info">
                        <div class="cs-product-compare__product">
                            <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow()) :?>
                                <div class="secondary-addto-links" data-role="add-to-links">
                                    <ul class="cs-links-block-addto">
                                        <li class="cs-links-block-addto__item cs-links-block-addto__item--wishlist">
                                            <a href="#" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($item) ?>' class="cs-links-block-addto__link action towishlist" data-action="add-to-wishlist">
                                                <?= $block->getChildHtml('catalog.compare.list.icon.wishlist'); ?>
                                                <span class="cs-links-block-addto__link-label"><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            <?php endif; ?>
                            <?php if (!$item->isSaleable()) :?>
                                <div class="cs-product-compare__stock">
                                    <?php if ($item->getIsSalable()) :?>
                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                    <?php else :?>
                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                            <a class="product-item-photo" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                            </a>
                            <a class="product-item-name" href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= /* @noEscape */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= /* @noEscape */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                            </a>
                            <div class="cs-product-compare__ratings">
                                <?php
                                    $rating = $csProductHelper->getReviewSummary($item, true);
                                    $ratingData = $rating["data"];
                                    $votes = $rating["data"]["votes"];
                                    $allVotes = array_sum($votes);

                                    echo $this->getLayout()
                                        ->createBlock(\Magento\Framework\View\Element\Template::class)
                                        ->setMaxStars($ratingData['maxStars'])
                                        ->setActiveStars($ratingData['activeStars'])
                                        ->setReviewsCount($allVotes)
                                        ->setHideReviewsCount(false)
                                        ->setLabelIfNoReviews('0 ratings yet')
                                        ->setAdditionalClasses('cs-star-rating--summary')
                                        ->setTemplate('Magento_Review::rating-stars.phtml')
                                        ->toHtml();

                                ;?>
                            </div>
                            <div class="cs-product-compare__price">
                                <?= /* @noEscape */ $block->getProductPrice($item, '-compare-list-top') ?>
                            </div>
                            <?php if ($taxInfoEnabled): ?>
                                <div class="cs-product-compare__tax">
                                    <?= $taxInfoLabel; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            <tr>
                <?php foreach ($block->getItems() as $item) :?>
                    <td>
                        <div class="product-item-actions hidden-print">
                            <?php if ($item->isSaleable()) :?>
                                <div class="actions-primary">
                                    <?= $this->getLayout()
                                        ->getBlock('product.tile.addtocart')
                                        ->setFormClass('cs-addtocart cs-product-compare__addtocart-form')
                                        ->setTile(
                                            $this->getLayout()
                                                ->createBlock(\MageSuite\ProductTile\Block\Tile::class)
                                                ->setProductEntity($item)
                                        )
                                        ->toHtml()
                                    ;?>
                                </div>
                            <?php endif; ?>
                            <div class="actions-secondary">
                                <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                                <a href="#" data-post='<?= /* @noEscape */ $compareHelper->getPostDataRemove($item) ?>' class="cs-product-compare__remove action delete" title="<?= $block->escapeHtmlAttr(__('Remove Product')) ?>">
                                    <span class="cs-product-compare__remove-text"><?= $block->escapeHtml(__('Remove Product')) ?></span>
                                    <?= $block->getChildHtml('catalog.compare.list.icon.remove'); ?>
                                </a>
                            </div>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getAttributes() as $attribute) :?>
                <?php $index = 0; ?>
                <?php if ($block->hasAttributeValueForProducts($attribute)) :?>
                    <tr>
                        <?php foreach ($block->getItems() as $item) :?>
                            <?php $label = $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())); ?>
                            <?php if ($index++ == 0) :?>
                                <th scope="row" class="<?= strtolower(preg_replace('/\s+/', '-', $label)); ?>">
                                        <span class="attribute label">
                                            <?= $label; ?>
                                        </span>
                                </th>
                            <?php endif; ?>
                            <td>
                                <div class="attribute value">
                                    <?php switch ($attribute->getAttributeCode()) {
                                        case "price": ?>
                                            <?=
                                            /* @noEscape */ $block->getProductPrice(
                                                $item,
                                                '-compare-list-' . $attribute->getCode()
                                            )
                                            ?>
                                            <?php break;
                                        case "small_image": ?>
                                            <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                            <?php break;
                                        default :?>
                                            <?php if (is_string($block->getProductAttributeValue($item, $attribute))) :?>
                                                <?= /* @noEscape */ $helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                            <?php else : ?>
                                                <?=  $block->escapeHtml($helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode())) ?>
                                            <?php endif; ?>
                                            <?php break;
                                    } ?>
                                </div>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </tbody>
            <?php if ($productNameInFooter): ?>
            <tfoot>
                <tr>
                    <th>
                        <span><?= $block->escapeHtml(__('Product')) ?></span>
                    </th>
                    <?php foreach ($block->getItems() as $item): ?>
                        <td>
                            <?= /* @noEscape */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                        </td>
                    <?php endforeach; ?>
                </tr>
            </tfoot>
            <?php endif; ?>
        </table>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
    <?php endif; ?>
<?php else :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('You have no items to compare.')) ?></div></div>
<?php endif; ?>
