<?php
/**
 * Custom template with magesuite star rating component
 */
?>
<?php
    $maxStars = is_numeric($block->getMaxStars()) ? $block->getMaxStars() : 5;
    $activeStars = (float)$block->getActiveStars();
    $reviewsCount = $block->getReviewsCount() ?? 0;
    $reviewsLink = $block->getReviewsLink();
    $reviewsUrl = $block->getReviewsUrl() ?? false;
    $labelIfNoRatings = $block->getLabelIfNoReviews() ?? '';
    $showCount = !$block->getHideReviewsCount() && ($reviewsCount > 0  || $labelIfNoRatings);
    $useCssStars = $block->getVar('star-rating/use-css-mask-for-stars', 'Magento_Review');
?>

<?php if ($activeStars || $labelIfNoRatings): ?>
    <div class="cs-star-rating <?= $block->getAdditionalClasses(); ?>">
        <?php if ($activeStars): ?>
            <div class="cs-star-rating__stars" role="img"
                 aria-label="<?= $block->escapeHtmlAttr(__('Rated %1 out of %2 stars', $activeStars, $maxStars)) ?>">
                <?php
                    $iconClass = 'cs-star-rating__star';

                    for ($starIndex = 0; $starIndex < $maxStars; $starIndex++) {

                        $iconStatus = '';

                        if (floor($activeStars) > $starIndex) {

                            if (!isset($ratingStarIconActive)) {
                                $iconStatusActive = ' ' . $iconClass . '--active';
                                $ratingStarIconActive =
                                    $useCssStars
                                        ? '<i class="' . $iconClass . $iconStatusActive . '" aria-hidden="true"></i>'
                                        : $this->getLayout()
                                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                        ->setIconUrl('images/icons/reviews/star.svg')
                                        ->setCssClass($iconClass . $iconStatusActive)
                                        ->setInlined(true)
                                        ->toHtml();
                            }

                            echo $ratingStarIconActive;
                        } else if ($activeStars > $starIndex) {

                            if (!isset($ratingStarIconHalfActive)) {
                                $iconStatusHalfActive = ' ' . $iconClass . '--half-active';
                                $ratingStarIconHalfActive =
                                    $useCssStars
                                        ? '<i class="' . $iconClass . $iconStatusHalfActive . '" aria-hidden="true"></i>'
                                        : $this->getLayout()
                                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                        ->setIconUrl('images/icons/reviews/star.svg')
                                        ->setCssClass($iconClass . $iconStatusHalfActive)
                                        ->setInlined(true)
                                        ->toHtml();
                            }

                            echo $ratingStarIconHalfActive;
                        } else {

                            if (!isset($ratingStarIconNotActive)) {
                                $ratingStarIconNotActive =
                                    $useCssStars
                                        ? '<i class="' . $iconClass . '" aria-hidden="true"></i>'
                                        : $this->getLayout()
                                        ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                        ->setIconUrl('images/icons/reviews/star.svg')
                                        ->setCssClass($iconClass)
                                        ->setInlined(true)
                                        ->toHtml();
                            }

                            echo $ratingStarIconNotActive;
                        }
                    }
                ?>
            </div>
            <?php if ($block->getShowNumericalScore()): ?>
                <span class="cs-star-rating__text"><?= $activeStars ?> / <?= $maxStars ?></span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($showCount): ?>
            <?php
                $reviewsCountMessage = $reviewsCount ? $reviewsCount .'<span class="cs-star-rating__text-annotation"> ' . ($reviewsCount == 1 ? __('review') : __('reviews')) . '</span>' : __($labelIfNoRatings);
            ?>
            <?php if ($reviewsLink): ?>
                <a class="cs-star-rating__link" href="<?= $reviewsUrl ? $reviewsUrl : '' ?>#reviews">
            <?php endif; ?>
                <span class="cs-star-rating__text <?= $reviewsCount ? 'cs-star-rating__text--count' : 'cs-star-rating__text--empty' ?>"><?= $reviewsCountMessage ?></span>
            <?php if ($reviewsLink): ?>
                </a>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
