<?php
    $maxStars = is_numeric($block->getMaxStars()) ? $block->getMaxStars() : 5;
    $activeStars = $block->getActiveStars();
    $reviewsCount = $block->getReviewsCount() ?? 0;
    $reviewsLink = $block->getReviewsLink();
    $reviewsUrl = $block->getReviewsUrl() ?? false;
    $labelIfNoRatings = $block->getLabelIfNoReviews() ?? '';
    $showCount = !$block->getHideReviewsCount() && ($reviewsCount > 0  || $labelIfNoRatings);
?>

<?php if ($activeStars || $labelIfNoRatings): ?>
    <div class="cs-star-rating <?= $block->getAdditionalClasses(); ?>">
        <?php if ($activeStars): ?>
            <div class="cs-star-rating__stars">
                <?php
                    $iconClass = 'cs-star-rating__star';

                    for ($starIndex = 0; $starIndex < $maxStars; $starIndex++) {

                        $iconStatus = '';
                        if ($activeStars > $starIndex) {
                            $iconStatus = ' ' . $iconClass . '--half-active';
                        }

                        if (floor($activeStars) > $starIndex) {
                            $iconStatus = ' ' . $iconClass . '--active';
                        }

                        echo( 
                            $this->getLayout()
                                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                ->setIconUrl('images/icons/reviews/star.svg')
                                ->setCssClass($iconClass . $iconStatus)
                                ->setAltText(__('star'))
                                ->setInlined(true)
                                ->toHtml()
                        ); 
                    }
                ?>
            </div>
            <?php if ($block->getShowNumericalScore()): ?>
                <span class="cs-star-rating__text"><?= $activeStars ?> / <?= $maxStars ?></span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($showCount): ?>
            <?php
                $reviewsCountMessage = $reviewsCount ? $reviewsCount .'<span class="cs-star-rating__text-annotation"> ' . ($reviewsCount == 1 ? __('review') : __('reviews')) . '</span>' : $labelIfNoRatings;
            ?>
            <?php if ($reviewsLink): ?>
                <a class="cs-star-rating__link" href="<?= $reviewsUrl ? $reviewsUrl : '' ?>#reviews">
            <?php endif; ?>
                <span class="cs-star-rating__text <?= $reviewsCount ? 'cs-star-rating__text--count' : 'cs-star-rating__text--empty' ?>"><?= $reviewsCountMessage ?></span>
            <?php if ($reviewsLink): ?>
                </a>
            <?php endif; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>