<?php
/**
 * Template overridden in order to:
 * - add no reviews message
 * - add form and summary
 * - add possibility of rendering first page of reviews server side
 *
 * Aligned with Magento 2.4.9 in 05/2026
 */

/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Review\Block\Product\Review $block */
$reviewsCount = $block->getCollectionSize();
/* MGS edit start */
$isRenderedFirstPageServerSide = $block->getVar('reviews_render_first_page_server_side/enabled', 'Magento_Review')
/* MGS edit end */
?>

<?= $block->getChildHtml('reviews_summary') ?>

<?php if ($reviewsCount === 0): ?>
    <div class="cs-product-details__no-reviews-message">
        <?= $escaper->escapeHtml(__('Be the first to review this product')) ?>
    </div>
<?php endif; ?>
<!--
Both role and class attributes values of #product-review-container are needed
for AJAX script to work because we no longer have tabs in MageSuite.
-->
<div id="product-review-container" data-role="product-review" role="tab" class="cs-reviews active">
    <?php /* MGS edit start */ ?>
    <?php if ($isRenderedFirstPageServerSide): ?>
        <?= /* @noEscape */ $block->getChildHtml('reviews_list') ?>
    <?php endif; ?>
    <?php /* MGS edit end */ ?>
</div>
<?php echo $block->getChildHtml('review_form'); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $escaper->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#product-review-container",
                "isRenderedFirstPageServerSide": <?= $escaper->escapeJs(json_encode($isRenderedFirstPageServerSide)) ?>
            }
        }
    }
</script>
