<?php
// @codingStandardsIgnoreFile
/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */ 
?>
<?php
$item = $block->getItem();
$order = $block->getItem()->getOrderItem()->getOrder()
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $item->getId() ?>">
    <td class="cs-table__col | name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <span class="cs-t-text cs-t-text--look_attention | product-item-name"><?php echo $block->escapeHtml($item->getName()) ?></span>
        <?php if ($options = $block->getItemOptions()): ?>
        <div class="cs-cart-item__options">

        <?php foreach ($options as $option) : ?>
                <dl class="cs-cart-item__options-group | item-options">
                    <dt class="cs-cart-item__options-label"><?php echo $block->escapeHtml($option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dd<?php if (isset($formatedOptionValue['full_view'])): ?> class="cs-cart-item__options-value | tooltip wrapper | tooltip wrapper"<?php endif; ?>>
                            <?php /* @escapeNotVerified */ echo $formatedOptionValue['value'] ?>
                            <?php if (isset($formatedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt class="cs-cart-item__options-label">
                                            <?php echo $block->escapeHtml($option['label']) ?>
                                        </dt>
                                        <dd class="cs-cart-item__options-value">
                                            <?php /* @escapeNotVerified */ echo $formatedOptionValue['full_view'] ?>
                                        </dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd class="cs-cart-item__options-value | tooltip wrapper">
                            <?php echo $block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value'])) ?>
                        </dd>
                    <?php endif; ?>
                </dl>
                <?php endforeach; ?>
           </div>
        <?php endif; ?>

        <?php /* downloadable */ ?>
        <?php if ($links = $block->getLinks()): ?>
            <dl class="item options">
                <dt class="cs-cart-item__options-label"><?php /* @escapeNotVerified */ echo $block->getLinksTitle() ?></dt>
                <?php foreach ($links->getPurchasedItems() as $link): ?>
                    <dd class="cs-cart-item__options-value"><?php echo $block->escapeHtml($link->getLinkTitle()); ?></dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php /* EOF downloadable */ ?>

        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="cs-table__col | sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
        <?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="cs-table__col | price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="cs-table__col | qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <?php /* @escapeNotVerified */ echo $item->getQty()*1 ?>
    </td>
    <td class="cs-table__col | subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
    <td class="cs-table__col | discount" data-th="<?php echo $block->escapeHtml(__('Discount Amount')); ?>">
        <?php /* @escapeNotVerified */ echo $order->formatPrice(-$item->getDiscountAmount()) ?>
    </td>
    <td class="cs-table__col | total" data-th="<?php echo $block->escapeHtml(__('Row Total')); ?>">
        <?php echo $block->getItemRowTotalAfterDiscountHtml(); ?>
    </td>
</tr>
