<?php
/**
 * Template has been overwritten in order to:
 * - add magesuite classes
 * - remove title
 * - reorganize elements
 * - add hotspots
 * - add "autocomplete" attribute for newsletter email input (line: 34)
 * Aligned with Magento 2.4.9 in 05/2026
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
/** @var \Magento\Framework\View\Element\ButtonLockManager|null $buttonLockManager */
$buttonLockManager = $block->getData('button_lock_manager');
$label = $block->getInputLabel();
$placeholder = $block->getInputPlaceholder();
$buttonLabel = $block->getButtonLabel();
/** @var $escaper \Magento\Framework\Escaper */
?>
<div class="block newsletter cs-newsletter">
    <form class="form subscribe cs-newsletter__form"
        novalidate
        action="<?= $escaper->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
        <div class="cs-newsletter__form-wrapper">
            <div class="field newsletter cs-newsletter__field">
                <?php if (!empty($label)): ?>
                    <label class="label cs-newsletter__label" for="newsletter">
                        <span><?= $escaper->escapeHtml($label) ?></span>
                    </label>
                <?php endif; ?>
                <div class="cs-newsletter__control control">
                    <label for="newsletter" class="cs-newsletter__label"><?=__('Email address') ?></label>
                    <input name="email" autocomplete="email" type="email" id="newsletter" class="input-text cs-newsletter__input"
                        <?php if (!empty($placeholder)): ?> placeholder="<?= $escaper->escapeHtmlAttr($placeholder) ?>" <?php endif; ?> value="<?= $escaper->escapeHtmlAttr($block->getInputValue()); ?>" data-validate="{required:true, 'validate-email':true}"
                    />
                </div>
            </div>
            <div class="actions cs-newsletter__actions">
                <button class="action subscribe primary cs-newsletter__button"
                        title="<?= !empty($buttonLabel) ? $escaper->escapeHtmlAttr($buttonLabel) : __('Subscribe') ?>"
                        type="submit"
                        <?php if ($buttonLockManager?->isDisabled('newsletter_form_submit')): ?>
                        disabled="disabled"
                    <?php endif; ?>>
                    <?= $block->getChildHtml('newsletter.subscribe.button.icon') ?>
                    <?php if (!empty($buttonLabel)): ?>
                        <span class="cs-newsletter__button-label<?= $block->getHideButtonLabel() ? ' cs-visually-hidden' : '' ?>"><?= $escaper->escapeHtml($buttonLabel) ?></span>
                    <?php endif; ?>
                </button>
            </div>
        </div>
        <?= $block->getChildHtml('newsletter.subscribe.hotspot.form_end'); ?>
    </form>
    <?= $block->getChildHtml('newsletter.subscribe.hotspot.form_below'); ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
