<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="newsletter">
    <div class="cs-footer__column-title"><strong>Newsletter</strong></div>
    <div class="cs-footer__list">
        <form class="cs-form | subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="cs-form__field | cs-input | newsletter">
                <div class="cs-input__control">
                    <input name="email" type="email" id="newsletter" class="cs-input__input"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Email address') ?>"
                           data-validate="{required:true, 'validate-email':true}"/>

                    <div class="cs-input__button">
                        <button class="cs-button cs-button--look_default cs-button--look_on-input" type="submit">
                            <svg class="cs-button__icon cs-button__icon--center cs-button__icon--plus">
                                <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#plus"></use>
                            </svg>
                            <span class="cs-visually-hidden"><?=__('Subscribe');?></span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
