<?php
$html = trim($block->getChildHtml());
?>
<?php if ($html): ?>
<div class="cs-offcanvas-filters">
    <div class="cs-offcanvas-filters__overlay overlay"></div>
    <div class="cs-offcanvas-filters__drawer drawer">
        <button class="cs-offcanvas-filters__close" title="<?= __('Close') ?>">
            <?=  $this->getLayout()
                    ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                    ->setIconUrl('images/icons/close.svg')
                    ->setCssClass('cs-offcanvas-filters__close-icon')
                    ->setAltText(__('Close'))
                    ->setInlined(true)
                    ->setLazyLoaded(true)
                    ->toHtml(); 
            ?>
        </button>
        <div class="cs-offcanvas-filters__headline"><?= __('Filters') ?></div>
        <?= $html ?>
    </div>
</div>
<?php endif; ?>

