<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
//"swatchRenderer": {
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<div class="cs-swatches cs-swatches--pdp" data-role="swatch-options"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "js/swatches-extended": {
                "jsonConfig": <?php /* @escapeNotVerified */ echo $swatchOptions = $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?php /* @escapeNotVerified */
                    echo $swatchOptions = $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>",
                "onlyMainImg": <?php /* @escapeNotVerified */ echo $block->getVar('change_only_base_image',
                    'Magento_Swatches') ?: 'false'; ?>,
                "classes": {
                    "attributeClass": "cs-swatches__attribute",
                    "attributeLabelClass": "cs-swatches__attribute-label",
                    "attributeSelectedOptionLabelClass": "cs-swatches__attribute-selected",
                    "attributeOptionsWrapper": "cs-swatches__list",
                    "attributeInput": "cs-swatches__input",
                    "optionClass": "cs-swatches__swatch",
                    "selectClass": "cs-swatches__select | swatch-select",
                    "moreButton": "cs-swatches__more",
                    "loader": "cs-swatches__loader | swatch-option-loading"
                }
            }
        }
    }
</script>

<?php // Remove this snippet after upgrade to version 2.2. According to github discussion this is going to be fixed by Magento core team ?>
<script>
    require([
        "jquery"
    ], function($){
        $(document).ready(function () {
            'use strict';
            var validationErrorMoved = false;

            $( '#product-addtocart-button' ).on( 'click', function() {
                if ( !validationErrorMoved ) {
                    $( '.cs-swatches__attribute' ).each(function() {
                        var attrId = $( this ).attr( 'attribute-id' );
                        var $validationElement = $( 'input[name="super_attribute[' + attrId + ']"]' );
                        $validationElement.insertAfter( this );
                    } );
                    validationErrorMoved = true;
                }
            });
        });
    });
</script>
