<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
//"swatchRenderer": {
?>
<?php /** @var $block \Magento\Swatches\Block\Product\Renderer\Configurable */ ?>
<div class="cs-swatches cs-swatches--pdp" data-role="swatch-options"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": <?php /* @escapeNotVerified */ echo $swatchOptions = $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?php /* @escapeNotVerified */
                    echo $swatchOptions = $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>",
                "onlyMainImg": <?php /* @escapeNotVerified */ echo $block->getVar('change_only_base_image',
                    'Magento_Swatches') ?: 'false'; ?>,
                "classes": {
                    "attributeClass": "cs-swatches__attribute",
                    "attributeLabelClass": "cs-swatches__attribute-label",
                    "attributeSelectedOptionLabelClass": "cs-swatches__attribute-selected",
                    "attributeOptionsWrapper": "cs-swatches__list",
                    "attributeInput": "cs-swatches__input",
                    "optionClass": "cs-swatches__swatch",
                    "selectClass": "cs-swatches__select",
                    "moreButton": "cs-swatches__more",
                    "loader": "cs-swatches__loader"
                }
            }
        }
    }
</script>
