<div class="cs-footer__columns">
    <div class="cs-footer__column cs-footer__column--first | cs-hide-mobile">
        <div class="cs-footer__column-title cs-footer__column-title--image">
            <img
                class="lazyload"
                src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
                data-src="<?= $this->getViewFileUrl('images/creativeshop-logo-reverse.png'); ?>"
                alt="<?php /* @escapeNotVerified */ echo __('Creativeshop logo') ?>"
                width="135" height="26"
            />
            <h2 class="cs-visually-hidden">
                <?php /* @escapeNotVerified */ echo __('Creativeshop footer') ?>
            </h2>
        </div>
    </div>
    <div class="cs-footer__column | cs-collapse cs-collapse--only-mobile">
        <h3 class="cs-footer__column-title | cs-collapse__trigger">Products</h3>
        <ul class="cs-footer__list | cs-footer-list | cs-collapse__content">
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Tops</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Shirts</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Equipment</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Athletic Wear</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Shoes</a>
            </li>
        </ul>
    </div>
    <div class="cs-footer__column | cs-collapse cs-collapse--only-mobile">
        <h3 class="cs-footer__column-title  | cs-collapse__trigger">Information</h3>
        <ul class="cs-footer__list | cs-footer-list | cs-collapse__content">
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">About us</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Customer Service</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Search Terms</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Privacy</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Contact us</a>
            </li>
        </ul>
    </div>
    <div class="cs-footer__column | cs-collapse cs-collapse--only-mobile">
        <h3 class="cs-footer__column-title | cs-collapse__trigger">About demo</h3>
        <ul class="cs-footer__list | cs-footer-list | cs-collapse__content">
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Cookie policy</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">About Creativestyle</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">M2C Account</a>
            </li>
            <li class="cs-footer-list__item">
                <a class="cs-footer-list__link" href="#">Account</a>
            </li>
        </ul>
    </div>

</div>
