<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
    $product = $block->getProduct();
    $buttonTitle = __('Add to Cart');
?>

<?php if ($product->isSaleable()): ?>
    <div class="cs-box-addtocart">
        <div class="cs-box-addtocart__fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="cs-box-addtocart__qty-wrapper">
                    <label class="cs-label | cs-box-addtocart__label" for="qty"><?php /* @escapeNotVerified */ echo __('Qty') ?></label>

                    <div class="cs-box-addtocart__qty-increment">
                        <?php $productDefaultQty = $block->getProductDefaultQty() * 1; ?>
                        <?=$this->getLayout()->createBlock(
                            'Creativestyle\FrontendExtension\Block\Twig',
                            'add-to-cart-pdp', [
                                'data' => [
                                    "namespace" => 'cs-',
                                    "minValue" => /* @escapeNotVerified */ $productDefaultQty,
                                    "initialValue" => /* @escapeNotVerified */ $productDefaultQty,
                                    "maxLength" => 12,
                                    "size" => 2,
                                    "name" => 'qty',
                                    "inputParams" => 'data-validate="'.$block->escapeHtml(json_encode($block->getQuantityValidators())).'"',
                                    "icons" => [
                                        "increment" => '#plus',
                                        "decrement" => '#minus'
                                    ]
                                ]
                            ]
                        )->setTemplate( "qty-increment/qty-increment.twig" )->toHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="cs-box-addtocart__actions">
                <button
                    type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="cs-button cs-button--type_wide cs-button--type_cart"
                    id="product-addtocart-button"
                >
                    <svg class="cs-button__icon cs-button__icon--cart">
                        <use xlink:href="#cart"></use>
                    </svg>
                    <span class="cs-button__span"><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>

                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>

<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "catalogAddToCart": {
                    "bindSubmit": false
                }
            }
        }
    </script>
<?php endif; ?>
