<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>

<?php if ($_additional = $block->getAdditionalData()): ?>
<div class="cs-collapsible-text js-collapsible-text" data-height="100" data-content=".js-collapsible-text-content" data-trigger=".js-collapsible-text-trigger">
    <div class="cs-collapsible-text__content cs-collapsible-text__content--contrast js-collapsible-text-content">
        <div class="cs-attributes-list">
            <dl class="cs-attributes-list__list cs-attributes-list__list--columns" id="product-attribute-specs-table">
                <?php foreach ($_additional as $_data): ?>
                    <dt class="cs-attributes-list__item-label"><?php echo $block->escapeHtml(__($_data['label'])) ?>:
                    </dt>
                    <dd class="cs-attributes-list__item">
                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        </div>
    </div>

    <button class="cs-button cs-button--look_light cs-button--size_300 | cs-collapsible-text__trigger js-collapsible-text-trigger" data-show-less-text="<?php /* @escapeNotVerified */ echo __('Less information'); ?>" data-show-more-text="<?php /* @escapeNotVerified */ echo __('More information'); ?>">
         <span class="cs-button__span"><?php /* @escapeNotVerified */ echo __('More information'); ?></span>
        <svg class="cs-button__icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </button>
</div>
<?php endif;?>
