<?php
$items = Array(0, 1);
$showNew = $items[array_rand($items)];
?>
<div class="cs-product-gallery__badge-wrapper">
    <?php if ($showNew): ?>

        <span class="cs-badge cs-badge--new cs-badge--label-big cs-badge--cut">
            <span class="cs-badge__span cs-badge__span--no-space"><?= __('New'); ?></span>
        </span>

    <?php endif; ?>

    <?php if ($showNew == 0 && $items[array_rand($items)]): ?>
        <div class="cs-multiple-badges">
            <span class="cs-badge cs-badge--attention cs-badge--label-big cs-badge--cut">
                <span class="cs-badge__span cs-badge__span--no-space"><?= __('Sale'); ?></span>
            </span>
            <span class="cs-badge cs-badge--label-big">
                <span class="cs-badge__span"><?= __('-30%'); ?></span>
            </span>
        </div>

    <?php endif; ?>
</div>


