<?php 
/** 
* Custom template for usps
*/ 
?>
<li class="cs-buybox__usp <?= $block->getAdditionalCssClasses() ?>">
    <?= $block->getChildHtml(''); ?>
    <?php if($block->getLink()): ?>
        <a href="<?= $block->getLink() ?>" class="cs-buybox__usp-label"><?= $block->getLabel() ?></a>
    <?php else: ?>
        <span class="cs-buybox__usp-label"><?= $block->getLabel() ?></span>
    <?php endif ?>
</li>
