<div class="cs-container__inner">
    <?php echo $this->getLayout()->createBlock(
        'Creativestyle\FrontendExtension\Block\Twig', 'daily-deal', [
            'data' => [
                "namespace" => 'cs-',
                "header" => [
                    "show" => true,
                    "title" => __('Limited time offer')
                ],
                "items" => [
                    "textBefore" => '',
                    "textAfter" => __('items left'),
                    "amount" => 15
                ],
                "deal" => [
                    "start" => 1520594598,
                    "end" => 1535587200
                ],
                "countdown" => [
                    "icon" => "#clock"
                ]
            ]
        ]
    )->setTemplate("dailydeal/dailydeal.twig")->toHtml(); ?>
</div>
