<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):
    $layout = $block->getLayout();
?>
    <div class="cs-product-description__nav">
        <ul class="cs-list cs-list--menu cs-list--menu-dark | cs-pdp-nav">
            <?php
            foreach ($detailedInfoGroup as $name):
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                $html = $layout->renderElement($name);
                $id = '#pdp-' . preg_replace("/[\.]/", "-", $alias);
                if (!trim($html)) {
                    continue;
                }
                if($html):
                    ?>
                    <li class="cs-list__item cs-list__item--menu-dark">
                        <a class="cs-list__link" href="<?=$id ?>">
                            <?php /* @escapeNotVerified */ echo __($label) ?>
                        </a>
                    </li>
                    <?php
                endif;
            endforeach;
            ?>
        </ul>
    </div>

    <?php foreach ($detailedInfoGroup as $name):
    $html = $layout->renderElement($name);
    if (!trim($html)) {
        continue;
    }
    $alias = $layout->getElementAlias($name);
    $id = 'pdp-' . preg_replace("/[\.]/", "-", $alias);
    $label = $block->getChildData($alias, 'title');
    $itemExtraClasses = '';
    if ($name == 'reviews.tab') {
        $itemExtraClasses = $itemExtraClasses . ' cs-product-description__item--bottom';
    }
    elseif ($name == 'product.attributes') {
        $itemExtraClasses = $itemExtraClasses . ' cs-product-description__item--penultimate';
    }

    if ($html):
        ?>

        <div
            class="cs-product-description__item | cs-collapse cs-collapse--only-mobile<?php echo $itemExtraClasses ?>"
            id="<?php echo $id ?>">
            <?php if ($name == 'reviews.tab'): ?>
            <div class="cs-product-description__item--bottom_inner">
                <div class="cs-product-description__item--bottom_column">
                    <?php endif;?>
                    <h2 class="cs-product-description__headline | cs-t-headline cs-t-headline--size_2 | cs-collapse__trigger">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </h2>
                    <div class="cs-collapse__content | cs-cms-block">
                        <div class="cs-product-description__content">
                            <?php /* @escapeNotVerified */ echo $html; ?>
                        </div>
                    </div>
                    <?php if ($name == 'reviews.tab'): ?>
                </div>
            </div>
        <?php endif;?>
        </div>
    <?php endif;
endforeach;
endif; ?>
<script>
    require([
        'jquery'
    ], function($) {

        $( '.cs-pdp-nav .cs-list__item,  .cs-product-sale-block__no-review' ).on( 'click', function( e ) {
            e.preventDefault();
            var href = $( this ).find( 'a' ).attr( 'href' );
            var target = href.substring( 0, 1 ) == '#' ? href : href.substring( href.indexOf( '#' ) );
            if ( $( window ).width() < 1024 ) {
                $( 'html, body' ).animate( {
                    scrollTop: $( target ).offset().top - $( '.cs-header__content' )
                        .height()
                }, 350 );
            } else {
                $( 'html, body' ).animate( {
                    scrollTop: $( target ).offset().top
                }, 350 );
            }

        });
    } );
</script>

