<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):
    $layout = $block->getLayout();
    $newPriority = array();
    foreach ($detailedInfoGroup as $name) {
        $alias = $layout->getElementAlias($name);
        $priority = $block->getChildData($alias,'priority') ? $block->getChildData($alias,'priority') : '10';
        array_push($newPriority, array($name, $priority));
    }
    usort($newPriority, function($a, $b) {
        return $a['1'] <=> $b['1'];
    });
?>
    <div class="cs-product-description__nav">
        <ul class="cs-list cs-list--menu cs-list--menu-dark | cs-pdp-nav">
            <?php
            foreach ($newPriority as $name):
                $name = $name[0];
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                $html = $layout->renderElement($name);
                $id = '#pdp-' . preg_replace("/[\.]/", "-", $alias);
                if (!trim($html)) {
                    continue;
                }
                if($html):
            ?>
                <li class="cs-list__item cs-list__item--menu-dark">
                    <a class="cs-list__link" href="<?=$id ?>">
                        <?php /* @escapeNotVerified */ echo __($label) ?>
                    </a>
                </li>
            <?php
                endif;
            endforeach;
            ?>
        </ul>
    </div>
    <?php foreach ($newPriority as $name):
        $name = $name[0];
        $html = $layout->renderElement($name);
        if (!trim($html)) {
            continue;
        }
        $alias = $layout->getElementAlias($name);
        $id = 'pdp-' . preg_replace("/[\.]/", "-", $alias);
        $label = $block->getChildData($alias, 'title');
        $itemExtraClasses = '';
        if ($name == 'reviews.tab') {
            $itemExtraClasses += ' cs-product-description__item--bottom';
        }
        elseif ($name == 'product.attributes') {
            $itemExtraClasses += ' cs-product-description__item--penultimate';
        }

        if ($html):
    ?>
            <div
                class="cs-product-description__item | cs-collapse cs-collapse--only-mobile<?php echo $itemExtraClasses ?>"
                id="<?php echo $id ?>">
                <?php if ($name == 'reviews.tab'): ?>
                    <div class="cs-product-description__item--bottom__inner">
                    <div class="cs-product-description__item--bottom__column">
                <?php endif;?>
                <h2 class="cs-product-description__headline | cs-t-headline cs-t-headline--size_2 | cs-collapse__trigger">
                    <?php /* @escapeNotVerified */ echo $label; ?>
                </h2>
                <div class="cs-collapse__content | cs-cms-block">
                    <div class="cs-product-description__content">
                        <?php /* @escapeNotVerified */ echo $html; ?>
                    </div>
                </div>
                <?php if ($name == 'reviews.tab'): ?>
                    </div>
                    </div>
                <?php endif;?>
            </div>
        <?php endif;
    endforeach;
endif; ?>
