<?php
// @codingStandardsIgnoreFile

// Override to display main image before gallery is loaded

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<?php
    $galleryImagesJson = $block->getGalleryImagesJson();
    // Extracting main image to show before JS gallery loads
    $galleryImages = json_decode($galleryImagesJson);
    $mainImageUrl  = '';
    $mainImageAlt  = '';

    for ($imageIndex = 0; $imageIndex < count($galleryImages); $imageIndex++) {
        $galleryImage = $galleryImages[$imageIndex];
        if ($galleryImage->isMain) {
            $mainImageUrl = $galleryImage->img;
            $mainImageAlt = $galleryImage->caption;
            break;
        }
    }

    // Fix for jumping content
    $imageWidth = $block->getImageAttribute('product_page_image_medium', 'width');
    $imageHeight = $block->getImageAttribute('product_page_image_medium', 'height');
    $loaderPadding = ($imageHeight / $imageWidth) * 100 . '%';

    // Webp support
    $imageTypeHelper = $this->helper('MageSuite\ThemeHelpers\Helper\ImageType');
    $isWebpSupported = $imageTypeHelper->supportsWebp($mainImageUrl);
    $imageMimeType = $imageTypeHelper->getMimeType($mainImageUrl);
?>
<div class="gallery-placeholder _block-content-loading cs-product-gallery" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask cs-product-gallery__loading-mask">
        <div class="loader cs-product-gallery__loader" style="padding-bottom: <?= $loaderPadding ?>">
            <picture class="cs-product-gallery__placeholder-image">
                <?php if ($isWebpSupported): ?>
                    <source
                        type="image/webp"
                        srcset="<?= $mainImageUrl ?>.webp"
                        alt="<?= $mainImageAlt ?>"
                    >
                <?php endif; ?>
                <source
                    type="<?= $imageMimeType ?>"
                    src="<?= $mainImageUrl ?>"
                    alt="<?= $mainImageAlt ?>"
                >
                <img
                    type="<?= $imageMimeType ?>"
                    src="<?= $mainImageUrl ?>"
                    alt="<?= $mainImageAlt ?>"
                >
            </picture>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/nav") ?>",
                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/loop") ? 'true' : 'false' ?>,
                    "keyboard": <?= /* @escapeNotVerified */ $block->getVar("gallery/keyboard") ? 'true' : 'false' ?>,
                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/arrows") ? 'true' : 'false' ?>,
                    "allowfullscreen": <?= /* @escapeNotVerified */ $block->getVar("gallery/allowfullscreen") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ? 'true' : 'false' ?>,
                    "width": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width') ?>",
                    "thumbwidth": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_small', 'width') ?>",
                    <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                        "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                        "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height')
                        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/transition/effect") ?>",
                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",
                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navdir") ?>",
                    "maxheight": "<?= /* @escapeNotVerified */ $block->getVar("gallery/maxheight") ?>"
                },
                "fullscreen": {
                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/nav") ?>",
                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/loop") ? 'true' : 'false' ?>,
                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navdir") ?>",
                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navtype") ?>",
                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/arrows") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/caption") ? 'true' : 'false' ?>,
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/effect") ?>"
                },
                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
