<?php
$layout = $block->getLayout();
$one_column = $block->getData('one_column');
$column_left = $block->getGroupChildNames('column_left', 'getChildHtml') ?? [];
$column_right = $block->getGroupChildNames('column_right', 'getChildHtml') ?? [];
?>
<?php if (!empty($column_left) || !empty($column_right)): ?>
<div class="cs-product-details-main<?php if ($one_column): ?> cs-product-details-main--column<?php endif; ?>">

    <?php if (!empty($column_left)): ?>
    <?php if (!$one_column): ?><div class="cs-product-details-main__column cs-product-details-main__column--left"><?php endif; ?>
        <?php foreach ($column_left as $blockName):
            $html = trim($layout->renderElement($blockName));
            if (empty($html)) {
                continue;
            }
            $alias = $layout->getElementAlias($blockName);
            $label = __($block->getChildData($alias, 'title'))->render();
            $id = str_replace('.', '-', $alias);
            $isCollapsible = $block->getChildData($alias, 'is_collapsible') ?? false;
            $collapseOptions = $block->getChildData($alias, 'collapsible_widget_options');
            $collapseOptionsJson = empty($collapseOptions) ? '{}' : json_encode($collapseOptions);
            $additionalCssClasses = $block->getChildData($alias, 'additional_css_classes');
        ?>
            <section
                class="cs-product-details-main__item cs-product-details-main__item--<?= $alias; ?> <?= $additionalCssClasses ?>"
                id="<?= $id; ?>"
                <?= $isCollapsible ? 'data-mage-init=\'{"collapsible": ' . $collapseOptionsJson . '}\'' : '' ?>
            >
                <?php if (!empty($label)): ?>
                    <?php var_dump($label); ?>
                    <header class="cs-product-details-main__headline" data-role="title">
                        <h3 class="cs-product-details-main__headline-title">
                            <?= /* @escapeNotVerified */ $label; ?>
                        </h3>
                    </header>
                <?php endif; ?>
                <div class="cs-product-details-main__content" data-role="content">
                    <?= /* @escapeNotVerified */ $html; ?>
                </div>
            </section>
        <?php endforeach; ?>
    <?php if (!$one_column): ?></div><?php endif; ?>
    <?php endif; ?>

    <?php if (!empty($column_right)): ?>
    <?php if (!$one_column): ?><div class="cs-product-details-main__column cs-product-details-main__column--right"><?php endif; ?>
        <?php foreach ($column_right as $blockName):
            $html = trim($layout->renderElement($blockName));
            if (empty($html)) {
                continue;
            }
            $alias = $layout->getElementAlias($blockName);
            $label = __($block->getChildData($alias, 'title'))->render();
            $id = str_replace('.', '-', $alias);
            $isCollapsible = $block->getChildData($alias, 'is_collapsible') ?? false;
            $collapseOptions = $block->getChildData($alias, 'collapsible_widget_options');
            $collapseOptionsJson = empty($collapseOptions) ? '{}' : json_encode($collapseOptions);
            $additionalCssClasses = $block->getChildData($alias, 'additional_css_classes');
        ?>
            <section
                class="cs-product-details-main__item cs-product-details-main__item--<?= $alias; ?> <?= $additionalCssClasses ?>"
                id="<?= $id; ?>"
                <?= $isCollapsible ? 'data-mage-init=\'{"collapsible": ' . $collapseOptionsJson . '}\'' : '' ?>
            >
                <?php if (!empty($label)): ?>
                    <header class="cs-product-details-main__headline" data-role="title">
                        <h3 class="cs-product-details-main__headline-title">
                            <?= /* @escapeNotVerified */ $label; ?>
                        </h3>
                    </header>
                <?php endif; ?>
                <div class="cs-product-details-main__content" data-role="content">
                    <?= /* @escapeNotVerified */ $html; ?>
                </div>
            </section>
        <?php endforeach; ?>
    <?php if (!$one_column): ?></div><?php endif; ?>
    <?php endif; ?>

</div>
<?php endif; ?>