 <?php
 /**
  * Additional price block for products with dailydeal (countdown only).
  *
  * @see \MageSuite|DailyDeal|Block|Product
  */
 ?>
<?php
$product = $block->getProduct();
$dailyDealHelper = $this->helper('MageSuite\DailyDeal\Helper\OfferData');
$dailyDealData = $dailyDealHelper->prepareOfferData($product);
$priceHtmlDeal = $dailyDealData && $dailyDealData['deal'] ? $dailyDealData['oldPriceHtmlOnPdp'] : '';

if($dailyDealData && $dailyDealData['deal'] && $dailyDealData['displayType'] !== 'none') {
    echo '<div class="price-box price-final_price_without_daily_deal" style="display: none;">'.$priceHtmlDeal.'</div>';
}
?>
