<div class="cs-special-attributes">
    <div class="cs-special-attributes__group">
        <svg class="cs-special-attributes__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#available"></use>
        </svg>
        <span class="cs-special-attributes__text"> <?php /* @escapeNotVerified */
            echo __('Immediately available'); ?></span>
    </div>
    <div class="cs-special-attributes__group">

        <svg class="cs-special-attributes__icon cs-special-attributes__icon--package">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#packaging"></use>
        </svg>

        <span class="cs-special-attributes__text"> <?php /* @escapeNotVerified */
            echo __('Discreet packaging'); ?></span>
    </div>
    <div class="cs-special-attributes__group">

        <svg class="cs-special-attributes__icon">
            <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#shipping"></use>
        </svg>
        <span class="cs-special-attributes__text"> <?php /* @escapeNotVerified */
            echo __('Free shipping'); ?></span>
    </div>
</div>

