<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form action="" method="post" id="form-validate" class="cs-form | confirmation" data-mage-init='{"validation":{}}'>
    <fieldset class="cs-form-fieldset cs-form__fieldset--level_1" data-hasrequired="<?php /* @escapeNotVerified */
    echo __('* Required Fields') ?>">
        <p class="cs-t-text cs-t-text--type_wide"><?php /* @escapeNotVerified */
            echo __('Please enter your email below and we will send you the confirmation link.') ?></p>

        <div class="cs-form__field | cs-input | required">
            <label for="email_address" class="cs-input__label"><?php /* @escapeNotVerified */
                echo __('Email') ?></label>

            <div class="cs-input__control">
                <input type="email" name="email" id="email_address" class="cs-input__input" value="<?php echo $block->escapeHtml($block->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
    </fieldset>
    <div class="cs-form__buttons">
        <button type="submit" class="cs-button cs-button--type_long cs-button--type_mobile-wide cs-button--look_default">
            <?php /* @escapeNotVerified */
            echo __('Send confirmation link') ?>
            <svg class="cs-button__icon">
                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
            </svg>
        </button>

        <a href="<?php /* @escapeNotVerified */
        echo $block->getLoginUrl() ?>" class="cs-link">
            <?php /* @escapeNotVerified */
            echo __('Back to Sign In') ?>
        </a>
    </div>
</form>
