<?php
// @codingStandardsIgnoreFile

?>
<form
    class="cs-form | password forget"
    action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
    method="post"
    id="form-validate"
    data-mage-init='{"validation":{}}'
>
    <fieldset
        class="cs-form-fieldset cs-form__fieldset--level_1"
        data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
    >
        <p class="cs-t-text cs-t-text--type_wide">
            <?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?>
        </p>
        <div class="cs-form__field | required">
            <label for="email_address" class="cs-input__label">
                <span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
            </label>
            <div class="control">
                <input
                    type="email"
                    name="email"
                    alt="email"
                    id="email_address"
                    class="cs-input__input"
                    value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>"
                    data-validate="{required:true, 'validate-email':true}"
                >
            </div>
        </div>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
    </fieldset>
    <div class="cs-form__buttons">
        <button type="submit" class="cs-button cs-button--type_long cs-button--type_wide-mobile cs-button--look_default">
           <span class="cs-button__span"> <?php /* @escapeNotVerified */ echo __('Reset My Password') ?></span>
            <svg class="cs-button__icon">
                <use xlink:href="#arrow_next"></use>
            </svg>
        </button>
    </div>
</form>
