<?php
// @codingStandardsIgnoreFile
?>
<?php echo $block->getChildHtml('form_before')?>
<div class="cs-dashboard__block">
    <form
        class="cs-form | form form-newsletter-manage"
        action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>"
        method="post"
        id="form-validate"
    >
        <fieldset class="cs-form__fieldset cs-form__fieldset--level_1">
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="cs-input cs-input--type-checkbox | field">
                <input
                    type="checkbox"
                    name="is_subscribed"
                    id="subscription"
                    value="1"
                    title="<?php /* @escapeNotVerified */ echo __('General Subscription') ?>"
                    <?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                    class="cs-input__checkbox | checkbox"
                >
                <label for="subscription" class="cs-input__label | label">
                    <span><?php /* @escapeNotVerified */ echo __('General Subscription') ?></span>
                </label>
            </div>
            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.newsletter.extra')?>
        </fieldset>
        <div class="cs-form__buttons">
            <button
                type="submit"
                title="<?php /* @escapeNotVerified */ echo __('Save') ?>"
                class="cs-button cs-button--type_long cs-button--type_mobile-wide cs-button--look_default"
            >
               <span class="cs-button__span"> <?php /* @escapeNotVerified */ echo __('Save') ?></span>
                <svg class="cs-button__icon">
                    <use xlink:href="#arrow_next"></use>
                </svg>
            </button>

        </div>
    </form>
</div>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.newsletter.extra2')?>
