<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/resetpasswordpost', ['_query' => ['id' => $block->getCustomerId(), 'token' => $block->getResetPasswordLinkToken()]]); ?>"
      method="post"
    <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?>
      id="form-validate"
      class="cs-form | form password reset"
      data-mage-init='{"validation":{}}'>
    <fieldset class="cs-form-fieldset cs-form__fieldset--level_1" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields'); ?>">
        <div class="cs-form__field | cs-input | required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <label class="cs-input__label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password'); ?></span></label>
            <div class="cs-input__control">
                <input type="password" class="cs-input__input" name="password" id="password"
                       data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
                <div id="password-strength-meter-container" data-role="password-strength-meter">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                        </span>
                        <div class="password-strength-meter__icons-wrapper">
                            <svg class="password-strength-meter__icon">
                                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                            </svg>
                            <svg class="password-strength-meter__icon">
                                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                            </svg>
                            <svg class="password-strength-meter__icon">
                                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                            </svg>
                            <svg class="password-strength-meter__icon">
                                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                            </svg>
                            <svg class="password-strength-meter__icon">
                                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                            </svg>
                            <svg class="password-strength-meter__icon">
                                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#rhomb"></use>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="cs-form__field | cs-input | required">
            <label class="cs-input__label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password'); ?></span></label>
            <div class="cs-input__control">
                <input type="password" class="cs-input__input" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
            </div>
        </div>
    </fieldset>
    <div class="cs-form__buttons">
        <button type="submit" class="cs-button cs-button--type_long cs-button--type_mobile-wide cs-button--look_default">
            <span class="cs-button__span"><?php /* @escapeNotVerified */ echo __('Set a New Password'); ?></span>
            <svg class="cs-button__icon">
                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
            </svg>
        </button>
    </div>
</form>
