<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
$gridLayoutComponentClass = $block->getGridLayoutComponentClass();
$pageLayout = $this->helper(\MageSuite\ThemeHelpers\Helper\PageLayout::class)->getPageLayout();
if ($pageLayout != '1column') {
    $gridLayoutComponentClass .= ' ' . $gridLayoutComponentClass . '--with-sidebar';
}
$gridLayoutComponentClass .= ' ' . $gridLayoutComponentClass . '--wishlist';
?>

<div class="<?= $gridLayoutComponentClass ?> cs-dashboard__wishlist-products-grid">
    <?php $iterator = 1; ?>
    <?php if (count($block->getItems())): ?>
        <?php $brickClass = $block->getGridLayoutComponentBrickClass() ?>
        <ol class="<?= $block->getGridLayoutComponentGridClass() ?> cs-dashboard__wishlist-grid">
            <?php foreach ($block->getItems() as $item): ?>
                <li class="<?= $brickClass ?> cs-dashboard__wishlist-brick" id="item_<?= $item->getId() ?>">
                    <?= $this->getLayout()
                        ->createBlock(\MageSuite\ProductTile\Block\Tile::class)
                        ->setIterator($iterator)
                        ->setAreas(['wishlist'])
                        ->setWishlistItem($item)
                        ->render($item->getProduct());
                    ?>
                </li>
                <?php $iterator++ ?>
            <?php endforeach; ?>
        </ol>
    <?php else: ?>
        <div class="cs-dashboard__wishlist-line">
            <span><?php /* @escapeNotVerified */
                echo __('This Wish List has no Items'); ?></span>
        </div>
    <?php endif; ?>
</div>

<?php foreach ($columns as $column): ?>
    <?php echo $column->getAdditionalHtml(); ?>
<?php endforeach; ?>
