<?php
/* @var $block \Aheadworks\Layerednav\Block\Navigation\FilterRenderer */

// @codingStandardsIgnoreFile
?>
<ol class="cs-aftersearch-nav__filter-items | items">
    <?php /** @var \Magento\Catalog\Model\Layer\Filter\Item[] $filterItems */ ?>
    <?php $index = 0; ?>
    <?php foreach ($filterItems as $filterItem): ?>
        <?php
        $requestVar = $filterItem->getFilter()->getRequestVar();
        $value = $filterItem->getValue();
        $htmlId = 'aw-filter-option-' . $requestVar . '-' . $value;
        $index = $index + 1;
        if ( $index > 5 && count($filterItems) != 6 ) {
            break;
        }
        ?>
        <li class="cs-aftersearch-nav__filter-item | item">
            <div class="cs-aftersearch-nav__filter-input cs-aftersearch-nav__filter-input--type_checkbox | cs-input cs-input--type-checkbox">
                <input
                    id="<?php /* @escapeNotVerified */ echo $htmlId ?>"
                    type="checkbox"
                    class="cs-input__checkbox"
                    name="<?php /* @escapeNotVerified */ echo $requestVar ?>"
                    value ="<?php /* @escapeNotVerified */ echo $value ?>"
                    <?php if ($block->isActiveItem($filterItem)) { /* @escapeNotVerified */ echo 'checked'; }?>
                    <?php if (!$filterItem->getCount() && !$block->isActiveItem($filterItem)) { /* @escapeNotVerified */ echo 'disabled'; } ?>
                    data-mage-init='{"awLayeredNavFilterItem": {}}'
                    data-role="aw-layered-nav-filter-item"
                />
                <label for="<?php /* @escapeNotVerified */ echo $htmlId ?>" class="cs-input__label">
                    <?php /* @escapeNotVerified */ echo __($filterItem->getLabel()) ?>
                </label>
            </div>
        </li>
    <?php endforeach ?>
</ol>

<input
    class="cs-visually-hidden | cs-aftersearch-nav__more-filters-checkbox"
    role="checkbox"
    type="checkbox"
    id="<?php /* @escapeNotVerified */ echo $requestVar?>"
/>
<div class="cs-aftersearch-nav__more-filters">
    <ol class="cs-aftersearch-nav__filter-items cs-aftersearch-nav__filter-items--inside | items">
        <?php $index = 0; ?>
        <?php foreach ($filterItems as $filterItem): ?>
            <?php
            $requestVar = $filterItem->getFilter()->getRequestVar();
            $value = $filterItem->getValue();
            $htmlId = 'aw-filter-option-' . $requestVar . '-' . $value;
            $index = $index + 1;
            ?>

            <?php if ( $index > 5 && count($filterItems) != 6 ): ?>
                <li class="cs-aftersearch-nav__filter-item cs-aftersearch-nav__filter-item | item">
                    <div class="cs-aftersearch-nav__filter-input cs-aftersearch-nav__filter-input--type_checkbox | cs-input cs-input--type-checkbox">
                        <input
                            id="<?php /* @escapeNotVerified */ echo $htmlId ?>"
                            type="checkbox"
                            class="cs-input__checkbox"
                            name="<?php /* @escapeNotVerified */ echo $requestVar ?>"
                            value ="<?php /* @escapeNotVerified */ echo $value ?>"
                            <?php if ($block->isActiveItem($filterItem)) { /* @escapeNotVerified */ echo 'checked'; }?>
                            <?php if (!$filterItem->getCount() && !$block->isActiveItem($filterItem)) { /* @escapeNotVerified */ echo 'disabled'; } ?>
                            data-mage-init='{"awLayeredNavFilterItem": {}}'
                            data-role="aw-layered-nav-filter-item"
                        />
                        <label for="<?php /* @escapeNotVerified */ echo $htmlId ?>" class="cs-input__label">
                            <?php /* @escapeNotVerified */ echo __($filterItem->getLabel()) ?>
                        </label>
                    </div>
                </li>
            <?php endif; ?>

        <?php endforeach ?>
    </ol>
</div>

<?php if ( count($filterItems) > 5 && count($filterItems) != 6 ): ?>
    <label
        for="<?php /* @escapeNotVerified */ echo $requestVar?>"
        class="cs-aftersearch-nav__more-filters-button | cs-collapse-inside__trigger cs-collapse-inside__trigger--no-arrow |
           cs-button cs-button--look_light cs-button--size_300 | cs-hide-mobile"
    >
        <span
            class="cs-button__span"
            data-show-less-text="<?php /* @escapeNotVerified */ echo __('Less Filters'); ?>"
            data-show-more-text="<?php /* @escapeNotVerified */ echo __('More Filters'); ?>"
        >
        </span>
        <span class="cs-visually-hidden">
            <?php /* @escapeNotVerified */ echo __('Check'. $requestVar . 'checkbox to see more filters. Uncheck it to see less filters'); ?>
        </span>
        <svg class="cs-button__icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </label>
<?php endif; ?>

