<?php
/* @var $block \Aheadworks\Layerednav\Block\Navigation\FilterRenderer */

// @codingStandardsIgnoreFile
?>
<ol class="cs-aftersearch-nav__filter-items | items">
    <?php /** @var \Magento\Catalog\Model\Layer\Filter\Item[] $filterItems */ ?>
    <?php foreach ($filterItems as $filterItem): ?>
        <?php
            $requestVar = $filterItem->getFilter()->getRequestVar();
            $value = $filterItem->getValue();
            $htmlId = 'aw-filter-option-' . $requestVar . '-' . $value;
        ?>
        <li class="cs-aftersearch-nav__filter-item | item">
            <div class="cs-aftersearch-nav__filter-input cs-aftersearch-nav__filter-input--type_checkbox | cs-input cs-input--type-checkbox">
                <input
                    id="<?php /* @escapeNotVerified */ echo $htmlId ?>"
                    type="checkbox"
                    class="cs-input__checkbox"
                    name="<?php /* @escapeNotVerified */ echo $requestVar ?>"
                    value ="<?php /* @escapeNotVerified */ echo $value ?>"
                    <?php if ($block->isActiveItem($filterItem)) { /* @escapeNotVerified */ echo 'checked'; }?>
                    <?php if (!$filterItem->getCount() && !$block->isActiveItem($filterItem)) { /* @escapeNotVerified */ echo 'disabled'; } ?>
                    data-mage-init='{"awLayeredNavFilterItem": {}}'
                    data-role="aw-layered-nav-filter-item"
                    />
                <label for="<?php /* @escapeNotVerified */ echo $htmlId ?>" class="cs-input__label"><?php /* @escapeNotVerified */ echo __($filterItem->getLabel()) ?></label>
            </div>
        </li>
    <?php endforeach ?>
</ol>
