<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

// @codingStandardsIgnoreFile

/** @var \Aheadworks\Pquestion\Block\Question\Form $this */
?>
<form id="aw-pq-question-form" class="form aw-pq-form" action="<?php echo $this->escapeUrl($this->getAddQuestionUrl()); ?>" method="post" >
    <h3 class="aw-pq-form__headline">
        Ask question:
        <span class="aw-pq-form__product-name">
            <?php echo $this->getProduct()->getName(); ?>
        </span>
    </h3>
    <div class="fieldset | aw-pq-form__fieldset">
        <div class="field required aw-pq-form__field-name">
            <label for="question_author_name" class="label">
                <span><?php echo $this->escapeHtml(__('Name')); ?></span>
            </label>
            <div class="control">
                <input type="text" name="author_name" id="question_author_name" class="input-text" data-validate="{required:true}" aria-required="true" value="<?php echo $this->escapeHtml(trim($this->getCustomerName())); ?>" title="<?php echo $this->escapeHtml(__('Name')); ?>" maxlength="255">
            </div>
        </div>
        <?php if (!$this->isLoggedIn()): ?>
            <div class="field required aw-pq-form__field-email">
                <label for="question_author_email" class="label">
                    <span><?php echo $this->escapeHtml(__('Email Address')); ?></span>
                </label>
                <div class="control">
                    <input type="text" name="author_email" id="question_author_email" class="input-text validate-email" data-validate="{required:true}" aria-required="true" title="<?php echo $this->escapeHtml(__('Email Address')); ?>" maxlength="255">
                </div>
            </div>
        <?php endif; ?>
        <div class="field required">
            <label for="question_content" class="label">
                <span><?php echo $this->escapeHtml(__('Question')); ?></span>
            </label>
            <div class="control">
                <textarea class="input-text" name="content" id="question_content" cols="5" rows="3" data-validate="{required:true}" aria-required="true"></textarea>
            </div>
        </div>
        <?php if ($this->canSpecifyVisibility()) : ?>
            <div class="field aw-pq-form__field-checkbox">
                <input class="checkbox" type="checkbox" name="is_private" id="question_visibility">
                <label for="question_visibility" class="aw-pq-form__checkbox-label">
                    <span><?php echo $this->escapeHtml(__('Private Question')); ?></span>
                </label>
            </div>
        <?php endif; ?>
        <div class="aw-pq-form__button-wrapper">
            <button type="submit" class="action submit aw-pq-form__button-question">
                <span class="aw-pq-form__button-question-span"><?php echo $this->escapeHtml(__('Send Question')); ?></span>
                <?= $block->getChildHtml('aw_pq_ask_question_form.send-question.button.icon'); ?>
            </button>
        </div>
    </div>
    <input type="hidden" name="product_id" value="<?php echo (int)$this->getProduct()->getId(); ?>" />
</form>
<script type="text/javascript">
    require(['prototype'], function() {
        var formKeyElement = new Element('input');
        formKeyElement.setAttribute('type', 'hidden');
        formKeyElement.setAttribute('name', 'form_key');
        formKeyElement.setAttribute('value', '<?php /* @noEscape */ echo $this->getSessionFormKey(); ?>');
        $('aw-pq-question-form').appendChild(formKeyElement);
    });
</script>
<script type="text/javascript">
    require(["jquery","mage/mage"],function($){
        $('#aw-pq-question-form').mage('validation');
    });
</script>
