<?php
/**
* Template overwritten to:
* - add magesuite classes
* - add title sttribute
* - replace text with childHtml block
* Aligned with Magento 2.4.6 at 04/2023
*/

/** @var \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()) : ?>
    <div class="cs-cart-item__link cs-cart-item__link--wishlist">
        <a
            class="cs-cart-item__link-wrapper use-ajax action towishlist action-towishlist"
            href="#"
            title="<?= $block->escapeHtml(__('Move to Wishlist')); ?>"
            data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
        >
            <?= $block->getChildHtml(); ?>
        </a>
    </div>
<?php endif ?>
