<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cs-cart-table__body cart item">
    <tr class="cs-cart-item item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="cs-cart-table__col cs-cart-item__item col item">
            <div class="cs-cart-item__product">
                <?php if ($block->hasProductUrl()):?>
                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"
                    title="<?= $block->escapeHtml($block->getProductName()) ?>"
                    tabindex="-1"
                    class="cs-cart-item__image product-item-photo">
                <?php else:?>
                    <span class="cs-cart-item__image product-item-photo">
                <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()):?>
                    </a>
                <?php else: ?>
                    </span>
                <?php endif; ?>
                <div class="cs-cart-item__details product-item-details">
                    <?php $isFreeBadge = (float)$_item->getPrice() ? false : true;
                    if($_item->getIsGift() and $isFreeBadge): ?>
                        <span class="cs-cart-item__badge cs-cart-item__badge--free">
                            <span class="cs-cart-item__badge-text"><?php echo __('Free') ?></span>
                        </span>
                    <?php endif; ?>
                    <strong class="cs-cart-item__name product-item-name">
                        <?php if ($block->hasProductUrl()):?>
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                        <?php else: ?>
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </strong>
                    <?php if ($_options = $block->getOptionList()):?>
                        <div class="<?= $product->getTypeId() == 'bundle' ? 'cs-cart-item__options cs-cart-item__options--rows' : 'cs-cart-item__options' ?>">
                            <?php foreach ($_options as $_option) : ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <?php if($block->hasProductUrl() && $block->getLinkOptions()): ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl() ?>" class="cs-cart-item__option-link">
                            <?php endif; ?>
                                <dl class="cs-cart-item__options-group item-options">
                                    <dt class="cs-cart-item__options-label">
                                        <?= $block->escapeHtml($_option['label']) ?>
                                    </dt>
                                    <dd class="cs-cart-item__options-value">
                                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                            <?= /* @escapeNotVerified */ $_formatedOptionValue['full_view'] ?>
                                        <?php else: ?>
                                            <?= /* @escapeNotVerified */ $_formatedOptionValue['value'] ?>
                                        <?php endif; ?>
                                        <?php if($block->hasProductUrl() && $block->getLinkOptions()): ?>
                                            <?= $block->getChildHtml('checkout.cart.item.renderers.default.option.edit'); ?>
                                        <?php endif; ?>
                                    </dd>
                                </dl>
                            <?php if($block->hasProductUrl() && $block->getLinkOptions()): ?>
                            </a>
                            <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    <?php endif;?>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="cs-cart-item__message cart item message <?= /* @escapeNotVerified */ $message['type'] ?>"><div><?= $block->escapeHtml($message['text']) ?></div></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif;?>
                </div>
            </div>
        </td>
        <?php if ($canApplyMsrp): ?>
            <td class="cs-cart-table__col cs-cart-item__price col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= /* @escapeNotVerified */ __('See price before order confirmation.') ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map" id="<?= /* @escapeNotVerified */ ($helpLinkId) ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?= /* @escapeNotVerified */ $helpLinkId ?>","productName": "<?= /* @escapeNotVerified */ $product->getName() ?>","showAddToCart": false}}'>
                        <span><?= /* @escapeNotVerified */ __("What's this?") ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="cs-cart-table__col cs-cart-item__price col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="cs-cart-table__col cs-cart-item__qty col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="cs-cart-item__qty-input">
                <?php 
                    $qtyBlock = $block->getChildBlock('checkout.cart.item.'.$_item->getProduct()->getTypeId().'.qty');
                    $qtyBlock->setData('item', $_item);
                    $qtyBlock->setData('qty', $block->getQty());
                    echo $qtyBlock->toHtml();
                ?>
            </div>
        </td>
        <td class="cs-cart-table__col cs-cart-item__subtotal col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <div class="cs-cart-item__subtotal-inner">
                <?php if ($canApplyMsrp): ?>
                    <span class="cart msrp subtotal">--</span>
                <?php else: ?>
                    <?= $block->getRowTotalHtml($_item) ?>
                <?php endif; ?>
            </div>
        </td>
        <td class="cs-cart-table__col cs-cart-item__bottom">
            <div class="cs-cart-item__buttons actions-toolbar">
                <?= /* @escapeNotVerified */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
