<?php
/**
 * Template overwritten to:
 * - add magesuite classes
 * - add different classes for options in case of bundle product
 * - add free badge if exists
 * - add checkout.cart.item.brand, checkout.cart.item.renderers.default.option.edit hotspots
 * - add qty-increment component instead of input
 * - remove attributes to show image link in tab order
 * - merge options into one link NKD-4574
 *
 * Aligned with Magento 2.4.9 in 05/2026
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
/** @var \Magento\Framework\Escaper $escaper */

$_item = $block->getItem();
$product = $_item->getProduct();
$productType = $product->getTypeId();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cs-cart-table__body cart item">
    <tr class="cs-cart-item cs-cart-item--<?= $escaper->escapeHtmlAttr($productType) ?> item-info">
        <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>" class="cs-cart-table__col cs-cart-item__item col item">
            <div class="cs-cart-item__product">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                    title="<?= $escaper->escapeHtml($block->getProductName()) ?>"
                    class="cs-cart-item__image product-item-photo">
                <?php else:?>
                    <span class="cs-cart-item__image product-item-photo">
                <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()): ?>
                    </a>
                <?php else: ?>
                    </span>
                <?php endif; ?>
                <div class="cs-cart-item__details product-item-details">
                    <?php $isFreeBadge = (float)$_item->getPrice() ? false : true;
                    if($_item->getIsGift() and $isFreeBadge): ?>
                        <span class="cs-cart-item__badge cs-cart-item__badge--free">
                            <span class="cs-cart-item__badge-text"><?= __('Free') ?></span>
                        </span>
                    <?php endif; ?>
                    <?= $block->getChildHtml('checkout.cart.item.brand.' . $_item->getProductType(), false); ?>
                    <strong class="cs-cart-item__name product-item-name">
                        <?php if ($block->hasProductUrl()): ?>
                            <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"><?= $escaper->escapeHtml($block->getProductName()) ?></a>
                        <?php else: ?>
                            <?= $escaper->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </strong>
                    <?php if ($_options = $block->getOptionList()): ?>
                        <div class="<?= $productType == 'bundle' ? 'cs-cart-item__options cs-cart-item__options--rows' : 'cs-cart-item__options' ?>">
                            <?php if($product->isVisibleInSiteVisibility() && $block->getLinkOptions()): ?>
                                <a class="cs-cart-item__option-link"
                                    href="<?= $escaper->escapeUrl($this->getUrl('checkout/cart/configure', ['id' => $_item->getId(),'product_id' => $product->getId()]));?>"
                                    title="<?= $escaper->escapeHtml(__('Edit item parameter')); ?>"
                                >
                            <?php endif; ?>
                            <?php foreach ($_options as $_option): ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                    <dl class="cs-cart-item__options-group item-options">
                                        <dt class="cs-cart-item__options-label">
                                            <?= $escaper->escapeHtml($_option['label']) ?>
                                        </dt>
                                        <dd class="cs-cart-item__options-value">
                                            <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                                <?= $escaper->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a']) ?>
                                            <?php else: ?>
                                                <?= $escaper->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                            <?php endif; ?>
                                            <?php if($block->hasProductUrl() && $block->getLinkOptions()): ?>
                                                <?= $block->getChildHtml('checkout.cart.item.renderers.default.option.edit'); ?>
                                            <?php endif; ?>
                                        </dd>
                                    </dl>
                            <?php endforeach; ?>
                            <?php if($product->isVisibleInSiteVisibility() && $block->getLinkOptions()): ?>
                            </a>
                            <?php endif; ?>
                        </div>
                    <?php endif;?>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="cs-cart-item__message cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>"><div><?= $escaper->escapeHtml($message['text']) ?></div></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif; ?>
                </div>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="cs-cart-table__col cs-cart-item__price col msrp" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $escaper->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($escaper->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "origin": "info",
                                            "helpLinkId": "#<?= $escaper->escapeJs($escaper->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $escaper->escapeJs($escaper->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $escaper->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="cs-cart-table__col cs-cart-item__price col price" data-th="<?= $escaper->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="cs-cart-table__col cs-cart-item__qty col qty" data-th="<?= $escaper->escapeHtml(__('Qty')) ?>">
            <div class="cs-cart-item__qty-input">
                <?php
                    $qtyBlock = $block->getChildBlock('checkout.cart.item.'.$_item->getProductType().'.qty');
                    $qtyBlock->setData('item', $_item);
                    $qtyBlock->setData('qty', $block->getQty());
                    echo $qtyBlock->toHtml();
                ?>
            </div>
        </td>

        <td class="cs-cart-table__col cs-cart-item__subtotal col subtotal" data-th="<?= $escaper->escapeHtml(__('Subtotal')) ?>">
            <div class="cs-cart-item__subtotal-inner">
                <?php if ($canApplyMsrp): ?>
                    <span class="cart msrp subtotal">--</span>
                <?php else: ?>
                    <?= $block->getRowTotalHtml($_item) ?>
                <?php endif; ?>
            </div>
        </td>
        <td class="cs-cart-table__col cs-cart-item__bottom">
            <div class="cs-cart-item__buttons actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
