<?php
/**
 * Template adjusted to match the success/success.scss component in case of css classes and tags
 */

?>
<div class="checkout-success | cs-page-success__section">
    <?php if ($block->getOrderId()) : ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p class="cs-page-success__subheadline">
                <?= $block->escapeHtml(__('Your order # is: %1.', sprintf(
                    '<a href="%s" class="order-number"><strong>%s</strong></a>',
                    $block->escapeUrl($block->getViewOrderUrl()),
                    $block->getOrderId())),
                    ['a', 'strong']) ?>
            </p>
        <?php else : ?>
            <p class="cs-page-success__subheadline">
                <?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?>
            </p>
        <?php endif; ?>
        <?php if ($block->getIsOrderStorePickup()->execute()) : ?>
            <p class="cs-page-success__text">
                <?= $block->escapeHtml(__('We\'ll email you an order and pick-up confirmation with details.')) ?>
            </p>
        <?php else : ?>
            <p class="cs-page-success__text">
                <?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?>
            </p>
        <?php endif; ?>
    <?php endif; ?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="cs-page-success__button-wrapper">
        <a class="cs-page-success__button" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
            <span class="cs-page-success__button-span"><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            <?= $block->getChildHtml('success.page.continue.button.icon'); ?>
        </a>
    </div>
</div>
