<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Customer\Block\Account\AuthorizationLink */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>

<ul class="cs-information-stripe__list | cs-list cs-list--inline cs-list--unstyled" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
    <li class="cs-information-stripe__item cs-information-stripe__item--last cs-information-stripe__item--login | cs-list__item | cs-text cs-t-text--size_300">
        <a href="#" class="cs-information-stripe__account-link"  <?php /* @escapeNotVerified */ echo $block->getLinkAttributes(); ?><?php /* @escapeNotVerified */ echo $dataPostParam; ?>>
            <svg class="cs-information-stripe__account-icon">
                <use xlink:href="<?=$this->getViewFileUrl('images/sprites.svg');?>#user"></use>
            </svg>
            <span class="cs-information-stripe__account-label">
                <?php echo $block->escapeHtml($block->getLabel()); ?>
            </span>
        </a>
    </li>
</ul>
