<?php
// @codingStandardsIgnoreFile
/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */
$dataPostParam = '';
$isLoggedIn = $block->isLoggedIn();
$htmlTag = $block->getHtmlTag() ?? 'div';
if ($isLoggedIn) {
    $dataPostParam = sprintf("data-post='%s' data-uenc-update='true'", $block->getPostParams());
}
?>
    <<?= $htmlTag ?> class="authorization-link cs-authorization-link <?= $block->getAdditionalCssClasses() ?>" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?> class="cs-authorization-link__link">
            <?= $block->getChildHtml($isLoggedIn ? 'authorization-link.icon.logout' : 'authorization-link.icon.login'); ?>
            <span class="cs-authorization-link__label">
                <?= $block->escapeHtml($block->getLabel()); ?>
            </span>
        </a>
    </<?= $htmlTag ?>>
