<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>

<dt class="cs-attributes-list__item-label">
<?php /* @escapeNotVerified */ echo __("Order status: ") ?>
</dt>
<dd class="cs-attributes-list__item">
    <?php /* @escapeNotVerified */ echo $block->getOrder()->getStatusLabel() ?>
</dd>
