<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<dt class="cs-attributes-list__item-label">
    <?php /* @escapeNotVerified */ echo __("Order placement date: ") ?>
</dt>
<dd class="cs-attributes-list__item">
    <date>
        <?php /* @escapeNotVerified */ echo $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) ?>
    </date>
</dd>

