<?php
// @codingStandardsIgnoreFile
/** @var  $block \Magento\Sales\Block\Order\View*/
?>
<div class="cs-info-block | cs-dashboard__block | ordered">
    <?php $order = $block->getOrder() ?>

    <div class="cs-info-block__title | cs-title-block cs-title-block--bordered">
        <div class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light">
            <?php /* @escapeNotVerified */ echo __('Ordered items') ?>
        </div>
        <?php if ($order->getTracksCollection()->count()) : ?>
        <span class="cs-t-headline__span | cs-link">
            <?php echo $block->getChildHtml('tracking-info-link') ?>
        </span>
        <?php endif; ?>
    </div>

    <?php echo $block->getChildHtml('order_items') ?>

    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $order) && $order->getGiftMessageId()): ?>
        <div class="block block-order-details-gift-message">
            <div class="block-title">
                <strong><?php /* @escapeNotVerified */ echo __('Gift Message for This Order') ?></strong>
            </div>
            <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($order); ?>
            <div class="block-content">
                <dl class="item-options">
                    <dt class="item-sender">
                        <strong class="label"><?php /* @escapeNotVerified */ echo __('From') ?></strong>
                        <?php echo $block->escapeHtml($giftMessage->getSender()) ?>
                    </dt>
                    <dt class="item-recipient">
                        <strong class="label"><?php /* @escapeNotVerified */ echo __('To') ?></strong>
                        <?php echo $block->escapeHtml($giftMessage->getRecipient()) ?>
                    </dt>
                    <dd class="item-message">
                        <?php /* @escapeNotVerified */ echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($order) ?>
                    </dd>
                </dl>
            </div>
        </div>
    <?php endif; ?>

</div>
