<?php
// @codingStandardsIgnoreFile
$item = $block->getItem();
$order = $block->getItem()->getOrderItem()->getOrder();
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $item->getId() ?>">
    <td class="cs-table__col | name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <span class="cs-t-text cs-t-text--look_attention | product-item-name">
            <?php echo $block->escapeHtml($item->getName()) ?>
        </span>
        <?php if ($options = $block->getItemOptions()): ?>
        <div class="cs-cart-item__options">
            <?php foreach ($options as $option) : ?>
                <dl class="cs-cart-item__options-group | item-options">
                    <dt class="cs-cart-item__options-label"><?php echo $block->escapeHtml($option['label']) ?></dt>
                    <?php if (!$block->getPrintStatus()): ?>
                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dd<?php if (isset($formatedOptionValue['full_view'])): ?> class="cs-cart-item__options-value | tooltip wrapper"<?php endif; ?>>
                            <?php /* @escapeNotVerified */ echo $formatedOptionValue['value'] ?>
                            <?php if (isset($formatedOptionValue['full_view'])): ?>
                                <div class="tooltip content">
                                    <dl class="item options">
                                        <dt class="cs-cart-item__options-label">
                                            <?php echo $block->escapeHtml($option['label']) ?>
                                        </dt>
                                        <dd class="cs-cart-item__options-value">
                                            <?php /* @escapeNotVerified */ echo $formatedOptionValue['full_view'] ?>
                                        </dd>
                                    </dl>
                                </div>
                            <?php endif; ?>
                        </dd>
                    <?php else: ?>
                        <dd class="cs-cart-item__options-value">
                            <?php echo $block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value'])) ?>
                        </dd>
                    <?php endif; ?>
                </dl>
            <?php endforeach; ?>
        </div>

        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="cs-table__col | sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
        <?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="cs-table__col | qty" data-th="<?php echo $block->escapeHtml(__('Qty Shipped')); ?>">
        <?php /* @escapeNotVerified */ echo $item->getQty()*1 ?>
    </td>
</tr>
