<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<form class="cs-header__search | cs-header-search | cs-input" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
    <input
        class="cs-header-search__input | cs-input__input"
        data-mage-init='{"quickSearch":{
        "formSelector":".cs-header-search",
        "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
        "destinationSelector":".cs-header-search__autocomplete"}
        }'
        type="search"
        name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
        value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
        placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
        maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
        role="combobox"
        aria-haspopup="false"
        aria-autocomplete="both"
        autocomplete="off">
    <div class="cs-header-search__autocomplete"></div>
    <div class="cs-input__button">
        <button class="cs-button cs-button--look_default cs-button--look_on-input" type="submit">
            <svg class="cs-button__icon cs-button__icon--center cs-button__icon--search">
                <use xlink:href="#search"></use>
            </svg>
            <span class="cs-visually-hidden"><?=__('Search');?></span>
        </button>
    </div>

</form>
