<?php
/**
* Custom template to preload category image in order to improve LCP
* see https://web.dev/optimize-lcp/#preload-important-resources
*/
// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Product\View\Gallery */
?>
<?php
    $galleryImagesJson = $block->getGalleryImagesJson();
    $galleryImages = json_decode($galleryImagesJson);
    $imgUrl = array_shift($galleryImages)->img;
?>
<link rel="preload" href="<?= $imgUrl ?>" as="image">
