<?php
// @codingStandardsIgnoreFile
?>
<div class="cs-input | cs-form__field | gender<?php if ($block->isRequired()) echo ' required' ?>">
    <label
        class="cs-input__label | label"
        for="<?php /* @escapeNotVerified */ echo $block->getFieldId('gender')?>"
    >
        <?php /* @escapeNotVerified */ echo __('Gender') ?>
    </label>
    <div class="cs-input__control">
        <select
            id="<?php /* @escapeNotVerified */ echo $block->getFieldId('gender')?>"
            class="cs-input__select"
            name="<?php /* @escapeNotVerified */ echo $block->getFieldName('gender')?>"
            title="<?php /* @escapeNotVerified */ echo __('Gender') ?>"<?php if ($block->isRequired()):?>
            class="validate-select"
            data-validate="{required:true}"<?php endif; ?> <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>
        >
            <?php $options = $block->getGenderOptions(); ?>
            <?php $value = $block->getGender();?>
            <?php foreach ($options as $option):?>
                <option
                    value="<?php /* @escapeNotVerified */ echo $option->getValue() ?>"
                    <?php if ($option->getValue() == $value) echo ' selected="selected"' ?>
                >
                    <?php /* @escapeNotVerified */ echo __($option->getLabel()) ?>
                </option>
            <?php endforeach;?>
        </select>
    </div>
</div>
