<?php
// @codingStandardsIgnoreFile
/* @var $block \Magento\Customer\Block\Widget\Name */
$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
?>

<?php if ($prefix || $middle || $suffix && !$block->getNoWrap()): ?>
<div class="field required fullname <?php /* @escapeNotVerified */echo $block->getContainerClassName() ?>">

    <div class="control">
        <fieldset class="cs-form__fieldset cs-form__fieldset--level_2 | fieldset-fullname">
            <?php endif; ?>

            <?php if ($prefix): ?>
                <?php $fieldId = $block->getFieldId('prefix') ?>
                <div class="cs-input | cs-form__field | field field-name-prefix<?php if ($block->isPrefixRequired()) echo ' required' ?>">
                    <label class="cs-input__label | label" for="<?php /* @escapeNotVerified */echo $fieldId ?>">
                        <span><?php /* @escapeNotVerified */echo $block->getStoreLabel('prefix') ?></span>
                    </label>

                    <div class="cs-input__control">
                        <?php if ($block->getPrefixOptions() === false): ?>
                            <input
                                type="text"
                                id="<?php /* @escapeNotVerified */echo $fieldId ?>"
                                name="<?php /* @escapeNotVerified */echo $block->getFieldName('prefix') ?>"
                                value="<?php echo $block->escapeHtml($block->getObject()->getPrefix()) ?>"
                                title="<?php /* @escapeNotVerified */echo $block->getStoreLabel('prefix') ?>"
                                class="cs-input__input <?php /* @escapeNotVerified */echo $block->getAttributeValidationClass('prefix') ?>"
                                <?php /* @escapeNotVerified */echo $block->getFieldParams() ?>
                                <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?>
                            >
                        <?php else: ?>
                            <select
                                id="<?php /* @escapeNotVerified */echo $fieldId ?>"
                                name="<?php /* @escapeNotVerified */echo $block->getFieldName('prefix') ?>"
                                title="<?php /* @escapeNotVerified */echo $block->getStoreLabel('prefix') ?>"
                                class="cs-input__select cs-input__select--short |<?php /* @escapeNotVerified */echo $block->getAttributeValidationClass('prefix') ?>"
                                <?php /* @escapeNotVerified */echo $block->getFieldParams() ?>
                                <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
                                <?php foreach ($block->getPrefixOptions() as $option): ?>
                                    <option
                                        value="<?php /* @escapeNotVerified */echo $option ?>"
                                        <?php if ($block->getObject()->getPrefix() == $option): ?> selected="selected"<?php endif; ?>
                                    >
                                        <?php /* @escapeNotVerified */echo __($option) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="cs-input | cs-form__field | field field-name-firstname required">
                <label class="cs-input__label | label" for="<?php /* @escapeNotVerified */echo $block->getFieldId('firstname') ?>">
                    <span><?php /* @escapeNotVerified */echo $block->getStoreLabel('firstname') ?></span>
                </label>

                <div class="cs-input__control">
                    <input
                        type="text"
                        id="<?php /* @escapeNotVerified */echo $block->getFieldId('firstname') ?>"
                        name="<?php /* @escapeNotVerified */echo $block->getFieldName('firstname') ?>"
                        value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
                        title="<?php /* @escapeNotVerified */echo $block->getStoreLabel('firstname') ?>"
                        class="cs-input__input <?php /* @escapeNotVerified */echo $block->getAttributeValidationClass('firstname') ?>"
                        <?php /* @escapeNotVerified */echo $block->getFieldParams() ?>
                        <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo ' data-validate="{required:true}"' ?>
                    >
                </div>
            </div>
            <?php if ($middle): ?>
                <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
                <div class="cs-input | cs-form__field | field field-name-middlename<?php echo $isMiddlenameRequired ? ' required' : '' ?>">
                    <label class="cs-input__label | label" for="<?php /* @escapeNotVerified */
                    echo $block->getFieldId('middlename') ?>">
                        <?php /* @escapeNotVerified */
                        echo $block->getStoreLabel('middlename') ?>
                    </label>

                    <div class="cs-input__control">
                        <input type="text" id="<?php /* @escapeNotVerified */
                        echo $block->getFieldId('middlename') ?>"
                               name="<?php /* @escapeNotVerified */
                               echo $block->getFieldName('middlename') ?>"
                               value="<?php echo $block->escapeHtml($block->getObject()->getMiddlename()) ?>"
                               title="<?php /* @escapeNotVerified */
                               echo $block->getStoreLabel('middlename') ?>"
                               class="cs-input__input <?php /* @escapeNotVerified */
                               echo $block->getAttributeValidationClass('middlename') ?>" <?php /* @escapeNotVerified */
                        echo $block->getFieldParams() ?> <?php echo $isMiddlenameRequired ? ' data-validate="{required:true}"' : '' ?>>
                    </div>
                </div>
            <?php endif; ?>
            <div class="cs-input | cs-form__field | field field-name-lastname required">
                <label class="cs-input__label | label" for="<?php /* @escapeNotVerified */
                echo $block->getFieldId('lastname') ?>">
                    <?php /* @escapeNotVerified */
                    echo $block->getStoreLabel('lastname') ?>
                </label>

                <div class="cs-input__control">
                    <input
                        type="text"
                        id="<?php /* @escapeNotVerified */echo $block->getFieldId('lastname') ?>"
                        name="<?php /* @escapeNotVerified */echo $block->getFieldName('lastname') ?>"
                        value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
                        title="<?php /* @escapeNotVerified */echo $block->getStoreLabel('lastname') ?>"
                        class="cs-input__input <?php /* @escapeNotVerified */echo $block->getAttributeValidationClass('lastname') ?>"
                        <?php /* @escapeNotVerified */echo $block->getFieldParams() ?>
                        <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo ' data-validate="{required:true}"' ?>
                    >
                </div>
            </div>
            <?php if ($suffix): ?>
                <div class="cs-input | cs-form__field | field field-name-suffix<?php if ($block->isSuffixRequired()) echo ' required' ?>">
                    <label
                        class="cs-input__label | label"
                        for="<?php /* @escapeNotVerified */echo $block->getFieldId('suffix') ?>"
                    >
                        <?php /* @escapeNotVerified */echo $block->getStoreLabel('suffix') ?>
                    </label>

                    <div class="cs-input__control">
                        <?php if ($block->getSuffixOptions() === false): ?>
                            <input
                                type="text" id="<?php /* @escapeNotVerified */echo $block->getFieldId('suffix') ?>"
                                name="<?php /* @escapeNotVerified */echo $block->getFieldName('suffix') ?>"
                                value="<?php echo $block->escapeHtml($block->getObject()->getSuffix()) ?>"
                                title="<?php /* @escapeNotVerified */echo $block->getStoreLabel('suffix') ?>"
                                class="cs-input__input <?php /* @escapeNotVerified */echo $block->getAttributeValidationClass('suffix') ?>"
                                <?php /* @escapeNotVerified */echo $block->getFieldParams() ?>
                                <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>
                            >
                        <?php else: ?>
                            <select
                                id="<?php /* @escapeNotVerified */echo $block->getFieldId('suffix') ?>"
                                name="<?php /* @escapeNotVerified */echo $block->getFieldName('suffix') ?>"
                                title="<?php /* @escapeNotVerified */echo $block->getStoreLabel('suffix') ?>"
                                class="cs-input__select | <?php /* @escapeNotVerified */echo $block->getAttributeValidationClass('suffix') ?>"
                                <?php /* @escapeNotVerified */echo $block->getFieldParams() ?>
                                <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>
                            >
                                <?php foreach ($block->getSuffixOptions() as $option): ?>
                                    <option
                                        value="<?php /* @escapeNotVerified */echo $option ?>"
                                        <?php if ($block->getObject()->getSuffix() == $option): ?>
                                            selected="selected"
                                        <?php endif; ?>
                                    >
                                        <?php /* @escapeNotVerified */echo __($option) ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($prefix || $middle || $suffix && !$block->getNoWrap()): ?>
        </fieldset>
    </div>
</div>
<?php endif; ?>
