<?php
/** @var $block \Creativestyle\ProductPositiveIndicatorsExtension\Block\FastShipping\Product */
$isEnabled = $block->isEnabled();

if($isEnabled) { ?>
    <div class="cs-indicator-fast-shipping <?= $block->getAdditionalCssClasses() ?>">
        <div class="cs-indicator-fast-shipping__content">
            <?= $block->getChildHtml('') ?>
            <?php foreach($block->getVariants() as $variantKey => $variantData): ?>
                <div class="cs-indicator-fast-shipping__element cs-indicator-fast-shipping__element--<?= $variantKey ?>" data-fs-scenario="<?= $variantKey ?>">
                    <?php if(isset($variantData['icon_url']) && !empty($variantData['icon_url'])): ?>
                        <?= $this->getLayout()
                                ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                                ->setIconUrl($variantData['icon_url'])
                                ->setCssClass('cs-indicator-fast-shipping__icon cs-indicator-fast-shipping__icon--'.$variantKey)
                                ->setInlined(true)
                                ->setLazyLoaded(true)
                                ->toHtml();
                        ?>
                    <?php endif; ?>
                    <div class="cs-indicator-fast-shipping__label">

                        <?php if(isset($variantData['headline'])): ?>
                            <span class="cs-indicator-fast-shipping__headline"><?= $variantData['headline'] ?></span>
                        <?php endif; ?>

                        <?php if(strpos($variantData['text'], '%1')):
                            echo __($variantData['text'], '<span class="cs-indicator-fast-shipping__text-placeholder-'.$variantKey.'"></span>');
                        else:
                            echo __($variantData['text']);
                        endif; ?>


                    </div>
                </div>
            <?php endforeach; ?>
        </div>

        <input type="hidden" name="cs-indicator-fast-shipping__labels" class="cs-indicator-fast-shipping__labels" value='<?= json_encode($block->getTimeLabels()) ?>'>
        <input type="hidden" name="cs-indicator-fast-shipping__data-time" class="cs-indicator-fast-shipping__data-time" value='<?= $block->getMaxTimeToday() ?>'>
        <input type="hidden" name="cs-indicator-fast-shipping__data-time-next" class="cs-indicator-fast-shipping__data-time-next" value='<?= $block->getNextShipDayTime() ?>'>
        <input type="hidden" name="cs-indicator-fast-shipping__data-delivery-day" class="cs-indicator-fast-shipping__data-delivery-day" value='<?= $block->getNextShipDayName() ?>'>
    </div>
<?php } ?>
