<?php
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart cs-form cs-container__cart-items">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?> cs-cart-table-wrapper">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar cs-cart-table__toolbar cs-cart-table__toolbar--top" data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table cs-cart-table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption cs-cart-table__caption"><?= /* @escapeNotVerified */ __('Shopping Cart Items') ?></caption>
            <thead class="cs-cart-table__head">
                <tr>
                    <th class="col item cs-cart-table__head-col" scope="col">
                        <span class="cs-cart-table__head-text"><?= /* @escapeNotVerified */ __('Item') ?></span>
                    </th>
                    <th class="col price cs-cart-table__head-col" scope="col">
                        <span class="cs-cart-table__head-text"><?= /* @escapeNotVerified */ __('Price') ?></span>
                    </th>
                    <th class="col qty cs-cart-table__head-col" scope="col">
                        <span class="cs-cart-table__head-text"><?= /* @escapeNotVerified */ __('Qty') ?></span>
                    </th>
                    <th class="col subtotal cs-cart-table__head-col" scope="col">
                        <span class="cs-cart-table__head-text"><?= /* @escapeNotVerified */ __('Subtotal') ?></span>
                    </th>
                    <th class="col cs-cart-table__head-col" scope="col">
                    </th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <div class="load indicator cs-no-display"></div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar cs-cart-table__toolbar cs-cart-table__toolbar--bottom" data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?></div>
        <?php endif ?>
    </div>
    <div class="cart main actions cs-visually-hidden">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
            </a>
        <?php endif; ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-empty=""
                value="empty_cart"
                title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                class="action clear" id="empty_cart_button">
            <span><?= /* @escapeNotVerified */ __('Clear Shopping Cart') ?></span>
        </button>
        <button type="submit"
                name="update_cart_action"
                id="update-cart-button"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= /* @escapeNotVerified */ __('Update Shopping Cart') ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

