<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cs-info-page">
    <div class="cs-info-page__inner">
        <?php echo $block->getChildHtml('checkout_cart_empty_widget'); ?>
        <p class="cs-info-page__subheadline"><?php /* @escapeNotVerified */ echo __('You have no items in your shopping cart.') ?></p>
        <p class="cs-info-page__text"><?php /* @escapeNotVerified */ echo __('You can add products by clicking “Add to cart” button on product detail page.') ?></p>
        <div class="cs-info-page__button">
            <a class="cs-button cs-button--look_default cs-button--type_long" href="<?php $block->escapeUrl($block->getContinueShoppingUrl()) ?>">
                <?php /* @escapeNotVerified */ echo __('Continue shopping') ?>
                <svg class="cs-button__icon">
                    <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
                </svg>
            </a>
        </div>

        <?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
    </div>
</div>

