<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cs-cart-summary cs-cart-summary--empty">
    <?php echo $block->getChildHtml('checkout_cart_empty_widget'); ?>
    <p class="cs-t-text"><?php /* @escapeNotVerified */ echo __('You have no items in your shopping cart.') ?></p>
    <p class="cs-t-text"><?php /* @escapeNotVerified */ echo __('Click <a href="%1">here</a> to continue shopping.',
            $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    <?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
</div>
