<?php
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Checkout\Block\Cart\Shipping */ ?>

<div id="block-shipping" class="cs-cart-summary__shipping | cs-collapse">
    <div
        class="cs-cart-summary__trigger | cs-collapse__trigger cs-collapse__trigger--arrowed cs-collapse__trigger--arrow-right"
        data-role="title"
    >
        <p id="block-shipping-heading" role="heading" aria-level="2">
            <?php /* @escapeNotVerified */ echo $block->getQuote()->isVirtual() ? __('Estimate Tax') : __('Estimate Shipping and Tax') ?>
        </p>
        <svg class="cs-collapse__trigger-icon">
            <use xlink:href="#arrow_next"></use>
        </svg>
    </div>
    <div
        id="block-summary"
        data-bind="scope:'block-summary'"
        class="cs-cart-summary__shipping-content | cs-collapse__content"
        data-role="content"
        aria-labelledby="block-shipping-heading"
    >
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#block-summary": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
        </script>
        <script>
            window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
            window.customerData = window.checkoutConfig.customerData;
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function(url, blockLoader) {
                blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
                return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
            })
        </script>
    </div>
</div>
