<?php
/**
 * Template overridden to:
 * - add magesuite class
 *
 * Aligned with Magento 2.4.6 at 04/2023
 */

/**
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
?>
<div id="cart-totals" class="cs-cart-summary__totals" data-bind="scope:'block-totals'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
    </script>
</div>
