<?php
/**
 * Original elasticsuite instant search template overwritten, to integrate MageSuite header functionallity
 * For differences please refer to the original file.
 * - added cs-header__search class name to wrapper
 * - removed default block search wrappers
 * - added close icons to support hiding search on mobile
 * Aligned with Smile_ElasticsuiteInstantSearch v2.11.4.1 in 04/2024
 *
 * Note: Instant search renders search form as a react component, which reflects this html structure.
 * There should not be any layout shifts when react component is initialized and replaces this markup.
 *
 * @var $block \Smile\ElasticsuiteInstantSearch\Block\Search\Form\Autocomplete
 */
?>
<?php
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="cs-header__search">
    <form class="form minisearch cs-instant-search" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
        <div class="field search">
            <label class="label" for="search" data-role="minisearch-label">
                <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
            </label>
            <div class="control">
                <input id="search"
                       type="text"
                       name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                       value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                       placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                       class="input-text"
                       maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                       role="combobox"
                       aria-haspopup="false"
                       aria-autocomplete="both"
                       autocomplete="off"
                       data-block="autocomplete-form"/>
                <div id="search_autocomplete" class="search-autocomplete"></div>
            </div>
        </div>
        <div class="actions">
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
                    class="action search">
                <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
            </button>
        </div>
    </form>
    <span class="cs-instant-search__close">
        <?= $block->getChildHtml('top.instant-search.icon.close'); ?>
        <span class="cs-instant-search__close-label"><?= /* @escapeNotVerified */ __('Close search'); ?></span>
    </span>
</div>
<?php $scriptString = <<<script
    window.ES_REACT_AUTOCOMPLETE_PROPS = {
        formSelector:"search_mini_form",
        url:"{$block->getUrl('search/ajax/suggest')}",
        storeCode:"{$block->getStoreCode()}",
        name:"{$helper->getQueryParamName()}",
        maxLength: {$helper->getMaxQueryLength()},
        placeholder:"{$block->escapeHtml(__('Search entire store here...'))}",
        title:"{$block->escapeHtml(__('Search'))}",
        label:"{$block->escapeHtml(__('Search'))}",
        submitButton:"{$block->escapeHtml(__('Search'))}",
        templates: {$block->getJsonSuggestRenderers()},
        priceFormat : {$block->getJsonPriceFormat()},
        currencyCode : "{$block->getCurrencyCode()}",
        dataProviders: {$block->getDataProvidersConfiguration()},
        productTitle:"{$block->escapeHtml(__('Products'))}",
        noResultTitle:"{$block->escapeHtml(__('No results'))}",
        productInCategoryLabel:"{$block->escapeHtml(__('in'))}",
        translations: JSON.stringify({$block->getTranslationsConfig()})
    }
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
