<?php /** @var \Amasty\Promo\Block\Add $block */ ?>

<div class="cs-promo-products-link | ampromo-items-add" <?php echo $block->hasItems() ? '' : 'style="display:none;"'?>>
    <svg class="cs-promo-products-link__icon">
        <use xlink:href="#packaging"></use>
    </svg>
    <?php echo $block->getMessage()?>
</div>
<script>
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        var applyPopup = function() {
            var autoOpen = <?= $block->isOpenAutomatically() ? "true" : "false" ?> || window.location.hash == "#choose-gift";
            var overlay = $('[data-role=ampromo-overlay]');

            overlay.ampromoPopup({
                sourceUrl: '<?= $block->getUrl('amasty_promo/popup/reload') ?>',
                uenc:   '<?= $block->getCurrentBase64Url() ?>',
                slickSettings: {
                    slidesToShow: 3,
                    slidesToScroll: 3,
                    dots: true,
                    dotsClass: 'cs-promo-products__pagination',
                    infinite: false,
                    respondTo: 'slider',
                    prevArrow: '<button class="cs-promo-products__nav cs-promo-products__nav--prev" type="button"><svg class="cs-promo-products__nav-icon"><use xlink:href="#icon_arrow-left"></use></svg></button>',
                    nextArrow: '<button class="cs-promo-products__nav cs-promo-products__nav--next" type="button"><svg class="cs-promo-products__nav-icon"><use xlink:href="#icon_arrow-right"></use></svg></button>',
                    responsive: [
                        {
                            breakpoint: 571,
                            settings: {
                                slidesToShow: 2,
                                slidesToScroll: 2
                            }
                        },
                        {
                            breakpoint: 281,
                            settings: {
                                slidesToShow: 1,
                                slidesToScroll: 1
                            }
                        }
                    ]
                },
                commonQty: '<?= $block->getAvailableProductQty()['common_qty'] ?>',
                products: <?= \Zend_Json::encode($block->getAvailableProductQty()) ?>,
                formUrl: '<?= $block->getFormActionUrl() ?>',
                selectionMethod: '<?= $block->getSelectionMethod() ?>',
                giftsCounter: '<?= $block->getGiftsCounter() ?>',
                autoOpenPopup: autoOpen
            });

            overlay.on('reloaded', function (e, itemsCount) {
                $('.ampromo-items-add').toggle(itemsCount > 0)
            });

            $('[data-role=ampromo-popup-show]').click(function (){
                overlay.ampromoPopup('show');
                return false;
            });
        };

        require(['Amasty_Promo/js/popup'],  applyPopup);
    });
</script>
