<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php /** @var \Amasty\Promo\Block\Banner $block */?>
<?php /** @var \Amasty\Promo\Model\Rule $_rule */?>
<?php foreach($block->getValidRules() as $_rule) :?>
    <?php if ($block->getDescription($_rule) || $block->getImage($_rule) || $block->isShowGiftImages($_rule)):?>
        <div class="cs-promo-products-view">
            <?php if ($block->getDescription($_rule)): ?>
                <div class="cs-promo-products-view__desc | ampromo-desc">
                    <p><?php echo $block->getPageTemplateProcessor()->filter($block->getDescription($_rule)); ?></p>
                </div>
            <?php endif; ?>
            <?php $img = $block->getImage($_rule); ?>
            <?php if ($img) :?>
                <a class="cs-promo-products-view__img | ampromo-img" href="<?php echo $block->getLink($_rule);?>" title="<?php echo $block->escapeHtml($block->getHoverText($_rule)) ?>">
                    <img src="<?php echo $img;?>" alt="<?php echo $block->escapeHtml($block->getAlt($_rule)) ?>" title="<?php echo $block->escapeHtml($block->getHoverText($_rule)) ?>" />
                </a>
            <?php endif; ?>
            <?php if ($block->isShowGiftImages($_rule)) :?>
                <ul class="cs-promo-products-view__gift | ampromo-gift">
                    <?php /** @var \Magento\Catalog\Model\Product $product */?>
                    <?php foreach($block->getProducts($_rule) as $product): ?>
                        <?php
                        $product->getAttributeRawValue($product->getId(), $block->getAttributeHeader(), 1);
                        $id = uniqid("ampromo-gift-img-");
                        ?>
                        <li class="cs-promo-products-view__gift-item" >
                            <a class="cs-promo-products-view__gift-image | product-image" href="<?php echo $product->getProductUrl()?>">
                                <img title="" class="cs-promo-products-view__gift-banner | ampromo-banner-<?php echo $block->getPosition()?>-img" id="<?php echo $id;?>" width="<?php echo $block->getWidth();?>" height="<?php echo $block->getHeight();?>" src="<?php
                                echo $block->getImageHelper()->init($product, 'mini_cart_product_thumbnail')
                                    ->keepFrame(false)
                                    ->constrainOnly(true)
                                    ->resize($block->getWidth())
                                    ->getUrl();
                                ?>"/>
                                <div class="cs-promo-products-view__gift-desc" id="<?php echo $id;?>-data">
                                    <div class="cs-promo-products-view__gift-name | ampromo-product-name"><?php echo $product->getResource()->getAttribute($block->getAttributeHeader())->getFrontend()->getValue($product);?></div>
                                    <div class="cs-promo-products-view__gift-short-desc | ampromo-short-description">
                                        <?php echo $product->getResource()->getAttribute($block->getAttributeDescription())->getFrontend()->getValue($product);?>
                                    </div>
                                </div>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    <?php endif;?>
<?php endforeach; ?>
<script>
    require([
        'tooltip',
        'jquery'
    ], function(tooltip, $) {
        $('.ampromo-banner-<?php echo $block->getPosition()?>-img').each(function(key, image){
            tooltip({
                tooltipClass: "cs-promo-products-view__tooltip | ampromo-banner-tooltip",
                content: function () {
                    return $('#' + this.id + '-data').html();
                },
            }, image);
        });
    });
</script>
