<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php
/** @var \Amasty\Promo\Block\Items $block */
use Magento\Framework\App\Action\Action;

$products = $block->getItems();
$imageHelper = $block->getImageHelper();
?>

<div class="cs-promo-products-list | ampromo-gallery" data-count="<?php echo $products ? count($products) : 0 ?>" data-role="ampromo-gallery">
    <?php if ($products)
        foreach ($products as $product): ?>
            <div class="cs-promo-products-list__item | ampromo-item" data-product-id="<?php echo $product->getId()?>" data-product-sku="<?php echo $product->getSku()?>">
                <form method="POST" action="<?php echo $block->getFormActionUrl()?>" class="cs-promo-products-list__form | ampromo_items_form" id="ampromo_items_form-<?php echo $product->getId()?>">
                    <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $block->getCurrentBase64Url() ?>">
                    <div class="cs-promo-products-list__item-name | ampromo-item-title">
                        <?php if ($product->getVisibility() != \Magento\Catalog\Model\Product\Visibility::VISIBILITY_NOT_VISIBLE):?>
                            <a href="<?php echo $product->getProductUrl()?>"><?php echo $product->getName()?></a>
                        <?php else: ?>
                            <h4><?php echo $product->getName()?></h4>
                        <?php endif?>
                    </div>
                    <?php $imageHelper->init($product, 'cart_page_product_thumbnail')
                        ->keepFrame(false)
                        ->constrainOnly(true)
                        ->resize(160, 160)
                    ;
                    ?>
                    <img src="<?php echo $imageHelper->getUrl() ?>" class="cs-promo-products-list__item-image | ampromo-item-image" alt="<?php echo $block->stripTags($product->getName(), null, true) ?>"/>

                    <input type="hidden" value="<?php echo $product->getId() ?>" name="product_id" />

                    <div class="cs-promo-products-list__item-options | product-options-wrapper" id="product-options-wrapper">
                        <fieldset class="cs-promo-products-list__item-fieldset | fieldset" tabindex="0">
                            <?php if ($optionsBlock = $block->getChildBlock($product->getTypeId() . '_prototype')): ?>
                                <?php echo $optionsBlock->setProduct($product)->toHtml(); ?>
                            <?php endif ?>
                            <?php echo $block->getChildBlock('options_prototype')->setProduct($product)->toHtml(); ?>
                        </fieldset>
                    </div>

                    <div class="cs-promo-products-list__button-wrapper | ampromo-item-buttons">
                        <button class="cs-promo-products-list__button | action tocart primary" type="submit" title="<?php echo __('Add to cart')?>"><span class="cs-button__span"><?php echo __('Add to cart')?></span></button>
                    </div>
                </form>
            </div>
        <?php endforeach ?>
</div>