<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php /** @var \Amasty\Promo\Block\Banner $block */?>
<?php foreach($block->getValidRules() as $_rule) :?>
    <?php if ($block->getLabelImage($_rule)): ?>
        <img class="cs-promo-products-label | ampromo-label" alt="<?php echo $block->getLabelImageAlt($_rule);?>" src="<?php
        echo $block->getLabelImage($_rule);
        ?>">
    <?php endif;?>
<?php endforeach; ?>