<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Promo
 */
?>
<?php
/** @var \Amasty\Promo\Block\Popup $block */
?>

<?= $block->getChildHtml('html_calendar') ?>
<div class="cs-overlay | ampromo-overlay" data-role="ampromo-overlay">
    <div class="cs-promo-products">
        <div class="cs-promo-products__container | ampromo-items">
            <div class="cs-promo-products__close | close" data-role="ampromo-popup-hide">
                <svg class="cs-promo-products__close-icon">
                    <use xlink:href="#close"></use>
                </svg>
            </div>

            <h3><?=__('Free Items')?></h3>

            <div data-role="cs-promo-products__items | ampromo-items-container">
                <?= $block->getChildHtml('items') ?>
            </div>
        </div>
    </div>
</div>