<?php
/**
 * @codingStandardsIgnoreFile
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */

?>
<?php if ($block->getCurrencyCount()>1): ?>
<?php
    $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
    $showCurrencyIcons = $block->getShowCurrencyIcons();
    $showLabels = $block->getShowLabels();
    $currencies = $block->getCurrencies();
    $currentCurrencyCode = $block->escapeHtml($block->getCurrentCurrencyCode());
?>
    <div class="switcher currency switcher-currency cs-dropdown-switcher <?= $block->getAdditionalCssClasses(); ?>" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
        <span class="cs-visually-hidden label switcher-label"><span><?= $block->escapeHtml(__('Currency')) ?></span></span>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger cs-dropdown-switcher__trigger" id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>">
                <span class="language-<?= $currentCurrencyCode ?> cs-dropdown-switcher__trigger-span ">
                    <?php if ($showCurrencyIcons): ?>
                        <?= $this->getLayout()
                            ->createBlock(MageSuite\ThemeHelpers\Block\Icon::class)
                            ->setIconUrl('images/icons/currency_'.strtolower($currentCurrencyCode).'.svg')
                            ->setCssClass('cs-dropdown-switcher__option-icon cs-dropdown-switcher__option-icon--'.strtolower($currentCurrencyCode).' cs-dropdown-switcher__option-icon--active')
                            ->setAltText($currentCurrencyCode)
                            ->toHtml(); ?>
                    <?php endif ?>
                    <?php if ($showLabels): ?>
                        <?= $currentCurrencyCode ?> 
                    <?php endif ?>
                    <?= $block->getChildHtml('currency.trigger-icon'); ?>
                </span>
            </div>
            <ul class="dropdown switcher-dropdown cs-dropdown-switcher__list"
                data-target="dropdown"
                data-mage-init='{"dropdownDialog":{
                    "appendTo":"#switcher-currency<?= /* @escapeNotVerified */ $id ?> > .options",
                    "triggerTarget":"#switcher-currency-trigger<?= /* @escapeNotVerified */ $id ?>",
                    "closeOnMouseLeave": false,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":null}}'>
                <?php foreach ($currencies as $_code => $_name): ?>
                        <?php if ($_code != $currentCurrencyCode): ?>
                            <?php $code = $block->escapeHtmlAttr($_code) ?>
                            <li class="currency-<?= $code ?> switcher-option cs-dropdown-switcher__list-item">
                                <a class="cs-dropdown-switcher__list-item-link" href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'>
                                    <?php if ($showCurrencyIcons): ?>
                                        <?= $this->getLayout()
                                            ->createBlock(MageSuite\ThemeHelpers\Block\Icon::class)
                                            ->setIconUrl('images/icons/currency_'.strtolower($code).'.svg')
                                            ->setCssClass('cs-dropdown-switcher__option-icon cs-dropdown-switcher__option-icon--'.strtolower($code))
                                            ->setAltText($code)
                                            ->toHtml(); ?>
                                    <?php endif ?>
                                    <?php if ($showLabels): ?>
                                        <?= $code ?>
                                    <?php endif ?>
                                </a>
                            </li>
                        <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
