<?php
/**
 * Async font loading based on https://timkadlec.com/remembers/2020-02-13-when-css-blocks
 */

$webFonts = $block->getWebFonts();
$localFonts = $block->getLocalFonts();

if (!empty($webFonts)):
    /**
     * Loop through all web fonts defined in XML
     */
    foreach ($webFonts as $url):
        if (!empty($url)): ?>
            <link rel="stylesheet" href="<?= $url ?>" media="print" onload="this.onload=null;this.media='all'">
            <noscript><link rel="stylesheet" href="<?= $url ?>"></noscript>
            <?php if (strpos($url, 'fonts.googleapis') !== false): ?>
                <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
            <?php endif;
        endif;
    endforeach;
endif;

if (!empty($localFonts)):
    /**
     * Loop through all local fonts defined in XML
     */
    foreach ($localFonts as $url):
        if (!empty($url)):
            $localFontUrl = $this->getViewFileUrl($url); ?>
            <link rel="stylesheet" href="<?= $localFontUrl ?>" media="print" onload="this.media='all'">
            <noscript><link rel="stylesheet" href="<?= $localFontUrl ?>"></noscript>
        <?php endif;
    endforeach;
endif;
