<?php
/**
 * Font loading based on https://dev.to/masakudamatsu/loading-google-fonts-and-any-other-web-fonts-as-fast-as-possible-in-early-2021-4f5o
 */

$webFonts = $block->getWebFonts();
$localFonts = $block->getLocalFonts();

if (!empty($webFonts)):
    /**
     * Loop through all web fonts defined in XML
     */
    foreach ($webFonts as $url):
        if (!empty($url)): ?>
            <?php if (strpos($url, 'fonts.googleapis') !== false): ?>
                <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
            <?php endif; ?>
            <link rel="preload" as="style" href="<?= $url ?>">
            <link rel="stylesheet" href="<?= $url ?>" media="print" onload="this.onload=null;this.media='all'">
            <noscript><link rel="stylesheet" href="<?= $url ?>"></noscript>
        <?php endif;
    endforeach;
endif;

if (!empty($localFonts)):
    /**
     * Loop through all local fonts defined in XML
     */
    foreach ($localFonts as $url):
        if (!empty($url)):
            $localFontUrl = $this->getViewFileUrl($url); ?>
            <link rel="preload" as="style" href="<?= $localFontUrl ?>">
            <link rel="stylesheet" href="<?= $localFontUrl ?>" media="print" onload="this.media='all'">
            <noscript><link rel="stylesheet" href="<?= $localFontUrl ?>"></noscript>
        <?php endif;
    endforeach;
endif; ?>
