
<?php if ($block->getVar('redirect_progress_bar/enabled', 'Magento_Theme')) : ?>
<script data-defer-ignore="true">
    window.onbeforeunload = function() {
        const progressElement = document.createElement("div")
        progressElement.classList.add("cs-redirect-progress-bar");

        setTimeout(() => {
            document.body.prepend(progressElement);
        });

        // Remove indicator after 30 seconds
        setTimeout(() => {
            progressElement.remove();
        }, 30000);

        return null;
    };
</script>
<?php endif; ?>