<?php
/**
 * Custom template
 * Loading redirect progress bar script
 */
?>
<?php if ($block->getVar('redirect_progress_bar/enabled', 'Magento_Theme')) : ?>
<script data-defer-ignore="true">
    window.addEventListener('beforeunload', function() {
        const progressElement = document.createElement("div")
        progressElement.classList.add("cs-redirect-progress-bar");

        setTimeout(() => {
            document.body.prepend(progressElement);
        });

        // Remove indicator after 30 seconds
        setTimeout(() => {
            progressElement.remove();
        }, 30000);

        // Remove the element when the page is hidden (handle back/forward cache)
        window.addEventListener('pagehide', function() {
            if (progressElement) {
                progressElement.remove();
            }
        });

        return null;
    });
</script>
<?php endif; ?>
