<?php 
/** 
* Custom template to preload category image in order to improve LCP
* see https://web.dev/optimize-lcp/#preload-important-resources 
*/ 

// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Category\View */
?>
<?php
    $category = $block->getCurrentCategory();
    $image = $block->getImage();
?>

<?php if ($image): ?>
    <?php 
        $imgUrl = $image->getUrl($category);
    ?>
    <link rel="preload" href="<?= $block->escapeUrl($imgUrl) ?>" as="image">
<?php endif; ?>
