<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder() ?>
<div class="cs-info-block | cs-dashboard__block">
    <div class="cs-info-block__buttons">
        <a href="<?php /* @escapeNotVerified */ echo $block->getPrintAllCreditmemosUrl($_order) ?>"
           onclick="this.target='_blank'"
           class="cs-button cs-button--size_300 cs-button--look_default">
            <?php /* @escapeNotVerified */ echo __('Print All Refunds') ?>
            <svg class="cs-button__icon">
                <use xlink:href="<?= $this->getViewFileUrl('images/sprites.svg'); ?>#arrow_next"></use>
            </svg>
        </a>
    </div>
    <?php foreach ($_order->getCreditmemosCollection() as $_creditmemo): ?>
        <div class="cs-info-block__title cs-info-block__title--space-top | cs-title-block cs-title-block--bordered">
            <div class="cs-title-block__span | cs-t-headline cs-t-headline--size_2 cs-t-headline--look_light"><?php /* @escapeNotVerified */ echo __('Refund #') ?><?php /* @escapeNotVerified */ echo $_creditmemo->getIncrementId(); ?> </div>
            <span class="cs-t-headline__span">
                <a href="<?php /* @escapeNotVerified */ echo $block->getPrintCreditmemoUrl($_creditmemo) ?>"
                   onclick="this.target='_blank'"
                   class="cs-link">
                    <?php /* @escapeNotVerified */ echo __('Print Refund') ?>
                </a>
            </span>

        </div>

        <div class="cs-table | order-items-creditmemo">
            <table class="cs-table__body | creditmemo" id="my-refund-table-<?php /* @escapeNotVerified */ echo $_creditmemo->getId(); ?>">
                <caption class="cs-visually-hidden"><?php /* @escapeNotVerified */ echo __('Items Refunded') ?></caption>
                <thead class="cs-table__head">
                <tr>
                    <th class="cs-table__col-head | name"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                    <th class="cs-table__col-head | sku"><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
                    <th class="cs-table__col-head | price"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                    <th class="cs-table__col-head | qty"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
                    <th class="cs-table__col-head | subtotal"><?php /* @escapeNotVerified */ echo __('Subtotal') ?></th>
                    <th class="cs-table__col-head | discount"><?php /* @escapeNotVerified */ echo __('Discount Amount') ?></th>
                    <th class="cs-table__col-head | total"><?php /* @escapeNotVerified */ echo __('Row Total') ?></th>
                </tr>
                </thead>
                <?php $_items = $_creditmemo->getAllItems(); ?>
                <?php $_count = count($_items) ?>
                <?php foreach ($_items as $_item): ?>
                    <?php if ($_item->getOrderItem()->getParentItem()) {
                        continue;
                    } ?>
                    <tbody class="cs-table__tbody">
                    <?php echo $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endforeach; ?>
                <tfoot class="cs-table__foot">
                <?php echo $block->getTotalsHtml($_creditmemo);?>
                </tfoot>
            </table>
        </div>
        <?php echo $block->getCommentsHtml($_creditmemo)?>
    <?php endforeach; ?>

</div>
