<?php
/**
* Template overwritten to:
* - add magesuite classes
* - wrap in li tag
* - add title attribute
* - add child block and customizable label
* Aligned with Magento 2.4.8 in 05/2025
*/
/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <?php
        $product = $block->getProduct();
        $productId = $product->getId();
    ?>
    <li class="cs-buybox__addto-item <?= $block->getAdditionalCssClasses() ?>">
        <a href="#"
           class="action towishlist cs-buybox__addto-link"
           title="<?= $escaper->escapeHtmlAttr($block->getLinkLabel()) ?? __('Add to wishlist') ?>"
           data-role="add-to-links"
           data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
           data-uenc-update='true'
           data-action="add-to-wishlist"
           data-product-id="<?= $escaper->escapeHtmlAttr($productId) ?>"
        >
            <?= /* @noEscape */ $block->getChildHtml('') ?>
            <span class="cs-buybox__addto-link-text"><?= $escaper->escapeHtml($block->getLinkLabel()) ?></span>
        </a>
    </li>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
