<?php
    $label = $block->getXmlLabel();
?>
<li class="cs-header-user-nav__item <?= $block->getAdditionalCssClasses() ?>">
    <span class="cs-header-user-nav__link cs-header-user-nav__link--search">
        <div class="cs-header-user-nav__icon-wrapper">
            <?= $block->getChildHtml('search-link.icon'); ?>
            <?php if (!empty($label)): ?>
                <span class="cs-header-user-nav__label"><?= $block->escapeHtml($label) ?></span>
            <?php endif; ?>
        </div>
    </span>
</li>
