<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
    $product = $block->getProduct();
    $buttonTitle = __('Update Cart');
?>
<?php if ($product->isSaleable()): ?>
    <div class="cs-box-addtocart | update">
        <div class="cs-box-addtocart__fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="cs-box-addtocart__qty-wrapper">
                    <label class="cs-label | cs-box-addtocart__label" for="qty">
                        <?php /* @escapeNotVerified */ echo __('Qty') ?>
                    </label>

                    <div class="cs-box-addtocart__qty-increment">
                        <?php $qtyValidators = $block->getQuantityValidators(); ?>
                        <?= $this->getLayout()
                              ->createBlock(\Magento\Framework\View\Element\Template::class)
                              ->setInputName('qty')
                              ->setInputInitialValue($block->getProductDefaultQty() * 1)
                              ->setInputAdditionalParams('data-validate="'.$block->escapeHtml(json_encode($qtyValidators)).'" min="'.$qtyValidators["validate-item-quantity"]["minAllowed"].'" max="'.$qtyValidators["validate-item-quantity"]["maxAllowed"].'"')
                              ->setDecrementIconUrl($block->getViewFileUrl($block->getVar('qty_increment/icons/decrement', 'MageSuite_ThemeHelpers')))
                              ->setIncrementIconUrl($block->getViewFileUrl($block->getVar('qty_increment/icons/increment', 'MageSuite_ThemeHelpers')))
                              ->setTemplate($block->getVar('qty_increment/template', 'MageSuite_ThemeHelpers'))
                              ->toHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="cs-box-addtocart__actions">
                <button
                    type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart cs-buybox__update"
                    id="product-updatecart-button"
                >
                    <span class="cs-buybox__update-span"><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
