<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
    $product = $block->getProduct();
    $buttonTitle = __('Update Cart');
?>
<?php if ($product->isSaleable()): ?>
    <div class="cs-box-addtocart | update">
        <div class="cs-box-addtocart__fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="cs-box-addtocart__qty-wrapper">
                    <label class="cs-label | cs-box-addtocart__label" for="qty">
                        <?php /* @escapeNotVerified */ echo __('Qty') ?>
                    </label>

                    <div class="cs-box-addtocart__qty-increment">
                        <?=$this->getLayout()->createBlock(
                            'Creativestyle\FrontendExtension\Block\Twig',
                            'add-to-cart-pdp', [
                                'data' => [
                                    "namespace" => 'cs-',
                                    "minValue" => /* @escapeNotVerified */ $block->getProductDefaultQty() * 1,
                                    "initialValue" => /* @escapeNotVerified */ $block->getProductDefaultQty() * 1,
                                    "maxLength" => 12,
                                    "size" => 2,
                                    "name" => 'qty',
                                    "inputParams" => 'data-validate="'.$block->escapeHtml(json_encode($block->getQuantityValidators())).'"',
                                    "icons" => [
                                        "increment" => '#plus',
                                        "decrement" => '#minus'
                                    ]
                                ]
                            ]
                        )->setTemplate( "qty-increment/qty-increment.twig" )->toHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="cs-box-addtocart__actions">
                <button
                    type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="cs-button cs-button--type_wide cs-button--type_cart"
                    id="product-updatecart-button"
                >
                    <svg class="cs-button__icon cs-button__icon--cart">
                        <use xlink:href="#cart"></use>
                    </svg>
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
