<?php
/**
* Template overridden to:
* - use CC carousel 
* - change headline wordings
*/

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $isWeightedRandom = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You might like...');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $isWeightedRandom = (int) $block->getRotation()->isWeightedRandom($block->getProductListType());

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('You might like...');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $isWeightedRandom = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
?>

<?php if ($exist): ?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div
                class="block products-<?= $block->escapeHtmlAttr($class) ?>"
                data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
                data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
                data-shuffle="<?= /* @noEscape */ $shuffle ?>"
                data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>"
            >
        <?php else: ?>
            <div
                class="block products-<?= $block->escapeHtmlAttr($class) ?>"
                data-mage-init='{"upsellProducts":{}}'
                data-limit="<?= $block->escapeHtmlAttr($limit) ?>"
                data-shuffle="<?= /* @noEscape */ $shuffle ?>"
                data-shuffle-weighted="<?= /* @noEscape */ $isWeightedRandom ?>"
            >
        <?php endif; ?>
    <?php else: ?>
        <div class="block products-<?= $block->escapeHtmlAttr($class) ?>">
    <?php endif; ?>

    <?php if ($block->getIncludeHeadline() ?? true): ?>
        <?= $block->getLayout()->createBlock(
            '\MageSuite\ContentConstructorFrontend\Block\Component', 'carousels-headline-'.$type, [
                'data' => [
                    'section' => 'content',
                    'type' => 'headline',
                    'data' => [
                        'title' => $title
                    ]
                ],
            ]
        )->toHtml(); ?>
    <?php endif; ?>

    <?php
    $productIds = [];

    foreach ($items as $item) {
        $productIds[] = $item->getEntityId();
    }

    echo $this->getLayout()->createBlock(
        \MageSuite\ContentConstructorFrontend\Block\Component::class, '', [
            'data' => [
                'type' => 'product-carousel',
                'data' => [
                    'carousel_on_mobile' => $block->getCarouselOnMobile(),
                    'view_mode' => $block->getViewMode(),
                    'product_ids' => $productIds
                ]
            ]
        ]
    )->toHtml();

    ?>
    </div>
<?php endif;?>
