<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

?>
<?php if ($block->getCollection()->getSize()): ?>
    <?php if ($block->getTotalNum()): ?>
    <div class="page-title__span | js-page-title-product-amount"> <?php echo '  (' . $block->getTotalNum() . ')'; ?></div>
    <?php endif ?>
    <div class="cs-category-page__toolbar" data-mage-init='<?php /* @escapeNotVerified */
    echo $block->getWidgetOptionsJson(); ?>'>

        <div class="cs-category-page__toolbar-left">
            <?php if ($block->isExpanded()): ?>
                <?php include($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
            <?php endif; ?>

            <?php include($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

            <?php if ($block->isExpanded()): ?>
                <?php include($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
            <?php endif; ?>

            <?php include($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

        </div>
        <div class="cs-category-page__toolbar-right">
            <?php echo $block->getPagerHtml() ?>
        </div>

    </div>
<?php endif ?>

<script>
    require([
        "jquery"
    ], function($){

        function updateItemsAmount() {
            $( '.page-title .js-page-title-product-amount' ).remove();
            $( '.js-page-title-product-amount' ).each( function( i, el ) {
                if ( i === 0 ) {
                    $( el ).appendTo( '.page-title' );
                }
            } );
        }

        updateItemsAmount();

        $( '.cs-aftersearch-nav button' ).on( 'click', updateItemsAmount );

    });
</script>

