<?php
/**
* Template overridden to:
* - add xml configuration (etc/view.xml) with possibility to hide some toolbar elements
*/

/** @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar */
// phpcs:disable Magento2.Security.IncludeFile.FoundIncludeFile
// phpcs:disable PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket
?>
<?php if ($block->getCollection()->getSize()): ?>
    <?php 
        $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
        $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div 
        class="toolbar toolbar-products cs-toolbar <?= $block->getAdditionalCssClasses() ?>" 
        data-mage-init='<?= /* @noEscape */ $widgetOptions ?>'
    >
        <?php if ($block->getVar('toolbar/filters_offcanvas_button/display', 'Magento_Catalog')): ?>
            <div class="cs-toolbar__item cs-toolbar__item--offcanvas">
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/filters-button.phtml')); ?>
            </div>
        <?php endif; ?>
        
        <?php if ($block->getVar('toolbar/amount/display', 'Magento_Catalog')): ?>
            <div class="cs-toolbar__item cs-toolbar__item--amount">
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')); ?>
            </div>
        <?php endif; ?>

        <?php if ($block->isExpanded() && $block->getVar('toolbar/sorter/display', 'Magento_Catalog')): ?>
            <div class="cs-toolbar__item cs-toolbar__item--sorter">
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')); ?>
            </div>
        <?php endif; ?>

        <?php if ($block->getVar('toolbar/limiter/display', 'Magento_Catalog')): ?>
            <div class="cs-toolbar__item cs-toolbar__item--limiter">
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')); ?>
            </div>
        <?php endif; ?>

        <?php if ($block->isExpanded() && $block->getVar('toolbar/viewmode_switcher/display', 'Magento_Catalog')): ?>
            <div class="cs-toolbar__item cs-toolbar__item--viewmode-switcher">
                <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')); ?>
            </div>
        <?php endif; ?>

        <?php if ($block->getVar('toolbar/pagination/display', 'Magento_Theme')): ?>
            <div class="cs-toolbar__item cs-toolbar__item--pagination">
                <?= $block->getPagerHtml(); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif ?>
