<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
$_items = $block->getReviewsCollection()->getItems();
?>
<div class="cs-reviews__title | cs-collapse__trigger">
    <h2 class="cs-t-headline cs-t-headline--size_2"><?php /* @escapeNotVerified */ echo __('Customer Reviews') ?> <span class="cs-t-headline__span">(<?php echo count($_items) ?>)</span></h2>
</div>


