<?php
/**
* Template overridden to add Magesuite stars component include
*/

/**
* @var \Magento\Review\Block\Customer\Recent $block
* @var \Magento\Framework\Escaper $escaper
* @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
*/
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>
<div class="block block-reviews-dashboard">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('My Recent Reviews')) ?></strong>
        <a class="action view" href="<?= $escaper->escapeUrl($block->getAllReviewsUrl()) ?>"><span><?= $escaper->escapeHtml(__('View All')) ?></span></a>
    </div>
    <div class="block-content">
        <ol class="items">
        <?php foreach ($block->getReviews() as $review): ?>
            <li class="item">
                <strong class="product-name"><a href="<?= $escaper->escapeUrl($block->getReviewUrl($review->getReviewId())) ?>"><?= $block->escapeHtml($review->getName()) ?></a></strong>
                <?php if ($review->getSum()): ?>
                <?php              
                    $review_count = $review->getCount();
                    $rating = $review->getSum() / $review_count;
                    $dividedRating = floor(($rating / 20) * 2) / 2;
                ?>
                    <?= $this->getLayout()
                            ->createBlock(\Magento\Framework\View\Element\Template::class)
                            ->setMaxStars(5)
                            ->setActiveStars($dividedRating)
                            ->setReviewsCount($dividedRating)
                            ->setHideReviewsCount(true)
                            ->setTemplate('Magento_Review::rating-stars.phtml')
                            ->toHtml();
                    ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
