<?php

// @codingStandardsIgnoreFile

?>
<?php
$product = $block->getProductData();
?>
<?php if ($product->getId()): ?>
    <div class="cs-reviews cs-reviews--single">
        <div class="cs-reviews__product-details">
            <div class="cs-reviews__product-media">
                <a class="cs-reviews__product-photo" href="<?php /* @escapeNotVerified */ echo $product->getProductUrl
                () ?>">
                    <?php /* customer_account_product_review_page */ ?>
                    <?php echo $block->getImage($block->getProductData(), 'customer_account_product_review_page')->toHtml() ?>
                </a>
            </div>
            <div class="cs-reviews__product-info">
                <h2 class="cs-reviews__single-name"><?php echo $block->escapeHtml($product->getName()) ?></h2>
                <?php if ($block->getRating() && $block->getRating()->getSize()): ?>
                    <span class="cs-reviews__rating-average-label">
                        <?php /* @escapeNotVerified */ echo __('Average Customer Rating:') ?>
                    </span>
                    <?php echo $block->getReviewsSummaryHtml($product) ?>
                <?php endif; ?>
            </div>
        </div>

        <div class="cs-reviews">
            <?php if ($block->getRating() && $block->getRating()->getSize()): ?>
                <h2 class="cs-reviews__legend | cs-t-headline">
                    <?php /* @escapeNotVerified */ echo __('Your Review'); ?>
                </h2>
                <div class="cs-reviews__form-wrapper">
                    <?php foreach ($block->getRating() as $reviewRating): ?>
                        <?php if ($reviewRating->getPercent()): ?>
                            <?php $rating = ceil($reviewRating->getPercent()) ?>
                                <h3 class="cs-reviews__subtitle">
                                    <?php echo $block->escapeHtml($reviewRating->getRatingCode()) ?>
                                </h3>
                                <div class="cs-reviews__content">
                                <?= $this->getLayout()->createBlock('MageSuite\Frontend\Block\Twig', 'my-review-rating-',
                                        ['data' => [
                                            'namespace' => 'cs-',
                                            'maxStars' => 5,
                                            'activeStars' => $rating/20,
                                            'text' => ''
                                        ]
                                        ])->setTemplate("star-rating/star-rating.twig")->toHtml(); ?>
                                </div>

                        <?php endif; ?>
                    <?php endforeach; ?>

                </div>
            <?php endif; ?>

            <h3 class="cs-reviews__subtitle">
                <?php echo __( 'Review title' ); ?>
            </h3>
            <div class="cs-reviews__content">
                <?php echo $block->escapeHtml($block->getReviewData()->getTitle()) ?>
            </div>

            <h3 class="cs-reviews__subtitle">
                <?php echo __( 'Review content' ); ?>
            </h3>
            <div class="cs-reviews__content">
                <?php echo nl2br($block->escapeHtml($block->getReviewData()->getDetail())) ?>
            </div>

            <h3 class="cs-reviews__subtitle">
                <?php echo __( 'Review date' ); ?>
            </h3>
            <div class="cs-reviews__content">
                <?php /* @escapeNotVerified */ echo __('Submitted on %1', '<time class="date">' . $block->dateFormat($block->getReviewData()->getCreatedAt()) . '</time>') ?>
            </div>

        </div>
    </div>
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="cs-link" href="<?php /* @escapeNotVerified */ echo $block->getBackUrl() ?>"><span><?php /*
            @escapeNotVerified */ echo __('Back to My Reviews') ?></span></a>
        </div>
    </div>
<?php endif; ?>
