<?php
    /** @var \Magento\Catalog\Block\Product\View\Description $block */
    $helper = $this->helper('MageSuite\Frontend\Helper\Product');
    $badgeValue = $helper->getSalePercentage($block->getProduct());
    $productId = $block->getProduct()->getId();

    $renderBadgeDynamicallyConfigurables = $block->getRenderBadgeDynamicallyConfigurables();
    $discountsPerProduct = $helper->getConfigurableDiscounts($block->getProduct());
    ?>

<?php if($badgeValue): ?>
    <?php
        $label = $block->getLabel();
        $value = $block->getValueDisplay();

        $wrapperTag = $block->getWrapperTag() ?? 'li';

        $wrapperClass = $block->getWrapperCssClass();
        $wrapperClass = $wrapperClass ? sprintf('class="%s"', $wrapperClass) : '';

        $cssClass = $block->getCssClass();
        $cssClass = $cssClass ? sprintf('class="%s"', $cssClass) : '';

        $badgeTextClass = $block->getTextCssClass();
        $badgeTextClass = $badgeTextClass ? sprintf('class="%s"', $badgeTextClass) : '';

        $configurablesText = $block->getConfigurablesDefaultBadgeText();

        $valuePrefix = $block->getValuePrefix();
        $valueSuffix = $block->getValueSuffix();
    ?>
    <<?= $wrapperTag ?> <?= $wrapperClass ?>>
        <span <?= $cssClass ?>>
        <?php if ($label): ?>
            <span <?= $badgeTextClass ?>><?= $label ?></span>
        <?php endif; ?>
        <?php if ($value): ?>
            <span <?= $badgeTextClass ?>>
                <span class="cs-page-product__badge-discount-text"><?= $configurablesText ?></span>
                <?= $valuePrefix ?>
                <span class="cs-page-product__badge-discount-value"><?= $badgeValue ?></span>
                <?= $valueSuffix ?>
            </span>
        <?php endif; ?>
        </span>

    </<?= $wrapperTag ?>>
<?php endif; ?>

<?php if ($renderBadgeDynamicallyConfigurables): ?>
    <script type="text/x-magento-init">
        {
            ".cs-buybox": {
                "Magento_Catalog/js/product/view/sale-badge-renderer": {
                    "discountsList": <?= /* @noEscape */ json_encode($discountsPerProduct); ?>
                }
            }
        }
    </script>
<?php endif; ?>



