<?php
// @codingStandardsIgnoreFile
/* @var \Magento\Wishlist\Block\Link $block */
    $label = $block->getXmlLabel();
?>
<li class="link wishlist cs-header-user-nav__item <?= $block->getAdditionalCssClasses() ?>" data-bind="scope: 'wishlist'">
    <a class="cs-header-user-nav__link" <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <div class="cs-header-user-nav__icon-wrapper">
            <?= $block->getChildHtml('wish-list-link.icon'); ?>
            <span class="cs-header-user-nav__qty-counter <?= $block->getBadgeAdditionalCssClasses() ?>" data-bind="css: { 'cs-header-user-nav__qty-counter--have-items': wishlist().counter, 'cs-header-user-nav__qty-counter--empty': !wishlist().counter }">
                <span class="counter qty cs-header-user-nav__qty-counter-span">
                    <!-- ko if: wishlist().counter -->
                        <!-- ko text: parseInt(wishlist().counter) --><!-- /ko -->
                    <!-- /ko -->
                    <!-- ko if: !wishlist().counter -->
                    0
                    <!-- /ko -->
                </span>
            </span>
        </div>
        <?php if(!empty($label)): ?>
            <span class="cs-header-user-nav__label"><?= $block->escapeHtml($label) ?></span>
        <?php endif; ?>
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
