<?php
// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Customer\Wishlist\Item\Options */
$options = $block->getOptionList();
?>
<?php if ($options): ?>
<div class="cs-attributes-list">
    <dl class="cs-attributes-list__list" >
        <?php foreach ($options as $option): ?>
            <dt class="cs-attributes-list__item-label"><?php echo $block->escapeHtml($option['label']) ?></dt>
            <dd class="cs-attributes-list__item">
                <?php if (is_array($option['value'])): ?>
                    <?php /* @escapeNotVerified */ echo nl2br(implode("\n", $option['value'])) ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo $option['value'] ?>
                <?php endif; ?>
            </dd>
        <?php endforeach; ?>
    </dl>
</div>
<?php endif ?>

