<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Wishlist\Block\Customer\Wishlist */
?>

<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
    <?php echo($block->getChildHtml('wishlist.rss.link'));?>
    <form class="cs-dashboard__block | cs-wishlist" id="wishlist-view-form"
          data-mage-init='{"wishlist":{
          "addToCartUrl":<?php /* @escapeNotVerified */ echo $block->getItemAddToCartParams("%item%");?>,
          "addAllToCartUrl":<?php /* @escapeNotVerified */ echo $block->getAddAllToCartParams(); ?>,
          "commentString":""},
          "validation": {}}' action="<?php /* @escapeNotVerified */ echo $block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId()]) ?>" method="post">
        <?php echo $block->getChildHtml('top'); ?>
        <?php if ($block->hasWishlistItems()): ?>
            <?php echo $block->getBlockHtml('formkey');?>
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?php echo $block->getChildHtml('items');?>
            <div class="cs-wishlist__buttons">
                <?php echo $block->getChildHtml('control_buttons');?>
            </div>
        <?php else: ?>
            <div class="cs-wishlist__line | cs-t-text cs-t-text--look_light"><span><?php /* @escapeNotVerified */ echo __('You have no items in your wish list.') ?></span></div>
        <?php endif ?>
        <?php echo $block->getChildHtml('bottom'); ?>
    </form>
    <script id="form-tmpl" type="text/x-magento-template">
        <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
            <% if (data.qty) { %>
            <input name="qty" value="<%- data.qty %>">
            <% } %>

            <% if (data.item) { %>
            <input name="item" value="<%- data.item %>">
            <% } %>

            <% if (data.entity) { %>
            <input name="entity" value="<%- data.entity %>">
            <% } %>
        </form>
    </script>
<?php endif ?>
