<?php
// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$item = $block->getItem();
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $item->getId() ?>">
    <td class="cs-table__col | name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <span class="cs-t-text cs-t-text--look_attention | product-item-name"><?php echo $block->escapeHtml($item->getName()) ?></span>
        <?php if ($options = $block->getItemOptions()): ?>
            <div class="cs-cart-item__options">
                <?php foreach ($options as $option) : ?>
                    <dl class="cs-cart-item__options-group | item-options">
                        <dt class="cs-cart-item__options-label">
                            <?php echo $block->escapeHtml($option['label']) ?>
                        </dt>
                        <?php if (!$block->getPrintStatus()): ?>
                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                            <dd class="cs-cart-item__options-value">
                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                    <?php /* @escapeNotVerified */ echo $formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?php /* @escapeNotVerified */ echo $formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd class="cs-cart-item__options-value">
                                <?php echo nl2br($block->escapeHtml((isset($option['print_value']) ? $option['print_value'] : $option['value']))) ?>
                            </dd>
                        <?php endif; ?>
                    </dl>
                <?php endforeach; ?>
            </div>

        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="cs-table__col | sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>">
        <?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="cs-table__col | price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="cs-table__col |  qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
            <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
                <li class="item">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered'); ?></span>
                    <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyShipped() > 0): ?>
                <li class="item">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Shipped'); ?></span>
                    <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyShipped()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
                <li class="item">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Canceled'); ?></span>
                    <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyCanceled()*1 ?></span>
                </li>
            <?php endif; ?>
            <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
                <li class="item">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Refunded'); ?></span>
                    <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyRefunded()*1 ?></span>
                </li>
            <?php endif; ?>
        </ul>
    </td>
    <td class="cs-table__col | subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
