<?php
    /**
     * Product list/grid template
     *
     * @var $block \Magento\Catalog\Block\Product\ListProduct
     */

    // @codingStandardsIgnoreFile

    $productCollection = $block->getLoadedProductCollection();
?>

<?php if (!$productCollection->count()): ?>
    <?= $block->getChildHtml('empty.category.message') ?>
<?php else: ?>
    <?= $block->getAdditionalHtml() ?>

    <div class="cs-page-category__toolbar-wrapper cs-page-category__toolbar-wrapper--top">
        <?= $block->getToolbarHtml() ?>
    </div>

    <?= $block->getChildHtml('hotspot.before.active.filters') ?>

    <?= $block->getChildHtml('state'); ?>

    <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $viewModeClass = $block->getGridComponentClass();
            $viewModeListClass = $block->getGridComponentListClass();
            $viewModeListItemClass = $block->getGridComponentListItemClass();
            $image = 'category_page_grid';
            $image2x = 'category_page_grid_x2';
        } else {
            $viewMode = 'list';
            $viewModeClass = $block->getListComponentClass();
            $viewModeListClass = $block->getListComponentListClass();
            $viewModeListItemClass = $block->getListComponentListItemClass();
            $image = 'category_page_list';
        }

        $pageLayout = $this->helper(\MageSuite\ThemeHelpers\Helper\PageLayout::class)->getPageLayout();
        $iterator = 0;

        if ($pageLayout != '1column') {
            $viewModeClass .= ' ' . $viewModeClass . '--with-sidebar';
        }
    ?>

    <div class="products wrapper <?= $viewMode ?> products-<?= $viewMode ?> cs-page-category__products-wrapper">

        <div class="<?= $viewModeClass ?> <?= $block->getAdditionalGridComponentClass() ?>">

            <?= $block->getChildHtml('hotspot.before.list') ?>

            <ol class="products list items product-items <?= $viewModeListClass ?>">
                <?php /** @var $product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($productCollection as $product): ?>
                    <?php $iterator++; ?>
                    <li class="<?= $viewModeListItemClass ?>">
                        <?= $this->getLayout()
                            ->createBlock(\MageSuite\ProductTile\Block\Tile::class)
                            ->setType($viewMode)
                            ->setIterator($iterator)
                            ->setSection('category')
                            ->render($product);
                        ?>
                    </li>
                <?php endforeach; ?>
                
                <?php if($viewMode == 'grid'): ?>
                    <?= $block->getChildHtml('hotspot.inside.list') ?>
                <?php endif; ?>
            </ol>

            <?= $block->getChildHtml('hotspot.after.list') ?>
        </div>
    </div>

    <div class="cs-page-category__toolbar-wrapper cs-page-category__toolbar-wrapper--bottom">
        <?= $block->getToolbarHtml() ?>
    </div>

    <?php if (!$block->isRedirectToCartEnabled() && $block->getVar('ajax_addtocart/enabled', 'Magento_Catalog')): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
