<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$csProductHelper = $this->helper('Creativestyle\FrontendExtension\Helper\Product');
/** @var $pricingHelper \Magento\Framework\Pricing\Helper\Data */
$pricingHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <div class="cs-category-page__toolbar-top">
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $viewModeClass = 'cs-items-grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    } else {
        $viewMode = 'list';
        $viewModeClass = 'cs-items-list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="">
        <?php $iterator = 0; ?>
        <ol class="<?php /* @escapeNotVerified */
        echo $viewModeClass; ?> cs-items-grid--in-column">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php $iterator++; ?>
                <li class="<?php echo /* @escapeNotVerified */ $viewModeClass; ?>__item | cs-grid-product">
                    <?php
                        $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                        $productImageUrl = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(400)->getUrl();
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                    ?>

                    <?=$this->getLayout()->createBlock( 
                        'Creativestyle\FrontendExtension\Block\Twig', 'grid-product-'.$iterator, [
                            'data' => [
                                'showWrapper' => false,
                                'url' => $_product->getProductUrl(),
                                'image' => [
                                    'src' => $productImageUrl,
                                    'alt' => $_productNameStripped
                                ],
                                'name' => $_helper->productAttribute($_product, $_product->getName(), 'name'),
                                'price' => [
                                    'content' => $block->getProductPrice($_product)
                                ],
                                'swatches' => [
                                    'content' => $block->getProductDetailsHtml($_product)
                                ],
                                'addons' => [
                                    'show' => true
                                ],
                                'rating' => [
                                    'maxStars' => $csProductHelper->getReviewSummary($_product)['data']['maxStars'],
                                    'activeStars' => $csProductHelper->getReviewSummary($_product)['data']['activeStars'],
                                    'text' => '('.$csProductHelper->getReviewSummary($_product)['data']['count'].')'
                                ],
                                'stock' => [
                                    'showInStock' => $_product->getIsSalable() ? true : false,
                                    'showOutOfStock' => $_product->getIsSalable() ? false : true,
                                    'inStockContent' => __('In stock'),
                                    'outOfStockContent' => __('Out of stock')
                                ],
                                'hotspots' => [
                                    'after' => [
                                        'inStock' => [
                                            'content' => '<ul class="cs-links-block-addto" data-role="add-to-links"><li class="cs-links-block-addto__item"><a href="#" class="cs-links-block-addto__link towishlist" title="'.$block->escapeHtml(__('Add to Wish List')).'" aria-label="'.$block->escapeHtml(__('Add to Wish List')).'" data-post=\''.$block->getAddToWishlistParams($_product).'\' data-action="add-to-wishlist" role="button"><svg class="cs-links-block-addto__icon cs-links-block-addto__icon--wishlist"><use xlink:href="'.$this->getViewFileUrl('images/sprites.svg').'#heart"></use></svg>'.__('Add to Wishlist').'</a></li></ul>'
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    )->setTemplate("grid-product/grid-product.twig")->toHtml(); ?>

                </li>
            <?php endforeach; ?>
        </ol>
    </div>

    <?php echo $block->getToolbarHtml() ?>
<?php endif; ?>
