<?php
/**
 * Template overriden to match the HTML structure
 * and styling to the remaining order details blocks.
 */
/** @var \Bold\OrderComment\Block\Order\Comment $block */
?>
<?php if($comment = $block->getOrderComment()):?>
<div class="block block-order-details-view">
    <strong class="block-title"><span><?= /* @escapeNotVerified */ __('Order Comment') ?></span></strong>
    <div class="block-content">
        <?= $block->getOrderCommentHtml();?>
    </div>
</div>
<?php endif; ?>