<?php
/**
 * Magento Commerce feature
 * Template overridden due to avoid page builder template (even with disabled PageBuilder the template is displayed)
 *
 * Aligned with Magento 2.4.6 at 04/2023
 */
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
/**
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if ($description = $block->getCurrentCategory()->getDescription()) :?>
    <div class="cs-page-category__description">
        <?= /* @noEscape */ $this->helper(\Magento\Catalog\Helper\Output::class)->categoryAttribute(
            $block->getCurrentCategory(),
            $description,
            'description'
        ) ?>
    </div>
<?php endif; ?>
